### ISSUE TITLE
iOS - InAppBillingProduct.MicrosPrice - always zero

### ISSUE THREAD

**Issue by jiripeli** [jamesmontemagno/InAppBillingPlugin#10]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 1.1.0.9 - Beta
Device Tested On: iPhone 6s
Simulator Tested On: --

### Expected Behavior
Expected price 

### Actual Behavior
always 0 (zero)

### Steps to reproduce the Behavior
await InAppBilling.GetProductsInformation(itemslist, (item) =>
			{
				var itemStr = item.ProductId.Replace(Common.DML_IAP_PREFIX, "");
				var i = gemsShopVM.FirstOrDefault(d => d.shopItem.IAP_CODE.Equals(itemStr));
				if (i != null)
				{
					i.LocalizedPrice = item.LocalizedPrice;
					i.SetPrice((double)item.MicrosPrice / 1000000d);
				}
			});

## Feature Request:
change ios Implementation to:
		public async Task<IEnumerable<InAppBillingProduct>> GetProductInfoAsync(ItemType itemType, params string[] productIds)
		{
			var products = await GetProductAsync(productIds);

			return products.Select(p => new InAppBillingProduct
			{
				LocalizedPrice = p.LocalizedPrice(),
				MicrosPrice = (long)(p.Price.DoubleValue * 1000000d),
				Name = p.LocalizedTitle,
				ProductId = p.ProductIdentifier,
				Description = p.LocalizedDescription,
				CurrencyCode = p.PriceLocale?.CurrencyCode ?? string.Empty
			});
		}

**Comment by jamesmontemagno** [comment]
That is correct, it is only on Android as only Google returns this information.

**Comment by jamesmontemagno** [comment]
All return the localized

**Comment by jiripeli** [comment]
But i need get price as number to compute other numbers. Apple provide price as number and i need this, Please. 

I have several consumable iap. Ratio between 10gems and 100gems are different between regions and currency. I need compute this ratio to display percentage between iaps.

**Comment by jamesmontemagno** [comment]
Let me look into it

**Comment by jamesmontemagno** [comment]
Checkout: 1.1.0.15-beta
