### ISSUE TITLE
iOS: PurchaseAsync returns immediately with an old purchase

### ISSUE THREAD

**Issue by acrabb** [jamesmontemagno/InAppBillingPlugin#101]
## Bug Information

Version Number of Plugin: 1.2.3.107
Device Tested On: iPad
Simulator Tested On: NA
Version of VS: 7.2.2
Version of Xamarin: Xamarin.iOS 11.3

### Steps to reproduce the Behavior
1. Purchase an auto-renewing subscription
2. Wait 5 minutes until the auto-renewing subscription expires
3. Go through the flow to purchase the subscription again.

### Expected Behavior
Upon calling `CrossInAppBilling.Current.PurchaseAsync`, app should show the native dialog, but shouldn't continue until the user has entered their credentials and completed a successful purchase.

### Actual Behavior
Upon calling `CrossInAppBilling.Current.PurchaseAsync`, app shows the native dialog, but simultaneously continues. The return value of `PurchaseAsync` has the transaction date of the previous purchase.
If the user completes this purchase with the dialogs, the thread will resume again when the purchase is successful.

**Comment by jamesmontemagno** [comment]
This is controlled by apple.

**Comment by acrabb** [comment]
So this is expected behavior?

**Comment by jamesmontemagno** [comment]
Yeah, I mean I can't do anything about what Apple does when the API is called.
