### ISSUE TITLE
Question: Dont we have to check PurchaseState?

### ISSUE THREAD

**Issue by EmilAlipiev** [jamesmontemagno/InAppBillingPlugin#104]
Are the lines below in the documentation are correct? are we not supposed to check PurchaseState or we accept it successful, if purchase  object is not null?

    if (state == PurchaseState.Purchased)

```
//possibility that a null came through.
        if(purchase == null)
        {
            //did not purchase
        }
        else
        {
            //purchased!
        }
```

**Comment by jamesmontemagno** [comment]
You can as well depending on how far down the rabit hole you want to go.

**Comment by EmilAlipiev** [comment]
I asked this because there statuses like Canceled, Failed, Deferred, PaymentPending etc. are we not expecting these?

**Comment by jamesmontemagno** [comment]
Anything can happen. It is possible that another value comes through, especially on iOS, but not very often from my testing.
