### ISSUE TITLE
Can not pass Microsoft permission about In-App Puchase

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [jamesmontemagno/InAppBillingPlugin#106]
When I submission my app have use Plugin.InAppBilling. My app get attention from Microsoft
They said:
Your app enables in-app purchase of digital goods or services but does not use the Microsoft Store in-app purchase API

How to fix this

**Comment by jamesmontemagno** [comment]
Is it this? https://social.msdn.microsoft.com/Forums/silverlight/en-US/8c3ce634-90f5-4c75-8891-d631f202e4a7/inapp-purchase-of-service-not-using-windows-store?forum=wpsubmit

**Comment by nguyenthanhliemfc** [comment]
Yes sir. @jamesmontemagno . That it is!

**Comment by jamesmontemagno** [comment]
I already have 1 app in the app store with the plugin and it worked fine. I am submitting a new one right now and will let you know.

What are your settings for Min/Target UWP versions?

**Comment by nguyenthanhliemfc** [comment]
@jamesmontemagno This is my project [OneDrive Link](https://1drv.ms/u/s!Ah-5hC3QyJDai7U8AH53P9ahXF6g1A)

**Comment by jamesmontemagno** [comment]
@nguyenthanhliemfc please don't post your project unless it is open source on github.

You can just look in the project settings;
![image](https://user-images.githubusercontent.com/1676321/35420415-412eb9f8-01f2-11e8-8c76-01e585fa2ebf.png)

**Comment by jamesmontemagno** [comment]
What as the actual email from Microsoft that you received?

**Comment by nguyenthanhliemfc** [comment]
@jamesmontemagno 
I dont care about my source code. I only want to know what happend and how to fix it. Don't worry my code
This is warning from Microsoft I copied:
Please take the following action
We reviewed your submission and identified some changes that are needed before we can publish or update the app. Please make these changes and resubmit your app. For more information, contact reportapp@microsoft.com Please include your app ID so we can act quickly.

App Policies: 10.8.1 In-App Purchase: Digital Goods & Services
Notes To Developer
Your app enables in-app purchase of digital goods or services but does not use the Microsoft Store in-app purchase API.
Tested Devices: Windows 10 Desktop
Please Note
Your current certification results might differ from earlier submissions because Windows Store policy requirements can change over time. When policies change, we might re-test according to the new requirements regardless of the submission type. Please always rely on your most recent certification results.

**Comment by nguyenthanhliemfc** [comment]
@jamesmontemagno My app live on store and this issue appear after I fix grammar of some Lable. I don't change any thing about InApp Purchase.

**Comment by jamesmontemagno** [comment]
I published my app just fine today using this. SO must be something else.
