### ISSUE TITLE
Randomly Android.OS.RemoteException on service connected.

### ISSUE THREAD

**Issue by fernandovm** [jamesmontemagno/InAppBillingPlugin#107]
Dear @jamesmontemagno, I have been receiving some times the unhandled exception: [https://gist.github.com/fernandovm/7d8e300bc56caad4f799b48fd94ad5f9](https://gist.github.com/fernandovm/7d8e300bc56caad4f799b48fd94ad5f9). I'm using the package 'Plugin.InAppBilling' version '1.2.4'. 

Unfortunately I not have the steps to reproduce the behavior, I always run the below code on startup of my xamarin forms app (in a background thread), but its happens randomly (were rarely):

```
try
{
	//...
	if (await CrossInAppBilling.Current.ConnectAsync())
	{
		//...
		var purchases = (await CrossInAppBilling.Current.GetPurchasesAsync(prodType));
		//...
	}
	//...
}
catch (Exception e)
{
	if (e is AggregateException)
	{
		(e as AggregateException).Flatten().Handle(ex => return true);
	}
}
finally
{
	await CrossInAppBilling.Current.DisconnectAsync();
}
```

Are there some way as I can better help you investigate this issue?

**Comment by jamesmontemagno** [comment]
This is not recommended to do in startup or in a background thread as that could cause a lot of issues. Try moving code into some other place.

**Comment by fernandovm** [comment]
Hi @jamesmontemagno, in really I does not run the code in exactly in startup, but immediately after the startup. Thus I think that I must understand from your reply that I does not must invoke the code from a background thread, I must always invoke it from the main thread. It is? Thank you so much by your attention!
