### ISSUE TITLE
Missing inf in Documentation

### ISSUE THREAD

**Issue by harrypotter06** [jamesmontemagno/InAppBillingPlugin#110]
Hello,

using Visual Studio 2017 c#, your Plugin and will make Purcases in store.
The Class "Verify" i create in root from the Project, split my key and ad it as follow:

const string key1 = @"myKeyPart1";
const string key2 = @"myKeyPart2";
const string key3 = @"myKeyPart3";

at this Moment, i get a error (use Android Emulator with Google Play Store Image API 25)
Bevore i checked on a Hardware device, that i must complet reset, because "publushers" can't buy IAP, i will verify, that all correct. 

So, on your documentation you wrote:

You MUST sign the APK even in debug mode. In XS this is in the properties. In VS you must manually add this to your project:
<AndroidKeyStore>True</AndroidKeyStore>
<AndroidSigningKeyStore>KeystoreLocation</AndroidSigningKeyStore>
<AndroidSigningStorePass>PASS</AndroidSigningStorePass>
<AndroidSigningKeyAlias>ALIAS</AndroidSigningKeyAlias>
<AndroidSigningKeyPass>PASS</AndroidSigningKeyPass>

On what file i must add this Entrees?

**Comment by jamesmontemagno** [comment]
That is correct you have to use a different account to test your in app purchases.

You would sign it in the Android project settings or in the csproj such as: https://github.com/Azure-Samples/MyDriving/blob/master/src/MobileApps/MyDriving/MyDriving.Android/MyDriving.Android.csproj#L31-L35

**Comment by harrypotter06** [comment]
Thanks for your quick Response.

Last question (sorry, i am new in dev Android apps)

AndroidSigningKeyStore : MyApp.Keystore - This is the Name from my keystore file?
AndroidSigningStorePass: >Build*1234  --- what this? AppName with Placeholder ?
AndroidSigningKeyAlias: MyApp  - App Alias?!
AndroidSigningKeyPass>Build*1234 --- what this? AppName with Placeholder ?

**Comment by jamesmontemagno** [comment]
See: https://developer.xamarin.com/guides/android/deployment,_testing,_and_metrics/signing/

**Comment by harrypotter06** [comment]
Thank you - have a nice day
