### ISSUE TITLE
PurchaseAsync returns null after canceling purchase

### ISSUE THREAD

**Issue by LukasT83** [jamesmontemagno/InAppBillingPlugin#111]
## Bug Information

Version Number of Plugin: 1.2.4
Device Tested On: Samsung Galaxy S5
Simulator Tested On: /
Version of VS: 2017
Version of Xamarin: 2.5
Versions of other things you are using:

### Steps to reproduce the Behavior

Same code as used in the tutorial for subscriptions. Execute it once, everything works great. But cancel buying the first time, then execute it again and PurchaseAsync will always return null. Only restarting the app makes it work again.

### Expected Behavior

Should work after canceling a purchase too

### Actual Behavior

Always returns null after canceling a purchase

### Code snippet

```csharp
public async Task<bool> PurchaseItem(string productId, string payload)
{
    var billing = CrossInAppBilling.Current;
    try
    {
        var connected = await billing.ConnectAsync();
        if (!connected)
        {
            //we are offline or can't connect, don't try to purchase
            return;
        }

        //check purchases
        var purchase = await billing.PurchaseAsync(productId, ItemType.Subscription, payload);

        //possibility that a null came through.
        if(purchase == null)
        {
            //did not purchase
        }
        else
        {
            //purchased!
        }
    }
    catch (InAppBillingPurchaseException purchaseEx)
    {
        //Billing Exception handle this based on the type
        Debug.WriteLine("Error: " + purchaseEx);
    }
    catch (Exception ex)
    {
        //Something else has gone wrong, log it
        Debug.WriteLine("Issue connecting: " + ex);
    }
    finally
    {
        await billing.DisconnectAsync();
    }
```

**Comment by AndreiMisiukevich** [comment]
Hi guys
Any updates about this issue?

Is it clear description to fix it? We need to get version of pack with fix too)

**Comment by LukasT83** [comment]
I've just updated to the new beta. Behavior is still exactly the same as described above. I thought this being marked as "Closed" means it should be fixed?

**Comment by Oleksandr-Tokmakov** [comment]
@jamesmontemagno ,
I have the same issue with buying InAppPurchases. 
First time, when I click on purchase button I get purchase dialog. And if I cancel it:
`var purchase = await billing.PurchaseAsync(productId, ItemType.InAppPurchase, payload);`
will never proceed. I.E. that PurchaseAsync task will hang for ever, so
```
finally
{
    await billing.DisconnectAsync();
}
```
will not be called. 
And any attempts to make purchases will end up with returned Null value from 
PurchaseAsync method.

**Comment by Oleksandr-Tokmakov** [comment]
@AndreiMisiukevich , no, I haven't. Is it stable enough for production?

**Comment by AndreiMisiukevich** [comment]
@Oleksandr-Tokmakov this is very good question :)
I have no information about releases. But i'm sure, you should try it.

**Comment by masterwok** [comment]
I'm running into this same issue running **2.1.0.187-beta** prerelease build.

When tapping out of or back from the initial purchase to cancel, the method never returns.

Future calls to PurchaseAsync return null.

This is occurring on a physical device and in the simulator.

**Comment by jfarinhote** [comment]
Facing the same problem
