### ISSUE TITLE
Not getting date of auto renewed subscriptions on playstore

### ISSUE THREAD

**Issue by tfuetterer** [jamesmontemagno/InAppBillingPlugin#112]
## Bug Information

Version Number of Plugin: 1.2.4
Device Tested On: S5 Neo
Simulator Tested On:
Version of VS: 15.5.4
Version of Xamarin: 2.5.0.122203
Versions of other things you are using:

### Steps to reproduce the Behavior
- Make a subscription purchase on android
- This testpurchase will renew every day
- One or more days later call the GetPurchasesAsync to validate if the subscription was not canceled by the user
### Expected Behavior
- Get the transaction date of when the subscription was auto renewed the last time
### Actual Behavior
- Get the transaction date when the subscription was initially purchased
### Screenshotst

Am I missing something in your plugin or how should I otherwise find out, if a subscription is still not cancelled?

**Comment by jamesmontemagno** [comment]
See: https://stackoverflow.com/questions/36591498/android-how-to-check-if-subscription-is-renewed

Essentially you will see additional orders that come in via the order number with appended orderId, however google recommends that you implement this on your server side.

https://developers.google.com/android-publisher/api-ref/purchases/subscriptions/get

also see: https://developer.android.com/google/play/billing/billing_subscriptions.html#strategies
