### ISSUE TITLE
Reliable way to get subscription expiry time

### ISSUE THREAD

**Issue by VVK1993** [jamesmontemagno/InAppBillingPlugin#114]
Hello guys,

I want to implement monthly auto-renewable subscription for iOS and Android and struggle to find a reliable way to calculate the expiry time.

Should I just add 1 month to _TransactionDateUtc_ property of a _InAppBillingPurchase_ object?

How to know if the subscription was renewed or not? Will _TransactionDateUtc_ be automatically updated when the subscription is auto-renewed? 
And does it work the same on both platforms?

I would really appreciate an answer as I am having difficulties finding a solution.

Thanks!

**Comment by jamesmontemagno** [comment]
You can check the receipt fields on iOS:

https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html

For receipts containing auto-renewable subscriptions, check the value of the latest_receipt_info key to get the status of the most recent renewal.

For Android:

For receipts containing auto-renewable subscriptions, check the value of the latest_receipt_info key to get the status of the most recent renewal.



I personally don't do subscriptions and just return the data that google and apple give me.
