### ISSUE TITLE
How to use the keys in Verify : IInAppBillingVerifyPurchase example ?

### ISSUE THREAD

**Issue by Toine-db** [jamesmontemagno/InAppBillingPlugin#116]
Can anyone add a few sentences about how de keys 1-3 are used in the verify purchases process
at [SecuringPurchases.md-android-security](https://github.com/jamesmontemagno/InAppBillingPlugin/blob/eee08678ec1801dd3350902d883cace81dcc4e8f/docs/SecuringPurchases.md#android-security)

This way a developer can self decide how the verify process / key(s) can be implemented; dynamic each startup, or at app installation or as constants. 

I opened a question on Stackoverflow on this; https://stackoverflow.com/questions/48660351/where-are-xor-keys-used-for-during-purchase-veryfication-in-inappbillingplugin

**Comment by jamesmontemagno** [comment]
It literally says it in the documentation:

The simplest and easiest (not necessarily the most secure) way is to do the following:

1. Take your public key and break into 3 parts
2. Run each through the helper XOR method: Plugin.InAppBilling.InAppBillingImplementation.InAppBillingSecurity.TransformString
3. Save each value out and put them in your app

**Comment by jamesmontemagno** [comment]
The idea here is not to put your public key in your application. What you are doing is breaking your key apart into 3 parts. Then you are transforming the string with the method in there, which basically scrambles it via XOR for you.

With these three XORed parts of your public key then you put those into your source code.

Then when you pass in your Verify implementation i take the signed data and run in through my VerifyPurchase method which will validate that the keys from google match up and validate the keys that you have XORed.

**Comment by Toine-db** [comment]
Got it, no self madeup keys or dynamic once.
the keys are the same every build or install because they just encoded partial keys. 

Thanks for the reply.

**Comment by mmehdidehghani** [comment]
I'm new in xamarin.forms.
Could you please help me? Is this correct?:
I add the class in my andorid and ios app:

[assembly: Dependency(typeof(InAppBillingVerify))]
namespace MyApp.Droid.Dependencies
{
    public class InAppBillingVerify : IInAppBillingVerifyPurchase
    {
        const string key1 = @"XOR_PublicKey_Part1";
        const string key2 = @"XOR_PublicKey_Part2";
        const string key3 = @"XOR_PublicKey_Part3";
        public Task<bool> VerifyPurchase(string signedData, string signature, string productId = null, string transactionId = null)
        {

#if __Android__
            var key1Transform = Plugin.InAppBilling.InAppBillingImplementation.InAppBillingSecurity.TransformString(key1, 1);
            var key2Transform = Plugin.InAppBilling.InAppBillingImplementation.InAppBillingSecurity.TransformString(key2, 2);
            var key3Transform = Plugin.InAppBilling.InAppBillingImplementation.InAppBillingSecurity.TransformString(key3, 3);
            return Task.FromResult(Plugin.InAppBilling.InAppBillingImplementation.InAppBillingSecurity.VerifyPurchase(key1Transform + key2Transform + key3Transform, signedData, signature));
#else
            return Task.FromResult(true);
#endif
        }
    }
}

And add this line before PurchaseAsync method:
var verify = DependencyService.Get<IInAppBillingVerifyPurchase>();

**Comment by CDrosos** [comment]
> key1Transform

yes, you are correct

**Comment by CDrosos** [comment]
@jamesmontemagno just to be 100% sure, 
if for example our public RSA key is "123456789" then then in your example the key1=@"123", key2=@"456", key3=@"789"?

**Comment by najak3d** [comment]
I am genuinely confused by the sample code and the directions.   

The sample code shows a line like this:

     const string key1 = @"XOR_PublicKey_Part1";   

Question: Is the string here supposed to be the unencrypted 1st part of your public key?  Or is it supposed to be already encrypted? (i.e. the output of TransformString()) ??

If it is the unencrypted part of public key -- then if someone disassembles the MSIL, they'll SEE your public see in plain text.  So I would assume that these constants should be "pre-encrypted", rather than encrypting the plain-text keys run-time.

I would have thought we'd use the TransformString() "in DEBUG mode" to produce the XOR results, and then the developer would PASTE these results directly into these  3 constants.   Thus the plain text strings would never appear in your production code.   And so in production code, we'd just concat these three constants without further run-time encryption.  (just send them to VerifyPurchase method "as is").

 And so I'm suspecting that I might be misunderstanding something crucial here.

**Comment by Devilcow** [comment]
Hello, please bare with me here lol... 
I am trying to make a free version of an app I have uploaded as a paid app. In the free version I will show ads, and limit the number of records the app can record and recall. 
The easiest way I can think of doing this, is to have an internal flag that specifies if it's the paid version or not, When the app starts, it checks this flag, and queries the API for the purchase state. if it's changed, the app sets the flag accordingly and continues on. The logic of the app would then use this flag to show or hide the ads, and potentially limit the number of DB records it would retrieve.

This way all I have to do is add a build target in my project, that uses a PRAGMA to define build targets Debug Paid / Debug free / Release Free / Release Paid. The only difference being that I have a pair of `bool` flags that are set to true, `bIsPaid` and `bIsPaidVersion` (which would bypass the checking logic). I can upload this as a new app in the Play Store, and define the in app purchases for that version. 

Which key should I be using for this? 
Should I use my Upload certificate? the App Signing certificate? or build a new key? I assume that if it's one of the prior, all I do is download the certificate, and save the key as a file with Base-64 encoding? 
At that point I just chop it into 3 chunks and use your process above XORing it from the debug code to get the encoded key that I put into the code? 

 I am sorry if this is a particularly dense question, I just wanted to make sure that I am on the right track and especially don't want to wind up posting a build that has broken or faulty billing logic.

Cheers!

**Comment by jamesmontemagno** [comment]
I would read through https://jamesmontemagno.github.io/InAppBillingPlugin/SecuringPurchases.html and all of the iOS and Android documentation. I provide the information to validate the purchases.

**Comment by Devilcow** [comment]
Excellent, thanks!
