### ISSUE TITLE
Android: PurchaseError.BillingUnavailable thrown when PurchaseError.ServiceUnavailable appropriate

### ISSUE THREAD

**Issue by BioTurboNick** [jamesmontemagno/InAppBillingPlugin#118]
Based on the Android API documentation (https://developer.android.com/reference/com/android/billingclient/api/BillingClient.BillingResponse.html#BILLING_UNAVAILABLE), it appears that BILLING_UNAVAILABLE is specific to an API version issue, while SERVICE_UNAVAILABLE is returned when the connection is down.

Currently, your implementation throws PurchaseError.BIllingUnavailable when the connection is down. I suggest changing this to PurchaseError.ServiceUnavailable to maintain consistency with the Android API and avoid overloading the error types, which you otherwise directly translate.

**Comment by jamesmontemagno** [comment]
Send down a PR;)
