### ISSUE TITLE
InAppBillingProduct - Price as double

### ISSUE THREAD

**Issue by jiripeli** [jamesmontemagno/InAppBillingPlugin#12]
## Feature Request:
Hi,
I need a new property on InAppBillingProduct class.
Price as double.
Can You do this, please?

Thank You very much.

**Comment by jamesmontemagno** [comment]
I will fix #10 and  an then you can calculate price off of this.

**Comment by jamesmontemagno** [comment]
Checkout: 1.1.0.15-beta

**Comment by jiripeli** [comment]
Perfect!
Thank you very much.
