### ISSUE TITLE
Purchase Task never completed if item is already purchased

### ISSUE THREAD

**Issue by jason2211** [jamesmontemagno/InAppBillingPlugin#121]
When attempting to purchase an item that has already been purchased, the tcsPurchase task will be created but is never complete so no future purchases can be made until the app is restarted.

In the Plugin.InAppBilling.Android project, class Plugin.InAppBillingImplementation, method PurchaseAsync (line 321), the code checks if the purchase has already been made and if so it returns the purchase.  However, the tcsPurchase is still in a state of WaitingforActivation.

Since the HandleActivityResult will never be called due to the BuyIntent never being sent to Android, all future purchase attempts will return null due to the tcsPurchase.Task.IsCompleted check at the beginning of PurchaseAsync method (line 290).

I would suggest modifying the task check verify the TaskStatus is not WaitingForActivation.  If it is still waiting for activation, I think it is safe to assume the prior purchase call never created the BuyIntent. 

Another option would be to set the tcsPurchase to null whenever the purchase is returned without invoking the BuyIntent.

Version Number of Plugin:   1.2.4 (also used the latest in GitHub)
Device Tested On:  Nexus 7
Simulator Tested On: None
Version of VS: Android 4.4.4
Version of Xamarin: 4.8.0.757

### Steps to reproduce the Behavior
Attempt to purchase an item that has already been purchased.  Code will correctly return the purchase item without attempting to purchase it again.  Attempt to buy another item and the call to PurchaseAsync will always return NULL until the app is restarted.

### Expected Behavior
Future calls to PurchaseAsync should not return null.

### Actual Behavior
Null is always returned from PurchaseAsync after attempting to purchase an item that is already purchased.

**Comment by AndreiMisiukevich** [comment]
Hi @jason2211 
You should consume previous product, before buying new one.

https://developer.android.com/google/play/billing/api.html

**Comment by jason2211** [comment]
Hi @AndreiMisiukevich 
Thanks for the reply.  Shouldn't the library respond better?  It appears to be coded for this exact scenario since it is checking if the item is already purchased and correctly returns it.  I would just expect the library not to go into a state where no future purchase calls will work after this scenario.

**Comment by AndreiMisiukevich** [comment]
I think, you are right.

@jamesmontemagno what do you think?

**Comment by jamesmontemagno** [comment]
We should handle it correct. Would need to see where in the code this is happening or send a PR I can review.

**Comment by AndreiMisiukevich** [comment]
@jamesmontemagno https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/src/Plugin.InAppBilling.Android/InAppBillingImplementation.cs#L322-L326

here is the reason.


I think, we should to throw error instead of trying to retrieve bought product.

**Comment by jamesmontemagno** [comment]
Ahhh I see, so we are basically just returning the existing purchase instead of throwing... 

I see why I did this. sounds good. can you PR me?

**Comment by AndreiMisiukevich** [comment]
no problem
give me some time

**Comment by meepou** [comment]
I still have the issue, it says that the item was already purchased and will be restored for free but then PurchaseAsync never ends. I have the latest version of the plugin.
