### ISSUE TITLE
State of test subscription is always PaymentPending

### ISSUE THREAD

**Issue by cncb-gh** [jamesmontemagno/InAppBillingPlugin#124]
## Bug Information

Version Number of Plugin: 1.2.4
Device Tested On: Moto E4
Simulator Tested On:
Version of VS: Community 2017, 15.5.6
Version of Xamarin: 26.1.0.1 (Android)
Versions of other things you are using: Xamarin Forms 2.5.0.280555, .NET Standard 2.0.1

### Steps to reproduce the Behavior
Create an InApp purchase that is a yearly subscription.  Make a purchase from a test purchase account.  Get the purchase from GetPurchasesAsync().
### Expected Behavior
The "State" should reflect the current state of the test subscription.  That is: FreeTrial, Purchased, Canceled
### Actual Behavior
The "State" of the subscription always is "PaymentPending".

**Comment by AndreiMisiukevich** [comment]
@cncb-gh Hi)
I'm sorry, but could you confirm, that you use test account?)
Did you add your account here http://prntscr.com/ini8wo and use it as primary in your play market?

It looks like you make real purchase, but your bank account hasn't got enough money..

**Comment by cncb-gh** [comment]
Hi,

Yes, it definitely is a test account.  I have tried 2 different accounts that I added as license testers (in the place your screenshot shows).  All the receipts and screens say that it is a test subscription and it follows the test subscription schedule (3 minutes trial, 30 minutes renewal for 6 times, and then canceled) but the State always returns PaymentPending for some reason.  Thanks.

**Comment by AndreiMisiukevich** [comment]
Hmm, okay.. Did you wait 3 minutes before check this status?
I think, the status must be changed only after pseudo-TRIAL period.

And another question. Did you receive email on your gmail account about writing-off of money?
Something like this http://prntscr.com/inm51f

**Comment by cncb-gh** [comment]
Yes, I checked all along until the subscription was automatically canceled after 3 hours.  It was always PaymentPending until it was canceled.

I received that email (attached) and one every 30 minutes when it renewed.  I wonder if it has something to do with the subscription being yearly?
![subscription](https://user-images.githubusercontent.com/8257394/37038752-a6c750ea-2123-11e8-8680-1bcaf20ad55a.JPG)

**Comment by AndreiMisiukevich** [comment]
I can suggest you to get source code of InapBillingImplementation and debug it.. maybe you will catch an error.. or it's just Google's magic

**Comment by cncb-gh** [comment]
I finally debugged this.  It looks like Google json purchase data only includes a "purchaseState" property while InappBillingImplementation is looking for a "paymentState" property for subscriptions.  purchaseState is also always 0 so I guess I will have to assume that if a purchase exists for the given id, the subscription is valid and the State is meaningless.

**Comment by EmilAlipiev** [comment]
I dont understand why is that closed. @cncb-gh  your assumption is wrong. if a purchase exist, it doesnt mean that subscription is valid. (at least for a test purchase). I have cancelled my test purchase which is renewed every 5 mins. but now i dont get how to understand if subscription is cancelled or not, as purchases always return even a cancelled subscription.

**Comment by nholloway91** [comment]
@cncb-gh I have come across the same issue with my current code. I was wondering if you ever came to a resolution with this other than just assuming it would work. Similar to @EmilAlipiev even if I have cancelled a subscription or it has expired when checking for subscriptions they are still being found in a payment pending state when my app searches for subscriptions.

Thanks

**Comment by cncb-gh** [comment]
Maybe I should test this again in case something has changed, but in my previous testing, after the subscription is cancelled or expired, there is no purchase with the given subscription id returned in GetPurchasesAsync().  I remember it takes a little while when testing with a test subscription, but eventually it is updated/removed.

**Comment by EmilAlipiev** [comment]
@cncb-gh  was that the case for live testing or with test account testing? basically what it happens is I set monthly subscription and test subscription will be evaluated as 5 mins? so every 5 mins is renewed. if I cancel in between so after 2 mins and check, Isrenewed parameter is false but subscription is returned, thats expected situation because full 5 mins is not finished yet. so after 3 more minutes, i expect that subscription is finished and it shouldnt be returned but it is still returned only after 6 times, it is not returned. 
this 6 time is also stated in google documentation that test subscriptions are only returned 6 times regardless cancelled or not. I still didnt go live with my subscriptions but it looks like that it is good to do some live testing to ensure but I am seeing stackoverflow question regarding this. It looks like it has nothing to do with plugin but googles error. 
there seems to be function to get expiry date even though and not exist in the plugin implementation.

**Comment by cncb-gh** [comment]
@EmilAlipiev I only tested with test account subscriptions.
