### ISSUE TITLE
IInAppBillingServiceStub+Proxy.IsBillingSupported (System.Int32 apiVersion, System.String packageName, System.String type) Java.Lang.Exception: Exception of type 'Java.Lang.Exception' was thrown.

### ISSUE THREAD

**Issue by Big-ED** [jamesmontemagno/InAppBillingPlugin#129]
Hi, somtimes it's happens, but I can't to reproduce it localy on my devices:

**## Bug Information**
Version Number of Plugin: tested on 1.2.4.130-beta and 1.2.4 
Device Tested On:  Nomi i5010 (Android 6.0), Redmi Note 4 (Android 7.0), HT17 (Android 7.1.1)
Simulator Tested On: no
Microsoft Visual Studio 2017 version: 15.5.6
Microsoft .NET Framework version: 4.7.02556
Xamarins version: 4.8.0.760
Xamarin Designer version: 4.8.188
Xamarin.Android SDK version: 8.1.5.0
Xamarin.Forms version: 2.5.0.122203

**### Steps to reproduce the Behavior**
I can't reproduce it localy

**### Expected Behavior**
Application not crashed

**### Actual Behavior**
Application crashed

**### Code snippet**
I'm not sure which part of the code results in an error

**### Stacktrace**
https://gist.github.com/Big-ED/4f1cc1875b30bda1f5736b4446c14af3

**Comment by jamesmontemagno** [comment]
Are you setting your linker to full?

**Comment by Big-ED** [comment]
Can you tell more? I will check, inapp billing implemented by another
developer, so I not fully understand yet how it's work

18 мар. 2018 г. 1:25 пользователь "James Montemagno" <
notifications@github.com> написал:

**Comment by jamesmontemagno** [comment]
https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker

**Comment by Big-ED** [comment]
Thanks, I found what I have "SDK assemblies only", I will try to change to "SDK and User assemblies"

**Comment by EmilAlipiev** [comment]
it is other way around "SDK assemblies only" shouldnt give any problem.

**Comment by jamesmontemagno** [comment]
I recommend only "SDK assemblies only"

**Comment by Toine-db** [comment]
I have the same issue with "SDK assemblies only"

**Comment by jamesmontemagno** [comment]
Most likely has to do with the billing library itself. 

Will eventually upgrade to: https://android-developers.googleblog.com/2017/09/google-play-billing-library-10-released.html

**Comment by jamesmontemagno** [comment]
in the latest version i now ask on Connect what type of purchase you are tryign to make. 

If i get an exception then i return false on connect as things are supported on that device.
