### ISSUE TITLE
[Feature Request] SubscriptionPeriod for subscriptions

### ISSUE THREAD

**Issue by Sevenish** [jamesmontemagno/InAppBillingPlugin#130]
Unfortunatly there in no `SubscriptionPeriod` property on InAppBillingProduct.

But both Android and iOS to supply this property for subsciptions although the format differs. 
Please expose this information.

**Comment by jamesmontemagno** [comment]
Do you have links to docs?

**Comment by Sevenish** [comment]
Apple:
`SKProduct` property `subscriptionPeriod`
https://developer.apple.com/documentation/storekit/skproduct/2936884-subscriptionperiod

Android:
`getSkuDetails()` returns `subscriptionPeriod` only for subscription products:
https://developer.android.com/google/play/billing/billing_reference#getSkuDetails

**Comment by JimWilcoxIII** [comment]
I am writing a subscription based app and this feature would be pretty essential.  Mainly because a user can renew before their current subscription expires and if you calculate the subscription end date from the transaction date, it will likely cheat the user out of some days.

**Comment by jamesmontemagno** [comment]
Implemented in next
