### ISSUE TITLE
[Request?] Amazon Appstore

### ISSUE THREAD

**Issue by Sebastian1989101** [jamesmontemagno/InAppBillingPlugin#131]
Is there already any way to enable the In-App-Purchase from the Amazon Appstore? I could not find any informations if this is possible or not (and if it is possible how to use it). I would like to publish my Apps to as much Appstores as possible so that every user is able to use them. The Plugin works fine on iOS and Google PlayStore Android but on Amazon Appstore Android it always get's a Null result.

**Comment by jamesmontemagno** [comment]
Would look here: https://developer.amazon.com/docs/cross-platform-plugins/cpp-use-the-iap-plugin-for-xamarin.html they have a completely different API

**Comment by Sebastian1989101** [comment]
@jamesmontemagno I know that they have a own API. Is there at least any way to overload the CrossInAppBilling.Current to return my own implementation for Amazon? As for now, I couln't find a way without modifing my PCL (removing this plugin from it and split it into each project - but thats not a clean solution for a "Cross-Plattform" plugin).

**Comment by jamesmontemagno** [comment]
I think you could implement the interface for Amazon and based on the platform do what you need to do :) You should just have a Singleton that returns the implementation. Sorta like: https://montemagno.com/unit-testing-plugins-for-xamarin/
