### ISSUE TITLE
Feature Request: iOS: Support  ApplicationUsername on SKPayment

### ISSUE THREAD

**Issue by KotiJocki** [jamesmontemagno/InAppBillingPlugin#133]
The Apple documentation recommends supplying a one-way hash of a user's account name to help detect irregular activity.

https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/RequestPayment.html#//apple_ref/doc/uid/TP40008267-CH4-SW6

I don't see anything equivalent on Android and I haven't looked into Windows.

**Comment by kenny128** [comment]
Can we get an update on if this feature is going to be implemented or if this is going to be up-for-grab? This property is actually pretty important it seems for handling subscriptions for linking server side accounts to apple accounts.

**Comment by JMCPH** [comment]
Hi KotiJocki.

Did you manage to create a workaround for the applicationUsername on iOS?

**Comment by KotiJocki** [comment]
Hi JMCPH,

No we didn't. Unfortunately the feature that required in-app purchases was put on hold.

**Comment by jamesmontemagno** [comment]
Not sure if this is still a thing at all, would need some docs. I don't see anything here https://developer.apple.com/documentation/storekit/in-app_purchase/requesting_a_payment_from_the_app_store
