### ISSUE TITLE
introductoryPrice feature crashes iOS app

### ISSUE THREAD

**Issue by AndreiMisiukevich** [jamesmontemagno/InAppBillingPlugin#134]
The crash occurs in our app (iOS ONLY)
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SKProduct introductoryPrice]: unrecognized selector sent to instance 0x174214a50'

Version 1.2.4-136beta
iphone 5s

**Comment by AndreiMisiukevich** [comment]
@jamesmontemagno thanks a lot ;0

**Comment by jamesmontemagno** [comment]
:)
