### ISSUE TITLE
Why is the 'AlreadyOwned' error not being raised on Android?

### ISSUE THREAD

**Issue by bellissimo** [jamesmontemagno/InAppBillingPlugin#135]
I am curious as to how the plugin is expected to behave on Android when initiating a purchase for a user who has already bought the IAP. On the old Xamarin IAB library (in the Component Store) if you initiated a purchase (non-consumable) for a user who has already bought it, the library would propagate an 'Item Already Purchased' callback. However in this library it simply returns a state of 'Purchased'. 

I guess I was expecting it to throw an InAppBillingPurchaseException with a PurchaseError of 'AlreadyOwned'. If not, then what is the point of this particular error and when is it raised?

**Comment by jamesmontemagno** [comment]
Fixed already in pre-release
