### ISSUE TITLE
GetProductInfoAsync returns NULL in beta 137 on iOS

### ISSUE THREAD

**Issue by Sebastian1989101** [jamesmontemagno/InAppBillingPlugin#136]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 1.2.4.137-beta
Device Tested On: iOS multiple
Simulator Tested On: iOS multiple
Version of VS: Latest
Version of Xamarin: Latest
Versions of other things you are using: -

### Steps to reproduce the Behavior
Call `GetProductInfoAsync(ItemType.InAppPurchase, identifiers)`

### Expected Behavior
Returns the list of products like the latest stable release and like it is on Android

### Actual Behavior
Returns NULL

### Screenshotst
With 1.2.4.137-beta: https://puu.sh/zU2HT/9e9969ad50.png
With latest stable 1.2.4 (same App, same Code): https://puu.sh/zU2R8/58c9893710.png

**Comment by jamesmontemagno** [comment]
Hmmm...

The only thing we did was add on a few new attributes:

LocalizedIntroductoryPrice = IsiOS112 ? p.IntroductoryPrice.LocalizedPrice() : string.Empty,
                MicrosIntroductoryPrice = IsiOS112 ? (long)(p.IntroductoryPrice.Price.DoubleValue * 1000000d) : 0

What Xcode version are you compiling against?

**Comment by jamesmontemagno** [comment]
I wonder if the introductory price is null and maybe that is throwing an exception.... hmmmm

**Comment by jamesmontemagno** [comment]
This is why i don't like to add stuff to the API, everything is fragile!

**Comment by jamesmontemagno** [comment]
try out 138 for me

**Comment by Sebastian1989101** [comment]
Will try 138 tomorrow. I'm just preparing the next beta of my app which will run with the latest stable. I'm using the latest Xcode.

**Comment by Sebastian1989101** [comment]
After the first day testing this, the products seems to load and activate properly. I will include this beta as a test for my next beta release of my app to test it with real users.
