### ISSUE TITLE
Feature Request Auto-renewable subscription extended support

### ISSUE THREAD

**Issue by rspear34** [jamesmontemagno/InAppBillingPlugin#138]
Auto-renewable subscriptions have an expiration date that could change if the user cancels their subscription.  The expiration date will also be extended if the user allows the renewal to happen.  

It would be great if this package detected changes and renewal transactions and provided the expiration date.  I know that we also need to have a server process verifying receipts to be totally secure as well.

**Comment by hendeavors** [comment]
I think a typical Auto-renewable subscription, if cancelled, stays active until the end of the subscription term.

If a "refundable subscription" is supported by any store, it would be nice to have the implementation in this library.

**Comment by jamesmontemagno** [comment]
Implemented
