### ISSUE TITLE
URGENT - Android Issue for InAppBilling - Partial Data

### ISSUE THREAD

**Issue by khadeeja-alif** [jamesmontemagno/InAppBillingPlugin#139]
## Bug Information

Version Number of Plugin: 1.2.4
Device Tested On: All Android Devices
Simulator Tested On: _
=== Visual Studio Community 2017 for Mac ===

Version 7.4.1 (build 48)
Installation UUID: 1488c34f-2fe3-4b7b-bc18-0b8125bff107
Runtime:
	Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508010000

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	2.0.0-preview2-25407-01
	2.0.0-preview1-002111-00
	1.0.1
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	2.0.0-preview2-006497
	2.0.0-preview1-005977
	1.0.0-preview2-003131
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.2.1.28 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.8.1.28 (Visual Studio Community)
Hash: 3979d081
Branch: d15-6
Build date: 2018-03-09 16:22:34-0500

=== Xamarin.Android ===

Version: 8.2.0.16 (Visual Studio Community)
Android SDK: /Users/Shared/Android/sdk
	Supported Android versions:
		2.3    (API level 10)
		4.0.3  (API level 15)
		4.1    (API level 16)
		4.2    (API level 17)
		4.3    (API level 18)
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)
		8.0    (API level 26)
		8.1    (API level 27)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 26.0.1

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704010048
Git revision: 6a86203dd590c6cfdf814c8832d24d2ad1e2606f
Build date: 2018-03-20 11:16:55-04
Xamarin addins: 8d83cea9e4ae03cb0c14ba3fbaafdbb0cbd170e7
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Gorilla Player 1.2.0.6
Internet of Things (IoT) development (Preview) 7.1

### Steps to reproduce the Behavior
Debugging App when redirected to Subscription page.
### Expected Behavior
Show Active Subscription Details correctly - along with price.
### Actual Behavior
Gets Only ProductId & Name , Other Details not obtained. App Already registered in Play Store. Still same issue exists. Works fine in iOS.
### Code snippet
<img width="835" alt="screen shot 2018-04-17 at 1 03 42 pm" src="https://user-images.githubusercontent.com/14857549/38855021-f0174876-423f-11e8-9731-e566522508d4.png">
### Screenshots
Debug Android -
<img width="943" alt="screen shot 2018-04-17 at 12 58 20 pm" src="https://user-images.githubusercontent.com/14857549/38854930-b0e1297e-423f-11e8-98ca-4428fb9d170c.png">
Debug iOS -
<img width="803" alt="screen shot 2018-04-17 at 2 32 53 pm" src="https://user-images.githubusercontent.com/14857549/38859914-a1dc9ed8-424c-11e8-9596-1c4ba699d23b.png">

**Comment by muhaym** [comment]
@jamesmontemagno  @prashantvc  

I debugged manually by adding the Source directly to the project and was surprised to see that 
when
`var x= new InAppBillingProduct();`
is used, it's not initializing other properties like CurrencyCode, Description, LocalizedPrice, etc. Only items created are Name and ProductId.

After checking, I found that Linker Settings was Link All and Linker was aggressively removing other properties.

Adding Plugin.InAppBilling;Plugin.InAppBilling.Abstractions into Linker exclusion list helped.

Do you think adding Preserve attribute in Abstraction project would help?

**Comment by EmilAlipiev** [comment]
how did you achieve to attach source code directly? I am not even able to do that. when I do that   Plugin.InAppBilling.InAppBillingImplementation.HandleActivityResult line is not recognized. I tried adding reference of  billing android project also but still doesnt work for me

     protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
        {
            base.OnActivityResult(requestCode, resultCode, data);
            Plugin.InAppBilling.InAppBillingImplementation.HandleActivityResult(requestCode, resultCode, data);
              
        }

**Comment by muhaym** [comment]
@EmilAlipiev  What's the problem you are facing at first place?

**Comment by EmilAlipiev** [comment]
When I try to attach the source code directly on my project, I am getting build error as below. not sure if that it something to do with Current Activity plugin

![image](https://user-images.githubusercontent.com/10422347/39184325-48d1448e-47c3-11e8-8705-a85bc1f00851.png)

**Comment by muhaym** [comment]
@EmilAlipiev Add Reference to All Projects except iOS project, uninstall the nugets which you had at first place.

**Comment by EmilAlipiev** [comment]
For example, Nuget installation doesnt add reference of Plugin.InAppBilling.Android on my Droid project. how does it work using nuget?

**Comment by muhaym** [comment]
@EmilAlipiev Nuget works with Bait and Switch https://log.paulbetts.org/the-bait-and-switch-pcl-trick/

**Comment by EmilAlipiev** [comment]
I have followed these steps
1) uninstalled package from all projects
2) added references on android project
![image](https://user-images.githubusercontent.com/10422347/39184684-af0ca724-47c4-11e8-9773-70cb45e6c820.png)

3) added reference on .net standard2.0 shared project

![image](https://user-images.githubusercontent.com/10422347/39184769-07a69ad4-47c5-11e8-906e-965e1738ffae.png)


but it still doesnt recognize  Plugin.InAppBilling.InAppBillingImplementation.HandleActivityResult in my mainactivity.

that works fine if i just use nuget.

**Comment by muhaym** [comment]
Check Plugin.InAppBilling.Android, it has Plugin.CurrentActivity nuget, this seems to be target version issue. Just update the nuget in it

**Comment by EmilAlipiev** [comment]
it shows that it is installed fine. plugin has standard 1.6 version. i thought that this could be the issue but even upgrading to 2.0.1 didnt help me

![image](https://user-images.githubusercontent.com/10422347/39187383-7415cac0-47cd-11e8-98ba-0f06d73f8a09.png)

**Comment by EmilAlipiev** [comment]
Do you have any sample project maybe you achieve to attach it? i can compare this way

**Comment by jamesmontemagno** [comment]
Closing for now as it was fixed up with linker. Will create a new issue to add preserve flags

**Comment by jamesmontemagno** [comment]
1.2.4.140-beta
