### ISSUE TITLE
Testing doesnt work in DEBUG but works in RELEASE

### ISSUE THREAD

**Issue by EmilAlipiev** [jamesmontemagno/InAppBillingPlugin#141]
Hi @jamesmontemagno 

I dont know why but although I have followed all advised points, even signing in Debug, IAP always returns "Item not available" error.  if I run it in release, it works fine. maybe it is the way it is, we still can debug in release more by enabling below, no problem. I only wanted draw your attention because documentation is incomplete and it caused me lose several hours trying to make it work in debug mode. 
if that is the case for every one, we should extend the documentation or just as annotation for new comers.

This is at least the case for Android

![image](https://user-images.githubusercontent.com/10422347/39198762-2b9f7f14-47e8-11e8-9aed-5c81038f7ffd.png)

**Comment by jamesmontemagno** [comment]
https://jamesmontemagno.github.io/InAppBillingPlugin/TestingAndTroubleshooting.html

**Comment by EmilAlipiev** [comment]
I went through all and testing on a real device, signed it exactly the same as what is in the beta version. this is just not working in debug mode but works in release mode. I used exact same parameters and exact the same account for purchase (not my developer account). error is not one of the listed there for android. error says that "item is not available". but Item is available. if I just change to "release" and try exact same item with exact same account, it works fine.

**Comment by jamesmontemagno** [comment]
Something else must be off in the signing or app version alignment. i have this working in debug for me, it is highly complicated to setup which is why i outline it there. Double check your csproj.

**Comment by EmilAlipiev** [comment]
this is just the problem. I set up exactly same for debug and release, even had check list in front of me, all 100% the same and was struggling with debug, pulling my hair off for hours and just switch to release, it worked like a charm. anyway i am fine with debugging in release. just wanted to create this for anybody else having same issue. thanks
