### ISSUE TITLE
Using promo code on Android returns null purchase

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/InAppBillingPlugin#143]
See #100 for reference.

**Comment by EmilAlipiev** [comment]
Hi James,

i would like to debug this issue attaching the source code on my project but i am having problem to get this working for android, although works for uwp. in the mainactivity, it doesnt recognize 
  `Plugin.InAppBilling.InAppBillingImplementation.HandleActivityResult(requestCode, resultCode, data);`

this is how my solution and references looks like. what is the trick here? my project is standard 2.0.1 and in app biliign 1.6. could this be the problem? if i install plugin all looks fine and references seems also same as plugin adds in each project

![image](https://user-images.githubusercontent.com/10422347/39310833-bfdd30ca-496b-11e8-9523-1aacf7bb305d.png)

**Comment by DevEddy** [comment]
I've tested this with the nuget 1.4.1.157-beta. Same result.

`const string PAYLOAD = "cloudmatic_app_payload_id";`
`public const string DESIGN = "app_design_id";`
`var purchase = await billing.PurchaseAsync(DESIGN, ItemType.InAppPurchase, PAYLOAD);`

purchase is null when I use a promo code.

I think the [PurchasesUpdatedListener](https://developer.android.com/reference/com/android/billingclient/api/PurchasesUpdatedListener#onPurchasesUpdated(int,%20java.util.List%3Ccom.android.billingclient.api.Purchase%3E)) is required for this step. Maybe I'm wrong.

Google docs say:
> To support promotion codes, your app must call the [queryPurchases()](https://developer.android.com/reference/com/android/billingclient/api/BillingClient.html#queryPurchases(java.lang.String)) method whenever the app starts or resumes. 

Also
> Your Activity's [onPurchasesUpdated()](https://developer.android.com/reference/com/android/billingclient/api/PurchasesUpdatedListener.html#onPurchasesUpdated(int,%20java.util.List%3Ccom.android.billingclient.api.Purchase%3E)) method receives a response intent identifying when a purchase is completed. However, your app should still call [queryPurchases()](https://developer.android.com/reference/com/android/billingclient/api/BillingClient.html#queryPurchases(java.lang.String)) in onStart() and onResume(), in the case the purchase and consumption workflow didn't complete. For example, if the user successfully redeems a promo code and then your app crashes before the item is consumed, your app still receives information about the purchase when the app calls [queryPurchases()](https://developer.android.com/reference/com/android/billingclient/api/BillingClient.html#queryPurchases(java.lang.String)) on its next startup.

> Your app should also support the scenario where a user redeems a promo code in the Play Store app while the app is running. Your app can find out about the redemption through the [onPurchasesUpdated()](https://developer.android.com/reference/com/android/billingclient/api/PurchasesUpdatedListener.html#onPurchasesUpdated(int,%20java.util.List%3Ccom.android.billingclient.api.Purchase%3E)) listener.

// EDDY

**Comment by chrisfoulds** [comment]
Also happens for test subscription purchases

**Comment by jamesmontemagno** [comment]
#268 dup
