### ISSUE TITLE
OnServiceConnected crashes on 5.1 Android devices 

### ISSUE THREAD

**Issue by Toine-db** [jamesmontemagno/InAppBillingPlugin#144]
According to Google play crash reports my users seem to have a crashing app when they use 5.1 devices, all other versions seem to work fine. 

[stacktrace](https://gist.github.com/Toine-db/93ba7014d33720e0c043a2a1bc76a7c5)

InAppBillingServiceConnection.onServiceConnected JavaProxyThrowable thrown more then once and I can't reproduce this issue because the lack of a real 5.1 device. Anyone any ideas/suggestions looking at the (small) stacktrace? 
PS: I already put the OnActivityResult() code in a try/catch, just to be sure, but no luck.

Found [same looking issue](https://github.com/jamesmontemagno/InAppBillingPlugin/issues/96) but this says something about navigating, while my app does NOT navigate at all during purchase proces, only what the plugin is triggering itself. 

## Bug Information

Version Number of Plugin: 1.2.4 (Android only)
Device Tested On: 
- Samsung Galaxy Grand Prime (grandprimeve3g), 1024MB RAM, Android 5.1
- rs617, Android 5.1
Simulator Tested On: - 
Version of VS: 2017 - 15.6.6
Version of Xamarin: 4.9.0.753
Versions of other things you are using: 
- Xamarin Android: 8.2.0.16
- Min Android SDK: 19
- Target Android SDK: 27 (8.1)
- Compile Android SDK: 27

### Steps to reproduce the Behavior
Can't reproduce it currently because lack of real 5.1 device.
But it happend more then once, according to Google Play analytics

**Comment by jamesmontemagno** [comment]
Duplicate #129
