### ISSUE TITLE
Autorenewing subscription on Android returns null

### ISSUE THREAD

**Issue by JimWolfCo** [jamesmontemagno/InAppBillingPlugin#145]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 1.24
Device Tested On: Samsung Note 8
Simulator Tested On:
Version of VS: 2017
Version of Xamarin: 2.5.1.44934
Versions of other things you are using:

### Steps to reproduce the Behavior
Make purchase successfully or android subscription item iOS_SubscriptionId = "com.uasidekick.mon";
Pops up the Google Play store subscription purchase which is successfully purchased. Can confirm in play store under subscriptions.
### Expected Behavior
return a receipt from var purchase = await CrossInAppBilling.Current.PurchaseAsync(iOS_SubscriptionId, ItemType.Subscription, "");
### Actual Behavior
purchase is null
### Code snippet
		public static async Task<PurchaseResult> PurchaseSubscription()
		{
			data.Purchases ps = new data.Purchases();

			try
			{
				var connected = await CrossInAppBilling.Current.ConnectAsync();
				if (!connected)
				{
					//Couldn't connect
					return PurchaseResult.CannotConnect;
				}

				var products = await CrossInAppBilling.Current.GetProductInfoAsync(ItemType.Subscription, new String[] { iOS_SubscriptionId });
				bool found = false;

				if (products != null)
				{
					foreach (var product in products)
					{
						if (product.ProductId.Equals(iOS_SubscriptionId))
						{
							ps.LocalizedPrice = product.LocalizedPrice;
							ps.CurrencyCode = product.CurrencyCode;
							ps.MicroPrice = product.MicrosPrice;
							ps.Name = product.Name;
							ps.ProductId = product.ProductId;
							found = true;
							break;
						}
					}
				}
				if (!found)
				{
					return PurchaseResult.CannotFindProduct;
				}

				var purchase = await CrossInAppBilling.Current.PurchaseAsync(iOS_SubscriptionId, ItemType.Subscription, "");
					if (purchase == null)
					{
.....						ENDS UP HERE WITH NULL
						return PurchaseResult.PurchaseFailed;
					}
					else
					{
						//Purchased now we can consume
					}
.....

**Comment by jamesmontemagno** [comment]
This is a bug with passing in "" , please pass in literally anything else or use the latest preview.

**Comment by JimWolfCo** [comment]
Thanks this did fix this problem but I have another issue or question. I am getting a receipt when doing an auto renewing subscription purchase on Google Play but not getting one (null) from Apple when running in debug or a release version in TestFlight. Should I expect a receipt from Apple when in TestFlight? If I should then what might I be doing wrong? Similiar code works fine with a non-subscription purchase. The subscription item on Apple has been approved. Maybe Im doing something really stupid but it is confusing.

Thanks
Jim Wolf

       public static string iOS_NDRProductId = "com.uasidekick.ndr";
       public static string iOS_SubscriptionId = "com.uasidekick.mon";

                           var purchase = await CrossInAppBilling.Current.PurchaseAsync(iOS_SubscriptionId, ItemType.Subscription, ps.pilot);
                           if (purchase == null)
                           {

                                  //Not purchased
                                  return PurchaseResult.PurchaseFailed;
                           }

                           ps.date = DateTime.Now;
                           ps.type = "Monthly";
                           if (Device.RuntimePlatform == Device.iOS)
                           {
                                  ps.Source = "IOS";
                           }
                           else ps.Source = "Android";
                           ps.receipt = purchase.PurchaseToken;
                           ps.valid = 1;
                           ps.start = ps.date;
                           ps.finish = ps.date.AddMonths(1);
                           data.Purchases.Insert(ps);
                           return PurchaseResult.Success;
                     }
