### ISSUE TITLE
On back button pressed the process dialog stops spinning and freezes the app

### ISSUE THREAD

**Issue by heathbm** [jamesmontemagno/InAppBillingPlugin#146]
## Bug Information

Version Number of Plugin: 1.2.5
Device Tested On: S9
Simulator Tested On:
Version of VS: 15.6.7
Version of Xamarin: Latest
Versions of other things you are using:

### Notes
This is in a fragment
### Steps to reproduce the Behavior
Implemented getting started code
### Expected Behavior
when the user presses back button for the process dialog to disappear 
### Actual Behavior
following break points, it disconnects, but the process dialog stops spinning and freezes the whole app 
### Code snippet
                subBtn.Click += async delegate
                {
                        var billing = CrossInAppBilling.Current;
                        try
                        {
                            var productId = "mysub";

                            bool connected = await billing.ConnectAsync();

                            if (!connected)
                            {
                                //Couldn't connect to billing, could be offline, alert user
                                return;
                            }

                            //try to purchase item
                            var purchase = await billing.PurchaseAsync(productId, ItemType.InAppPurchase, "apppayload");
                            if (purchase == null)
                            {
                                //Not purchased, alert the user
                            }
                            else
                            {
                                //Purchased, save this information
                                var id = purchase.Id;
                                var token = purchase.PurchaseToken;
                                var state = purchase.State;
                            }
                        }
                        catch (System.Exception ex)
                        {
                            System.Diagnostics.Debug.WriteLine(ex);
                            //Something bad has occurred, alert user
                        }
                        finally
                        {
                            //Disconnect, it is okay if we never connected
                            await billing.DisconnectAsync();
                            billing.Dispose();
                        }
                };

// This is in the home activity and is hit
        protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
        {
            base.OnActivityResult(requestCode, resultCode, data);
            InAppBillingImplementation.HandleActivityResult(requestCode, resultCode, data);
        }

**Comment by EmilAlipiev** [comment]
Did you try latest Version?  There is newer Version i saw today

**Comment by jamesmontemagno** [comment]
fixed
