### ISSUE TITLE
PurchaseToken is always NULL in the iOS plugin

### ISSUE THREAD

**Issue by jahlen** [jamesmontemagno/InAppBillingPlugin#147]
Hi,

I was trying to implement server side verification of iOS InApp purchases, and never was able to get anything but NULL in the PurchaseToken.

I checked the source code and noticed that the PurchaseToken is never set from either **InAppBillingImplementation.PurchaseAsync** or **InAppBillingImplementation.ToIABPurchase**. 

Probably this is because there is nothing called PurchaseToken in iOS, but instead a TransactionReceipt (which can be validated server side against https://buy.itunes.apple.com/verifyReceipt or https://sandbox.itunes.apple.com/verifyReceipt). 

I see that the IInAppBillingVerifyPurchase callback is passed a receipt, but that is the receipt for the app (NSBundle.MainBundle.AppStoreReceiptUrl) instead of the InAppPurchase receipt.

### Suggestions
* Pass the TransactionReceipt in the PurchaseToken field
* In the IInAppBillingVerifyPurchase callback, make sure to pass the TransactionReceipt from the InAppPurchase, not the app

I can provide the code changes if that helps.

Kind Regards
Johan

**Comment by erviem99** [comment]
Note that TransactionReceipt is deprecated!

Apple recommends using the mainBundle's appStoreReceiptURL instead.
