### ISSUE TITLE
IInAppBillingVerifyPurchase 

### ISSUE THREAD

**Issue by tjismh** [jamesmontemagno/InAppBillingPlugin#149]
I am struggling to understand exactly what data/format is sent to the IInAppBillingVerifyPurchase implementation for iOS (VerifyPurchase method).

The documentation indicates signedData: Full Receipt as a string in Base 64 Encoding.

However if I try to decode the Base64 string the data does not make sense and when I forward this data to the server to verify with Apple I get a 21002 status indicating it is a bad receipt.

What am I missing here?

**Comment by tjismh** [comment]
I resolved the issue

**Comment by jamesmontemagno** [comment]
Can you share what you did so others have insight. Also I can improve the docs too if so.
