### ISSUE TITLE
Unfinished transactions iOS 

### ISSUE THREAD

**Issue by Sebastian1989101** [jamesmontemagno/InAppBillingPlugin#15]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 1.1.0.12-beta
Device Tested On: iPhone 6S
Simulator Tested On: multiple iOS

### Expected Behavior
A transaction is finished after the purchase or restore method is called (problem only occured before version 1.1.0.15-beta and only on iOS).

### Actual Behavior
A transaction stays open from version 1.1.0.12-beta (seems to be fixed in 1.1.0.15-beta). The testing device reminds me over and over again about the open transaction and requested me to sign in into my sandbox account but nothing happens, even if I do. See: http://stackoverflow.com/questions/2124895/stuck-with-sandbox-account (with working and tested solution). 

### Steps to reproduce the Behavior 
Purchase a product, delete the app, restore the product with the purchase method - problem created.

**Comment by jamesmontemagno** [comment]
That is correct, but if you have .15-beta install and call the product status it will clear them all out.
