### ISSUE TITLE
Requires Current Activity Plugin, which is not compatible with netstandard 2.0

### ISSUE THREAD

**Issue by BillyMartin1964** [jamesmontemagno/InAppBillingPlugin#151]
Plugin.CurrentActivity 2.0.0.6-beta is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Plugin.CurrentActivity 2.0.0.6-beta supports: monoandroid44 (MonoAndroid,Version=v4.4)

**Comment by jamesmontemagno** [comment]
You only install current activity in Android project

**Comment by Charuwaka** [comment]
Hi James,

i am Getting Error as following , i am trying to install only for Android with Xamarin Forms 3.4, can you please help me with this ?

All packages and projects are compatible with MonoAndroid,Version=v8.1.
Package restore failed. Rolling back package changes for
