### ISSUE TITLE
Android IInAppBillingVerifyPurchase

### ISSUE THREAD

**Issue by tjismh** [jamesmontemagno/InAppBillingPlugin#154]
Curious why productId and transactionId are not set to  IInAppBillingVerifyPurchase.VerifyPurchase in the Android implementation?

**Comment by jamesmontemagno** [comment]
They aren't needed really at all as you are just verifying the signed data and signature.

Do you need them for something?

**Comment by tjismh** [comment]
they come in handy for server side verification and processing of GCP notifications

**Comment by Farbklex** [comment]
It is also rather confusing if you want to access this information directly from the methods parameters only to realize that you have to parse it from the JSON in signedData yourself.
