### ISSUE TITLE
Retrieving SKDownloads

### ISSUE THREAD

**Issue by sethom** [jamesmontemagno/InAppBillingPlugin#155]
I didn't see anything in the docs regarding retrieving content downloadable as a result of an IAP. Is there a way with this library to get access to the transaction (iOS) so that I can retrieve any SKDownloads that are included with the transaction?

**Comment by jamesmontemagno** [comment]
Out of the scope for this project. Would highly recommend if you are in this complex that you hit the APIs directly.

**Comment by sethom** [comment]
Sounds good, thanks..
