### ISSUE TITLE
Cancelled Subscription is returned when after it is expired

### ISSUE THREAD

**Issue by EmilAlipiev** [jamesmontemagno/InAppBillingPlugin#156]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:1.2.5
Device Tested On: Android device
Simulator Tested On: 
Version of VS: 2017
Version of Xamarin: 3.0
Versions of other things you are using:

### Steps to reproduce the Behavior
- Create test subscription which renews every 5 mins
- Cancel the subscription
- Check the values returned using 
 `var purchases = await billing.GetPurchasesAsync(ItemType.Subscription);`
### Expected Behavior
- If I cancel a subscription; i think that purchases shouldnt consist expired purchase
### Actual Behavior
It returns Purchase with status purchased and autorenew =false

In this case how can we understand if a purchase is active when it is cancelled ? 

I am not sure if that is only the case for Test Subscriptions but I expect that it should be same as a live one

**Comment by EmilAlipiev** [comment]
This issue seems to be googles error. there are many posts on SO like this one about this  and I really dont see a good solution. it is really strange from google. 
What happens is subscription seems to be cached in google play cache and until you restart the phone or clear google play cache, cancelled subscription  is always returned and status is purchased. 

https://stackoverflow.com/questions/37635996/how-to-determine-if-user-cancels-google-play-subscription

**Comment by jamesmontemagno** [comment]
Closing as found in SO
