### ISSUE TITLE
Amazon IAP Revisited

### ISSUE THREAD

**Issue by BillyMartin1964** [jamesmontemagno/InAppBillingPlugin#158]
It seems most of us would like to release our apps on both Google and Amazon.

Is there any way that Xamarin Forms can detect, not the device nor the platform, but **where the app was purchased**?

If that were possible, this plugin could easily have a switch statement for the various app stores.

I know it would require extra work, James, but it would be well worth it. Thanks.

**Comment by jamesmontemagno** [comment]
I have no plans to add Amazon IAP.

Anyone could easily take this library, implement the API for Amazon and release a nuget on top of it that depends on this one. That would be my recommendation.

**Comment by BillyMartin1964** [comment]
Are there some tutorials on this somewhere?
