### ISSUE TITLE
Exception when using promotional time in iOS

### ISSUE THREAD

**Issue by aortega3512** [jamesmontemagno/InAppBillingPlugin#160]
We are using this code to get information about packages in iOS store:

var items = await billing. GetProductInfoAsync(ItemType.Subscription, productIds);

where productIds is the array of the products. This works perfectly until I select on iOS store to use a  Introductory Price, with one week free. When we change that on the store then an exception 

System.Argument Null Exception. 
Message: Value cannot be null
Parameter name: value

Version Number of Plugin: 1.2.5
Device Tested On: iPhone 6s
Simulator Tested On: 
Version of VS: Visual studio community 2017 
Version of Xamarin: 2.3.4.270 (Xamarin forms)
Versions of other things you are using:

### Steps to reproduce the Behavior
Add product in itunesConnect as subscription price
Test GetProductInfoAsync works correct
Change in iTunesConnect the price adding introductory price, free 1 week 
Launch exception.

**Comment by jamesmontemagno** [comment]
Upgrade to latest.
