### ISSUE TITLE
Android: After clicking outside of the purchase pop-up PurchaseAsync runs forever

### ISSUE THREAD

**Issue by alierdogan70** [jamesmontemagno/InAppBillingPlugin#163]
## Bug Information
I run this code via button:

var purchase = await billing.PurchaseAsync(productId, ItemType.InAppPurchase, PayLoad);

 and Android buy item popup appears. If I click to gray area outside of the white popup, the popup closes but the PurchaseAsync method runs forever. Right after, the second time I touch to buy button, the popup does not appear and the method returns null without any exeception.

Version Number of Plugin: 2.0.0
Device Tested On:  Samsung Galaxy Fit -  Android 19
Simulator Tested On: Android 27 x86 
Version of VS: VS for Mac Version 7.5 (build 1254) / Also tried on Visual Studio for Windows
Version of Xamarin: Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)
Versions of other things you are using:
Target Android SDK 27

### Steps to reproduce the Behavior
+ Click to buy button
+ After the popup appers click the gray area
+ Click to buy button again
+ Purchase pop up never appears again

### Expected Behavior
The popup should appear again
### Actual Behavior
The popup does not appear again
### Code snippet

```     
var billing = CrossInAppBilling.Current;
  
     
           try
            {
                var connected = await billing.ConnectAsync();
                if (!connected)
                {
                    //we are offline or can't connect, don't try to purchase
                    return false;
                }
               

                
                //check purchases
				var purchase = await billing.PurchaseAsync(productId, ItemType.InAppPurchase, PayLoad);

                //possibility that a null came through.
                if (purchase == null)
                {
                    return false;
                    //did not purchase
                }
                else if (purchase.State == PurchaseState.Purchased)
                {
                    return true;
                    //purchased!

                }
```

**Comment by alierdogan70** [comment]
Even after successful purchase the Purchase Async method runs forever. I waited for 5 minutes to see if it is going to finish working but it did not. Purchasing works correctly but the method never returns a value.

**Comment by EmilAlipiev** [comment]
try passing payload as empty string like below and make sure that you are using the latest version of the plugin.

  var purchase = await current.PurchaseAsync(productId, iapType, "");

**Comment by jamesmontemagno** [comment]
Did you add the code required on Android: https://jamesmontemagno.github.io/InAppBillingPlugin/GettingStarted.html

**Comment by T-0pel** [comment]
@jamesmontemagno You are right, I re-read the getting started instructions after I have posted the reply and I have missed the OnActivityResult method override. I must have skipped the whole section after reading that I do not need to add the permissions manually.

It is working correctly now, sorry for wasting your time. I would assume @alierdogan70 had the same problem, so I think the issue can be closed.
