### ISSUE TITLE
Cannot modify user's subscription in iOS

### ISSUE THREAD

**Issue by basakserit** [jamesmontemagno/InAppBillingPlugin#166]
I am trying to modify subscription of the user from app inside within the same subscription group. During _PurchaseAsync_ first pop-up is for confirming the purchase which is "Do you want to upgrade to 1 Month auto-renewable subscription? Your upgrade will start now. You'll receive a refund for the remaining time of your 1-year subscription to yearly auto-renewable." After clicking "Continue", I got a General Error as below. Is the issue related to refunding and sandbox?

Exception:
_Plugin.InAppBilling.Abstractions.InAppBillingPurchaseException: Cannot connect to iTunes Store_

## Bug Information

Version Number of Plugin: 2.0.0
Device Tested On: iPhone 6p
Version of VS: 7.5
Version of Xamarin: Xamarin.iOS Version: 11.6.1.4

### Steps to reproduce the Behavior
- User A buys a subscription with his Apple ID.
- User A updates his subscription with the same Apple ID.
- The system displays a pop-up for confirmation
- The system throws an error which is "General Error, Cannot connect to iTunes Store"

### Expected Behavior
Users should update their subscription with the other ones which are in the same subscription group.

**Comment by nexxuno** [comment]
I could look into this one too as soon as my colleague will enable subscriptions on apple store (should be in the next weeks). @jamesmontemagno : from a plugin point of view this functionality can be paired with the one I'm fixing in #26 on the android side, do you agree? Can you approve (or reject) my pull request for the Android part and I will extend it if it is needed to fix this bug?

**Comment by jamesmontemagno** [comment]
This is implemented now
