### ISSUE TITLE
How to acquire Android purchase data and data signature from InAppBillingPurchase for verification?

### ISSUE THREAD

**Issue by SuperStromboli** [jamesmontemagno/InAppBillingPlugin#167]
I'm definitely missing something here.  I don't see these properties available in the Purchase object.

Seems like maybe the overloading of PurchaseAsync to include the IInAppBillingVerifyPurchase implementation is the only flow?

**Comment by jamesmontemagno** [comment]
See: https://jamesmontemagno.github.io/InAppBillingPlugin/SecuringPurchases.html

**Comment by SuperStromboli** [comment]
Hooked up to the overloaded function then. Thanks.
