### ISSUE TITLE
Android IInAppBillingVerifyPurchase - documentation

### ISSUE THREAD

**Issue by curelom** [jamesmontemagno/InAppBillingPlugin#168]
documentation is out of date for IInAppBillingVerifyPurchase - SecuringPurchases

The following methods don't look like they exist anymore.

var key1Transform = Plugin.InAppBilling.InAppBillingImplementation.InAppBillingSecurity.TransformString(key1, 1);
            var key2Transform = Plugin.InAppBilling.InAppBillingImplementation.InAppBillingSecurity.TransformString(key2, 2);
            var key3Transform = Plugin.InAppBilling.InAppBillingImplementation.InAppBillingSecurity.TransformString(key3, 3);

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

**Comment by jamesmontemagno** [comment]
This exist, but only in Android so you need to be inside of an Android project to use this code.
