### ISSUE TITLE
Question: does the plug-in support IPv6?

### ISSUE THREAD

**Issue by klint01** [jamesmontemagno/InAppBillingPlugin#17]
I submitted my app for review with Apple and they found a bug related to making a purchase on a IPv6 Network.  Since I am not specifically calling any IP addresses in my app and the issue is related specifically to making purchases, I am wondering if it is related to the plug-in.

Another piece of information, I have your Xam.Plugin.Connectivity installed which I understands supports IPv6.

Again not sure if this is the issue, but hoping to rule it out.  Thanks!

Version Number of Plugin: 1.1.0.23 -beta
Device Tested On: iPad running iOS 10.2.1 on Wi-Fi connected to an IPv6 network

### Expected Behavior
successful completion of in-app purchase

### Actual Behavior
unable to complete an in-app purchase

**Comment by jamesmontemagno** [comment]
Has absolutely no issues at all and I have 2 apps in the app store that support it.

**Comment by klint01** [comment]
I figured as much, but wanted to cover my basis.  I've read a number of complaints be developers that apple has rejected their app for the same reason, changed nothing, resubmitted and it passed.  My test work for me, so I sent it back to them asking to retest.  Thank!
