### ISSUE TITLE
ValidateReceipt crash in iOS

### ISSUE THREAD

**Issue by erviem99** [jamesmontemagno/InAppBillingPlugin#170]
## Bug Information

Version Number of Plugin: 2.0.0
Device Tested On: iPhone 6s
Version of VS: Visual Studio for Mac 7.5.2

### Steps to reproduce the Behavior
Make a call to GetPurchasesAsync when there has been no purchases

### Expected Behavior
Should return no purchases

### Actual Behavior
Crashes in ValidateReceipt with a null exception

NSData.FromUrl(NSBundle.MainBundle.AppStoreReceiptUrl) will return null

This is documented behaviour here:
https://developer.apple.com/documentation/foundation/nsbundle/1407276-appstorereceipturl

**Comment by jamesmontemagno** [comment]
#TotallyFixed!
