### ISSUE TITLE
How can I purchase an app (iOS/Android) that is in trial mode?

### ISSUE THREAD

**Issue by Fox9MonoGame** [jamesmontemagno/InAppBillingPlugin#171]
https://jamesmontemagno.github.io/InAppBillingPlugin/
I have read your tutorial about purchasing consumable in-app products. But there is no section in your tutorial on how purchasing an app that is currently in trial mode. I have created a game that is in trial mode, and the user can buy the game if he taps on a "BUY IT" button in the game.

How can I get the current license information of the app and how can I initiate the purchase?
Could you please explain me how to do that? Maybe with a code sample?

**Comment by Fox9MonoGame** [comment]
Can I use a non-consumable in-app product in this case?
If  the user taps the "BUY IT" button in the game, then a non-consumable in-app product would be purchased and the user has access to the full game.

**Comment by jamesmontemagno** [comment]
Correct, a non-consumable is a 1 time purchase. Seems like the correct route if you are implementing it yourself.
