### ISSUE TITLE
Version 2 IOS hangs on autorenewing subscription purchase

### ISSUE THREAD

**Issue by JimWolfCo** [jamesmontemagno/InAppBillingPlugin#172]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.0
Device Tested On: IPhone 5s Simulator
Simulator Tested On: MacInCloud
Version of VS: 2017
Version of Xamarin: 3.1.0.583944
Versions of other things you are using: windows 10, MacOs 10.13.15
### Steps to reproduce the Behavior

Due to lack of receipt upgraded from 1.24 to 2.0 InAppBillingPlugin. Previously made purchase successfully with Apple subscription item iOS_SubscriptionId = "com.uasidekick.mon" in1.24 but had no receipt;
Version 2.0 pops up the Apple store subscription purchase, shows price and allows confirmation in sandbox. Hangs at that point and never returns.

### Expected Behavior
Return from 	var purchase = await CrossInAppBilling.Current.PurchaseAsync(iOS_SubscriptionId, ItemType.Subscription, ps.pilot);
 
with a valid purchase  non null item and receipt.

### Actual Behavior

Hangs and never returns from PurchaseAsynch. Previous function returned a valid subscription id to use for the call.

### Code snippet
```
		public static string iOS_SubscriptionId = "com.uasidekick.mon";
...
				var purchase = await CrossInAppBilling.Current.PurchaseAsync(iOS_SubscriptionId, ItemType.Subscription, ps.pilot); //where ps.pilot is pilot string
				if (purchase == null)
....
```

**Comment by jamesmontemagno** [comment]
Totally tested this out today during a list stream on twitch and seems to be working great!
