### ISSUE TITLE
Payment Processor Stripe

### ISSUE THREAD

**Issue by amolk7** [jamesmontemagno/InAppBillingPlugin#174]
I am looking to implement  payment processor stripe.
Can you please help me.

**Comment by jamesmontemagno** [comment]
https://xamarinhelp.com/stripe-in-xamarin/

**Comment by amolk7** [comment]
Hi jamesmontemagno,
Thank you for quick response.
Above given like is about Stripe card payment. 

I am looking for Google + Apple pay with Stripe as payment processor.
Can you please advise me on this.
