### ISSUE TITLE
Missing the last purchase when calling GetPurchasesAsync

### ISSUE THREAD

**Issue by jonathanfontaine** [jamesmontemagno/InAppBillingPlugin#175]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.0.0
Device Tested On: iPhone
Simulator Tested On:
Version of VS: 15.7.4
Version of Xamarin: 4.10.10.2
Versions of other things you are using:
Xamarin.iOS SDK 11.12.0.4

### Steps to reproduce the Behavior

Call _GetPurchasesAsync()_ in auto-renewable subscription mode (each month).

### Expected Behavior

Get all the purchases of the user.
**On July 4th, 2018**, everything was OK. I got 2 purchases because the user made the initial purchase on May 14th, 2018. Here is the purchases I got :

```
{Plugin.InAppBilling.Abstractions.InAppBillingPurchase}
  Id: ""420000385937917""
  TransactionDateUtc: 14/06/2018 09:40:37
  ProductId: ""my.product.id""
  AutoRenewing: False
  PurchaseToken: """"
  State: Purchased
  ConsumptionState: NoYetConsumed
  Payload: null
{Plugin.InAppBilling.Abstractions.InAppBillingPurchase}
  Id: ""420000403386838""
  TransactionDateUtc: 14/05/2018 09:40:37
  ProductId: ""my.product.id""
  AutoRenewing: False
  PurchaseToken: """"
  State: Restored
  ConsumptionState: NoYetConsumed
  Payload: null"
```

### Actual Behavior

**Since July 5th, 2018**, I only get 1 purchase and I really don't get why. The user didn't change anything ! Any idea ? Why _GetPurchasesAsync()_ doesn't return the last purchase anymore ?
Please note that the user's subscription is still active in his Apple account and "will be automatically renewed on July 14th, 2018".

```
{Plugin.InAppBilling.Abstractions.InAppBillingPurchase}
  Id: ""420000403422144""
  TransactionDateUtc: 14/05/2018 09:40:37
  ProductId: ""my.product.id""
  AutoRenewing: False
  PurchaseToken: """"
  State: Restored
  ConsumptionState: NoYetConsumed
  Payload: null"
```

### Code snippet

```
var purchases = CrossInAppBilling.Current.GetPurchasesAsync(ItemType.Subscription).Result;
```

**Comment by WongWeiLoon** [comment]
Hi Jonathan, may I know did you get any solutions for this issues? :)

**Comment by jonathanfontaine** [comment]
Hi @WongWeiLoon, not yet. Are you experiencing the same issue ?

**Comment by WongWeiLoon** [comment]
yes, me too. I'm looking for solutions for this issues.

**Comment by jonathanfontaine** [comment]
OK. Well that's strange because without changing any code, a user now receive again all his InAppBillingPurchases. But some other users still don't.

I supposed it was maybe a problem coming from Apple, so I posted an issue on Apple's forum. No answer yet.

I will try to call Apple's servers by myself without using InAppBillingPlugin to understand where the problem comes from.

Did you recently change your inapp purchase length ? I recently changed it from 1 month to 3 months, I'm wondering if it could be the cause.

**Comment by WongWeiLoon** [comment]
Just for your information, I didn't change any in-app purchase length. Our app only provide 1 month and 1 year subscription. 
And, I hit a similar issues as yours, sometimes get only 1 purchase record, sometimes get full records. Hmmm... I'm still thinking it's caused by Apple or this plugin .....

**Comment by jonathanfontaine** [comment]
OK. And for how long are you experiencing this issue ? In my case it's about 1 month.

**Comment by WongWeiLoon** [comment]
around 2 weeks ago

**Comment by jonathanfontaine** [comment]
Same here

**Comment by jonathanfontaine** [comment]
I didn't find what's wrong with **InAppBillingPlugin** so when I don't receive a good response from **InAppBillingPlugin**, I call _"https://buy.itunes.apple.com/verifyReceipt"_ by myself and check the json from Apple.

**Comment by WongWeiLoon** [comment]
ya, agreed. I think right now the best way is to validate the receipt with _verifyReceipt_ server.

**Comment by jamesmontemagno** [comment]
Are you still experiencing this issue? When I restore I am finding the original transactions for the users in the queue:

```
foreach (var trans in SKPaymentQueue.DefaultQueue.Transactions)
			{
				var original = FindOriginalTransaction(trans);
				if (original == null)
					continue;

				allTransactions.Add(original);
			}

			// Start receiving restored transactions
			SKPaymentQueue.DefaultQueue.RestoreCompletedTransactions();

			return tcsTransaction.Task;
		}



		static SKPaymentTransaction FindOriginalTransaction(SKPaymentTransaction transaction)
		{
			if (transaction == null)
				return null;

			if (transaction.TransactionState == SKPaymentTransactionState.Purchased ||
				transaction.TransactionState == SKPaymentTransactionState.Purchasing)
				return transaction;

			if (transaction.OriginalTransaction != null)
				return FindOriginalTransaction(transaction.OriginalTransaction);

			return transaction;

		}
```

I am curious for subscriptions if that means i shouldn't find the original and just return all of them.... hmmmmm

**Comment by jamesmontemagno** [comment]
I would encourage you to do this:

```
foreach (var trans in SKPaymentQueue.DefaultQueue.Transactions)
```
and see if all transactions are reported in here as I am filtering out some of them perhaps?
