### ISSUE TITLE
Potential BUG: Unable to get purchases

### ISSUE THREAD

**Issue by Bmahecha123** [jamesmontemagno/InAppBillingPlugin#177]
Hello, not sure if I'm dealing with a bug or conflictions in versions of Xamarin with this plugin. I have an application that was successfully making purchases and getting purchases but I notice that after updating all my dependencies from Xamarin Forms Xamarin.Forms.2.5.1.444934 to 3.1.0.637273 and InAppBillingPlugin from 1.2.4 to 2.0.0 I can't grab my purchases anymore. The actual shell to make and grab purchases is the same that was demoed in all the tutorials for this plugin. Thank you for your time. I'll attach a video and code snippet along with Bug information.

Fortunately this issue was caught by Apple before publishing my App to App Store and breaking the currently working version of the app that's out there. The most dumbfounding thing is all I did were styling and theming changes and didn't touch any of this logic. 

Thank you for your time everyone.

## Bug Information

Version Number of Plugin: 2.0.0
Device Tested On: iPad Mini
Simulator Tested On:
Version of VS: Mac Community 7.5.4 (build 3)
Version of Xamarin: iOS 11.12.0.4 (VS Community) and Forms 3.1.0.637273 (VS Community)
Versions of other things you are using:

### Steps to reproduce the Behavior
VIDEO LINK -> https://www.youtube.com/watch?v=yMb3j6Ibkeg&feature=youtu.be
### Expected Behavior
Expect purchases to be successfully grabbed to validate a user on login.
### Actual Behavior
Receiving InAppBillingPurchaseException with same exact code that was working prior.
### Code snippet
`
public async Task<bool> WasPackagePurchased(string productId)
        {
            var billing = CrossInAppBilling.Current;

            try
            {
                var connected = await billing.ConnectAsync();

                if (!connected)
                {
                    //Couldn't Connect
                    return false;
                }

                //Check Purchases
                var purchases = await billing.GetPurchasesAsync(ItemType.InAppPurchase);

                //Check for null just incase
                if (purchases?.Any(p => p.ProductId == productId) ?? false)
                {
                    //Purchase restored
                    return true;
                }
                else
                {
                    //no purchases found
                    return false;
                }
            }
            catch (InAppBillingPurchaseException purchaseEx)
            {
                //Billing Exception handle this based on the type
                Debug.WriteLine("Error: " + purchaseEx);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                //Something has gone wrong
            }
            finally
            {
                await billing.DisconnectAsync();
            }

            return false;
        }`

**Comment by jamesmontemagno** [comment]
Hmmmm... are you able to pull in the code directly and see where this is happening? https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/src/Plugin.InAppBilling.iOS/InAppBillingImplementation.cs

**Comment by Bmahecha123** [comment]
Thank you for the reply! From looking through that file I see that the exception is being thrown at line 133 from RestoreAsync(). Which tells me that it can't find my purchases. Just double checked my purchase history for that id and it's still there.

**Comment by jamesmontemagno** [comment]
Yeah, so it is just reporting back nothing in there... are you using the correct sandbox account?

**Comment by Bmahecha123** [comment]
I'm trying it on a real account. I use my own IPad Mini which I used to purchase the in app purchase for my app when I released it back in February. This testing flow for my in app purchases worked prior, it's been frustrating.

**Comment by jamesmontemagno** [comment]
Is this item a consumable or a non-consumable?

**Comment by jamesmontemagno** [comment]
I mean i basically just follow : https://docs.microsoft.com/en-us/xamarin/ios/platform/in-app-purchasing/transactions-and-verification

You can do something like this:


```csharp
class PaymentObserver : SKPaymentTransactionObserver
{
// called when the transaction status is updated
public override void UpdatedTransactions (SKPaymentQueue queue, SKPaymentTransaction[] transactions)
{
   foreach (SKPaymentTransaction transaction in transactions)
   {
     //check stuff here
   }
}

public override void PaymentQueueRestoreCompletedTransactionsFinished (SKPaymentQueue queue)
{
   Console.WriteLine(" ** RESTORE Finished ");
}
public override void RestoreCompletedTransactionsFailedWithError (SKPaymentQueue queue, NSError error)
{
   Console.WriteLine(" ** RESTORE FailedWithError " + error.LocalizedDescription);
}
}

```

then elsewhere do:

```csharp
var paymentObserver = new PaymentObserver(OnPurchaseComplete);
SKPaymentQueue.DefaultQueue.AddTransactionObserver(paymentObserver);

SKPaymentQueue.DefaultQueue.RestoreCompletedTransactions();
```

**Comment by jamesmontemagno** [comment]
if it is a consumable you can't restore that, which is why I asked originally.

**Comment by Bmahecha123** [comment]
Thanks for the code snippet! It's a non-consumable purchase.
I'm going to downgrade XForms and Plugin version to the state it was in when it was all working. I'll update this issue in a few hours!

**Comment by jamesmontemagno** [comment]
Sounds good. Xamarin.Forms would have nothing to do with it. Would just be something with the plugin, but haven't heard anything form anyone lately. I will upgrade and test some of my apps this week.

**Comment by Bmahecha123** [comment]
Thank you for taking the time to help me through this. Unfortunately I'm at a loss at the moment after trying a bunch of different versions of Plugin app out and making sure all my Certificates, Identifiers & Profiles are valid.

**Comment by jamesmontemagno** [comment]
I am unable to validate this as I jsut tested it and working great for me today.

**Comment by Bmahecha123** [comment]
Hey James! I asked the apple devs to test for me on there end to validate my release and things checked out on there end.

When I DLed app to my phone it was working as expected to this is a relief. I don't think I set anything up wrong in the video I sent you.

Thank you for following up on this. My apologies for getting back to you so late.
