### ISSUE TITLE
Can we separate "PurchaseError.UserCancelled" cases?

### ISSUE THREAD

**Issue by EmilAlipiev** [jamesmontemagno/InAppBillingPlugin#178]
## Bug Information

Version Number of Plugin:latest
Device Tested On: 
Simulator Tested On:
Version of VS: 2017
Version of Xamarin:3.1
Versions of other things you are using:

### Steps to reproduce the Behavior
when purchase popup appears on android, if user cancels it plugin throws "PurchaseError.UserCancelled" as expected. But also the same error is thrown in case of user is not having a valid email address for purchase. 
### Expected Behavior ### Actual Behavior
can we separate these cases in order to handle exceptions on the UI better? because I want to display user "Please check if you have valid gmail address on for purchasing" message but this is difficult if same exception is thrown when user just taps out and cancels purchase himself.

### Code snippet

i am guessing that it is here but i am not sure if google already returns different response for these 2 cases.

  ```
Bundle buyIntentBundle = serviceConnection.Service.GetBuyIntent(3, Context.PackageName, productSku, itemType, payload);
                var response = GetResponseCodeFromBundle(buyIntentBundle);

                switch (response)
                {
                    case 0:
                        //OK to purchase
                        break;
                    case 1:
                        //User Cancelled, should try again
                        throw new InAppBillingPurchaseException(PurchaseError.UserCancelled);
                    case 2:
                        //Network connection is down
                        throw new InAppBillingPurchaseException(PurchaseError.ServiceUnavailable);
                    case 3:

```

**Comment by jamesmontemagno** [comment]
Looks like all Google gives us is: https://developer.android.com/google/play/billing/billing_reference

**Comment by EmilAlipiev** [comment]
Hi James,

Will you extend this information in next release by any chance? :) 
thanks

**Comment by jamesmontemagno** [comment]
There is no information to extend.... I already return all proper exceptions that google gives me.
