### ISSUE TITLE
GetPurchasesAsync throwing COMException (0x80190194) on UWP

### ISSUE THREAD

**Issue by drossoft** [jamesmontemagno/InAppBillingPlugin#179]
Stacktrace:
https://gist.github.com/drossoft/80c4dc4d7fadf6a033814d4fcc478356

## Bug Information

Version Number of Plugin: 2.0.0
Device Tested On: Android (OK), Windows PC (Fail)
Simulator Tested On:
Version of VS: Visual Studio 2017
Version of Xamarin: 3.1.0.697729
Versions of other things you are using:

### Steps to reproduce the Behavior
On UWP device, Initialize InApp purchases.

### Expected Behavior
Return List of InApp products

### Actual Behavior
Exception thrown

### Code snippet
****

**Comment by drossoft** [comment]
this is the method I use to init InAppPurchases:

public async Task InitInAppPurchasesAsync()
        {
            if (!CrossInAppBilling.IsSupported)
                return;

            try
            {
                if (!_isInAppPurchasesInitialized)
                {
                    _isInAppPurchasesInitialized = true;

                    var connected = await CrossInAppBilling.Current.ConnectAsync();

                    if (connected)
                    {
                        //CrossInAppBilling.Current.InTestingMode = true;

                        var purchases = await CrossInAppBilling.Current.GetPurchasesAsync(Plugin.InAppBilling.Abstractions.ItemType.InAppPurchase);

                        //check for null just incase
                        IsRemoveAdsPurchased = (purchases?.Any(p => p.ProductId == "remove_ads") ?? false);

                        var productIds = new string[] { "remove_ads" };
                        _productItems = await CrossInAppBilling.Current.GetProductInfoAsync(Plugin.InAppBilling.Abstractions.ItemType.InAppPurchase, productIds);
                        PurchaseItems = new ObservableCollection<InAppItemPurchase>();
                        if (_productItems != null)
                        {
                            Plugin.InAppBilling.Abstractions.InAppBillingProduct product = _productItems.FirstOrDefault(p => p.ProductId == "remove_ads");
                            if (product != null)
                            {
                                PurchaseItems.Add(new InAppItemPurchase() { Product = product, IsPurchased = IsRemoveAdsPurchased });
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }
            finally
            {
                await CrossInAppBilling.Current.DisconnectAsync();
            }
        }

If InTestingMode is set to true, it works correctly.

I've also tried to call GetProductInfoAsync, and it throws the same exception.

The issue is only on UWP, it works correctly on Android and have not tested yet on IOS.

Thank you!

**Comment by drossoft** [comment]
I found the answer to this problem [here](https://social.msdn.microsoft.com/Forums/en-US/e1f84934-45a6-43c9-8b33-4f138ae38db5/loadlistinginformationasync-0x80190194-not-found-404?forum=wpsubmit)

It looks like Windows Store In App Purchases are not available when the App is published as "Private" and it throws the 404 error by design.

In case someone else hits this issue, i have solved it by updating the app on the Windows Store to "Public" with direct link only and it works perfectly.

**Comment by assassin316** [comment]
@drossoft  thank you for specifying this, I was getting the same thing.

**Comment by olographio** [comment]
> I found the answer to this problem [here](https://social.msdn.microsoft.com/Forums/en-US/e1f84934-45a6-43c9-8b33-4f138ae38db5/loadlistinginformationasync-0x80190194-not-found-404?forum=wpsubmit)
> 
> It looks like Windows Store In App Purchases are not available when the App is published as "Private" and it throws the 404 error by design.
> 
> In case someone else hits this issue, i have solved it by updating the app on the Windows Store to "Public" with direct link only and it works perfectly.

This should be either fixed or documented. I'm getting a 404 not found COMException too from having my app in private+link only mode.
