### ISSUE TITLE
[Android] Xamarin Forms InAppBillingPlugin PurchaseAsync exeption

### ISSUE THREAD

**Issue by efactorpl** [jamesmontemagno/InAppBillingPlugin#180]
### Bug Information
Version Number of Plugin: 2.0.0
Device Tested On: Android (Fail)
Simulator Tested On:
Version of VS: Visual Studio 2017
Version of Xamarin: 3.1.0.697729

I need some support regarding InAppBillingPlugin for Xamarin.Forms. First of all I did configuration according to documnetation: https://jamesmontemagno.github.io/InAppBillingPlugin/

application, Google Console (managed products) and iTunes Connect site.

Here is my application code.

private async Task TryInAppPurchace(string androidProductId, string iOSProductId="")
{
    if (!CrossInAppBilling.IsSupported)
        return;

    //Android
    var products = new string[] { androidProductId };

    if(Device.RuntimePlatform == Device.iOS)
        products = new string[] { iOSProductId };

    var billing = CrossInAppBilling.Current;
    //billing.InTestingMode = true;

    try
    {
        var connected = await billing.ConnectAsync(ItemType.InAppPurchase);

        if (!connected)
        {
            await Application.Current.MainPage.DisplayAlert("Connectivity Error", "Unable to connect to the internet.", "OK");
            return;
        }

        var items = await billing.GetProductInfoAsync(ItemType.InAppPurchase, products);
        var item = items.ToList().First();

        //try to purchase item
        var purchase = await billing.PurchaseAsync(item.ProductId, ItemType.InAppPurchase, item.ProductId);

        //possibility that a null came through.
        if (purchase == null)
        {
            await Application.Current.MainPage.DisplayAlert("Purchase Error", "You are unable to buy this product.", "OK");
            return;
        }
        else
        {
            await _pageService.DisplayAlert("Purchased", "Consumable product.", "OK");

            if (Device.RuntimePlatform == Device.iOS)
                return;

            var consumedItem = await CrossInAppBilling.Current.ConsumePurchaseAsync(purchase.ProductId, purchase.PurchaseToken);

            if (consumedItem != null)
            {
                await Application.Current.MainPage.DisplayAlert("New Package added", "Successfully added new package", "OK");
            }
        }
    }
    catch (InAppBillingPurchaseException purchaseEx)
    {
        var message = string.Empty;
        await Application.Current.MainPage.DisplayAlert("Exeption", purchaseEx.Message, "OK");
        switch (purchaseEx.PurchaseError)
        {
            case PurchaseError.BillingUnavailable:
                message = "BillingUnavailable";
                break;
            case PurchaseError.DeveloperError:
                message = "DeveloperError";
                break;
            case PurchaseError.ItemUnavailable:
                message = "ItemUnavailable";
                break;
            case PurchaseError.GeneralError:
                message = "GeneralError";
                break;
            case PurchaseError.UserCancelled:
                message = "UserCancelled.";
                break;
            case PurchaseError.AppStoreUnavailable:
                message = "AppStoreUnavailable.";
                break;
            case PurchaseError.PaymentNotAllowed:
                message = "PaymentNotAllowed.";
                break;
            case PurchaseError.PaymentInvalid:
                message = "PaymentInvalid";
                break;
            case PurchaseError.InvalidProduct:
                message = "InvalidProduct";
                break;
            case PurchaseError.ProductRequestFailed:
                message = "ProductRequestFailed";
                break;
            case PurchaseError.RestoreFailed:
                message = "RestoreFailed";
                break;
            case PurchaseError.ServiceUnavailable:
                message = "ServiceUnavailable";
                break;
        }
    }
    catch (Exception ex)
    {
        //Something else has gone wrong, log it
        await Application.Current.MainPage.DisplayAlert("Exeption", ex.Message, "OK");
    }
    finally
    {
        await billing.DisconnectAsync();
    }
}
My problem is that I am not able to buy the same product again and I am getting exeption from Google Play:

{Plugin.InAppBilling.Abstractions.InAppBillingPurchaseException: Unable to process purchase. at Plugin.InAppBilling.InAppBillingImplementation+d__33.MoveNext () [0x00116] in C:\projects\inappbillingplugin\src\Plugin.InAppBilling.Android\InAppBillingImplementation.cs:324

--- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in :0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in :0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in :0 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in :0 at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in :0 at Plugin.InAppBilling.InAppBillingImplementation+d__32.MoveNext () [0x00090] in C:\projects\inappbillingplugin\src\Plugin.InAppBilling.Android\InAppBillingImplementation.cs:264

--- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in :0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in :0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in :0 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in :0 at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in :0 at DrivingCourse_app.ViewModels.AccessPageViewModel+d__18.MoveNext () [0x0025c] in C:\Projects\GIT-REPO\DrivingCourse_DE\DrivingCourse_app\DrivingCourse_app\DrivingCourse_app\ViewModels\AccessPageViewModel.cs:136 }

Is something wrong with my code? This code is working for every fist purchase of the product, so configuration itself and the general process works.

Any ideas?

**Comment by BioTurboNick** [comment]
Is your purchase a consumable? If not, you can only purchase it once and if you try again, you'll get an InAppBillingPurchaseException with PurchaseError == PurchaseError.AlreadyOwned, which you should handle.

**Comment by efactorpl** [comment]
Ok, thanx. Everything seems to fo fine now. It was type of products.

**Comment by marisrr** [comment]
Hello,

Seems I missed first time in my project this line as I want to allow users to purchase many times:

var consumedItem = await CrossInAppBilling.Current.ConsumePurchaseAsync(purchase.ProductId, purchase.PurchaseToken);

First time purchase was successful, but by trying the next time, error is received.

{Plugin.InAppBilling.Abstractions.InAppBillingPurchaseException: Unable to process purchase

Is it possible to fix this so that same users could make a purchase again?

Thanks
