### ISSUE TITLE
Version 2.0.0 is available in nuget but not listed as a release here

### ISSUE THREAD

**Issue by garie** [jamesmontemagno/InAppBillingPlugin#181]
Version 2.0.0 was released 3 months ago.

https://www.nuget.org/packages/Plugin.InAppBilling/

It looks to have backwards breaking changes, when updating the readme contains the note:

> - Change to "ConnectAsync()" on ANDROID! Please pass in the ItemType that you are about to purchase! The default is normal in app purchase.

**Comment by jamesmontemagno** [comment]
Added to change log
