### ISSUE TITLE
Plugin V2 on iOS 12 - PurchaseAsync() hangs

### ISSUE THREAD

**Issue by DigitalNut** [jamesmontemagno/InAppBillingPlugin#183]
## Bug Information

Version Number of Plugin: 2.0
Device Tested On: 9.7" iPad Pro
Simulator Tested On:
Version of VS: 2017 for Mac (7.6.6 build 17)
Version of Xamarin: 12.0.0.15 (iOS)
Versions of other things you are using:

### Steps to reproduce the Behavior
Call into PurchaseAsync for a consumable item hangs. Worked under iOS 11. Upgraded to iOS 12 and now hangs (also upgraded VS and Xcode to support iOS 12). I'm using the code as described in purchasing a consumable item.

I'm using a sandbox account. I'm signed out of my iPad.
Note calls to get product info (e.g. GetProductInfoAysnc) work.

### Expected Behavior
PurchaseAsync returns with purchased item

### Actual Behavior
Hangs on PurchaseAsync()

### Code
```c#
var purchase = await billing.PurchaseAsync(productId, ItemType.InAppPurchase, payload);
```

**Comment by DigitalNut** [comment]
Setup debug version of InAppBillingPlugin. The payment object seem to be added to the queue in 		Task<SKPaymentTransaction> PurchaseAsync(string productId):

```c#
SKPaymentQueue.DefaultQueue.AddPayment(payment);
```

They just seem to be stuck in 'Purchasing' state. I see from UpdatedTransactions, the product keeps being added to the queue, but all are in 'Purchasing' state.

**Comment by jamesmontemagno** [comment]
Just tested this on the latest version -preview and working great for me.
