### ISSUE TITLE
How can I use Android security?

### ISSUE THREAD

**Issue by Fox9MonoGame** [jamesmontemagno/InAppBillingPlugin#189]
I want to implement the Android security but I don't know how to do that. I broke my public key into 3 parts and ran each through the helper XOR method. But now I don't know how to continue because I don't know what "string signedData" and "string signature" are. What are these two strings?

In addition, where exactly should I call public Task<bool> VerifyPurchase(string signedData, string signature)? Right after the line "var purchase = await CrossInAppBilling.Current.PurchaseAsync(productId, ItemType.InAppPurchase, "apppayload", verify);"?

    `try
     {
	var productId = "mysku";
	var connected = await CrossInAppBilling.Current.ConnectAsync(ItemType.InAppPurchase);
	if (!connected)
	{
		//Couldn't connect to billing
		return;
	}

    var verify = DependencyService.Get<IInAppBillingVerifyPurchase>();
    //try to purchase item
    var purchase = await CrossInAppBilling.Current.PurchaseAsync(productId, ItemType.InAppPurchase, "apppayload", verify);

//Should I call VerifyPurchase(string signedData, string signature) here or is this not the right moment to call it?

	if(purchase == null)
	{
		//Not purchased, may also throw excpetion to catch
	}
	else
	{
		//Purchased!
	}
    }`

**Comment by jamesmontemagno** [comment]
This is beign removed and obsolete
