### ISSUE TITLE
How can I get SKPaymentTansaction.TransactionReceipt

### ISSUE THREAD

**Issue by deadean** [jamesmontemagno/InAppBillingPlugin#19]
How can I get SKPaymentTansaction.TransactionReceipt Base64-encode the transaction receipt data.

**Comment by jamesmontemagno** [comment]
When you implement IInAppBillingVerifyPurchase and pass it in to PurchaseAsync it will pass you this information:

https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/src/Plugin.InAppBilling.iOS/InAppBillingImplementation.cs#L156-L162
