### ISSUE TITLE
Receipt - Interface InAppBillingVerifyPurchase

### ISSUE THREAD

**Issue by Abesoddy** [jamesmontemagno/InAppBillingPlugin#193]
Hello, 

Thank you for this plugin !! However, I do not understand everything about the verification of renewable auto subscriptions.

What should the InAppBillingVerifyPurchase interface do in IOS? public Task <bool> VerifyPurchase should return a bool but in which case will it be true or false? Should we compare the expiry date with the current date and return true if it has not expired?

I read a lot of topics, documentation etc but I still do not understand everything about this plugin.

Thank you for your answers :)

**Comment by jamesmontemagno** [comment]
See: https://jamesmontemagno.github.io/InAppBillingPlugin/SecuringPurchases.html

**Comment by jamesmontemagno** [comment]
That method will return true if you validated the receipt with apple else return false.
