### ISSUE TITLE
Android : You are not connected to the Google Play App store

### ISSUE THREAD

**Issue by Abesoddy** [jamesmontemagno/InAppBillingPlugin#195]
Hello,

I tried to implement the plugin on Android but I have an exception for each connection to the play store : `Plugin.InAppBilling.Abstractions.InAppBillingPurchaseException: You are not connected to the Google Play App store.
`

The plugin is installed with Nuget, the apk is published on the play store in the same version as the development. I don't understand where the worry comes from?

Have you ever had this problem ?

Thank you

**Comment by EmilAlipiev** [comment]
hi, this problem occurs if you dont have valid email with payment options on your android phone. try to add a new payment option on your gmail and see if you get this error still.
