### ISSUE TITLE
Android - Debug InAppBilling 

### ISSUE THREAD

**Issue by Abesoddy** [jamesmontemagno/InAppBillingPlugin#196]
Hello,

Is it possible to debug the alpha apk ? When I debug with visual studio, the application installs but when paying I have an error: “This version of the application is not configured for billing through Google Play”. Yet everything is configured, the application is signed with the publication keystore, the version number is same as playstore... 

Thanks for answers :)

**Comment by jamesmontemagno** [comment]
See: https://jamesmontemagno.github.io/InAppBillingPlugin/TestingAndTroubleshooting.html
