### ISSUE TITLE
serviceConnection?.Service returns null for some cases

### ISSUE THREAD

**Issue by EmilAlipiev** [jamesmontemagno/InAppBillingPlugin#197]
## Bug Information

Version Number of Plugin:
Device Tested On: 
Simulator Tested On:
Version of VS: 2017
Version of Xamarin: 3.3
Versions of other things you are using:

### Steps to reproduce the Behavior

I am getting bunch or error messages from the lines below, serviceConnection?.Service looks like returned null. 

```
  public async override Task<IEnumerable<InAppBillingProduct>> GetProductInfoAsync(ItemType itemType, params string[] productIds)
        {
            if (serviceConnection?.Service == null)
            {
                throw new InAppBillingPurchaseException(PurchaseError.ServiceUnavailable, "You are not connected to the Google Play App store.");
            }
```
I first thought this can be because user doesnt have latest version of google play but, i cant reproduce it if I uninstall all google play updates and restore to factory version. It still works for me.
Also not having email address assigned on google play is not the reason, because then It fails not on these lines but it fails on `ConnectAsync`() function before reaching `GetProductInfoAsync`
 
I attached the source code and debugged every possible scenario with different android version, with real device but i am not able to get that null exception. What could be the reason? I wouldnt ask this question if I had below exception a few times but my App center logs shows 77 times in 1 month. I have also successful purchases. so it is not my general implementation but there must be some problem with the plugin. Here is the full stracktrace

https://gist.github.com/EmilAlipiev/a0f569cc1f63fbf98e7d31d17b233003

**Comment by jamesmontemagno** [comment]
Could be multiple reasons... maybe they are offline, maybe they have a weird version of Google Play, maybe billing isnt' configured, hard to say. I throw this exception because we couldnt' connect.

**Comment by EmilAlipiev** [comment]
But here problem is that IsConnected() method returns true and serviceConnection?.Service is failing. how can it possible if It is connected, Service is null. that confuses me.
