### ISSUE TITLE
ItemType ignored

### ISSUE THREAD

**Issue by ghost** [jamesmontemagno/InAppBillingPlugin#198]
Version Number of Plugin: 2.0.0
Device Tested On: iPhone 6
Simulator Tested On: iPhone 6
Version of VS: Visual Studio for Mac 7.8

**Steps to reproduce the behavior:**
Test on sandbox where you have in app purchased purchased:
 `var purchases = await billing.GetPurchasesAsync(ItemType.Subscription);`

**Expected behaviour:**
Any non-subscription items should not show.

**Actual behaviour:**
All in app purchases returned. Regardless of whether they are subscription or not. This only happens the other way. i.e. if item type is inapppurchase then subscriptions will show in list

Need advice on whether to use ItemType subscription if i want to get subscriptions or InAppPurchase. Any why is the itemtype ignored?

**Comment by luqmanhussain** [comment]
Ive noticed from the code for GetPurchasesAsync that you dont use that itemtype parameter. So why not just remove it?
And you also dont seem to wait for the RestoreCompletedTransactionsFinished?
