### ISSUE TITLE
missing purchases

### ISSUE THREAD

**Issue by ghost** [jamesmontemagno/InAppBillingPlugin#199]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.0.0
Device Tested On: iPhone 6
Simulator Tested On: iPhone 6
Version of VS: 7.8 on Mac

### Steps to reproduce the Behavior
Call await ProductsAsync(ItemType.InAppPurchase)

### Expected Behavior
Should return all purchase

### Actual Behavior
Only return some purchases.
I believe this is because the ProductsAsync method doesn't seem to wait for RestoreCompletedTransactionsFinished or am I not seeing this?

**Comment by jamesmontemagno** [comment]
unable to reproduce
