### ISSUE TITLE
Consumption API

### ISSUE THREAD

**Issue by aer127** [jamesmontemagno/InAppBillingPlugin#2]
## Feature Request:
Well, you beat me to it :) I had been working on a very similar plugin the past few weeks. See here:
https://github.com/aer127/CrossPurchase

That being said, I see your plugin does not have support for consumption at the moment. Are you actively working on this? If not, I would love to submit a pull request for this feature. Wanted to check with you first to make sure we aren't duplicating work.

**Comment by jamesmontemagno** [comment]
I have it in my pipeline, I have it tested for Android as it is easy, but feel free to send a PR down  :)

**Comment by jamesmontemagno** [comment]
I have a branch currently and have it implemented for Android/UWP. Working on iOS now

**Comment by aer127** [comment]
Cool. Thanks. I haven't had time to work on it so now worries about duplicating work.

**Comment by klint01** [comment]
@jamesmontemagno I've installed 1.1.03-beta, once you publish an update with the consumable products for Android and iOS, I will be happy to test it for you.

**Comment by jamesmontemagno** [comment]
:) will do, getting close

**Comment by jamesmontemagno** [comment]
@klint01 checkout: 1.1.0.9-beta just added in
