### ISSUE TITLE
DependencyService is not direclty suported in Xamarin Android and also how to get signedData and signature using this plugin?

### ISSUE THREAD

**Issue by Ajay311** [jamesmontemagno/InAppBillingPlugin#203]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

**Comment by jamesmontemagno** [comment]
You just pass it in an implementation of the interface, you don't have to use a dependency service at all. Just implement the interface in a class and pass that class to the methods.

**Comment by Ajay311** [comment]
But it is mentioned here in code. https://jamesmontemagno.github.io/InAppBillingPlugin/SecuringPurchases.html
 Also what to pass for signedData and signature?

**Comment by jamesmontemagno** [comment]
See this: it is passed into the method for you: https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/docs/SecuringPurchases.md#android-security

**Comment by Ajay311** [comment]
Solved that. Thank you. One more question, Should I directly break my public key in three parts and paste in place of XOR_key1, XOR_key2 and XOR_key3? In below lines. I have added this code in my app itself
  const string key1 = @"XOR_key1";
  const string key2 = @"XOR_key2";
  const string key3 = @"XOR_key3";

**Comment by jamesmontemagno** [comment]
You don't have to break it into 3 parts. What you want to do is to run your public key through the xor and then put the in it's place. You don't want to put your public key directly in there. 

http://stackoverflow.com/questions/11671865/how-to-protect-google-play-public-key-when-doing-inapp-billing

**Comment by CDrosos** [comment]
I dont understand what "run your public key through the xor and then put the in it's place" means or what you have to do from the link. Can you explain more?
