### ISSUE TITLE
Is there a Xamarin.Forms Example?

### ISSUE THREAD

**Issue by longhornleads** [jamesmontemagno/InAppBillingPlugin#209]
Do you have an example of using this plugin with Xamarin Forms or is it required to do this in Xamarin.iOS or Xamarin.Droid?

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

**Comment by jamesmontemagno** [comment]
Works with any. all the code is cross-platform. The sample in the repo is a xamarin.forms app.

**Comment by longhornleads** [comment]
Awesome! It's not clearly noted or a part of the docs like you usually do.  I'll see if I can piece it together.  Are you talking about the folder marked Tests?  I assumed from the readme that the majority of the code in the repo was the plugin itself and that tests would be ... a test harness not an example.  Thanks though this should be a HUGE help!

**Comment by longhornleads** [comment]
I also don't see any examples of people using this from the nuget package for XF.  I do see the example using it from the dependent project.  I'll just extract that and then add the nuget package and create a standalone example.  Since there is a lot of configuration (with the respective app stores) it may actually not be useful to post but I'll share it if it makes sense.
