### ISSUE TITLE
Plugin not working after activity switch

### ISSUE THREAD

**Issue by netvandal** [jamesmontemagno/InAppBillingPlugin#21]
## Bug 

I'm using the plugin in an Xamarin Android app, and I successfully get it to work following the sample in the README.
User navigate in my app, reach the activity where he can purchase a non consumable product, click on the "buy button" and go thought the process and successfully [or not is the same if the user quit] buy the product.
Now if the user go back to the product list, click on another items and a new product activity kicks.
Now if the user click on the same "buy button" as before nothing happen.

I debugged my app and it seems that I connect and disconnect correctly from the service on the first time, then the second time my app connect to the service [CrossInAppBilling.Current.ConnectAsync(); returns true] but just after the call  CrossInAppBilling.Current.GetProductInfoAsync(ItemType.InAppPurchase, productIds);
I'm unable to debug further. The app is still usable, no error message, but no Google Play popup show up.
I'm trying to build right now a sample app to test the behaviour, but at the moment I can't figure out what's going on.

Version Number of Plugin: 1.1.0.23
Device Tested On: Android 5/6

Thankyou for any suggestion.

**Comment by jamesmontemagno** [comment]
Did you consume the consumable?

**Comment by netvandal** [comment]
The products are "not consumable" .

**Comment by jamesmontemagno** [comment]
So they already purchased them? If they already purchased them then I don't think anything will really happen. I don't kwon what your code looks like so would need more info.

**Comment by jamesmontemagno** [comment]
Did you add this code into the activity? https://github.com/jamesmontemagno/InAppBillingPlugin/#setup-1  this will ensure things will go through. I have this exact same thing setup and working great in my bike app.

**Comment by netvandal** [comment]
Yes, I have it.
I have it in the Activity that load the fragment where i actually have the connection/purchase/disconnect code. Could be this the problem?
To mee sound strange that the first time it works great, and the second not..

**Comment by jamesmontemagno** [comment]
I haven't been able to reproduce this at all sorry.

**Comment by jamesmontemagno** [comment]
Fixed up in new based on another user
