### ISSUE TITLE
iOS Rejection Question about Restore.

### ISSUE THREAD

**Issue by rodneykorn** [jamesmontemagno/InAppBillingPlugin#211]
I go the following rejection from Apple but I have no idea how to address it with the plugin. 

"We found that your app includes a feature to restore previously purchased in-app purchase products by entering the user's Apple ID and password. However, non-renewing subscription in-app purchases cannot be restored in this manner.

To resolve this issue, please revise your binary to remove this feature. If you would like users to be able to restore non-renewing subscription in-app purchase products, you will need to implement your own restore mechanism."

The UI that they are pointing out is simply a Purchase Button. Removing the button essentially removes my in app purchases.  When the button is pressed it check for an subscription (with GetPurchasesAsync) and only called MakePurchase if that fails to find a purchase. 

Any ideas or clues because I am sure someone else will run into this.

**Comment by jamesmontemagno** [comment]
You need to add a button to "Restore", which will query the purchases the user has and restore it for them. I had this happen to me before and I added a simple "Restore" button and they accepted it.

**Comment by rodneykorn** [comment]
Thanks, the weird thing is that I don't save any state on the device and always query for the purchases at this time.  I understand that this is not ideal but I was pushed to get the app out quickly.

**Comment by jamesmontemagno** [comment]
They are extremely extremely picky. Frank had to modify his app tons when he did it.

**Comment by pulmuone** [comment]
same issue
