### ISSUE TITLE
iOS implementation of ConsumePurchaseAsync just returns null despite being async

### ISSUE THREAD

**Issue by aeonblaire** [jamesmontemagno/InAppBillingPlugin#215]
## Bug Information
The iOS implementation is just an empty expression-bodied method that returns null, despite the method being async. Using await on this method causes a null reference exception.

Version Number of Plugin: 2.0.0
Device Tested On: iPhone 8+
Simulator Tested On: [none]
Version of VS: 15.9.7
Version of Xamarin: 4.12.3.80
Versions of other things you are using:

### Steps to reproduce the Behavior
Just use CrossInAppBilling.Current.ConsumePurchaseAsync(...) in iOS;

### Expected Behavior
the method should not return null, because it is async

### Actual Behavior
the method returns null

### Code snippet
var task = CrossInAppBilling.Current.ConsumePurchaseAsync("", "");
if (task == null)
{
     // try breakpoint here
]

**Comment by mnxamdev** [comment]
I agree if a bug it should be fixed. FYI I thought we didn't actually need to use this method on iOS per the latest web page documentation.
https://jamesmontemagno.github.io/InAppBillingPlugin/PurchaseConsumable.html
```
Consumables are unique and work a bit different on each platform and the ConsumePurchaseAsync may need to be called after making the purchase:

Apple: As soon as you purchase they are consumed
```

**Comment by aeonblaire** [comment]
I used it cross-platform, and for me it defeats the purpose of being cross-platform if I need to determine the OS

**Comment by jamesmontemagno** [comment]
On iOS they are consumed immediately with null.... so if on iOS then don't try to consume it. Check with [Xamarin.Essentials](https://docs.microsoft.com/xamarin/essentials/device-information?context=xamarin%2Fxamarin-forms&amp;tabs=ios&amp;WT.mc_id=docs-github-jamont)

**Comment by aeonblaire** [comment]
Then the OS should be determined even in the cross-platform parts of the codes!?

**Comment by jamesmontemagno** [comment]
You can determine the OS in the shared code. Unfortunately all platforms aren't the same and you need to have some cases to handle this as this is how I designed the API. You are free to fork it and use the code directly.

**Comment by stevehurcombe** [comment]
Would it be better to throw an exception in this case? Documentation is great, but a well worded exception would be more so. There seem to be a lot of edge cases to trip over...
