### ISSUE TITLE
GetProductInfo not returning iOS products

### ISSUE THREAD

**Issue by Drew-FitEpic** [jamesmontemagno/InAppBillingPlugin#217]
I cannot get a list of products or purchase items when debugging locally with the Debug build.

If I upload the app to TestFlight, I can at least get products back (have not tested purchase yet).

Is there an issue with this plugin when using the Debug build?  I went back and I listened the Merge Conflict podcast, and it sounded like James had this same problem.   However, he didn't provide a clear resolution.

Things I have verified
- the development profile has App Store provisions.
- the development profile, phone, and signing certificate all line up in when building under Debug
- The sandbox account authenticates

What else am I missing?   I am using subscriptions, and my stomach is turning over thinking about having a dev cycle that involves having to upload to Testflight in order to test things out.

**Comment by vjsystematix** [comment]
I have also facing the same issue did i need to do some special configuration

**Comment by EmilAlipiev** [comment]
did you sign your debug build? I dont know about iOS but on android you need to sign your build with the same key as you upload on the store and your app must be already in the store(beta, alpha at least)

**Comment by lars-rogalski** [comment]
Hey, i have the same problem, subscription buy works in debug but no Infos from GetProductInfoAsync -> i cant debug the code it feels like it freezes even try catch dont return anything

**Comment by Meekohi** [comment]
Anyone figure out how to resolve this? This also effects our Testflight builds.

**Comment by Lelelo1** [comment]
Does it work in production?

**Comment by assassin316** [comment]
I'm having the same problem when debugging in android, I never get my products. My app is in Internal Testing and I get nothing back. I even opened a SO question about it:

https://stackoverflow.com/questions/65332635/unable-to-fetch-inapp-products-for-xamarin-android-using-plugin-inappbilling-pac/65348286#65348286

**Comment by jamesmontemagno** [comment]
Unable to reproduce, is good here
