### ISSUE TITLE
[iOS] Restored purchasing missing original transaction date

### ISSUE THREAD

**Issue by davidjade** [jamesmontemagno/InAppBillingPlugin#219]
When restoring purchases on iOS, the purchases that are returned are new "restored" state purchases - not the original purchase receipts. I'm not sure if this is by-design or a bug because what is missing, is the original purchase date when a purchase is restored (newly restored purchases have a transaction date at the time of restoration). This makes it impossible to run a non-consumable trial period since any restore or re-install would just reset the trial period if you were using that transaction date.

If line 147 of InAppBillingImplementation.cs for iOS was changed to this, then the original receipt gets returned instead which seems much more useful.

```
allTransactions.AddRange(transactions.Select(t => FindOriginalTransaction(t)));
```
I something similar is done for other receipts that get restored so I'm not sure why some restored receipts don't get this treatment.

I can submitted a pull request that makes this simple change but I thought I'd ask first - is that the right intention here? Maybe instead InAppBillingPurchase should also include the original receipt for restored purchases or at least the original transaction date for restored purchases?

**Comment by davidjade** [comment]
More info: Now I see what looks like maybe another contributing factor. I now think what is happening is that info from two SKPaymentTransaction are getting blended together. 

In SKTransactionExtensions.ToIABPurchase(), which GetPurchasesAsync() calls to process all restored purchases, there is this code that selects the OriginalTransaction if there is one.

InAppBillingImplementation.cs line 512
```
var p = transaction?.OriginalTransaction ?? transaction;
```

However, when constructing the InAppBillingPurchase object (line 518), it uses "transaction" instead of "p" to access the TransactionDate when everything else in the conversion code uses "p"

```
return new InAppBillingPurchase
{
    TransactionDateUtc = NSDateToDateTimeUtc(transaction.TransactionDate),
    Id = p.TransactionIdentifier,
    ProductId = p.Payment?.ProductIdentifier ?? string.Empty,
    State = p.GetPurchaseState(),
    PurchaseToken = p.TransactionReceipt?.GetBase64EncodedString(NSDataBase64EncodingOptions.None) ?? string.Empty
};
```

This seems like the more obvious bug as the code is blending together two transactions, using one for the Date and using the other for everything else. Since it is using "transaction" for the date, this leads to a Purchased state that uses the Restored transaction's Date, which is always the time of retrieval from iTunes.

Or maybe this was intentional for some reason? Perhaps the intent was to deal with purchases moving from Purchasing to Purchased to capture the final Purchased date, but this messes up Restored dates by losing the original transaction date which seems the important date for a Restored purchase.

So I'm confused why there are at least 3 separate ways of dealing with dates when converting to a InAppBillingPurchase object. I'm not sure why RestoreAsync() only converts some transaction to Originals via FindOriginalTransaction() and then GetPurchasesAsync() converts any not already converted to Originals but does so in a blended way inside ToIABPurchase(). They also convert to Originals in very different ways (one takes the first Original, the other recurses all Originals until a Purchase/Purchasing is found).

To make it even more confusing, PurchaseAsync() seem to do yet another form of date determination for Purchases when converting to InAppBillingPurchase with a date conversion function that isn't used for Restored transactions.

At this point, it is not clear to me what parts are correct and what parts are not (in the sense the Restored purchases don't return the original transaction date, which I need). Maybe both things I have pointed out are bugs?

**Comment by jamesmontemagno** [comment]
This is fixed

**Comment by davidjade** [comment]
Awesome, by any chance can you point out the commit that fixed this? I just want to understand it better since I had to work around this.

**Comment by jamesmontemagno** [comment]
https://github.com/jamesmontemagno/InAppBillingPlugin/pull/307/files
