### ISSUE TITLE
Not connecting from Xamarin.Forms 4.0 project ( VS 2019 )

### ISSUE THREAD

**Issue by SandhaniCom** [jamesmontemagno/InAppBillingPlugin#220]
I have tried to test payment from Xamarin forms app 4.0 but not connecting showing following error

Unhandled Exception:

System.ArgumentNullException: Value cannot be null.
Parameter name: source occurred

## Bug Information

Version Number of Plugin: 2.0
Device Tested On: Xiaomi mi max android 7
Simulator Tested On: android version 5
Version of VS: 2019
Version of Xamarin: 4.0
Versions of other things you are using:

### Steps to reproduce the Behavior

Just connect after referencing the library at new project and adding required code into main activity

### Expected Behavior
should connect to in-app purchase system
### Actual Behavior
throws exception
### Code snippet
var billing = CrossInAppBilling.Current;
            try
            {
                var connected = billing.ConnectAsync().Result;  // Throws exception here 

                if (!connected)
                {
                    Debug.WriteLine("Error");
                }
                else
                {
                    var rsp = billing.PurchaseAsync("it.horsense.mag.hs201801eng", ItemType.InAppPurchase, "Payment").Result;
                }   

                //make additional billing calls
            }
            finally
            {
                billing.DisconnectAsync().Wait();
            }

**Comment by jamesmontemagno** [comment]
Please read through: https://jamesmontemagno.github.io/InAppBillingPlugin/

Also, you are calling .Result and .Wait which will surely lock your application. https://montemagno.com/c-sharp-developers-stop-calling-dot-result/

**Comment by SandhaniCom** [comment]
You are right .Result blocks the UI. I have changed that code and followed your tutorial still throws exception at connect call. Have you tested your library with new Xamarin forms 4.0 application at Visual Studio 2019 ? 


Error Message: 

System.ArgumentNullException: Value cannot be null.
Parameter name: source
  at System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source)


Stack Trace

  at System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0000d] in <bae3cbc34c1846fe81f905a6e2680c06>:0 
  at Plugin.InAppBilling.InAppBillingImplementation+InAppBillingServiceConnection.ConnectAsync () [0x0003b] in C:\projects\inappbillingplugin\src\Plugin.InAppBilling.Android\InAppBillingImplementation.cs:642 
  at Plugin.InAppBilling.InAppBillingImplementation.ConnectAsync (Plugin.InAppBilling.Abstractions.ItemType itemType) [0x00012] in C:\projects\inappbillingplugin\src\Plugin.InAppBilling.Android\InAppBillingImplementation.cs:373 
  at PaymentGateway.MainPage.PayBtn_Clicked (System.Object sender, System.EventArgs e) [0x0003c] in X:\path to project\PaymentGateway\MainPage.xaml.cs:31

**Comment by SandhaniCom** [comment]
Yes, It is connected now. I think you should mention troubleshooting content at the beginning of tutorial. That clear all the issues.

**Comment by jamesmontemagno** [comment]
I wrote an entire blog on it... https://montemagno.com/c-sharp-developers-stop-calling-dot-result/

**Comment by mbilalbenli** [comment]
Same exception here.

When I cancel purchase, Androids throwing same exception.

`                await ConnectBilling();

                var purchase = await Billing.PurchaseAsync(productId, ItemType.InAppPurchaseConsumable);

                if (purchase == null)
                {

                }
                else if (purchase.State == PurchaseState.Purchased)
                {
                   
                    var consumedItem = await Billing.ConsumePurchaseAsync(purchase.ProductId, purchase.TransactionIdentifier);
                
                }`
