### ISSUE TITLE
Automated Android settings are broken in VS2019

### ISSUE THREAD

**Issue by zoli13** [jamesmontemagno/InAppBillingPlugin#223]
I install the plugin (2.0.0, latest stable) in VS2019 (right click on Solution > Manage nuget packages for solution > install InAppBillingPlugin for all projects (.net / android / ios).

**Result**:
Android MainActivity.cs is not updated (OnActivityResult)
Android MainApplication.cs is not updated (CrossCurrentActivity)
Android manifest is not extended with "com.android.vending.BILLING" during build.

**Expected**:
All these to happen - as documented.

**NOTE**
All these worked in VS2017

**Workaround**
Add these manually to .cs files and manifest.

**Comment by jamesmontemagno** [comment]
You need to manually add these items now. This is documented and expected.
