### ISSUE TITLE
[Android] GetProductInfoAsync returns NULL

### ISSUE THREAD

**Issue by K232** [jamesmontemagno/InAppBillingPlugin#228]
## Bug Information

Version Number of Plugin: 2.0.0 and 2.1.0.187-beta
Device Tested On: Wiko Lenny 3
Version of VS: VS for Mac 2019 8.0.9 (Build 5)
Version of Xamarin Forms: 4.0.0.425677
Versions of other things you are using:
NETStandard.Library: 2.0.3
Newtonsoft.Json: 12.0.2
Plugin.CurrentActivity (Android only): 2.1.0.4
Xamarin.Android.Support...: 28.0.0.1
Minimum Android Version: 4.4 (API level 19)
Target Android Version: 9.0 (API level 28)

### Steps to reproduce the Behavior

- Created new application in Google Play Store
- Added Plugin.InAppBilling to all 3 Projects (NETStandard, Android, iOS)
- Uploaded apk to Google Play Store
- Updated settings in Google Play Store. Status is "Pending Publication".
- Setup 2 Managed Products in In-app products in Google Play Status. Status of both products is "Active".
- Added section to MyApp.Android.csproj (see below) for automatic signing
- await billing.ConnectAsync(ItemType.InAppPurchase); return true
- await billing.GetProductInfoAsync(ItemType.InAppPurchase, productIds); returns NULL

### Expected Behavior
Get details of in app items

### Actual Behavior
await billing.GetProductInfoAsync(ItemType.InAppPurchase, productIds); returns NULL on Android. On iOS it works fine.

### Code snippet
```
var billing = CrossInAppBilling.Current;
try
{
   var connected = await billing.ConnectAsync(ItemType.InAppPurchase);
   Debug.WriteLine($"Billing is connected: {connected}.");
   if (connected)
   {
      iaps = await billing.GetProductInfoAsync(ItemType.InAppPurchase, productIds);
      if (iaps == null)
         Debug.WriteLine("No (null) InApp Purchases retrieved from AppStore.");
      else
         {
         Debug.WriteLine($"Retreived {iaps.Count()} InApp Purchases from AppStore.");
```
                    
Required Permissions as shown in Google Play Store:

> android.permission.ACCESS_NETWORK_STATE, 
> android.permission.INTERNET, 
> android.permission.READ_EXTERNAL_STORAGE, 
> android.permission.WRITE_EXTERNAL_STORAGE, 
> com.android.vending.BILLING

MainActivity.cs
```
using System;

using Android.App;
using Android.Content.PM;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Android.OS;
using Plugin.InAppBilling;
using Android.Content;

namespace MyApp.Droid
{
    [Activity(Label = "MyApp", Icon = "@mipmap/icon", Theme = "@style/SplashTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        protected override void OnCreate(Bundle savedInstanceState)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            Window.AddFlags(WindowManagerFlags.Fullscreen);
            Window.ClearFlags(WindowManagerFlags.ForceNotFullscreen);

            base.SetTheme(resid: Resource.Style.MainTheme);
            base.OnCreate(savedInstanceState);

            Xamarin.Essentials.Platform.Init(this, savedInstanceState);
            global::Xamarin.Forms.Forms.Init(this, savedInstanceState);
            Acr.UserDialogs.UserDialogs.Init(this);
            Plugin.CurrentActivity.CrossCurrentActivity.Current.Init(this, savedInstanceState);
            Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity = this;

            LoadApplication(new App());
        }
        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Android.Content.PM.Permission[] grantResults)
        {
            Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);

            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
        protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
        {
            base.OnActivityResult(requestCode, resultCode, data);
            InAppBillingImplementation.HandleActivityResult(requestCode, resultCode, data);
        }
    }
}
```

MyApp.Android.cs
```
  <PropertyGroup>
    <AndroidKeyStore>True</AndroidKeyStore>
    <AndroidSigningKeyStore>/Users/me/Library/Developer/Xamarin/Keystore/MyApp/MyApp.keystore</AndroidSigningKeyStore>
    <AndroidSigningStorePass>-password-</AndroidSigningStorePass>
    <AndroidSigningKeyAlias>MyApp</AndroidSigningKeyAlias>
    <AndroidSigningKeyPass>-samepasswordagain-</AndroidSigningKeyPass>
</PropertyGroup>
```

Readme.txt says that a file "MainApplication.cs" will be added to Android application but it was not. I also tried copying https://github.com/jamesmontemagno/CurrentActivityPlugin/blob/0b712af88deef177a379569a48989e0b936013c9/src/CurrentActivityTest.Droid/MainApplication.cs to my project, but no changes.

Got these lines in application output
> [Mono] Loading reference 4 of /storage/emulated/0/Android/data/app.myapp/files/.__override__/Plugin.InAppBilling.dll asmctx DEFAULT, looking for Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
> [Mono] Assembly Loader probing location: '/storage/emulated/0/Android/data/app.myapp/files/.__override__/Newtonsoft.Json.dll'.
> [Mono] AOT: image '/storage/emulated/0/Android/data/app.myapp/files/.__override__/Newtonsoft.Json.dll.so' not found: dlopen failed: library "/storage/emulated/0/Android/data/app.myapp/files/.__override__/Newtonsoft.Json.dll.so" not found
> [Mono] AOT: image '/Users/builder/jenkins/workspace/xamarin-android-d16-0/xamarin-android/external/mono/sdks/out/android-armeabi-v7a-release/lib/mono/aot-cache/arm/Newtonsoft.Json.dll.so' not found: dlopen failed: library "/Users/builder/jenkins/workspace/xamarin-android-d16-0/xamarin-android/external/mono/sdks/out/android-armeabi-v7a-release/lib/mono/aot-cache/arm/Newtonsoft.Json.dll.so" not found
> [Mono] Assembly Ref addref Plugin.InAppBilling[0xab5293a0] -> Newtonsoft.Json[0xab528fe0]: 2
> [ztgl] asset != NULL

Any ideas?

**Comment by K232** [comment]
I've restarted from scratch, and now it's working fine for both Android and iOS :-)

Only thing I changed: **I published my Android App!** This seems to be the only fix for me. 

The other things are just the basic steps:

- Added InAppBilling Plugin to all 3 projects
- Added _Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity = this;_ to OnCreate in Android MainActivity.cs
- Added _OnActivityResult_ to Android MainActivity.cs

No other steps within the app (like automatic code signing) were necessary.

Now I could also unpublish my app in Google Play Store (in _Pricing & Distribution_) and InApp Purchases are still returned!

**Comment by 1iveowl** [comment]
I'm having the same issue on Android. 

By "**I published my Android App!**" did you publish to production or was Internal/Alpha/Beta sufficient? I read in the documentation that Draft is not enough, but that Alpha and Beta should be OK. 

BTW. I have no issue on iOS.

**Comment by K232** [comment]
@1iveowl , I've published to live and then restricted the countries so that chance is very rare that someone installs by mistake during live-time.

**Comment by 1iveowl** [comment]
@K232 nice hack. Thanks

**Comment by EMANSO** [comment]
Same issue here on Android as well. Works fine on iOS. The workaround doesn't work for us. Any expectation to be fixed soon per chance?

**Comment by mnxamdev** [comment]
We are having issues with this as well. We create new accounts and some accounts it fails, some it doesn't. I had a phone which it was working just fine, same accounts as a broken device, then I minimized the app and came back to the app and all of a sudden it broke. I wonder if something is happening in the ActivityResult code where we add the following:
`
protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
        {
            base.OnActivityResult(requestCode, resultCode, data);

Plugin.InAppBilling.InAppBillingImplementation.HandleActivityResult(requestCode, resultCode, data);
}
`
