### ISSUE TITLE
[iOS] No Consumable inApp Purchase after Adding Payment Method in iTunes AppStore

### ISSUE THREAD

**Issue by SprengerS** [jamesmontemagno/InAppBillingPlugin#233]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 2.0.0
Device Tested On: all iOS Devices
Simulator Tested On:
Version of VS: current
Version of Xamarin: current
Versions of other things you are using:

### Steps to reproduce the Behavior
- No Payment Methods added to your AppleID
- Make an inApp Purchase
- iOS navigates you to the AppStore
- Complete Payment Methods, e.g. Credit Card
- Finish InApp Payment
- Navigate Back to the App

### Expected Behavior
- when loading inApp Purchases, I would expect that there is a inApp Purchase i can work with
### Actual Behavior
- the consumable inApp Purchase is lost

OutOfBand `OnPurchaseComplete` is implemented but never called

**Comment by wclark17** [comment]
I just ran into this.
Any idea if GetPurchases should pull down the purchase the when the app resumes?

**Comment by jamesmontemagno** [comment]
Closing due to age of issue and mass changes in library. haven't had issues getting new purchases
