### ISSUE TITLE
Question: Checking for In App Purchase intermittently gives the wrong result (android)

### ISSUE THREAD

**Issue by mikeedwards83** [jamesmontemagno/InAppBillingPlugin#235]
In the Android app we are making an in app purchase which executes correctly. The problem occurs when we try to check if the user has already bought the item. 

When the app loads we check to see if the user has bought the product using the following code:
https://gist.github.com/mikeedwards83/3709f5a54a041993da3853ad7bcef1ea

We are finding that intermittently the code is telling us that the user hasn't purchased the product when they actually have. Closing the app and opening it again seems to resolve the issue and return the correct result. 

I am not sure if this is a bug with the framework, my code or a misunderstanding on my part about how Google Play handles In App purchases.

Version Number of Plugin:  2.0.0
Device Tested On: Nexus 5x
Version of VS: 2017
Version of Xamarin: 9.1.5

Any help or guidance very much appreciated! This project has saved me a lot of time :-)

**Comment by bellissimo** [comment]
@mikeedwards83 Are you still having this issue, as I think I am getting something similar for a small number of users? 

Also, was the problem for you that GetPurchasesAsync was returning nothing, or that the 'State' was something other than 'Purchased' for the items that were returned?
