### ISSUE TITLE
PurchaseError return canceled if item already owned

### ISSUE THREAD

**Issue by JohnGaby** [jamesmontemagno/InAppBillingPlugin#236]
When I attempt to purchase an item on Android that is already owned, the purchase dialog tells me it is already owned (which is correct), however the exception that is thrown tells me that the transaction was UserCancelled.

Note that this is when using test purchases. I cannot say what the behavior would be during a real purchase but I assume it would be the same.

## Bug Information

Version Number of Plugin: 2.0.0
Device Tested On: 8/9/2019
Tested On: Samsung S5
Version of VS: 2017
Version of Xamarin: 4.12.3.83
Versions of other things you are using:

### Steps to reproduce the Behavior
Attempt to purchase a product that you already own.

### Expected Behavior
InAppBillingPurchaseException thrown with PurchaseError set to AlreadyOwned

### Actual Behavior
InAppBillingPurchaseException thrown with PurchaseError set to UserCancelled

**Comment by ant81584** [comment]
This issue also persists on iOS as well
