### ISSUE TITLE
How to perform iOS receipt validation on Xamarin Forms

### ISSUE THREAD

**Issue by sachinkanadia** [jamesmontemagno/InAppBillingPlugin#238]
I am using the in-app billing plugin for subscription purchases on iOS using Xamarin Forms.

1. When using the IInAppBillingVerifyPurchase interface I receive an NullReference exception when the user has no subscription instead of it returning false. 

2. How do you implement the iOS version of the interface?

3. How would one perform receipt validation for iOS, is it possible to perform the validation from the app or would I need a server?

**Comment by sachinkanadia** [comment]
Also I can't seem to change user account on iOS and its always returning the subscription for GetPurchasesAsync() no matter what account I sign in with on my iPhone

**Comment by Nerves82** [comment]
Did you find an answer to this question? I am looking for the same information now, how to do validation on iOS. https://github.com/jamesmontemagno/InAppBillingPlugin/issues/280
