### ISSUE TITLE
Automatic adding of billing permission in Android

### ISSUE THREAD

**Issue by navneet-webority** [jamesmontemagno/InAppBillingPlugin#24]
For Android, the plugin automatically adds the permission,

[assembly: UsesPermission("com.android.vending.BILLING")]

We use the plugin in a reusable common PCL which we use for all apps we have and some of them don't use billing. I suggest the permission shouldn't be hardcoded in the library and should be put in Readme for Android setup.

**Comment by jamesmontemagno** [comment]
I auto add permissions to all my libraries, sorry that is just my convention.
