### ISSUE TITLE
Does iOS cache purchase information?

### ISSUE THREAD

**Issue by cncb-gh** [jamesmontemagno/InAppBillingPlugin#242]
I was under the impression that iOS (like Android) caches purchase information so that purchases can still be retrieved when offline.  But it seems to fail to retrieve purchases when there is no internet connection available.  Is this a bug of recent iOS updates or was this always the case?  Thanks.

**Comment by jamesmontemagno** [comment]
I am not positive that it does. I would consult the iOS docs: https://jamesmontemagno.github.io/InAppBillingPlugin/TestingAndTroubleshooting.html
