### ISSUE TITLE
Plugin fails on Xamarin.Android with vague error message ("Something went wrong on our end. Please try again.")

### ISSUE THREAD

**Issue by Swiftloke** [jamesmontemagno/InAppBillingPlugin#244]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Generally speaking, I have an adversity to requesting assistance on GitHub; however, this issue has completely confounded me and the author of this plugin seems to be willing to take questions here.
Detailed information can be found here: https://stackoverflow.com/questions/57936383/in-app-billing-plugin-fails-on-xamarin-android-with-a-vague-error-message-some

Version Number of Plugin: v2.0.0
Device Tested On: Galaxy S9 (SM_G960U)
Simulator Tested On: N/A
Version of VS: Community 2019: 16.1.6
Version of Xamarin: 9.3.0.23
Versions of other things you are using:

**Comment by mtanml** [comment]
I am having this same issue

**Comment by jamesmontemagno** [comment]
Make sure you use my guide to android testing: https://jamesmontemagno.github.io/InAppBillingPlugin/TestingAndTroubleshooting.html
