### ISSUE TITLE
Plugin.CurrentActivity 2.1.0.4 is not compatible

### ISSUE THREAD

**Issue by RakeshRaviGovindhan** [jamesmontemagno/InAppBillingPlugin#245]
Error	NU1202	Package Plugin.CurrentActivity 2.1.0.4 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Plugin.CurrentActivity 2.1.0.4 supports: monoandroid44 (MonoAndroid,Version=v4.4)

**Comment by jamesmontemagno** [comment]
This package is only for the Android project in your app.
