### ISSUE TITLE
CrossInAppBilling.Current.ConnectAsync() fails in 3.0.0-beta

### ISSUE THREAD

**Issue by tipa** [jamesmontemagno/InAppBillingPlugin#247]
## Bug Information

Version Number of Plugin: 3.0.0-beta
Device Tested On: OnePlus 5 & OnePlus 7 Pro
Version of VS: 16.3.2
Version of Xamarin: 16.3.0

### Steps to reproduce the Behavior
Enable full linking & R8 code-shrinking

### Expected Behavior
`await CrossInAppBilling.Current.ConnectAsync()` returns true

### Actual Behavior
`await CrossInAppBilling.Current.ConnectAsync()` returns false

### Code snippet
```
<DebugSymbols>True</DebugSymbols>
<DebugType>Full</DebugType>
<Optimize>False</Optimize>
<OutputPath>bin\Debug\</OutputPath>
<DefineConstants>TRACE;DEBUG</DefineConstants>
<ErrorReport>prompt</ErrorReport>
<WarningLevel>4</WarningLevel>
<AndroidUseSharedRuntime>True</AndroidUseSharedRuntime>
<AndroidLinkMode>Full</AndroidLinkMode>
<EmbedAssembliesIntoApk>False</EmbedAssembliesIntoApk>
<AndroidEnableMultiDex>false</AndroidEnableMultiDex>
<AndroidSupportedAbis />
<AndroidHttpClientHandlerType>Xamarin.Android.Net.AndroidClientHandler</AndroidHttpClientHandlerType>
<AndroidTlsProvider>btls</AndroidTlsProvider>
<AndroidEnableSGenConcurrent>true</AndroidEnableSGenConcurrent>
<AotAssemblies>false</AotAssemblies>
<EnableLLVM>false</EnableLLVM>
<AndroidDexTool>d8</AndroidDexTool>
<AndroidUseAapt2>true</AndroidUseAapt2>
<AndroidLinkTool>r8</AndroidLinkTool>
```

**Comment by jamesmontemagno** [comment]
Does this only happen when you enable full linking?

**Comment by tipa** [comment]
Yes, it works fine when "Sdk Assemblies Only" linking

**Comment by jamesmontemagno** [comment]
### Final Builds
For linking you may need to add:

#### Android:
```
Plugin.InAppBilling;
```

#### iOS:
```
--linkskip=Plugin.InAppBilling
```

That should fix it up fo ryou.

**Comment by tipa** [comment]
That did not work unfortunately. I also see this message in the logs:
`Unable to check if billing is supported: abstract method "int com.android.vending.billing.IInAppBillingService.isBillingSupported(int, java.lang.String, java.lang.String)"`
It appears one have to exclude `Xamarin.Android.Google.BillingClient` from linking to get it to work

**Comment by jamesmontemagno** [comment]
Ah gotcha! Good to know! Will update readme
