### ISSUE TITLE
if serviceConnection?.Service is null, try to reconnect

### ISSUE THREAD

**Issue by EmilAlipiev** [jamesmontemagno/InAppBillingPlugin#248]
```
 public async override Task<IEnumerable<InAppBillingProduct>> GetProductInfoAsync(ItemType itemType, params string[] productIds)
        {
            if (serviceConnection?.Service == null)
            {
                throw new InAppBillingPurchaseException(PurchaseError.ServiceUnavailable, "You are not connected to the Google Play App store.");
            }
```

Above code or other api functions throws exception very often because of although ConnectAsync function is used before and connected=true returned. Google api just randomly disconnect you in the middle of the process. thats why below issues created earlier.
it would be better to try to reconnect before every other api function attempt.

https://github.com/jamesmontemagno/InAppBillingPlugin/issues/197
https://github.com/jamesmontemagno/InAppBillingPlugin/issues/195

**Comment by nacompllo** [comment]
I am having the same problem, I am running the example in this same repository but the serviceConnection always appears null, when I try to make a purchase I get the same error: You are not connected to the Google Play App store. Any idea what might be happening?

![pluginSample](https://user-images.githubusercontent.com/20904914/93000524-55319b00-f529-11ea-907b-38c3228b5211.PNG)

**Comment by EmilAlipiev** [comment]
I have an alternative [nuget](https://github.com/EmilAlipiev/XFInAppBilling), you can try if you want. I reprogrammed from the scratch and i don't see this error any longer.

**Comment by jamesmontemagno** [comment]
Would recommend trying 4.0 which uses the new Android APIs.
