### ISSUE TITLE
Version 3 - can not compile

### ISSUE THREAD

**Issue by amallini** [jamesmontemagno/InAppBillingPlugin#249]
#128  Bug Information

Version Number of Plugin:
3.0.0-beta
Device Tested On:
Xiaomi Redmi 4.
Simulator Tested On:
No
Version of VS: 
Visual Studio Community 2019 v.16.2.1
Version of Xamarin:
v.28.0.0.3
Versions of other things you are using:

### Steps to reproduce the Behavior
Upgrade InAppBilling plugin (in existing project) to the last version 3.0.0.-beta
### Expected Behavior
My project can be compiled.
### Actual Behavior
I see compile errors.
1. 
using Plugin.InAppBilling.Abstractions;
Error: Abstractions does not exists in Plugin.InAppBilling namespace.
2.
in file MainActivity.cs
InAppBillingImplementation.HandleActivityResult(requestCode, resultCode, data);
Error: InAppBillingImplementation does not exists in current content.

In documentation I see the following:
--
Version 3 Linker Settings
For linking if you are setting Link All you may need to add:
Android:
Plugin.InAppBilling;Xamarin.Android.Google.BillingClient;
--
But I have no idea in what place I have to add this string.

Please help me.

 
### Code snippet
protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
 {
            base.OnActivityResult(requestCode, resultCode, data);
            InAppBillingImplementation.HandleActivityResult(requestCode, resultCode, data);
  }

**Comment by jamesmontemagno** [comment]
The namespace changed. Remove the using statement.

**Comment by amallini** [comment]
Hi James.

Thank you.

But what about the second error?
2.
in file MainActivity.cs
InAppBillingImplementation.HandleActivityResult(requestCode, resultCode, data);
Error: InAppBillingImplementation does not exists in current content.

May I comment this statement?

**Comment by jamesmontemagno** [comment]
You need to import the same using statement
