### ISSUE TITLE
Version 3.0.0-beta Compile error.

### ISSUE THREAD

**Issue by amallini** [jamesmontemagno/InAppBillingPlugin#250]
## Bug information

Version Number of Plugin:
3.0.0-beta
Device Tested On:
Xiaomi Redmi 4.
Simulator Tested On:
No
Version of VS:
Visual Studio Community 2019 v.16.2.1
Version of Xamarin:
v.28.0.0.3
Versions of other things you are using:

Steps to reproduce the Behavior
Upgrade InAppBilling plugin (in existing project) to the last version 3.0.0.-beta

Expected Behavior
My project can be compiled.

Actual Behavior
I see compile error.

In file MainActivity.cs
statement:
InAppBillingImplementation.HandleActivityResult(requestCode, resultCode, data);
Error: InAppBillingImplementation does not exists in current content.
I do use this statemnet:
using Plugin.InAppBilling;
But I see it in gray color.

### Code snippet
using Android.App;
using Android.Content.PM;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Android.OS;
using Plugin.InAppBilling; // this string is gray!
using Android.Content;

namespace <MyNameSpace>.Droid
{
    [Activity(Label = "<My Label>", Icon = "@drawable/icon", Theme = "@style/MainTheme", ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
        {
            base.OnActivityResult(requestCode, resultCode, data);
            InAppBillingImplementation.HandleActivityResult(requestCode, resultCode, data); //ERROR here
        }
...

### Screenshotst

Please help me to compile my project.

**Comment by jamesmontemagno** [comment]
Can you uninstall and re-install the nuget package. Works fine for me, see attached project.
[App25.zip](https://github.com/jamesmontemagno/InAppBillingPlugin/files/3726305/App25.zip)

**Comment by amallini** [comment]
James, thank you.

You've sent me project without InAppBilling plugin installed.
But don't worry.
I've created a new project.
I've installed version 3.0.0-beta of InAppBilling plugin.
I've added 
protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
{
base.OnActivityResult(requestCode, resultCode, data);
InAppBillingImplementation.HandleActivityResult(requestCode, resultCode, data); //ERROR here
}
And I've compiled it successfully!

But.
I still can not compile my old project.
I've deleted plugin from project.
I've installed plugin.
I've cleaned the solution.
But still I have the same error:
Error CS0103: The name 'InAppBillingImplementation' does not exist in the current context (CS0103) (<MyNamespace>.Android)
And string 
using Plugin.InAppBilling;
is gray.

I've made Update all plugins.
I've made Restore all plugins.
No luck.

What can you recommend in this situation?

**Comment by jamesmontemagno** [comment]
Make sure that you are compiling against Android 9.0 or higher. and remove the nuget and re-add it. I would need to see your csproj file.

You can see what it is installing by  going into your android project folder and into the OBJ folder and find **project.assets.json** and open that

validate that it is using lib/monoandroid90

```
"Plugin.InAppBilling/3.0.0-beta": {
        "type": "package",
        "dependencies": {
          "Newtonsoft.Json": "12.0.2",
          "Plugin.CurrentActivity": "2.1.0.4",
          "System.ValueTuple": "4.5.0",
          "Xamarin.Android.Google.BillingClient": "2.0.0",
          "Xamarin.Android.Support.Annotations": "28.0.0.3"
        },
        "frameworkAssemblies": [
          "Java.Interop"
        ],
        "compile": {
          "lib/monoandroid90/Plugin.InAppBilling.dll": {}
        },
        "runtime": {
          "lib/monoandroid90/Plugin.InAppBilling.dll": {}
        }
      },
```
[App25.zip](https://github.com/jamesmontemagno/InAppBillingPlugin/files/3731474/App25.zip)

See which has the nugets installed
