### ISSUE TITLE
Code does not continue after purchase

### ISSUE THREAD

**Issue by gktval** [jamesmontemagno/InAppBillingPlugin#251]
## Bug Information

Version Number of Plugin: 2.0.0.0
Device Tested On: Android
Version of VS: 2019
Version of Xamarin: 4.12.3.83
Versions of other things you are using:

### Steps to reproduce the Behavior
After purchasing a consumable item, the code never continues.
I have the following code, The purchase is successful, But after the purchase is made, it is supposed to save the results to a file (which never happens). For testing purposes, I am using an AlertDialog to show that a purchase was made. This never happens either.

       public async void MakePurchase(object sender, PurchaseEventArgs e)
        {
               var connected = await _billing.ConnectAsync(ItemType.InAppPurchase);
                if (connected == false)
                {
                    await DisplayAlert("Error Connecting", "Could not connect to the Google Play purchases", "OK");
                    return;
                }

                //try to purchase item
                InAppBillingPurchase purchase = await _billing.PurchaseAsync(e.ProductId, ItemType.InAppPurchase, e.AccountId.ToString());
                if (purchase != null)
                    await DisplayAlert("Is Purchased?", purchase.State.ToString(), "OK");

                if (purchase == null)
                    await DisplayAlert("Error Purchasing Item", "There was an error processing the in-app product.", "OK");
                else 
                {
                //... Consume the item. Tell the server it was consumed. Save the token to a file...
                }
                await _billing.DisconnectAsync();
         }

**Comment by AndrewSatMap** [comment]
I'm having exactly the same problem. The following code is not hit, and no exceptions are thrown. I have added try/catch individually around each call to the plugin in order to isolate the problem.

The effect of this is that none of the code after billing.PurchaseAsync() is called, meaning that the purchase is not consumed, which then means that I am unable to purchase the item again

```
private async Task<bool> Purchase()
{
    // CONNECT
    try
    {
        await Logger.Debug(PURCHASE, "Connecting to In-App purchases");   // LOGGED ok
        connected = await billing.ConnectAsync(ItemType.InAppPurchase);
        if (!connected)
            return await Logger.Info(PURCHASE, "Connection failed");

        await Logger.Debug(PURCHASE, "Connected");    // LOGGED ok
    }
    catch (InAppBillingPurchaseException purchaseEx)
    {
        return Logger.Error(PURCHASE, "InAppBillingPurchaseException", purchaseEx.Message);
    }
    catch (Exception ex)
    {
        return await Logger.Error(PURCHASE, "Exception", ex.Message);
    }

    // PURCHASE
    await Logger.Info(PURCHASE, "Beginning purchase", $"SKU: {purchase.ProductId}");     // LOGGED ok
    try
    {
        purchase = await billing.PurchaseAsync(vm.SelectedProduct.SKU, ItemType.InAppPurchase, Constants.InAppBillingPayload);
        await Logger.Debug(PURCHASE, "PurchaseAsync - exception NOT thrown"); // NOT LOGGED
    }
    catch (InAppBillingPurchaseException purchaseEx)
    {
        await billing.DisconnectAsync();
        return await Logger.Error(PURCHASE, "InAppBillingPurchaseException", purchaseEx.Message);  // NOT LOGGED
    }
    catch (Exception ex)
    {
        await billing.DisconnectAsync();
        return await Logger.Error(PURCHASE, "Exception", ex.Message);
    }
    await Logger.Debug(PURCHASE, "Purchase operation returned");  // NOT LOGGED

    // CONSUME
    if (purchase != null && Device.RuntimePlatform != Device.iOS)
    {
        await Logger.Info(PURCHASE, "Android purchase successful - need to consume it");  // NOT LOGGED
        try
        {
            consumed = await billing.ConsumePurchaseAsync(purchase.ProductId, purchase.PurchaseToken);
            if (consumed != null)
                await Logger.Info(PURCHASE, $"{Device.RuntimePlatform} purchased and consumed");  // NOT LOGGED
            else
                await Logger.Warning(PURCHASE, $"{Device.RuntimePlatform} purchased but NOT consumed");   // NOT LOGGED
        }
        catch (InAppBillingPurchaseException purchaseEx)
        {
            await billing.DisconnectAsync();
            return await Logger.Error(PURCHASE, "InAppBillingPurchaseException (consumption)", purchaseEx.Message);    // NOT LOGGED
        }
        catch (Exception ex)
        {
            await billing.DisconnectAsync();
            return await Logger.Error(PURCHASE, "Exception (consumption)", ex.Message); // NOT LOGGED
        }
    }    
}
```

So even though the UI reports that the first purchase is successful, the code to consume the purchase is never reached. Consequently, subsequent purchases fail because the item has already been purchased and not consumed.

The logging output I receive on the first run is as follows
```
Connecting to In-App purchases
Connected
Beginning purchase
```

... and on the seccond run
```
Connecting to In-App purchases
Connected
Beginning purchase
InAppBillingPurchaseException - Already Owned
```

None of the catch blocks are triggered

I am using the following tools
```
Plugin.InAppBilling	v2.0.0
Xamarin.Forms	v4.3.0.947036
Tested On		Android 9 and 10
Visual Studio		2019 (Community)
```

**Comment by AndrewSatMap** [comment]
I have also tried the beta version 3.0.0-beta, with exactly the same outcome

**Comment by AndrewSatMap** [comment]
I have managed to respove the problem. it was being caused becuase of the following code in the MainActivity.cs of the Android project...

```
using Plugin.InAppBilling;

protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
{
    base.OnActivityResult(requestCode, resultCode, data);
    // InAppBillingImplementation.HandleActivityResult(requestCode, resultCode, data);
}
```

The call to `InAppBillingImplementation.HandleActivityResult()` was commented out (because the associated `using Plugin.InAppBilling;` was missing). As soon as I restored this call, the full workflow was in place, and the call to `await billing.PurchaseAsync()` was able to complete, and all of the subsequent logic then worked.

Thanks

**Comment by gktval** [comment]
I have this code in my activity already:

       protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
        {
            base.OnActivityResult(requestCode, resultCode, data);
            InAppBillingImplementation.HandleActivityResult(requestCode, resultCode, data);
        }

But it still never executes past the purchase. The only way I have gotten it to work is by saving a file to the phone once the player enters the store. Then, when the app is started again after the purchase, it checks if there the special file is there, if so, then it queries the store for any purchases and consumes them then. This is not ideal though as it creates a lapse in the process that error could happen.

**Comment by gktval** [comment]
Figured out how to resolve this. I was finishing the activity on pause do to other related code. This, in turn cause the OnActivityResult to not continue the code.
