### ISSUE TITLE
How to debug subscriptions in production

### ISSUE THREAD

**Issue by sachinkanadia** [jamesmontemagno/InAppBillingPlugin#262]
Hi There,

I have successfully verified my iOS subscriptions on the Apple Test Servers however, I would like to test against the Apple Production Servers from visual studio. When running my app with a non sandbox user account from my physical iOS device I receive the error "Cannot connect to the iTunes Store" on purchase. I think there maybe a constraint with running the App with the correct certificate and provisioning profile because you can't run an App through visual studio with distribution certificate and distribution provisioning profile.

Is the scenario of testing against production possible? If so, how this be achieved?

**Comment by aidan-waite** [comment]
I believe the only way is to use a promo code and build your app so it's pointing at production servers/products. https://medium.com/uvimate/how-to-generate-and-redeem-ios-app-promo-codes-in-2018-for-the-new-app-store-835d6a1654c1
