### ISSUE TITLE
GetProductInfoAsync freezes on iOS

### ISSUE THREAD

**Issue by MajdSharp** [jamesmontemagno/InAppBillingPlugin#263]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:2.0.0
Device Tested On:iPhone 6 plus
Simulator Tested On:
Version of VS: 2017
Version of Xamarin:4.0.0.425677
Versions of other things you are using:

### Steps to reproduce the Behavior
create a merchant id and app id;
add an test account to the sandbox sections on the appstoreconnect.apple.com and to device;
 running the app in debug mode;
call GetProductInfoAsync;
### Expected Behavior
get product info
### Actual Behavior
freezing of the app without any exceptions and without returning any thing, just freezing;
with output message:
Thread finished: <Thread Pool> #6
The thread 0x6 has exited with code 0 (0x0).
Thread finished: <Thread Pool> #5
The thread 0x5 has exited with code 0 (0x0).
### Code snippet
```
`` private void Button_Clicked(object sender, EventArgs e)
        {
            if (!CrossInAppBilling.IsSupported)
                return;
            System.Diagnostics.Debug.WriteLine("billing is supported");
            var billing = CrossInAppBilling.Current;
            //billing.InTestingMode = true;
            try
            {
                var productIds = new string[] { "<ID>" }; 
                var connected = billing.ConnectAsync(ItemType.InAppPurchase).Result;

                if (!connected)
                {
                    System.Diagnostics.Debug.WriteLine("billing is not connected");
                    return;
                }

                System.Diagnostics.Debug.WriteLine("billing is connected");

                var items = billing.GetProductInfoAsync(ItemType.InAppPurchase, productIds).Result;
                System.Diagnostics.Debug.WriteLine("billing returned");
                if (items == null)
                {
                    System.Diagnostics.Debug.WriteLine("billing items is null");
return;
                }
                else
                {
                    System.Diagnostics.Debug.WriteLine("billing success get item" + items.ToList()[0].Name);
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("billing exception: " + ex.Message);

            }
        }``
```

**Comment by asj-it** [comment]
it's freezing because you a calling `.Result` when you call `GetProductInfoAsync`.  Calling `.Result `blocks threads until the call has completed.

You need to `await` the call instead.

**Comment by jamesmontemagno** [comment]
See^
