### ISSUE TITLE
Is this Beta 3.0.0 codeline?

### ISSUE THREAD

**Issue by excellapay** [jamesmontemagno/InAppBillingPlugin#265]
I am trying to debug a subscription issue with the 3.0.0 nuget package. Is this the same code that is released as that beta version?

**Comment by jamesmontemagno** [comment]
3.0 is in this branch https://github.com/jamesmontemagno/InAppBillingPlugin/tree/feature/android-billing-client

**Comment by EmilAlipiev** [comment]
> 3.0 is in this branch https://github.com/jamesmontemagno/InAppBillingPlugin/tree/feature/android-billing-client

Hi @jamesmontemagno 

I cloned this branch and tried to debug UWP test but it always returns not implemented exception. It seems that click bait implemenation below not falling into else part. It always returns as NETSTANDARD2_0. Do you know why?

```
#if NETSTANDARD1_0 || NETSTANDARD2_0
            return null;
#else
#pragma warning disable IDE0022 // Use expression body for methods
			return new InAppBillingImplementation();
#pragma warning restore IDE0022 // Use expression body for methods
#endif
```
