### ISSUE TITLE
How to go abouts implementing a free trial for a subscriptions orientated app

### ISSUE THREAD

**Issue by sachinkanadia** [jamesmontemagno/InAppBillingPlugin#266]
Hi There,

I have successfully implemented subscriptions in my app thanks to your API. I was wondering if I wanted to offer users a free trial how I would go abouts doing this?

I notice in Xamarin Forms its not possible to get the device Id or apple id/google id so how would I track the free trials?

I'd appreciate any advise on the matter.

Many Thanks

**Comment by ouma** [comment]
Free trial is managed by Apple/Google. Yo do not have write any code for that.
