### ISSUE TITLE
GetPurchasesMethodReturns Empty list

### ISSUE THREAD

**Issue by mahit777** [jamesmontemagno/InAppBillingPlugin#267]
## Bug Information

Version Number of Plugin:2.2
Device Tested On:Samsung M30
Simulator Tested On:Google Pixel
Version of VS: 2017
Version of Xamarin:2.5
Versions of other things you are using: Android API Level 28

### Expected Behavior
Getpurchases should return the list of purchases
### Actual Behavior
Calling get purchases method returns empty list

### Code snippet

var purchases = this._serviceConnection.BillingHandler.GetPurchases(ItemType.Product);

### Screenshotst
N/a

**Comment by jamesmontemagno** [comment]
Unable to reproduce
