### ISSUE TITLE
Supporting Promo Codes in App

### ISSUE THREAD

**Issue by Alex-59** [jamesmontemagno/InAppBillingPlugin#268]
Hello,
Thank you for this very useful plugin. I would like to use promo codes (configured in Google play Console) for consumables and subscriptions. In the documentation of your plugin, I did not find how to manage these coupon codes. Is it possible to manage these promo codes (enter them in the application) with your plugin?
If so, how can I do it?
Thanks in advance

**Comment by SebastianKruseWago** [comment]
Those promotional codes needs to be used in the iOS AppStore or Google PlayStore app in the redeem section and afterwards restored within your app. In case of Google see: https://developer.android.com/google/play/billing/billing_promo

**Comment by jamesmontemagno** [comment]
There is a new apple api for opening a promo screen, but is a swift only api right now and can't access it.

I am not sure if this is really an issue anymore as we use the latest billing library from google.
