### ISSUE TITLE
Android only test purchases in 3.0 beta? How to disable test?

### ISSUE THREAD

**Issue by mzhukovs** [jamesmontemagno/InAppBillingPlugin#269]
I must be missing something obvious here but I packaged up an app using InAppBilling latest version (3.0 beta) and it's only letting users do a "test" purchase, i.e. they actually can get all the in-app purchases for free.... what am I missing? How do I disable this and actually make them supply real payment info?
Insight would be much appreciated...
Thank you.

**Comment by jamesmontemagno** [comment]
Does it work fine with 2.x?
