### ISSUE TITLE
Question: Deferred iOS Purchases are supported?

### ISSUE THREAD

**Issue by Bartmax** [jamesmontemagno/InAppBillingPlugin#27]
I implemented all this before realizing that this plugin exist 😢 
Before replacing my code I wanted to be sure deferred iOS purchases are supported.

Looking at the code I can't be 100% sure. So are they?

If they are not, are you willing to accept a PR ?

Thanks.

**Comment by Bartmax** [comment]
Oh and another question, does your library check if InApps are enabled on the device or it must be done by the application?

**Comment by jamesmontemagno** [comment]
I can accepts PRs, however when you purchase it will tell you the state and tell you if it was deferred or not. 

It depends on the code that you would write on iOS to do the defer part

**Comment by Bartmax** [comment]
closing this one in favor of this more detailed issue with deferred.
https://github.com/jamesmontemagno/InAppBillingPlugin/issues/29
