### ISSUE TITLE
Misleading message for already subscribed but under trial subscription [Android]

### ISSUE THREAD

**Issue by kumarvikram** [jamesmontemagno/InAppBillingPlugin#271]
The plugin throws exception with message "Unable to process purchase" an display following message on UI
> Your order is processing, your item will be available in few minutes

![image](https://user-images.githubusercontent.com/5526914/72496514-d5471a00-384f-11ea-8614-6bceccad16c1.png)

This message is misleading as user is already subscribed.

**Comment by jamesmontemagno** [comment]
Have to ask google
