### ISSUE TITLE
GetPurchasesAsync returned old subscribtion

### ISSUE THREAD

**Issue by MaxFinit** [jamesmontemagno/InAppBillingPlugin#272]
Hello James! When I restoring subscription on android , the purchases that are returned is old. Subscription renewal has occurred but the function returns an old purchase.

## Bug Information

Version Number of Plugin: 2.0.0
Device Tested On: xiaomi redmi 8a / 9android
Version of VS: 2017 15.9.13
Version of Xamarin: 4.12.3.83
Versions of other things you are using:

### Steps to reproduce the Behavior

Call GetPurchasesAsync  func

`var purchases = await billing.GetPurchasesAsync(ItemType.Subscription);`

### Expected Behavior

Current subscribtion after prolongation

### Actual Behavior

First purchased subscription

**Comment by jamesmontemagno** [comment]
https://montemagno.com/ios-android-subscription-implemenation-strategies/
