### ISSUE TITLE
<GetAppReceiptAsync>d__3.MoveNext ()

### ISSUE THREAD

**Issue by BillyMartin1964** [jamesmontemagno/InAppBillingPlugin#273]
Worked great for years, but many of my users are suddenly getting hit by this error:

System.Runtime.ExceptionServices
ExceptionDispatchInfo.Throw () f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs at 63:13
System.Runtime.CompilerServices
TaskAwaiter.ThrowForNonSuccess (Task task) f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\TaskAwaiter.cs at 186:25
System.Runtime.CompilerServices
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task) f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\TaskAwaiter.cs at 154:48
System.Runtime.CompilerServices
TaskAwaiter.ValidateEnd (Task task) f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\TaskAwaiter.cs at 125:17
Plugin.InAppBilling.CurrentAppMock
<GetAppReceiptAsync>d__3.MoveNext ()
System.Runtime.ExceptionServices
ExceptionDispatchInfo.Throw () f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs at 63:13
System.Runtime.CompilerServices
TaskAwaiter.ThrowForNonSuccess (Task task) f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\TaskAwaiter.cs at 186:25
System.Runtime.CompilerServices
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task) f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\TaskAwaiter.cs at 154:48
System.Runtime.CompilerServices
TaskAwaiter.ValidateEnd (Task task) f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\TaskAwaiter.cs at 125:17
Plugin.InAppBilling.InAppBillingImplementation
<GetPurchasesAsync>d__8.MoveNext ()
System.Runtime.ExceptionServices
ExceptionDispatchInfo.Throw () f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs at 63:13
System.Runtime.CompilerServices
TaskAwaiter.ThrowForNonSuccess (Task task) f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\TaskAwaiter.cs at 186:25
System.Runtime.CompilerServices
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task) f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\TaskAwaiter.cs at 154:48
System.Runtime.CompilerServices
TaskAwaiter.ValidateEnd (Task task) f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\shared\System\Runtime\CompilerServices\TaskAwaiter.cs at 125:17
Yatzy.Services.YatzyIAP
<WasItemPurchased>d__1.MoveNext ()

**Comment by BillyMartin1964** [comment]
Not sure what's going on. I now have over a hundred users who have experienced this issue.

**Comment by jamesmontemagno** [comment]
Billy did you figure out what was going on. I have never seen this.

**Comment by BillyMartin1964** [comment]
No. totally lost on this bug.

**Comment by jamesmontemagno** [comment]
Unable to reproduce.
