### ISSUE TITLE
GetProductInfoAsync hangs on iOS

### ISSUE THREAD

**Issue by DM1145** [jamesmontemagno/InAppBillingPlugin#274]
Version Number of Plugin: 2.0.0
Device Tested On: iPhone 7plus, iOS 13.3.1
Simulator Tested On: iOS 13.3.1
Version of VS: 8.4.5 (build 19) for OSX
Version of Xamarin: 4.4.0.991537

### Steps to reproduce the Behavior
Use tutorial code.  Call GetProductInfoAsync with no items available in store (items missing price, as example)

### Expected Behavior
Return null or return error

### Actual Behavior
hangs, task doesn't finish

**Comment by jamesmontemagno** [comment]
Unable to reproduce with latest
