### ISSUE TITLE
PaymentPending instead of Purchased or FreeTrial

### ISSUE THREAD

**Issue by wojciech-kulik** [jamesmontemagno/InAppBillingPlugin#276]
## Bug Information

Version Number of Plugin: 2.0.0
Device Tested On: LG-H440n, Asus Zenfone 3
Simulators tested on: Pixel 2
Version of VS: Visual Studio Community 2019 for Mac Version 8.4.5 (build 19)
Version of Xamarin: 4.2.0.848062

### Steps to reproduce the Behavior
I published application with 1-year subscription auto-renewing with 14-days free trial.
When I buy it, I always get state `PaymentPending`. It never changes, even though in Developer Console it shows that payment is finished according to settings.

### Expected Behavior
Returned state should be `FreeTrial` or `Purchased`.

### Actual Behavior
Returns state `PaymendPending`

### Notes
I checked code and `InAppBillingImplementation.cs` and it seems that json returned in
`serviceConnection.Service.GetPurchases(3, Context.PackageName, itemType, null);` really contains `paymentState: 0` which is according to https://developers.google.com/android-publisher/api-ref/purchases/subscriptions payment pending...

Question is why it happens, is to Google's bug?

**Comment by wojciech-kulik** [comment]
I have found a root cause of this issue.

You have:
```
[JsonIgnore]
            public PurchaseState SubscriptionState
            {
                get
                {
                    if (PaymentState == 0)
                        return Abstractions.PurchaseState.PaymentPending;
                    else if (PaymentState == 1)
                        return Abstractions.PurchaseState.Purchased;
                    else if (PaymentState == 2)
                        return Abstractions.PurchaseState.FreeTrial;

                    return Abstractions.PurchaseState.Unknown;
                }
            }
```

However `PaymentState` is never returned in payload from Google Play Billing AIDL (see Table 7: https://developer.android.com/google/play/billing/billing_reference)

So when deserializing payload and this field is not available it always sets `0`, therefore it always returns `Abstractions.PurchaseState.PaymentPending`

**Comment by jamesmontemagno** [comment]
This will be fixed with the new version I am working on with the new Billing Client
