### ISSUE TITLE
Google Play Billing AIDL is deprecated

### ISSUE THREAD

**Issue by wojciech-kulik** [jamesmontemagno/InAppBillingPlugin#277]
Currently Android implementation is using `VendingLibrary` which is `Google Play Billing AIDL`.

You can read here: https://developer.android.com/google/play/billing/billing_reference

> Warning: AIDL is now deprecated and will be removed in a future release. To implement Google Play Billing features, use the Google Play Billing library.

Are there any plans to migrate this library?

**Comment by SuddalaSuraj** [comment]
Facing the same issue, any update issue.

**Comment by ivanicin** [comment]
@SuddalaSuraj @wojciech-kulik I have subscribed to this issue too, but this plugin is not active for some time and @jamesmontemagno many times noted that he won't develop it anymore, while everyone is free to submit the code.

This is perfectly fine for other plugins that he has developed and which are in the same state but their functionality is mostly contained in Xamarin.Essentials where I believe he contributed the code now.

At this point we can only hope that Xamarin.Essentials will include something similar to this in the future. Or we will have to fix it ourselves...

**Comment by mgoodfellow** [comment]
I think you might be looking for the v3 pre-release: https://www.nuget.org/packages/Plugin.InAppBilling/3.0.0-beta ?

I believe the v3 pre-release comes from this branch: https://github.com/jamesmontemagno/InAppBillingPlugin/tree/feature/android-billing-client 

It has been changed to use the Xamarin bindings for the Google Play Billing library: https://github.com/jamesmontemagno/InAppBillingPlugin/commit/fc8e8451bea4dfbe9142e62784e62490403d2903#diff-08c081149f48aedb20064b092c4d9217R55

This in turn uses: https://developer.android.com/google/play/billing/billing_library_overview - bindings from here (https://github.com/xamarin/XamarinComponents/tree/master/Android/GoogleBillingClient)

@jamesmontemagno can we get that feature branch merged in and a stable release issued to nuget? It has been perfectly stable for me so far, and I haven't seen any issues raised from other users?

**Comment by wojciech-kulik** [comment]
@mgoodfellow Great catch! Actually this migration is super easy. Especially that I was using directly library code instead of NuGet Package. It's just: 

- remove `VendingLibrary` project
- replace `Service = IInAppBillingServiceStub.AsInterface(service);` line with `Service = InAppBillingServiceStub.AsInterface(service);` (one letter change)
- add NuGet Package `Xamarin.Android.Google.BillingClient`

I already tried it and it looks like everything is working as previously.

I was only concerned about documentation saying:

> If you use the Google Play Billing Library version 2.0 or newer, you must acknowledge all purchases within three days. Failure to properly acknowledge purchases results in those purchases being refunded.

(https://developer.android.com/google/play/billing/billing_library_overview)

However, probably it is not necessary, because when I'm validating receipts from purchases using latest library, they have already flag `acknowledgementState=1`.

🍺

**Comment by wojciech-kulik** [comment]
I've got only question about:

```
public Task<bool> ConnectAsync()
{
    if (IsConnected)
        return Task.FromResult(true);

    tcsConnect = new TaskCompletionSource<bool>();
    var serviceIntent = new Intent("com.android.vending.billing.InAppBillingService.BIND");

	if(serviceIntent == null)
		return Task.FromResult(false);

	serviceIntent.SetPackage("com.android.vending");

    if (Context.PackageManager.QueryIntentServices(serviceIntent, 0).Any())
    {
        Context.BindService(serviceIntent, this, Bind.AutoCreate);
        return tcsConnect?.Task ?? Task.FromResult(false);
    }

    return Task.FromResult(false);
}
```

Will this code be still valid after deprecating AIDL? I'm not sure what is it for.

**Comment by de1081** [comment]
..sorry, so is this plugin still going to work, has anyone made the fix for this yet?

**Comment by jamesmontemagno** [comment]
I am hard at work on this. https://github.com/jamesmontemagno/InAppBillingPlugin/pull/295

It is a full re-write, going well actually. @Redth  is going to update the billing library to 2.2.1 soon.
