### ISSUE TITLE
The problem of changing to the Google Play fake store

### ISSUE THREAD

**Issue by pro777s** [jamesmontemagno/InAppBillingPlugin#278]
Hi, in version 2.0 of the plugin several times I encountered the problem of changing to the Google Play fake store. At the same time, purchases are successfully completed. Can this be somehow ruled out?

**Comment by charlesroddie** [comment]
> the problem of changing to the Google Play fake store

Can you clarify what you mean by this?

**Comment by pro777s** [comment]
Attackers somehow use a fake Google Play store to make a purchase in the program. The idea here is to add a Google Play store domain certificate verification to exclude the use of a fake Google Play store.

**Comment by ouma** [comment]
You should use server side validation to verify the purchase on the server.

**Comment by pro777s** [comment]
Yes, I do. But it would be correct to exclude this problem at the stage of purchase.
