### ISSUE TITLE
PurchaseAsync on iOS, unpredictable behavior

### ISSUE THREAD

**Issue by llandru54** [jamesmontemagno/InAppBillingPlugin#279]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:   2.0
Device Tested On:   iPhone X, iOS 13.3
Simulator Tested On:
Version of VS: 16.4.4
Version of Xamarin:  4.4
Versions of other things you are using:

### Steps to reproduce the Behavior

I have a subscribe button in my app.  The user taps it, the iOS Confirmation box should pop up asking the user for password (if needed) or to OK if confirmed.

### Expected Behavior

The call to PurchaseAsync should wait until the user confirms or cancels.

### Actual Behavior

In debug mode, sometimes the call to PurchaseAsync returns immediately.  I can see this with breakpoints in the calling method (button click event).  I can also see this because the activity indicator stops (because it is set to false in the click event).  In fact, the verify method is sometimes also invoked.

In release mode, I have seen intermittent crashes when the subscribe button is tapped.

In debug mode, I sometimes see "Consistency error: you are calling a UIKit method that can only be invoked from the UI thread."  I am not (to my knowledge) accessing anything from a different thread.

I've tried wrapping the PurchaseAsync call with BeginInvokeOnMainThread, with no difference in behavior.

 I could really use some help on this -- it seems to be working find on Android, but I can't get it to behave consistently on iOS.  I'm in trial-and-error troubleshooting mode right now, which is worrisome because I need a working solution published on the App Store relatively soon.

### Code snippet
private async void Subscribe_Clicked(object sender, EventArgs e)
        {
            activitySubscribe.IsRunning = true;
            {
                await MakePurchase();
                activitySubscribe.IsRunning = false;
            }
       }

public async Task<bool> MakePurchase()
        {
            var verify = DependencyService.Get<IInAppBillingVerifyPurchase>();
            var billing = CrossInAppBilling.Current;
            try
            {
                var connected = await billing.ConnectAsync(ItemType.Subscription);
                if (!connected)
                    return false;

                InAppBillingPurchase purchase = null;
                purchase = await billing.PurchaseAsync(MYITEMID, ItemType.Subscription, MYITEMID, verify);
                if (purchase != null)
                {
                    return true;
                }
            }
            catch (InAppBillingPurchaseException ex)
            {
                return false;
            }
            finally
            {
                await billing.DisconnectAsync();
            }
            return true;
        }

**Comment by RobertBickers** [comment]
Did you get anywhere with this, we're seeing the same issue on my team?

**Comment by Meekohi** [comment]
Similar issue here. When this happens, the `purchase` object contains an old expired receipt. When I validate the receipt server side, I get a 21006 error indicating the purchase is expired, even though it was just returned from `PurchaseAsync`.

**Comment by jamesmontemagno** [comment]
I return what apple gives me sorry.
