### ISSUE TITLE
Extend support to Amazon App Store

### ISSUE THREAD

**Issue by solomonfried** [jamesmontemagno/InAppBillingPlugin#281]
If I am offering my app on the Amazon App Store (for Android Apps), does this plugin support it and if not are there guidelines to extend this to support that app store?

Thank you.

**Comment by jamesmontemagno** [comment]
It does not support it as of today. I have no current plans to add it in as it is very complicated and tedious to support more platforms fully.

**Comment by cklenk** [comment]
Is there a way to add Amazon to the CrossInAppBilling.IsSupported flag then so it doesn't try to make an IAP and crash?

Thanks

**Comment by jamesmontemagno** [comment]
I would probably put this check in your code and don't allow Amazon devices to do IAPs... would be my thought.

**Comment by cklenk** [comment]
I ended up doing a device manufacture check and put up an alert saying not supported. However, that apparently doesn't work with Amazon guidelines. They rejected the app. This is what I had, they are saying there shouldn't be any error. I guess I will just have to take it out completely?

![image](https://user-images.githubusercontent.com/12185742/86026053-f3b76100-b9fc-11ea-8738-57c8461a838f.png)

**Comment by jamesmontemagno** [comment]
What I have done in the past is create 2 versions of my app. 1 for google and one for amazon. Then i conditionally compile the code needed for IAP so you can then bring in their API directly.
