### ISSUE TITLE
Converting signedData within the InAppBillingVerifyPurchase.VerifyPurchase give gibberish 

### ISSUE THREAD

**Issue by Nerves82** [jamesmontemagno/InAppBillingPlugin#283]
Hi all. I am working on validating in app purchase receipts and having trouble because when I decode the signeddata I get a bunch of gibberish included with some recognizable information. This is a receipt from a sandbox purchase.

        public async Task<bool> VerifyPurchase(string signedData, string signature, string productId = null, string transactionId = null)
        {

            var base64EncodedBytes = System.Convert.FromBase64String(signedData);
            var s = System.Text.Encoding.UTF8.GetString(base64EncodedBytes);
            return true;
        }

s ends up looking like this:

   
0�	*�H��
��0�10	+�10000006527433310�10000006527382230�2020-04-16T13:07:22Z0�2020-04-16T12:57:23Z0�2020-04-16T13:12:22Z0C�:8com.companyname.appname.unlimitedlevelsubscription0����1��0�ions.appname.unlimitedlevelsubscription0����1��0��R�%
v������k�[^�sQIV��C�̎�Р��\��ii��h&&9�s�
]�s��v;�-و�������&U���I#c.1,0*U#Apple Worldwide Developer Relations1D0BU;Apple Worldwide Developer Relations Certification Authority0�"0
	*�H��
.1&0$UApple Certification Authority10U
Apple Root CA0�"0
	*�H��
S10U

Apple Inc.1,0*U#Apple Worldwide Developer Relations1D0BU;Apple Worldwide Developer Relations Certification Authority�W��	�0	+

What am I doing wrong?

**Comment by de1081** [comment]
Try a different encoding

**Comment by Nerves82** [comment]
Hello. This is still an issue. No form of encoding results in a proper result. It is always gibberish.

**Comment by jamesmontemagno** [comment]
Please read google docs for this, i just return the data
