### ISSUE TITLE
Support for Expiration Date

### ISSUE THREAD

**Issue by sachinkanadia** [jamesmontemagno/InAppBillingPlugin#285]
I'm wondering if it is possible to provide an expiration date for the InAppPurchaseItem. I'm trying to create offline features for my Xamarin.Forms app, however the fact that I must call GetPurchases() every time the user launches my App means they must be online. If I could somehow store the expiration date then I could store this value and check against this on launch instead.

Is this possible?

Thanks Sach

**Comment by jamesmontemagno** [comment]
You would just store the expiration data that you calculate from the time of purchase. These are not returned by any of the APIs.
