### ISSUE TITLE
Calling GetPurchasesAsync() returns history of purchase with all in Purchased state.

### ISSUE THREAD

**Issue by Nerves82** [jamesmontemagno/InAppBillingPlugin#287]
I am yet unable to tell if this is an error with the library or Apple Store Kit, but when calling GetPurchasesAsync() against the Apple sandbox environment on renewable subscriptions, I get a large list of historical purchase, which is expected but they all have the Status set to "purchased" so I am unable to tell what the current subscription is. I am trying to use the library directly so I can debug the issue, but also having issues doing that. Any suggestions on what may be causing this?

**Comment by MrAndrewAu** [comment]
For me, when I call GetPurchasesAsync() in Sandbox, I only ever get one result, and each time I call it, the one result is different than the last time I called it (different purchase dates). Also, the purchaseToken is always an empty string. Other people reported the same problem, so I don't think GetPurchasesAsync() is usable in its current state until somebody contributes to fix it...
