### ISSUE TITLE
Feature Request: Free Trial Period Product Info

### ISSUE THREAD

**Issue by InquisitorJax** [jamesmontemagno/InAppBillingPlugin#288]
Would be great if we setup a free trial period for X amount of days, that this information be available on the InAppBillingProduct

This comes in handy when displaying an IAP page in the app, to be able to display to the user how long the trial period is. The added properties should complement the HasIntroductoryPrice property.

**Comment by yonkahlon** [comment]
Agreed

**Comment by jamesmontemagno** [comment]
This is coming :) I just started  the Android implementation and will surface it in iOS too :)

**Comment by davidbuckleyni** [comment]
That’s good to see I think I added a request of the same
