### ISSUE TITLE
URGENT: DLL on Nuget is infected with a Trojan: MSIL.Kryptik.NE@81eks7

### ISSUE THREAD

**Issue by PaymonK** [jamesmontemagno/InAppBillingPlugin#292]
You can see it detected by Comodo virus scanner.

Please fix it and release a new Nuget ASAP.

## Bug Information

Version Number of Plugin: Latest
Device Tested On: Comodo AntiVirus
Simulator Tested On: All platforms
Version of VS: 2019
Version of Xamarin: Latest
Versions of other things you are using: Latest Comodo anti virus

### Steps to reproduce the Behavior
Just scan the DLL. My app APK was detected as a Trojan, which led me to find this.

### Expected Behavior
Clean and virus-free!

### Actual Behavior
Dirty and viral!

### Code snippet
Not applicable

**Comment by jamesmontemagno** [comment]
No idea what you are talking about.

**Comment by PaymonK** [comment]
This is a real issue James. 

You probably had this virus on your system when you compiled it and it transferred itself into the DLL. You can see for yourself if you run a Comodo virus scanner on that DLL or any app APK that uses it.
