### ISSUE TITLE
Question about Testing under IOS 

### ISSUE THREAD

**Issue by dirkzp** [jamesmontemagno/InAppBillingPlugin#296]
Hello,

We have a problem with testing annual subscription in TestFlight. The subscription is not expiring, so after the first virtual purchase in Sandbox mode, it is not possible to test it again.

We've done all the steps described in the manual:
https://jamesmontemagno.github.io/InAppBillingPlugin/TestingAndTroubleshooting.html

Does anyone have a suggestion? 
We tried the following things:
- Delete the App
- Logout of Itunes & AppStore
- Remove tester from TestFlight Group and add him again

On Android this issue is not present.

 public async Task<bool> CheckSubscriptionAlreadyPurchased()
        {
            string productId = "XXX_subscription";

            if (!CrossInAppBilling.IsSupported)
                return false;

            var billing = CrossInAppBilling.Current;

            try
            {
                billing.InTestingMode = true;
                var connection = await billing.ConnectAsync(ItemType.Subscription);

                if (!connection)
                {
                    return false;
                }

                //check purchases
                var purchases = await billing.GetPurchasesAsync(ItemType.Subscription);

                //check for null just incase
                if (purchases?.Any(p => p.ProductId == productId) ?? false)
                {
                    // purchase restored
                    return true;
                }
                else
                {
                    // no purchases found
                    return false;
                }
            }
            catch (InAppBillingPurchaseException purchaseEx)
            {
                var message = string.Empty;
                switch (purchaseEx.PurchaseError)
                {
                    case PurchaseError.AppStoreUnavailable:
                        message = "Currently the app store seems to be unavailble. Try again later.";
                        break;
                    case PurchaseError.BillingUnavailable:
                        message = "Billing seems to be unavailable, please try again later.";
                        break;
                    case PurchaseError.PaymentInvalid:
                        message = "Payment seems to be invalid, please try again.";
                        break;
                    case PurchaseError.PaymentNotAllowed:
                        message = "Payment does not seem to be enabled/allowed, please try again.";
                        break;
                }

                //Decide if it is an error we care about
                if (string.IsNullOrWhiteSpace(message))
                    return false;

                return false;
            }
            catch (Exception)
            {
                throw new Exception();
            }
            finally
            {
                await billing.DisconnectAsync();
            }
        }

System Information:
Version Number of Plugin: 3.0.0beta
Device Tested On: IPad, IPhone with IOS 13.5
Version of VS: 16.5.5
Version of Xamarin: 4.6.0.800

**Comment by oicangi05** [comment]
did you find something on this?

**Comment by InquisitorJax** [comment]
It looks like that code is only valid for android, because android will only return active purchases on that call.
iOS, however, returns all purchases, with no real way to tell if the purchase has expired or not (they recommend doing a receipt validation on the server to update the subscription state)
There does seem to be a work-around mentioned in this thread (by looking for expired-date value in the token of a purchase) 
https://github.com/jamesmontemagno/InAppBillingPlugin/issues/311 - but I haven't tried it yet.

**Comment by Meekohi** [comment]
Same issue here. Verifying server-side doesn't help, the sandbox returns code 21006 and a deprecated iOS6 style receipts
> This receipt is valid but the subscription has expired. When this status code is returned to your server, the receipt data is also decoded and returned as part of the response. Only returned for iOS 6-style transaction receipts for auto-renewable subscriptions.

Is there anyone who has actually succeeded in cross-app subscriptions with Xamarin? Would love to see some "working" code.

**Comment by greg84** [comment]
My code is as follows, this checks for a valid auto renewing 30 day subscription. I have verified that on iOS the transaction date this plugin uses should be the last time a payment was taken for that particular subscription.

I am ok with accepting some risk that the transaction wasn't necessarily successful, but I don't want to go through the hassle of validating the receipt, so this will have to do for now.

In your case, you could just check that a subscription exists with a transaction date within the last year, plus a week or so - just in case!

```
                var purchases = await billing.GetPurchasesAsync(ItemType.Subscription);

                var productId = GetProductId();

                purchases = purchases?.Where(p => p.ProductId == productId);

                if (DeviceInfo.Platform == DevicePlatform.iOS)
                {
                    var fortyDaysAgo = DateTime.UtcNow.AddDays(-40);

                    purchases = purchases?.Where(p => p.TransactionDateUtc > fortyDaysAgo);
                }

                var purchase = purchases?.OrderByDescending(p => p.TransactionDateUtc).FirstOrDefault();

                if (purchase != null
                    && (purchase.State == PurchaseState.Purchased
                        || purchase.State == PurchaseState.Restored))
                {
                    // user has active subscription
                }
                else
                {
                    // user does not have active subscription
                }
```

**Comment by Meekohi** [comment]
Thanks for sharing! I have made a little progress since two weeks ago, but it is extremely difficult to test due to the behavior on iOS Sandbox. We don't mind the hassle of validating the iOS receipts (made a small Azure Functions App to do this and record the result in the db so we can also access it on Android), but the Sandbox will frequently return expired receipts even in response to `.PurchaseAsync`. If I wait ~10-15 minutes and try again, usually it will start working.

**Comment by jamesmontemagno** [comment]
See: https://montemagno.com/ios-android-subscription-implemenation-strategies/

**Comment by jamesmontemagno** [comment]
https://www.revenuecat.com/blog/the-ultimate-guide-to-subscription-testing-on-ios
