### ISSUE TITLE
AlreadyOwned exception gets thrown when using static Google product testing

### ISSUE THREAD

**Issue by de1081** [jamesmontemagno/InAppBillingPlugin#298]
## Bug Information
When attempting to make a test purchase using the static Google product id ("android.test.purchased"). This will work once. Then every time after it will throw an exception "Already owned". 

Setting the InAppBilling.Current.InTestingMode = true; Has no effect.

This has only recently surfaced and was not an issue before

Version Number of Plugin: 3.0.0-beta
Device Tested On: Android tablet
Simulator Tested On:
Version of VS: 16.6.2
Version of Xamarin: 4.5.0.617
Versions of other things you are using:

**Comment by jamesmontemagno** [comment]
I think this is expected. Once you own it you get an error to process that it was already owned, i would check this in your error codes.
