### ISSUE TITLE
Android Orientation Change during Purchase causes exception during DisconnectAsync

### ISSUE THREAD

**Issue by Yeshia** [jamesmontemagno/InAppBillingPlugin#299]
When I initiate a purchase and then rotate the screen, the purchase seems to work but an exception is thrown when it hits DisconnectAsync.  "Service not Registered".   Is this expected behavior?

**Comment by jamesmontemagno** [comment]
Hmmm interesting, i will test this in the next update. Strange.

**Comment by Yeshia** [comment]
Just did a couple quick tests and when I changed the Context in ConnectAsync and DisconnectAsync to ApplicationContext, I did not get any errors.

**Comment by jamesmontemagno** [comment]
Cool, in v3 i have it so Connect uses applicationcontext, however a purchase does take in an activity.

**Comment by Yeshia** [comment]
I have it set to always use the AppContext for the Connect/Disconnect methods, but the purchase method uses the Activity.
