### ISSUE TITLE
HandleActivityResult change in 3.1.0-beta

### ISSUE THREAD

**Issue by AntvissMedia** [jamesmontemagno/InAppBillingPlugin#300]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Hello James,

3.1.0-beta no longer has a HandleActivityResult method. Is this not needed anymore or has it been replaced with a different method?

Also, the ConnectAsync method no longer takes an ItemType object, so I have removed this from the parameters. Is this the right way to go and leave the default bool value there? Or is there another way it needs to be done? Thank you for your time!

Version Number of Plugin: 3.1.0-beta
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

**Comment by jamesmontemagno** [comment]
That is correct. This uses the latest Billing API, so you no longer need any of the HandleActivityResult stuff. And yup you no longer need to pass in an ItemType as their API no longer requires it as we can figure it out at purchase time.

You should now ensure you handle pending purchase -> https://developer.android.com/google/play/billing/integrate#ooap

**Comment by Sebastian1989101** [comment]
@jamesmontemagno Is this anything we have to implement? Or does the plugin already handle the pending purchases for us?
