### ISSUE TITLE
ConnectAsync does not return a response (the app freezes)

### ISSUE THREAD

**Issue by NikkiTheStitchQueen** [jamesmontemagno/InAppBillingPlugin#301]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: Pulled project directly in (feature/new-android-billing)
Device Tested On: Google Pixel 2
Simulator Tested On:
Version of VS: VS Community 2019 - version 16.6.4
Version of Xamarin: 
Versions of other things you are using: 
* Target framework: Android 10.0Q
* Xamarin.Android.Google.BillingClient (version 2.0.0) - when I tried to upgrade to 3.0.0, I got errors in Plugin.InAppBilling

### Steps to reproduce the Behavior

Follow documentation for: 

 var connected = await billing.ConnectAsync(ItemType.InAppPurchase);

### Expected Behavior

App will either connect or send back an error

### Actual Behavior

My app freezes. Debugging the code, it will go through the ConnectAsync code, but I never get a value for "connected" and the app freezes.

**Comment by lamoureux29** [comment]
Same here, did you found a solution?

**Comment by tinytownsoftware** [comment]
I am suffering from the same problem. Did you ever find out what the issue was?

**Comment by Ozden79** [comment]
I've the very same issue, anybody can shad a light on what might be wrong?

**Comment by jamesmontemagno** [comment]
Please upgrade to 4.0, i am using this in production just fine :)

**Comment by Ozden79** [comment]
Upgrading to 4.0 didn’t solve my problem, however, I found the issue. I was calling the the function with a “Task<bool>” object as return and than was using “Task.Wait()” call to wait finish the call which caused the freeze. Instead of this, if you use “await”, it works fine.
