### ISSUE TITLE
Upgrading Plugin.InAppBilling from 3.0.0-beta to 3.1.0-beta causes purchase error (Android)

### ISSUE THREAD

**Issue by Sebastian1989101** [jamesmontemagno/InAppBillingPlugin#302]
After upgrading Plugin.InAppBilling from 3.0.0-beta to 3.1.0-beta, it's no longer possible to purchase products on my Android version of the app. The user always gets a error message. Is there something else todo beside the NuGet package upgrade and the removal of `InAppBillingImplementation.HandleActivityResult(requestCode, resultCode, data);` from `OnActivityResult(int requestCode, Result resultCode, Intent data)`? Or is this a actual bug? 

Restoring seems to work so I'm not sure what causes this on new purchases. Just tested it with 3 devices.

**Comment by jamesmontemagno** [comment]
Hmmm. I am still testing things out on my end and just wrote the code. it is really a 4.0.0

It is correct that we no longer  need the HandleActivityResult.

What error are you getting? 

Is it InAppPurchase or Subscription?

Can you get product info?

This is the code that I run: https://github.com/jamesmontemagno/InAppBillingPlugin/blob/feature/new-android-billing/src/Plugin.InAppBilling/InAppBilling.android.cs#L220

**Comment by Sebastian1989101** [comment]
Sadly it only says "Error on purchasing the product". It only appears on new purchases, old purchases are just restored (as they should) and the normal restore also works. All of the purchases I tested are normal InAppPurchases (tested one time purchases and consumeables even if those two are the same for Android) so no subscriptions tested. 

If I see this correctly, I just get a `NULL` from this call as a result: `await InAppBillingPlatformWrapper.Implementation.PurchaseAsync(identifier, ItemType.InAppPurchase, _verifyPurchase)` (`identifier` is my product ID which still works on the live version that uses 3.0.0-beta; `_verifyPurchase` is my instance for `IInAppBillingVerifyPurchase` which is never getting called). 

Also it seems like `IInAppBillingVerifyPurchase` is no longer used on a restore call? Or was this never the case? But how does a subscription in this case validate if it is still active? But maybe that is another question anyway.

This however works with 3.0.0-beta without any issues (and also on iOS with 3.1.0-beta).

**Comment by jamesmontemagno** [comment]
So question.....

Does your `_verifyPurchase` get called? I am curious if it gets that far or not.

You are correct the identifier should not have changed.


Do you at all call: `GetProductInfoAsync`.... this will query the productId and get the details.... it would be nice to know if this works as I also have to call the same methods in `PurchaseAsync`

**Comment by jamesmontemagno** [comment]
Between 2.0 and 3.1 the iOS implementation hasn't really changed for context. 

3.1 introduced a full re-write of Android code to use the new billing library to be compliant.

**Comment by jamesmontemagno** [comment]
If you are up for an adventure, you could just shove https://github.com/jamesmontemagno/InAppBillingPlugin/blob/feature/new-android-billing/src/Plugin.InAppBilling/InAppBilling.android.cs into your code and debug through it. This is the hardest sstuff to debug.

**Comment by Sebastian1989101** [comment]
@jamesmontemagno I just debugged through your linked code. If I use this code the `tcsPurchase` is already `null` in `PurchaseAsync(string productSku, string itemType, IInAppBillingVerifyPurchase verifyPurchase)`. So it leaves the purchase method on the very first line already. 


> Does your `_verifyPurchase` get called? I am curious if it gets that far or not.
No as already said above.

> Do you at all call: `GetProductInfoAsync`.... this will query the productId and get the details.... it would be nice to know if this works as I also have to call the same methods in `PurchaseAsync`
Yes, I use `GetProductInfoAsync` in advance to check which purchases are available and I also used this when `await InAppBillingPlatformWrapper.Implementation.PurchaseAsync(identifier, itemType, _verifyPurchase);` returns `null` after a few seconds to check if the purchase was still running in the background which happens sometimes.

**Comment by PiTi2k5** [comment]
Maybe you will find the answer in https://github.com/EmilAlipiev/XFInAppBilling/tree/Billing221updateAndroidX
Support for AndroidX Lib, Android10 and Google Play Billing Library 3.0

**Comment by jamesmontemagno** [comment]
@Sebastian1989101 ahh i think i see what i did...

I had 

```csharp
var completed = tcsPurchase?.Task?.IsCompleted ?? false;
if (!completed)
  return null;
```

but should be -> 
```csharp
// If we have a current task and it is not completed then return null.
            // you can't try to purchase twice.
            if(tcsPurchase?.Task != null && !tcsPurchase.Task.IsCompleted)
            {
                return null;
            }
```

So, if it is completed

**Comment by jamesmontemagno** [comment]
Give 4.0.0-beta a try :)

**Comment by CDrosos** [comment]
I would like also to ask soemthing about the beta version.

Im using 3.10 beta too and i see things have changed from the time the documentation https://jamesmontemagno.github.io/InAppBillingPlugin/ was written. for example billing.ConnectAsync() now only takes bool as parameter.
I want to ask this: should i use the stable version for now or try to use the 4.0 version. For the 4 version we dont have for now documentation, am i right?

**Comment by jamesmontemagno** [comment]
You should not use 3.1 (I have removed it.) 2.0/3.0 still used AIDL and 4.0 uses the new Play Billing 2.0

**Comment by jamesmontemagno** [comment]
I have added documentation for changes here -> https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/README.md#version-4-major-update---android
