### ISSUE TITLE
IOS 14

### ISSUE THREAD

**Issue by JohnGaby** [jamesmontemagno/InAppBillingPlugin#303]
I just received this message from Google:

"As part of iOS 14, developers will need to: 
 
1. Update to use GMA SDK v7.64 or later. 
 
2. Request the new AppTrackingTransparency Framework permission. 
 
Both of these steps are crucial to avoid unintentional revenue loss. "

Is anything being done to address this?

Thanks

**Comment by jamesmontemagno** [comment]
Yeah, that isn't form me at all that is the google mobile ads sdk.
