### ISSUE TITLE
Restore / Subscription validation no longer possible with 3.1.0 / 4.0.0

### ISSUE THREAD

**Issue by Sebastian1989101** [jamesmontemagno/InAppBillingPlugin#304]
After the upgrade to 3.1.0 or 4.0.0, the `GetPurchasesAsync` no longer checks with the `IInAppBillingVerifyPurchase` for a server side validation. This is a problem for canceled subscriptions because they can no longer be validated (or is there a new way to validate subscriptions?).

**Comment by InquisitorJax** [comment]
@jamesmontemagno can we get that included in the "breaking changes" section in the readme? We were blissfully unaware that had been removed :(
