### ISSUE TITLE
Allow user to Un-Subscribe or Cancel Subscription

### ISSUE THREAD

**Issue by blmiles** [jamesmontemagno/InAppBillingPlugin#305]
Hello,

My app is required to allow a user to cancel a subscription.
There does not seem to be any method to do so.

I do see a purchase.State property and PurchaseState.Canceled value but no further documentation or sample on actually canceling the subscription with the respective store from within the app. How to use the AutoRenewing property would be very useful too.

Can someone please point out how to CANCEL a subscription? And set a purchase to AutoRenew?

Further to that, I also see a PurchaseState.FreeTrial

My app has a 14 day trial period but I'm not using that state value.
Methinks using the PurchaseState.FreeTrial on a purchase to initiate/monitor the trial period would be better than what I've implemented NOT using the In App Billing API.

Is there any sample on how best to use that?

Thanks

**Comment by blmiles** [comment]
@jamesmontemagno 
Hello, I was wondering if you could address this at all?

With so many apps going to a subscription based model, it'd be very helpful to see a refined implementation for that using your plugin.
Specifically using the FreeTrial capability, the AutoRenew and also allow the user to Cancel the subscription from within an App.
Your docs got my implementation to a certain point (thank you btw) but could do with more detail around managing subscriptions within an App, with platform-specific anomalies thrown in.

Xamarin.Forms (iOS and Android with a shared project). I've created a BillingService as a dependency to handle differences in each platform but could do with more guidance per the above suggestions.

Thank you!

**Comment by Abesoddy** [comment]
It would be great if an example was available!!!

**Comment by stesvis** [comment]
@jamesmontemagno I am looking forward to this too !
