### ISSUE TITLE
InAppBillingImplementation does not exist (ver. 4.0.0)

### ISSUE THREAD

**Issue by Flying-Light** [jamesmontemagno/InAppBillingPlugin#306]
Hello,
I cannot update to your 4.0.0 beta version,
Once I did, `InAppBillingImplementation.HandleActivityResult(requestCode, resultCode, data);` not work and shows me 'InAppBillingImplementation does not exist'

If I commented this line, the plugin not work and I cannot process any in-app payment.
I can update up to 3.0.0 version only.
How can I solve this problem?

Thanks in advance

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 4.0.0
Device Tested On:
Simulator Tested On:
Version of VS: Latest
Version of Xamarin:  Latest
Versions of other things you are using:

**Comment by jamesmontemagno** [comment]
You can remove this. It isn't needed

**Comment by Flying-Light** [comment]
Thanks,
but when I did so, the CrossInAppBilling.IsSupported returns 'false'
If I ignored it, then the app crash with:
System.NotImplementedException: 'This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.'

Any ideas?

**Comment by Flying-Light** [comment]
I am using real samsung device, and I can run it using the 3.0.0 beta version.
This error only comes with the 4.0.0 beta version,

CrossInAppBilling.IsSupported always = false

**Comment by jamesmontemagno** [comment]
I probably forgot to override it. I'll put out a 4.0.1 that fixes that.

**Comment by jamesmontemagno** [comment]
Actually i checked the code and it looks fine. Maybe uninstall and re-install the nuget in all of your projects

**Comment by Flying-Light** [comment]
These are the steps I followed:
1- Uninstall the plugin
2- Delete (bin, obj) folders
3- Clean
4- Install the latest plugin version (4.0.0 beta)
5- Build the project
6- Run
>> IOS
Works fine
>> Android 
CrossInAppBilling.IsSupported always = false

**Comment by Flying-Light** [comment]
Is there anything I can do from my side right now?
I still cannot use the plugin on Android, it is fine with IOS
CrossInAppBilling.IsSupported always false

Is there a way to solve it with 4.0.0, or I have to wait for the next release?

Thanks in advance

**Comment by jamesmontemagno** [comment]
Oh... you MUST set your Android project to compile against Android 10.0 or above. The default projects are 9.0, so adjust that and it will work :)

**Comment by Flying-Light** [comment]
I Already tried this option, and it is not working.
I even used your Test application, your InAppBillingTests.Android uses Target Framework "Android 10.0 (Q)"
But it returns False as well,
when I debuge the following lines:
>static IInAppBilling CreateInAppBilling()
>        {
>#if NETSTANDARD1_0 || NETSTANDARD2_0
>            return null;
>#else
>#pragma warning disable IDE0022 // Use expression body for methods
>			return new InAppBillingImplementation();
>#pragma warning restore IDE0022 // Use expression body for >methods
>#endif
>		}

Always it returns null. 
that is why "public static bool IsSupported => implementation.Value == null ? false : true;" returns false.

I am testing your source "InAppBillingPlugin-4.0.0.1"

So,
Changing Target Framework to "Android 10.0 (Q)" do nothing for this problem.

**Comment by jamesmontemagno** [comment]
Works fine for me:
![image](https://user-images.githubusercontent.com/1676321/92009213-04d26600-ecfd-11ea-8356-ba96a0594b46.png)


Compile set to 10 -> 
![image](https://user-images.githubusercontent.com/1676321/92009234-10be2800-ecfd-11ea-8198-75d866691923.png)

Sample app:
[App10.zip](https://github.com/jamesmontemagno/InAppBillingPlugin/files/5163504/App10.zip)

**Comment by Flying-Light** [comment]
Your app works with me,
I am using Xamarin.Forms, 
I install fresh VS, and uninstall tens of plugins which uses support.v7,
Now I am not facing the problem anymore,
but I have another error "Current Activity is null, ensure that the MainActivity.cs file is configuring Xamarin.Essentials in your source code so the In App Billing can use it."

While I am double sure I set the 
> "CrossCurrentActivity.Current.Activity".

I even can call it from inside the shared application:
> var activity = Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity;

I can use my CrossCurrentActivity everywhere else, but not from billing plugin.

Any clue, please?

**Comment by Flying-Light** [comment]
I solved it with:
> Xamarin.Essentials.Platform.Init(this, bundle);


> protected override void OnCreate(Bundle bundle)
> {
>     base.OnCreate(bundle);
>     Xamarin.Essentials.Platform.Init(this, bundle);
> }


I do not know why this line is needed, it was working without it.
And I cannot remember that I see it in the instruction of "CrossCurrentActivity" before!

Anyway, thanks a million
Keep your great work

**Comment by jamesmontemagno** [comment]
I switched to using Xamarin.Essentials in the latest..
