### ISSUE TITLE
Getting exception "This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation."

### ISSUE THREAD

**Issue by quicoli** [jamesmontemagno/InAppBillingPlugin#309]
Hello,

When I try to use it 
I get exception "This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation."

Am I missing something?

## Bug Information

Version Number of Plugin: 4.0.0-beta
Device Tested On: Samsung Galaxy S8
Simulator Tested On: no simulators
Version of VS:  16.6.2
Version of Xamarin: 4.8.0.1364
Versions of other things you are using: Plugin.CurrentActivity 2.1.0.4

I have set licensing account, uploaded the app to internal track test and released, subscription is active in android developer console page. 

Error seems to occur here:  CrossInAppBilling.shared.cs:28 

### Steps to reproduce the Behavior
Configured Plugin.CurrentActivity as https://github.com/jamesmontemagno/CurrentActivityPlugin/blob/master/README.md
In Forms project try to use wait CrossInAppBilling.Current.ConnectAsync();

### Expected Behavior
Not exception

### Actual Behavior
Exception

### Code snippet
```
               var isConnected = await CrossInAppBilling.Current.ConnectAsync();
                if (isConnected)
                {
                    var _subscriptionList = await CrossInAppBilling.Current.GetPurchasesAsync(ItemType.Subscription);
                    if (_subscriptionList.Any())
                    {
                        foreach (var _subscription in _subscriptionList)
                        {
                            if (_subscription.State == PurchaseState.Purchased || _subscription.State == PurchaseState.PaymentPending)
                            {
                                await SecureStorage.SetAsync("premiun", "true");
                                break;
                            }
                        }
                    }
                }
```

### Screenshotst
![image](https://user-images.githubusercontent.com/8388239/92287283-459acc80-ef01-11ea-9597-49bcff555e91.png)

**Comment by jamesmontemagno** [comment]
See - https://github.com/jamesmontemagno/InAppBillingPlugin/issues/306#issuecomment-685843711
