### ISSUE TITLE
iOS Cancel purchase improvement

### ISSUE THREAD

**Issue by Bartmax** [jamesmontemagno/InAppBillingPlugin#31]
When starting a new purchase, the iTunes confirmation dialog pop ups with the option to `OK` or `Cancel`.
If the user clicks `Cancel` a `FailedTransaction` is issued.

right now in the handler, when a `FailedTransaction` occurs it set the `TaskCompletionSource` with an exception.
```
if (!success)
    tcsTransaction.TrySetException(new Exception(tran?.Error.LocalizedDescription));
else
    tcsTransaction.TrySetResult(tran);
```
https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/src/Plugin.InAppBilling.iOS/InAppBillingImplementation.cs#L197-L200

The error description will show **"Cannot connect to iTunes Store".**

Here there is room for improvement because a `Cancel` action is not really an exception. Normally in your application code, when an exception occurs you want to display a message to the user that there was a problem yada yada, but when the user press `Cancel` you may not want to do that.

The way this can be handled is by the Error Code provided by the Error object on the transaction.
If the Error Code is 2, the user cancelled the operation.
It's amazing that on apple docs https://developer.apple.com/reference/storekit/skpaymenttransaction they mention to check the codes list but I wasn't able to find the doc or a list of error codes.

So I think there are multiple ways to handle this.
1) Don't throw an exception, just set the transaction as `null`.
2) Throw a custom exception like `StoreCancelledException`

Both ways will provide the application a way to detect from one or the other and respond accordingly.
I most inclined to 1, since this isn't really an exception. The downside to the first option is that application needs to try/catch and null check, while with option 2 a try/catch will handles the error with the option to use a catch/when for the specific `Cancel` case.

Either way, this is my suggested code update (option1). If you want I can PR, whatever option you want.
<details>
  <summary>Cilck to reveal proposed code update.</summary>

```
Task<SKPaymentTransaction> PurchaseAsync(string productId)
{
    TaskCompletionSource<SKPaymentTransaction> tcsTransaction = 
                new TaskCompletionSource<SKPaymentTransaction>();

    Action<SKPaymentTransaction, bool> handler = null;
    handler = new Action<SKPaymentTransaction, bool>((tran, success) =>
    {


        // Only handle results from this request
        if (productId != tran.Payment.ProductIdentifier)
            return;

        // Unsubscribe from future events
        paymentObserver.TransactionCompleted -= handler;


        if (!success)
        {
            if (tran?.Error.Code == 2)
            {
                tcsTransaction.TrySetResult(null);
            }
            else
            {
                tcsTransaction.TrySetException(new Exception(tran?.Error.LocalizedDescription));
            }
        }
        else
            tcsTransaction.TrySetResult(tran);
    });

    paymentObserver.TransactionCompleted += handler;

    var payment = SKPayment.CreateFrom(productId);
    SKPaymentQueue.DefaultQueue.AddPayment(payment);

    return tcsTransaction.Task;
}
```
and
```
public async Task<InAppBillingPurchase> PurchaseAsync(string productId, 
                     ItemType itemType, 
                     string payload, 
                     IInAppBillingVerifyPurchase verifyPurchase = null)
{
    var p = await PurchaseAsync(productId);
    if (p == null)
    {
        return null;
    }
    // .......
}
```
</details>

**Comment by jamesmontemagno** [comment]
Good improvement. I am actually going to streamline this like I did for Android and return a bunch of exceptions with error codes

**Comment by Bartmax** [comment]
wow that was fast!! impressive! thank you!
