### ISSUE TITLE
Android VerifyPurchase failing

### ISSUE THREAD

**Issue by michaelfoster9** [jamesmontemagno/InAppBillingPlugin#314]
Hello, I am using your SDK to make in-App purchases on Android.  I am experiencing some results that lead me to believe that it's not working.

Here is the code for how I call your API to make a purchase.
`var result = await billing.PurchaseAsync(option.FeatureCode, type, new Verify(_analytics));`

My verification code looks as follows

        public Task<bool> VerifyPurchase(string signedData, string signature)
        {
            var key1Transform = InAppBillingImplementation.InAppBillingSecurity.TransformString(key1, 1);
            var key2Transform = InAppBillingImplementation.InAppBillingSecurity.TransformString(key2, 2);
            var key3Transform = InAppBillingImplementation.InAppBillingSecurity.TransformString(key3, 3);          
            bool verified = InAppBillingImplementation.InAppBillingSecurity.VerifyPurchase(key1Transform + key2Transform + key3Transform, signedData, signature);
            return Task.FromResult(verified);
        }

These are the results that I am seeing.  
When in a debug environment, VerifyPurchase returns true and the purchase appears to succeed. However, after about 5 minutes after the purchase I get an email that says **This test purchase was cancelled because it was not acknowledged. You should ensure all purchases are acknowledged so they are not subject to refunds**.  I had always assumed that it might be normal because it's a test account and the purchases use a test credit card that auto approves

However, in my released product, I notice that every time a customer makes a purchase, they purchase is refunded EXACTLY 3 days to the minute after the purchase was made.  

Am I doing the right thing with my validation? Is there anything to explain what could be going wrong?

thanks!!
Michael

**Comment by michaelfoster9** [comment]
I believe I figured out my problem. I was not calling AcknowledgePurchaseAsync.

**Comment by assassin316** [comment]
@michaelfoster9  Does your code work with 4.x version?  It seems InAppBillingImplementation doesn't exist anymore. I raised an issue about that.
