### ISSUE TITLE
[Question] Expired subscriptions in production

### ISSUE THREAD

**Issue by nrcpp** [jamesmontemagno/InAppBillingPlugin#315]
```
var purchases = await CrossInAppBilling.Current.GetPurchasesAsync(ItemType.Subscription);                
if (purchases?.Any() != true)
                    return Result(SubscriptionType.None);
```

Such way I am checking either my iOS application contains active subscriptions (even canceled) or not. I believe that when subscription is expired then the `purchases` list will be empty. In Sandbox I've got such behaviour, but not sure about how it will work in AppStore.

We have yearly subscription with 7 day free trial. Lets say user will subscribe for yearly subscription and cancel it on day two, i.e. before free trial ends. 

For such case, at what point I could expect that `purchases` list will be empty. So it could be treated as there are no active subscriptions. At day seven? Unfortunetly I can't handle this case normally in Sandbox environment, because of `purchases` list become empty after several minutes.

I use stable version 2 of _InAppBillingPlugin_, in Xamarin.Forms app, to manage In-App subscriptions.

**Comment by nrcpp** [comment]
Is it a correct way to check active subscriptions, even that was already canceled?

**Comment by jamesmontemagno** [comment]
please see: https://developer.android.com/google/play/billing/subs

**Comment by nrcpp** [comment]
Thank you for response, but the link above relates to Android, as I need implementation for iOS.

Now in production I haven't a way to check cancelled in-app subscriptions for iOS. 

CrossInAppBilling.Current.GetPurchasesAsync() returns non-empty list even when subscription
expired. And there is no way to check if it was canceled or not. 

Example:
```
var connected = await billing.ConnectAsync(ItemType.Subscription);
if (!connected)  return ;

// check purchases
var purchases = await billing.GetPurchasesAsync(ItemType.Subscription);
var yearly = purchases.FirstOrDefault(p => p.ProductId == YearlySubscriptionId);
if (yearly != null)
{
if (yearly.AutoRenewing)	// this always false when user starts and has active trial
{
}
return true;	// app thinks that yearly is active, even it was already cancelled. 
		// It works in production.
}
```

How to solve this issue please?
