### ISSUE TITLE
Help setting up 

### ISSUE THREAD

**Issue by Saxby-source** [jamesmontemagno/InAppBillingPlugin#316]
Hey James,

I'm writing an app where the user pays for 'walking games', and I'm struggling setting up the IAP's, I understand it is a non-consumable item that I'm using and I have set that up in the play console, as well as having an active release with the permissions set up. However I'm struggling to get anything else set up, would you be able to help me. Cheers in advance

**Comment by WorldOfBasti** [comment]
Hi @Saxby-source I had similar problems setting up in-app purchases. In the play console, go to settings -> mail-lists and add your google play account. Then go to your app -> to your active release -> tester and add the mail there too. A very important point is, that you need to accept to participation for testing. The link is in the bottom from the tester page. 
Another important point is, you need to sign every apk. You can do this in the Android-Package signing options in visual studio. If it still doesn't work, maybe [this link](https://jamesmontemagno.github.io/InAppBillingPlugin/TestingAndTroubleshooting.html) helps..
Regards.

**Comment by Saxby-source** [comment]
Thank you for your response, ill give it a try

**Comment by WorldOfBasti** [comment]
What is the problem? I don't get it, can you post a code snippet or something similar?

**Comment by Saxby-source** [comment]
This is my code for a single purchase page, it works fine until I put multiple 'links' to it, that's when i get the error 'you ar enot connected to google play store.

`public partial class PuchasePage : ContentPage
    {
        bool isPurchased;
        string skuId;
        ContentPage navigateTo;
        public PuchasePage(string productId, string gameDescription, string gameImgSource, ContentPage navTo)
        {
            InitializeComponent();
            skuId = productId;
            navigateTo = navTo;
            gameImage.Source = gameImgSource;
            DescriptionTxt.Text = gameDescription;
            CheckPurchase(skuId);
        }
        async private void CheckPurchase(string productId)
        {
            var connected = await CrossInAppBilling.Current.ConnectAsync();
            if (!connected)
            {
                // Could not connect, alert the user
                await DisplayAlert("ALERT", "Could not connect", "Try again");
                return;
            }
            var purchaseCheck = await CrossInAppBilling.Current.GetPurchasesAsync(ItemType.InAppPurchase);
            if (purchaseCheck?.Any(p => p.ProductId == productId) ?? false)
            {
                Purchased.IsVisible = true;
            }
            else
            {
                PurcahseBttn.IsVisible = true;
            }
        }
        async private void PurchaseProduct(string productId)
        {
            try
            {
                var connected = await CrossInAppBilling.Current.ConnectAsync();
                if (!connected)
                {
                    // Could not connect, alert the user
                    await DisplayAlert("ALERT", "Could not connect", "Try again");
                    return;
                }
                // Try to purchase item
                var purchase = await CrossInAppBilling.Current.PurchaseAsync(productId, ItemType.InAppPurchase, "applyLoad");
                if (purchase == null)
                {
                    // Not purchased, alert the user
                    await DisplayAlert("ALERT", "Could not purchase " + productId, "Try again");
                }
                else
                {
                    // Prucahsed, alert the user
                    var id = purchase.Id;
                    var token = purchase.PurchaseToken;
                    var state = purchase.State;
                    await DisplayAlert("Awesome", "Purchased item " + productId, "Ok");
                    isPurchased = true;
                }
            }
            catch (Exception)
            {
                // An error has occured, alert user
                await DisplayAlert("Alert", "Error: could not process payment", "Try again");

            }
            finally
            {
                // Disconect CrossInAppBilling
                await CrossInAppBilling.Current.DisconnectAsync();
            }
            CrossInAppBilling.Dispose();
        }

        private void PurcahseBttn_Clicked(object sender, System.EventArgs e)
        {
            if (!isPurchased)
            {
                PurchaseProduct(skuId);
            }
            if (isPurchased)
            {
                PurcahseBttn.IsVisible = false;
                Purchased.IsVisible = true;
            }
        }
        async private void Purchased_Clicked(object sender, EventArgs e)
        {
            await Navigation.PushModalAsync(navigateTo);
        }
    }`

**Comment by WorldOfBasti** [comment]
The first point is, that you also need to disconnect after Checking the purchases.
The second point is, that I would use an async Task for `PurchaseProduct` instead an async void. Add an async to the  `PurcahseBttn_Clicked` Method. Then add the await keyword to the `PurchaseProduct(skuId)` call. 
You need to make sure, that the purchase check is complete before purchasing..
You can look [at the documentation](https://jamesmontemagno.github.io/InAppBillingPlugin/) if you need any examples.
I think it should work with this, please test:
```
public partial class PuchasePage : ContentPage
{
    bool isPurchased;
    string skuId;
    ContentPage navigateTo;
    public PuchasePage(string productId, string gameDescription, string gameImgSource, ContentPage navTo)
    {
        InitializeComponent();
        skuId = productId;
        navigateTo = navTo;
        gameImage.Source = gameImgSource;
        DescriptionTxt.Text = gameDescription;
        CheckPurchase(skuId);
    }
    async private void CheckPurchase(string productId)
    {
        try
        {
            var connected = await CrossInAppBilling.Current.ConnectAsync();
            if (!connected)
            {
                // Could not connect, alert the user
                await DisplayAlert("ALERT", "Could not connect", "Try again");
                return;
            }
            var purchaseCheck = await CrossInAppBilling.Current.GetPurchasesAsync(ItemType.InAppPurchase);
            if (purchaseCheck?.Any(p => p.ProductId == productId) ?? false)
            {
                Purchased.IsVisible = true;
            }
            else
            {
                PurcahseBttn.IsVisible = true;
            }
        }
        catch (Exception)
        {
            // An error has occured, alert user
            await DisplayAlert("Alert", "Error: could not process payment", "Try again");
        }
        finally
        {
            // Disconect CrossInAppBilling
            await CrossInAppBilling.Current.DisconnectAsync();
        }
    }
    async private Task PurchaseProduct(string productId)
    {
        try
        {
            var connected = await CrossInAppBilling.Current.ConnectAsync();
            if (!connected)
            {
                // Could not connect, alert the user
                await DisplayAlert("ALERT", "Could not connect", "Try again");
                return;
            }
            // Try to purchase item
            var purchase = await CrossInAppBilling.Current.PurchaseAsync(productId, ItemType.InAppPurchase, "applyLoad");
            if (purchase == null)
            {
                // Not purchased, alert the user
                await DisplayAlert("ALERT", "Could not purchase " + productId, "Try again");
            }
            else
            {
                // Prucahsed, alert the user
                var id = purchase.Id;
                var token = purchase.PurchaseToken;
                var state = purchase.State;
                await DisplayAlert("Awesome", "Purchased item " + productId, "Ok");
                isPurchased = true;
            }
        }
        catch (Exception)
        {
            // An error has occured, alert user
            await DisplayAlert("Alert", "Error: could not process payment", "Try again");

        }
        finally
        {
            // Disconect CrossInAppBilling
            await CrossInAppBilling.Current.DisconnectAsync();
        }
    }

    private async void PurcahseBttn_Clicked(object sender, System.EventArgs e)
    {
        if (!isPurchased)
        {
            await PurchaseProduct(skuId);
        }
        if (isPurchased)
        {
            PurcahseBttn.IsVisible = false;
            Purchased.IsVisible = true;
        }
    }
    async private void Purchased_Clicked(object sender, EventArgs e)
    {
        await Navigation.PushModalAsync(navigateTo);
    }
}

```

**Comment by Saxby-source** [comment]
awesome, so after a bit of testing it's gotten me past the initial problem, however, I'm not going to close the post until I've done more through testing. Cheers for all the help :P
