### ISSUE TITLE
Questions regarding latest changes in Google Play Billing

### ISSUE THREAD

**Issue by Alexander3178** [jamesmontemagno/InAppBillingPlugin#317]
Hi James,

Great plugin, thank you so much! 
I am testing currently version 4.0 and everything looks great.
Few questions though as to Upcoming Changes in Google Play Billing:

**I get this information on my Google Play Console:**
You must have account hold and restore implemented in your app by November 1, 2020. 
Subscription pause and resubscribe will also be enabled by default, unless you explicitly opt out.

**How should I handle Account Hold and Restore using your Plugin?**

I understand that there is an API to query subscriptions that the user has and get details such as: Status (Paused, Active, Pending, etc..) , Expiration Date and so on. 
**Will this API be supported in the plugin?**

**And last one: I get this message in the subscriptions page in Google Console:**
Resubscribe is not currently available for your users because your app does not use Billing Library 2.0 in all active APKs.

Latest version of this plugin uses Billing Library 2 right? Is there Billing Library 3?

Thanks!

**Comment by Alexander3178** [comment]
There are also push notifications according to Google Documentation that can inform the app about changes in subscriptions.
Is this something that will be supported in the plugin?

**Comment by pooran** [comment]
@jamesmontemagno any plan to integrate Billing Library 3?

**Comment by Alexander3178** [comment]
I am still not clear if this plugin will work after November 1st or not.
Anyone knows?

**Comment by jamesmontemagno** [comment]
The latest beta uses the new Billing 3 Library and the readme outlines new usage.

This is how you will have to handle subscription pauses -> https://developer.android.com/google/play/billing/subs#lifecycle

The data is already there when you query a purchase you will get it back, you will see the "state" and the AutoRenewing flag.

As far as lifecycle -> technically even AIDL BL1 will be supported until next year:
![image](https://user-images.githubusercontent.com/1676321/96181133-608d3300-0ee8-11eb-8830-d93f2d12bf36.png)
