### ISSUE TITLE
How to proper setup InAppBillingPlugin in fragments

### ISSUE THREAD

**Issue by CDrosos** [jamesmontemagno/InAppBillingPlugin#318]
Hello, im curious about this line in the setup instructions in Version 2 of InAppBillingPlugin :

**protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
{
    base.OnActivityResult(requestCode, resultCode, data);
    InAppBillingImplementation.HandleActivityResult(requestCode, resultCode, data);
}**

It says in the docs here https://jamesmontemagno.github.io/InAppBillingPlugin/GettingStarted.html that we have to put this code in the main activity. What if we are using purchasing functions inside a fragment? we still have to put this code in the Activity holder of the fragment and write the rest of the purchase code functions in fragment in the same way as if everything happens in an Activity?

I have already implement in app purchases in fragments and they seem to work but im not 100% sure because of the limitations we have in testing purchases in beta/alpha releases so im trying to be sure before public release

**Comment by jamesmontemagno** [comment]
Use the new V4 please this handles everything for you.
