### ISSUE TITLE
ConnectAsync

### ISSUE THREAD

**Issue by pavelsedina** [jamesmontemagno/InAppBillingPlugin#32]
Hi guys, please, any idea why CrossInAppBilling.Current.ConnectAsync() Is raising an exception "Object reference not set to an instance of an object." in my Xamarin.Forms project? I went through README and I think I did everything correctly. Thanks!

**Comment by klint01** [comment]
Android or iOS?

If Android, I had a similar issue and it was related to the below code in my AssemblyInfo.cs file in the Android project.  Either delete or comment out the code and then everything worked.

```
#if DEBUG
    [Application(Debuggable=true)]
#else
    [Application(Debuggable=false)]
#endif
```

**Comment by pavelsedina** [comment]
Hi, thanks for your reply (and yes, this is Android project). Unfortunately, it still doesn't work. As this is real beginning of the usage of this component (no passing productid or other specific stuff), some xamarin.forms issue maybe? Trying to create simple test project doing just this connectAsync, but no luck ;-( thanks for any hint!

**Comment by jamesmontemagno** [comment]
Read: https://github.com/jamesmontemagno/InAppBillingPlugin#android-setup

You must be using a real device with google play services, your app needs to be in app store, version must match, must have a version in alpha, and tons of other stuff in docs
