### ISSUE TITLE
[Question] How to get receipt and validate it?

### ISSUE THREAD

**Issue by megumi-terada-fa** [jamesmontemagno/InAppBillingPlugin#320]
I'm developing Android app includes IAP (auto-renewable subscription) , but how to get receipt only by using this plugin?
My app needs row receipt information for receipt validation in server-side.

Plugin ver.2.0.0 could get receipt and verify it when call "GetPurchasesAsync()",
however, I think calling "VerifyPurchase()" lines in "GetPurchasesAsync()" on Plugin ver. 4.0.0-beta are removed.

**When users purchase item** : my app can get receipt and verify it.
**When purchases are auto renewed** : 
    how to get current receipt and validate?? 
    "GetPurchasesAsync()" returns only InAppBillingPurchases object.

Version Number of Plugin: 4.0.0-beta
Device Tested On: Android 10

**Comment by Meekohi** [comment]
After
```
InAppBillingPurchase purchase = await billing.PurchaseAsync(productId, ItemType.Subscription);
```
`purchase.PurchaseToken` is a base64 encoded JSON object, but it is essentially useless on its own -- the token returned may or may not represent the purchase you just made, especially in the case of subscriptions where it might return an expired subscription purchase from years ago.

You need to send `purchase.purchaseToken` to `POST https://buy.itunes.apple.com/verifyReceipt`
to get the "real" purchase token with information about when the subscription will expire. See https://developer.apple.com/documentation/appstorereceipts/verifyreceipt for more information.
