### ISSUE TITLE
How do we implement VerifyPurchase for Android with the 4.X version ??

### ISSUE THREAD

**Issue by assassin316** [jamesmontemagno/InAppBillingPlugin#322]
For pre-4.X versions, I had the following code:

```cs
public class InAppBillingVerifyPurchase : IInAppBillingVerifyPurchase
{
	const string key1 = @"XOR_key1";
	const string key2 = @"XOR_key2";
	const string key3 = @"XOR_key3";

	public Task<bool> VerifyPurchase(string signedData, string signature, string productId = null, string transactionId = null)
	{
#if __ANDROID__
		var key1Transform = Plugin.InAppBilling.InAppBillingImplementation.InAppBillingSecurity.TransformString(key1, 1);
		var key2Transform = Plugin.InAppBilling.InAppBillingImplementation.InAppBillingSecurity.TransformString(key2, 2);
		var key3Transform = Plugin.InAppBilling.InAppBillingImplementation.InAppBillingSecurity.TransformString(key3, 3);

		return Task.FromResult(Plugin.InAppBilling.InAppBillingImplementation.InAppBillingSecurity.VerifyPurchase(key1Transform + key2Transform + key3Transform, signedData, signature));
#else
		return Task.FromResult(true);
#endif
	}
}
```

But with the 4.X version, `InAppBillingImplementation` does not exist anymore. Has anyone updated their implementation to reflect the major changes in 4.x ??

**Comment by jamesmontemagno** [comment]
It still exists -> https://github.com/jamesmontemagno/InAppBillingPlugin/blob/feature/new-android-billing/src/Plugin.InAppBilling/InAppBilling.android.cs#L426 what doesn't seem to be popping up for you?

**Comment by assassin316** [comment]
@jamesmontemagno 

![image](https://user-images.githubusercontent.com/17514380/98014389-93c93080-1dc9-11eb-86d3-8a925ea3e9d3.png)

**Comment by jamesmontemagno** [comment]
Are you targeting Android 10 or higher? 
![image](https://user-images.githubusercontent.com/1676321/98054229-3d6ee880-1def-11eb-9f65-ad8262e04b69.png)

**Comment by assassin316** [comment]
I tried it on a seperate sample app and it works fine...something definitely wrong in my project.....I'll keep you posted once I find the issue. Thanks for the help!

**Comment by jasonfisherjlf** [comment]
> I tried it on a seperate sample app and it works fine...something definitely wrong in my project.....I'll keep you posted once I find the issue. Thanks for the help!

@assassin316 I am experiencing the same issue. Did you ever figure out what was wrong in your project?
