### ISSUE TITLE
Log in window with app id shown on iOS

### ISSUE THREAD

**Issue by Lelelo1** [jamesmontemagno/InAppBillingPlugin#325]
I have question about the app id login window that is shown. Is it shown when connected to app store, or when `ActivatePurchase`? Is it shown irregardless of being logged in on the device with app id or not?

A popup with price was skipped in my implementation and user's see only the prompt to enter app id and password. When they are done it dosen't come up again.
Will it be there in production?

**Comment by jamesmontemagno** [comment]
If you are on sandbox it will pop up.  https://www.revenuecat.com/blog/the-ultimate-guide-to-subscription-testing-on-ios
