### ISSUE TITLE
I get a NotImplementedException exception on Android

### ISSUE THREAD

**Issue by assassin316** [jamesmontemagno/InAppBillingPlugin#327]
I have installed the latest beta version (4.0.1-beta). It used to work fine but now recently I've been getting this error:

`System.NotImplementedException: 'This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.'`

I have the nuget on all my projects. Any idea what I can do to fix this issue? This occurs when I launchon Android, haven't yet tested on iOS. UWP is fine.

**Comment by jamesmontemagno** [comment]
Are you compiling against Android 10 or 11?

**Comment by assassin316** [comment]
@jamesmontemagno  I'm targeting Android 11. Is that a problem for this package?

**Comment by assassin316** [comment]
What is stange is that this error is only supposed to happen in a NetStandard project:

https://github.com/jamesmontemagno/InAppBillingPlugin/blob/d543b4d3a2187c6c8c0726996b4e7a95fb20288d/src/Plugin.InAppBilling/CrossInAppBilling.shared.cs#L34

**Comment by assassin316** [comment]
Hi @jamesmontemagno,

Would you have an idea of how I can go about investigating this issue? I've created another sample app with the same nuget packages and setup, but sadly it works in that sample. I'm looking for other ideas to help figure out the issue.

**Comment by assassin316** [comment]
@jamesmontemagno found the problem 👍 Within my Android csproj file, there was a PropertyGroup section that contained a TargetFrameworkVersion still targeting v9.0. Changing it to v10.0 fixed the issue!

**Comment by danieltabarest** [comment]
> @jamesmontemagno found the problem 👍 Within my Android csproj file, there was a PropertyGroup section that contained a TargetFrameworkVersion still targeting v9.0. Changing it to v10.0 fixed the issue!

it works, thanks
