### ISSUE TITLE
[Android] Support for pending purchases must be enabled

### ISSUE THREAD

**Issue by rrispoli** [jamesmontemagno/InAppBillingPlugin#328]
When call ConnectAsync(false) to disable pending purchases this cause an exception "Support for pending purchases must be enabled".

## Bug Information

Version Number of Plugin: 4.0.1-beta
Device Tested On: Redmi 4X (Android 7.1.2)
Simulator Tested On: N/A
Version of VS: 2019 16.7.6
Version of Xamarin: 16.7.000.456

### Steps to reproduce the Behavior
Just execute the ConnectAsync method with "enablePendingPurchased" parameters set to false.

### Expected Behavior
Connection to billing service works with pending purchased not enabled.

### Actual Behavior
Exception "Support for pending purchases must be enabled"

### Code snippet
```
try
{
	var billing = CrossInAppBilling.Current;
	var connected = await billing.ConnectAsync(false);
}
catch (Exception exception)
{
}
finally
{
	await billing.DisconnectAsync();
}
```

**Comment by blmiles** [comment]
Hello,

Do this: var connected = await billing.ConnectAsync(**true**);

Make sure you handle PendingPurchases...

**Comment by rrispoli** [comment]
> 
> 
> Hello,
> 
> Do this: var connected = await billing.ConnectAsync(**true**);
> 
> Make sure you handle PendingPurchases...

Hi, with "true" enablePendingPurchased parameter I know that that it works, but I want to use with "false" to disable pending purchases.

**Comment by blmiles** [comment]
I wonder if your IAP or subscriptions need to have a 0/zero grace-period set?
That might cause the connection to fail because it's needed for handling the grace-period.
My thought anyway.

**Comment by zigcarruse** [comment]
+1 wanting the ability to turn off pending purchases

**Comment by jamesmontemagno** [comment]
You would have to use version 2.0 of the library, which uses AIDL. Pending Purchases are required when using the new library -> https://developer.android.com/google/play/billing/migrate#pending

You might as well do it now seeing that Starting on August 2, 2021, all new apps must use Billing Library version 3 or newer. By November 1, 2021, all updates to existing apps must use Billing Library version 3 or newer

It isn't hard to do.
