### ISSUE TITLE
Error, "value connot be null. Parameter name: source"

### ISSUE THREAD

**Issue by realex82** [jamesmontemagno/InAppBillingPlugin#33]
I'm trying to test the plugin with my app(on **android**), and i follow all instruction,  but when i execute the code the simulator show me this error:  "Value connot be null. Parameter name: source" . 

stacktrace
  **at System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00006] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/System.Core/System/Linq/Enumerable.cs:1192 
  at Plugin.InAppBilling.InAppBillingImplementation+InAppBillingServiceConnection.ConnectAsync () [0x00043] in <1ecca8595de5416485857bb67e2ec090>:0 
  at Plugin.InAppBilling.InAppBillingImplementation.ConnectAsync () [0x00000] in <1ecca8595de5416485857bb67e2ec090>:0** 
-

I've make a debug, and throw this exception in this part of code:
**var connected = CrossInAppBilling.Current.ConnectAsync();**
how can i resolve it ?
thanks 
alex

**Comment by jamesmontemagno** [comment]
YOu can not use the simulator, has to be a physical device
