### ISSUE TITLE
See subscriptions/purchases from other platforms

### ISSUE THREAD

**Issue by curelom** [jamesmontemagno/InAppBillingPlugin#331]
Is there a way to be able to access apple store from android or android store from iphone?  Our users may have selected a subscription from one or the other or 3rd party and may switch around devices.  Would like to be able to see subscriptions (editing not needed) in other platforms.

**Comment by WorldOfBasti** [comment]
I think you need a own backand which manages the subscriptions. The user should be able to log in to his account, to achieve this. A example for this is Spotify or Netflix.. One thing which is to be observed are the store guidelines that you must adhere to. 
[Here](https://medium.com/ux-for-india/building-netflix-style-in-app-subscription-payments-in-your-multi-platform-product-88d780b7da3d) is a blog about this.

**Comment by curelom** [comment]
Thanks for the info
