### ISSUE TITLE
[iOS] Testing Purchases

### ISSUE THREAD

**Issue by oicangi05** [jamesmontemagno/InAppBillingPlugin#333]
Hi James, would you please explain how to test the purchases in ios. thanks in advance!

**Comment by mnxamdev** [comment]
You need the following:
* Items for purchase in App Store Connect.
* A sandbox account in App Store Connect
* Updated provisioning profile/cert that allows for purchasing from the Developer portal.
** App signed with that for debug/dev. If you want to test from third party download of your IPA you'll need to sign with an Ad-Hoc cert. Otherwise just upload to TestFlight for testing.
* Note when you are testing purchases the IAP dialog will show the word [Sandbox] in it.

I think that about covers it, I hope this helps and I apologize if I missed something.

**Comment by oicangi05** [comment]
thanks, i did that and it worked! is there a way to do the testing with storekit, to revoke Purchases, simulate delayed payment, etc..?

**Comment by oicangi05** [comment]
Thanks! I'll try that... Is there a way to test locally like in xcode?

**Comment by blmiles** [comment]
@mnxamdev 

Hello, maybe you can help...
I have an IAP subscription item in the Apple app store set as AutoRenewable. I can connect and execute a purchase using this:

var verify = DependencyService.Get<IInAppBillingVerifyPurchase>(); //verify is always null
var purchase = await billing.PurchaseAsync(productId, ItemType.Subscription, verify); //tried swapping verify for "payload", method won't take that...

(I login using a tester account, all properly set up etc - Apple Pay is set)

Every time the purchase is returned with these basic attributes:
{ProductId:{prodid]| IsAcknowledged:False | AutoRenewing:False | State:Purchased | Id:1000000747513385}

Any idea why the AutoRenewing is false? When the item IN the store is clearly AutoRenewable?
When I try "manage subscriptions" on the device, there are none...

Is there any other method I should be calling after that to complete the purchase?
Is there something else I should be handling?

I'm using Beta build 4.0.1 for now...

Unfortunately up-to-date documentation and timely responses to questions is sorely lacking on here :(

Any advice would be appreciated.

**Comment by mnxamdev** [comment]
@blmiles I'm not sure why unless it's not setup correctly in the app store. Also, we're on v3 of the plugin and set this up in the AppDelegate, we don't do anything when we call PurchaseAsync without a "verify" and wait for the response to come back via the event handler setup below. Unless you have a compelling reason to use v4 I recommend v3 with the setup below as that has been pretty rock solid for our customers for well over a year:

```
public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            //Load up Xamarin.Forms and other stuff

            Plugin.InAppBilling.InAppBillingImplementation.OnPurchaseComplete = async purchase =>
            {
                try
                {
                    //validate the purchase
                }
                catch(Exception ex)
                }
                    //Log exception
                }
            }
```

**Comment by Meekohi** [comment]
As best I can tell, testing in Sandbox does not work at all for subscriptions at least. I always receive bogus expired receipts from `billing.PurchaseAsync(productId, ItemType.Subscription);`

**Comment by jamesmontemagno** [comment]
See https://montemagno.com/ios-android-subscription-implemenation-strategies/ and https://www.revenuecat.com/blog/the-ultimate-guide-to-subscription-testing-on-ios
