### ISSUE TITLE
How to test Play Store Purchases without using "debug mode"

### ISSUE THREAD

**Issue by blmiles** [jamesmontemagno/InAppBillingPlugin#336]
Hello,

It seems I cannot step through my billing code for the Google Play Store in debug mode as connecting to the playstore, the playstore expects the connecting app to be in Release mode and the .apk to be signed.

Can anyone advise or share their test methods on Play Store billing code?

I'd like step into this to see what the Play Store returns in the token, IF this will even be able to extract that info:

`        internal bool IsPurchaseValid(string token)
        {
            if (string.IsNullOrEmpty(token)) return false;

            if (Device.RuntimePlatform == Device.Android)
            {

                //TO DO  - Handle PlayStore tokens here

            }

            if (Device.RuntimePlatform == Device.iOS)
            {
                var data1 = System.Convert.FromBase64String(token);
                if (!data1.Any()) return false;

                //Recipt Dictionary
                var receiptDic = (NSDictionary)PropertyListParser.Parse(data1);
                if (receiptDic == null) return false;

                //Purchase Info
                var purchaseInfoContent = receiptDic.ObjectForKey("purchase-info").ToString();
                if (string.IsNullOrEmpty(purchaseInfoContent)) return false;

                byte[] data2 = System.Convert.FromBase64String(purchaseInfoContent);
                var purchaseInfoDic = (NSDictionary)PropertyListParser.Parse(data2);

                //output key/value pairs to debug
                //int count = 0;
                //ICollection<string> keys = purchaseInfoDic.Keys;
                //foreach (string s in keys)
                //{
                //    Debug.WriteLine(count + ": " + s + "\n");
                //    count++;
                //}

                //count = 0;
                //ICollection<NSObject> values = purchaseInfoDic.Values;
                //foreach (NSObject v in values)
                //{
                //    Debug.WriteLine(count + ": " + v + "\n");
                //    count++;
                //}

                if (purchaseInfoDic == null) return false;

                var msStr = purchaseInfoDic.ObjectForKey("expires-date").ToString();
                if (string.IsNullOrEmpty(msStr)) return false;

                //Expiry Date
                var expireDate = new DateTime(1970, 1, 1).AddMilliseconds(Convert.ToInt64(msStr));

                var isValid =  DateTime.Now.ToUniversalTime().Date <= expireDate.Date;
                return isValid;
            }
            return false;
        }
    }
`

Any ideas?

Thx

**Comment by blmiles** [comment]
A bit more info...

I found this [article](http://jonathanpeppers.com/Blog/securing-google-play-in-app-purchases-for-xamarin-with-azure-functions)

Take a look at the section - **_So if the keystore has to match, how in the world can you debug?_**

Seems scary. Screw one thing up and the package name needs changing and the knockon effect across both platforms is huge (redoing both apps in both app/play stores as well as other services like Auth0 etc.

Critique?
Thoughts?

How else to properly debug Google Play Store billing code?

Thx

**Comment by jamesmontemagno** [comment]
You can put it into the private beta/alpha testing as well and will work well.
