### ISSUE TITLE
await CrossInAppBilling.Current.ConnectAsync();  Hangs

### ISSUE THREAD

**Issue by nicolgit** [jamesmontemagno/InAppBillingPlugin#34]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 
Version Number of Plugin: 1.1.0.23
Device Tested On: android 7.1.1
Simulator Tested On: android 5.1

### Expected Behavior
Open Activity1
Open Activity2
press button: await CrossInAppBilling.Current.ConnectAsync();  OK
close activity2
Open activity2
press button: await CrossInAppBilling.Current.ConnectAsync();   OK

### Actual Behavior
hangs on second call of connectAsync

### Steps to reproduce the Behavior
Open Activity1
Open Activity2
press button: await CrossInAppBilling.Current.ConnectAsync();  
close activity2
Open activity2 again
press button: await CrossInAppBilling.Current.ConnectAsync();   < HANGS

## Feature Request:
I think that the problem is related to 
 public InAppBillingImplementation()
       {
            serviceConnection = new InAppBillingServiceConnection(Context);
        }

the service is a singleton and if the activity changes, also Context changes...

**Comment by jamesmontemagno** [comment]
Pushed new nuget, give it a shot
