### ISSUE TITLE
how to acknowledge subscriptions

### ISSUE THREAD

**Issue by ish-1313** [jamesmontemagno/InAppBillingPlugin#341]
Hi, 

thank you for nice plugin.
trying to write in app subscriptions related code (for android now ) .

after calling GetPurchasesAsync () i am getting purchase with the following data
State = Plugin.InAppBilling.Abstractions.PurchaseState.PaymentPending
ConsumptionState = Plugin.InAppBilling.Abstractions.ConsumptionState.NoYetConsumed

my google account (with test license) receives letters from google that payment was made (including renewals ) 

i assumed that purchased is not finished on my side.
(i didn't write verification code for now, but i am not sure that is the reason ) , 
so i went to google docs and found that we need to acknowledge subscription with google 

Subscriptions are handled similarly to non-consumables. You can acknowledge a subscription Acknowledgement using either BillingClient.acknowledgePurchase() from the Google Play Billing Library or Purchases.Subscriptions.Acknowledge from the Google Play Developer API. All initial subscription purchases need to be acknowledged.

but found no related code in plugin source.
also, there is nothing related to acknowledgment in sample here https://jamesmontemagno.github.io/InAppBillingPlugin/PurchaseSubscription.html

am i doing something wrong ? or this part is not implemented and i need to sort it out myself this way or other . 

tia 
ish

**Comment by ish-1313** [comment]
Hi,

made a fork to take a look in a debugger. 


this:
**State = Plugin.InAppBilling.Abstractions.PurchaseState.PaymentPending**

Purchase.State & Purchase.SubscriptionState referer different underline fields (PurchaseState and PaymentState respectively).
0 for products means paid, 0 for subscription means pending .
but GetProductAsync never returns PaymentState and always returns 0 in PurchaseState. 

"purchaseState | The purchase state of the order. It always returns 0 (purchased)."

so this
'State = itemType == ItemType.InAppPurchase ? p.State : p.SubscriptionState,'

incorrectly evaluates to paymentpending for subscriptions
to correct this i would set paymentstate to 1 if we queried for subscriptions

as to the subscriptions acknowledgement, still looking. because backend call to Purchases.Subscriptions.Get returns that it is already acknowledged. 


i am new to google billing, so may be i am wrong. may be all of the above  not an issue ;)
tia
ish

**Comment by jamesmontemagno** [comment]
I will check on this, but the matrix is this:
![image](https://user-images.githubusercontent.com/1676321/103401138-a4153780-4afc-11eb-84d0-e2aa7bb0bd54.png)

**Comment by jamesmontemagno** [comment]
I can add PaymentState in there as well though, or if you wan tto send a PR.

**Comment by ish-1313** [comment]
> 
> 
> I will check on this, but the matrix is this:

may be this is the difference between 2 and 3 versions of api

you are using GetPurchases, its response is different 

```
         Bundle ownedItems = serviceConnection.Service.GetPurchases(3, Context.PackageName, itemType, null);
                    var response = GetResponseCodeFromBundle(ownedItems);

                    if (response != 0)
                    {
                        break;
                    }

                    if (!ValidOwnedItems(ownedItems))
                    {
                        Console.WriteLine("Invalid purchases");
                        return purchases;
                    }

                    var items = ownedItems.GetStringArrayList(RESPONSE_IAP_PURCHASE_ITEM_LIST);
                    var dataList = ownedItems.GetStringArrayList(RESPONSE_IAP_PURCHASE_DATA_LIST);
                    var signatures = ownedItems.GetStringArrayList(RESPONSE_IAP_DATA_SIGNATURE_LIST);
```
here it is https://developer.android.com/google/play/billing/billing_reference#getPurchases

i decided to finish with ios version of my app before (and look around issues here. )  before thinking about pr ;)

**Comment by jamesmontemagno** [comment]
Yeah the new version is different as AIDL is going away. I will have to take another look.

Docs: https://developer.android.com/google/play/billing/subscriptions

**Comment by ish-1313** [comment]
Hi @jamesmontemagno ,
testing with IOS version. can't find in docs or in sample, should i clear transaction by manually calling FinishTransaction ? 
i have 3 transactions sitting in the que  and they are not cleared

[0:] Updated Transaction | ProductId:dfc.noadv.1y | AutoRenewing:False | State:Purchased | Id:1000000760518526
[0:] Updated Transaction | ProductId:dfc.noadv.1y | AutoRenewing:False | State:Purchased | Id:1000000760518526
[0:] Updated Transaction | ProductId:dfc.noadv.1y | AutoRenewing:False | State:Purchased | Id:1000000760518526

and i found no reference to this method in plugin code

tia
ish

**Comment by ish-1313** [comment]
@jamesmontemagno 
well, i finished with my app ios version.
changed couple of things in your sources. 

GetPurchasesAsync if there is no purchases now returns empty array, not null.  this is in line with android and allow to distinguish from exceptions in caller code (imo)

```
protected async override Task<IEnumerable<InAppBillingPurchase>> GetPurchasesAsync(ItemType itemType, IInAppBillingVerifyPurchase verifyPurchase, string verifyOnlyProductId)
{
	var purchases = await RestoreAsync();
	var validPurchases = new List<InAppBillingPurchase>();

	if ((purchases?.Count() ?? 0) < 1) return (validPurchases);

	var comparer = new InAppBillingPurchaseComparer();
	var converted = purchases
		.Where(p => p != null)
		.Select(p2 => p2.ToIABPurchase())
		.Distinct(comparer);

	foreach (var purchase in converted)
	{
		if ((verifyOnlyProductId != null && !verifyOnlyProductId.Equals(purchase.ProductId)) || await ValidateReceipt(verifyPurchase, purchase.ProductId, purchase.Id))
			validPurchases.Add(purchase);
	}
	return validPurchases;
} 
```
and some changes in project file to allow it to build on mac os 
```
<TargetFrameworks>netstandard1.0;netstandard2.0;MonoAndroid90;Xamarin.iOS10;Xamarin.TVOS10</TargetFrameworks>
<TargetFrameworks Condition="'$(OS)'=='Windows_NT'">$(TargetFrameworks);uap10.0.16299</TargetFrameworks>
```
don't know is it worth a pr. if yes, may include some samples of server side code for receipt verification. 

thanks again for this plugin ;)
ish

**Comment by ish-1313** [comment]
small side note .. 
also hit this const int PURCHASE_REQUEST_CODE = 1001;
some samples contains same values for requestcodes. changed mine , but may be for plugin it would be nice to move it much higher to lessen probability of using same codes in caller code

**Comment by jamesmontemagno** [comment]
See https://montemagno.com/ios-android-subscription-implemenation-strategies/
