### ISSUE TITLE
Are there plans to add this to XamarinCommunityToolkit

### ISSUE THREAD

**Issue by maxkoshevoi** [jamesmontemagno/InAppBillingPlugin#343]
Hi, starting from Xamarin 5 there will be `XamarinCommunityToolkit` NuGet package that is supported by community and intended to be single stop for all Xamarin needs that isn't included in official NuGets. 

Are there plans to add this package there?

**Comment by jamesmontemagno** [comment]
Not to XCT or Essentials. Anything with In app purchases is so complicated and impacts actual $ that I don't want to make it official. It is good here as just out from me.
