### ISSUE TITLE
Android Delayed Purchase Decline never fails

### ISSUE THREAD

**Issue by zigcarruse** [jamesmontemagno/InAppBillingPlugin#344]
After upgrading to the 4.0 plugin on android I am working on pending purchases. 

When app starts up we are grabbing all not Acknowledge Purchases by calling GetPurchasesAsync

We successfully get all purchases that haven't been Acknowledge  

When we are checking the state of the purchases that haven't been Acknowledge  we get a few behaviors

- delayed Card but Accepted
At first, like expected it comes back as Payment Pending, and within a few minutes once we re-grab all purchases that haven't been Acknowledge the purchase state reads as purchased now
- Delayed card but Rejected
Again at first, like expected it comes back as payment pending, but we are never then seeing it changed to any other state other than payment pending 

My question is. how are meant to know if a payment has been canceled so we can Acknowledge it and thus allowing user to purchase again as well as clear out all failed purchase data from our end?

Thanks
Brenden

**Comment by jamesmontemagno** [comment]
Hmmmm, I do the parsing here:
https://github.com/jamesmontemagno/InAppBillingPlugin/blob/dec5edee9fd7b96347c1b747cc5193790b2fb7b3/src/Plugin.InAppBilling/Converters.android.cs#L22

I think that they have 3 days to confirm it.... I think.

https://developer.android.com/google/play/billing/integrate#pending

**Comment by zigcarruse** [comment]
upon diving deeper i found this, which seems to be on the google side and just might be an issue with a test card 
https://issuetracker.google.com/issues/149668311

But not 100% sure yet
