### ISSUE TITLE
ConnectAsync method signature change

### ISSUE THREAD

**Issue by bulente** [jamesmontemagno/InAppBillingPlugin#345]
With version 4.0, method parameters changed and can't use it like ConnectAsync(ItemType.Subscription) or ConnectAsync(ItemType.InAppPurchase) anymore. It is accepting a bool enablePendingPurchases parameter only. But Getting Stated documentation still showing the old usage. Also I need this separation in my connection since one store my IAP is a consumable but on the other store it is a subscription.

**Comment by jamesmontemagno** [comment]
Correct, it is just ConnectAsync();

I am updating docs this week.

**Comment by bulente** [comment]
`if (Device.RuntimePlatform == Device.iOS)
{
    connected = await billing.ConnectAsync(ItemType.Subscription);
}
else
{
    connected = await billing.ConnectAsync(ItemType.InAppPurchase);
}`

how do we convert this code to v4.0?

**Comment by jamesmontemagno** [comment]
Correct, just a single call. It was only ever for Android and they changed their API so you pass in Sub or IAP during the purchase calls.

**Comment by bulente** [comment]
Thanks.
