### ISSUE TITLE
inappbilling does not connect after published a new version of my app.

### ISSUE THREAD

**Issue by ksoft1** [jamesmontemagno/InAppBillingPlugin#347]
Hi, i have publishihed my app on pay store. the inapp billing workined fine (no consomable).
However, when i published a new version of my app on play store, the inappbilling is not working. in the new version of my app i did not touch the code of inappbiling. i have the exception message:
"you are not connected to the Google play app store"

Could you please help.
best regards.

Bug Information
Version Number of Plugin: 4.0.1
Device Tested On: android
Simulator Tested On:
Version of VS: 2019
Version of Xamarin:4.8.0
Versions of other things you are using:

**Comment by jamesmontemagno** [comment]
Unable to reproduce on my end. You need to install it from beta/alpha testing to test it out. Working on my production apps just fine.
