### ISSUE TITLE
Cannot convert from 'Plugin.InAppBilling.ItemType' to 'bool'

### ISSUE THREAD

**Issue by dirkzp** [jamesmontemagno/InAppBillingPlugin#348]
Hi,

After updating to newest Version, I got the follwing error calling this:

`var connection = await billing.ConnectAsync(ItemType.Subscription);
                if (!connection)
                {
                    return false;
                }
`
--> Cannot convert from 'Plugin.InAppBilling.ItemType' to 'bool'	

I read your documentation and it seems there was no changes on this line?
Thanks.

**Comment by jamesmontemagno** [comment]
You no longer need to pass this in for version 4
