### ISSUE TITLE
Build Error with latest package version 1.1.0.33-beta

### ISSUE THREAD

**Issue by asjit** [jamesmontemagno/InAppBillingPlugin#35]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 1.1.0.33-Beta
Device Tested On: n/a
Simulator Tested On: n/a

Have updated to latest version of the package - no errors during the upgrade.  However when I build my project I the `The Name 'CrossInAppBilling' does not exist in current context.`  If I revert back to v1.1.0.23-beta it all builds and runs fine.
I can see that the DLL has been referenced.

This build error is only currently showing in my PCL Project

I tried clean and rebuilds and even deleted the bin/obj folders and rebuilt, restarted VS.  Same.

**Comment by asjit** [comment]
Lightening fast fix there, thanks man!

**Comment by jamesmontemagno** [comment]
Yeah, was trying to tidy up nuspec stuff, and had some wrong code in there :) thanks for reporting
