### ISSUE TITLE
Is the version 4.0.2 implementation in compliance with SCA policy of EU? 

### ISSUE THREAD

**Issue by nayumtamboli** [jamesmontemagno/InAppBillingPlugin#351]
Hi,

I am using InAppBillingPlugin in my app. With new Strong Customer Authentication policy coming in place for EU, there are some changes suggested by Apple and Google regarding compliance perspective. I have been looking into code base for this and unable to decide if InAppBillingPlugin takes care of it on both Apple and Google side or as a developer I need to make additional changes at my end? Could you please help me with this?

**Comment by jamesmontemagno** [comment]
It uses standard iOS/Android APIs so I assume so.....

https://developer.apple.com/support/psd2/ you should be able to use these 2 callbacks -> https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/src/Plugin.InAppBilling/InAppBilling.apple.cs#L23-L25

Android I am pretty sure you you just need to check on app startup or have a restore as it will have PENDING -> https://iaphub.medium.com/get-ready-for-sca-strong-customer-authentication-iap-transactions-in-the-eu-iaphub-34e825e2349 is a good link to read
