### ISSUE TITLE
[iOS] GetPurchasesAsync freezes on the second call

### ISSUE THREAD

**Issue by RadoslawKubas** [jamesmontemagno/InAppBillingPlugin#352]
## Bug Information

Version Number of Plugin: 4.0.2
Device Tested On: iPhone XS, iPhone 8
Version of VS: 16.8.4
Version of Xamarin: 5.0.0.1931

### Steps to reproduce the Behavior

1. call GetPurchasesAsync - it works fine and fast
2. wait (10-20 seconds, even longer, but if you wait enough long problem not appears)
3. call GetPurchasesAsync again - this time it freezes for long time, if you wait enough long (one minute or even longer) it completes correctly

or

1. call GetPurchasesAsync - it works fine and fast
2. wait (10-20 seconds, even longer, but if you wait enough long problem not appears)
3. call PurchaseAsync - it freezes for long time, purchases confirmation popup not appear, if you wait enough long it appears, also if you restart the app, purchase confirmation window can appear after a moment (without any user action)

This problem appears only after GetPurchasesAsync, there is no problem to PurchaseAsync or GetProductInfoAsync multiple times. Problem appears only on iOS, on Android works fine.

### Expected Behavior

GetPurchasesAsync works fast every time, and doesn't block entire functionality.

### Actual Behavior

I tried to debug inside plugin and it seems there is different behaviour between 1st and 2nd time GetPurchasesAsync. 

**1st time**
1. GetPurchasesAsync
2. RestoreAsync
3. SKPaymentQueue.DefaultQueue.Transactions is empty
4. SKPaymentQueue.DefaultQueue.RestoreCompletedTransactions();
5. UpdatedTransactions and OnPurchaseComplete for each purchase
6. RestoreCompletedTransactionsFinished
7. invoke paymentObserver.TransactionsRestored > handler
8. GetPurchasesAsync  result is retuned

**2nd time**
1. GetPurchasesAsync
2. RestoreAsync
3. SKPaymentQueue.DefaultQueue.Transactions has items ->  allTransactions.Add(original);
4. SKPaymentQueue.DefaultQueue.RestoreCompletedTransactions();
5. FREEZ for long time (2 minut), paymentObserver.TransactionsRestored > handler is not invoked.
6. UpdatedTransactions and OnPurchaseComplete for each purchase
7. RestoreCompletedTransactionsFinished
8. invoke paymentObserver.TransactionsRestored > handler
9. GetPurchasesAsync  result is retuned

**Comment by prok155** [comment]
Hello, i have the same issue. When I call **PurchaseAsync** after calling **GetPurchasesAsync** the app freezes and I can't do anything, I can only close the app. I've tested it on IOS 14.3 and iPhone XR.

**Comment by WorldOfBasti** [comment]
Maybe this is similar to my issue [here](https://github.com/jamesmontemagno/InAppBillingPlugin/issues/326).

**Comment by RadoslawKubas** [comment]
@WorldOfBasti Yes, I noticed it too, after restoring, it is impossible to purchase for a moment, if you wait a moment, it is possible again, but purchase takes few minutes, and if you wait few minutes it just works fine again fine.

BTW, do you, or maybe @prok155  tested already released app from App Store? Could you confirm problem there? I was testing with previous app version it is already in the store, and it seems to be fine, so maybe this is just sandbox account problem?

**Comment by WorldOfBasti** [comment]
Yeah, our app is currently in test (same issue in TestFlight), but I think also it will be fixed in production. Unfortunately it still takes a long time until our app is in production (school, work, etc.), but when it is, I will report my experiences here. 
As example I found a similar post [at a swift library](https://github.com/bizz84/SwiftyStoreKit/issues/587), which confirms that this is perhaps a issue from apple.. we will see.

**Comment by jamesmontemagno** [comment]
Hmmm maybe I need to put in a task completion source with a time out.... or I guess you could do that manually and wrap it as well.....

**Comment by RadoslawKubas** [comment]
@jamesmontemagno I don't think it is necessary. At least in my case, it doesn't freeze the app and as I mentioned earlier, it more feels like an issue with Apple's sandbox. 

I was debugging inside the plugin and it seems that 2nd time after `SKPaymentQueue.DefaultQueue.RestoreCompletedTransactions();`
nothing happened for few minutes. UpdatedTransactions, RestoreCompletedTransactionsFinished, RestoreCompletedTransactionsFailedWithError are not called. After few minutes UpdatedTransactions and RestoreCompletedTransactionsFinished is called and everything continue correctly. 

I believe the reason could be a mix of sandbox and account with over 150 transactions on the receipt (expired auto renewable subscriptions). 

 I plan to release the new app version on the App Store next week, so I can confirm if problem disappears.

**Comment by RadoslawKubas** [comment]
@jamesmontemagno Good news, I just checked the new released version from the App Store and it works fine without freezing. The same build installed from Test Flight an issue, so I it is  just sandbox issue.
