### ISSUE TITLE
Messagebox "in-app purchases are not allowed" displayed when checking for active subscriptions

### ISSUE THREAD

**Issue by sjorsmiltenburg** [jamesmontemagno/InAppBillingPlugin#357]
An iOS user can set the ability to use in-app purchases to "not allowed".
https://support.apple.com/en-us/HT204396

When booting my app I want to know if there is an active subscription.
I use billing.GetPurchasesAsync for this.
When the in-app purchases are set to "not allowed" calling this method triggers a messagebox to be shown shown (by ios i assume) that states "In-app-purchases are not allowed". This is unwanted behaviour.

**I would like that calling this function does NOT trigger this messagebox.**

I am probably able to detect if people have set in-app purchases to "not allowed" by checking 
SKPaymentQueue.CanMakePayments (https://developer.apple.com/documentation/storekit/skpaymentqueue/1506139-canmakepayments).

But that does not help me in the situation
- in-app purchase setting is set to "allowed"
- a user buys a subscription
- the setting is changed to "not allowed"
- app is rebooted and I again want to check if there is an active subscription

**Comment by jamesmontemagno** [comment]
This is a good feature request for sure and should be able to add it in.

**Comment by jamesmontemagno** [comment]
Imlementing in next beta
