### ISSUE TITLE
Play Billing Library 3 or newer

### ISSUE THREAD

**Issue by nicolgit** [jamesmontemagno/InAppBillingPlugin#358]
Just received this message from Google:

----

Google Play’s Billing   Library helps developers to build high-quality apps that users love, with   safe and secure experiences that users expect. Last July, we announced Billing   Library 3 with new payment options, subscription promotion capabilities, game   purchase attribution, and improved reliability and security.

This update impacts one or more of your apps, which uses AIDL or an older version of Billing Library.

* Starting on August       2, 2021, all new apps must use Google Play Billing Library 3       or newer.                                                              * Starting on November       1, 2021, all updates to existing apps must use Google       Play Billing Library 3 or newer. 

After these dates,   publishing new apps or app updates with AIDL or older versions of Billing   Library will be blocked.

----

InAppBillingPlugIn already uses this library or not? If not, are you planning to support it?

**Comment by justingden** [comment]
This is our question as well, so we are greatly hoping someone will answer this.

**Comment by jamesmontemagno** [comment]
The latest version uses billing v3 :)

**Comment by justingden** [comment]
You rock, James! We could never repay you for all the help we have received
from your work. :)
