### ISSUE TITLE
Can not compile on Android after updating from version 2 to version 4

### ISSUE THREAD

**Issue by Hobbit7** [jamesmontemagno/InAppBillingPlugin#359]
I have changed the Target Android version in AndroidManifest.xml to Android 10.0 (API level 29). But I still get a few error messages after updating from version 2 to version 4.

` protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);
            Xamarin.Essentials.Platform.Init(this, bundle);
            Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity = this;
       }`

**Error CS0234: The type or namespace name 'CurrentActivity' does not exist in the namespace 'Plugin' (are you missing an assembly reference?)**

Should I remove the line _Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity = this;_? Is this line not needed in version 4?

`  protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
        {
            base.OnActivityResult(requestCode, resultCode, data);
            InAppBillingImplementation.HandleActivityResult(requestCode, resultCode, data);
        }`

**Error CS0117: 'InAppBillingImplementation' does not contain a definition for 'HandleActivityResult'**

I have not understand if I only should delete the line _InAppBillingImplementation.HandleActivityResult(requestCode, resultCode, data);_ or if I should delete the entire code block _void OnActivityResult_?

In addition, I get two error messages when I want to purchase an item:
`  if (CrossInAppBilling.IsSupported == true)
            {
                var billing = CrossInAppBilling.Current;
                try
                {
                    var connected = await billing.ConnectAsync(ItemType.InAppPurchase);
                    if (connected == true)
                    {
                        var verify = DependencyService.Get<IInAppBillingVerifyPurchase>();

                        var purchase = await billing.PurchaseAsync(productId, ItemType.InAppPurchase, payload, verify);`

**Error CS1503: Argument 1: cannot convert from 'Plugin.InAppBilling.ItemType' to 'bool'**
**Error CS1501: No overload for method 'PurchaseAsync' takes 4 arguments**

What is wrong with the purchase code? What should I change?

I read this here on github:
`Version 3+ Linker Settings

For linking if you are setting Link All you may need to add:

Android:

Plugin.InAppBilling;Xamarin.Android.Google.BillingClient;
iOS:

--linkskip=Plugin.InAppBilling`

Is it necessary that I change something after I updated from version 2 to version 4 or is this for version 3 only?

**Comment by jamesmontemagno** [comment]
See -> https://github.com/jamesmontemagno/InAppBillingPlugin#version-4-major-update---android

**Comment by Meekohi** [comment]
Needed to be 
```
            var context = Xamarin.Essentials.Platform.AppContext;
            var activity = Xamarin.Essentials.Platform.CurrentActivity;
```
