### ISSUE TITLE
Support for family sharing

### ISSUE THREAD

**Issue by MarvinFrankenfeld** [jamesmontemagno/InAppBillingPlugin#360]
How can we handle familiy sharing for purchases?
https://developer.apple.com/documentation/storekit/in-app_purchase/supporting_family_sharing_in_your_app

When checking for available purchase as described in the documentation we only get the purchase for the account that actually purchased but not for the other accounts that are shared in the family.

Do we have to implement something special for this case or is it not yet supported?

Best regards
Marvin

**Comment by jamesmontemagno** [comment]
This should work out of the box as long as you turned it on. It should just show up as a shared purchase.

See:
Handle purchased (SKPaymentTransactionState.purchased) transactions. This is a standard state apps must handle, and you don’t need anything special for Family Sharing.
