### ISSUE TITLE
When should I use AcknowledgePurchaseAsync instead of ConsumePurchaseAsync?

### ISSUE THREAD

**Issue by Hobbit7** [jamesmontemagno/InAppBillingPlugin#361]
When should I use AcknowledgePurchaseAsync instead of ConsumePurchaseAsync when I purchase a product on Android with PurchaseAsync?
Can I use ConsumePurchaseAsync for both consumable and non-consumable products?
Or is ConsumePurchaseAsync only for consumables and AcknowledgePurchaseAsync only for non-consumables?
In the following code, I use ConsumePurchaseAsync and AcknowledgePurchaseAsync but I'm not sure if I use them correctly:

       `if (Device.RuntimePlatform == Device.Android)
        {
             if (purchase.ProductId == "consumable1")
             {
                 var consumedItem = await billing.ConsumePurchaseAsync(purchase.ProductId, purchase.PurchaseToken);
                 if (consumedItem == true)
                 {
                     // Add consumable1 to the player inventory
                 }
             }

             if (purchase.ProductId == "nonconsumable1")
             {
                 var consumedItem = await billing.AcknowledgePurchaseAsync(purchase.PurchaseToken);
                 if (consumedItem == true)
                 {
                     // Add nonconsumable1 to the player inventory
                 }
             }
        }`

Complete code:

       `public async Task<bool> PurchaseItem(string productId)
        {
            var purchaseSuccesful = false;

            if (CrossInAppBilling.IsSupported == true)
            {
                var billing = CrossInAppBilling.Current;
                try
                {
                    var connected = await billing.ConnectAsync();
                    if (connected == true)
                    {
                        var verify = DependencyService.Get<IInAppBillingVerifyPurchase>();
                        var purchase = await billing.PurchaseAsync(productId, ItemType.InAppPurchase, verify);

                        if (purchase == null)
                        {
                            //did not purchase
                            purchaseSuccesful = false;
                        }
                        else
                        {
                            if (purchase.State == PurchaseState.Purchased)
                            {
                                purchaseSuccesful = true;

                                if (Device.RuntimePlatform == Device.iOS)
                                {
                                    //Consumed
                                    if (purchase.ProductId == "consumable1")
                                    {
                                        // Add consumable1 to the player inventory
                                    }

                                    if (purchase.ProductId == "nonconsumable1")
                                    {
                                        // Add nonconsumable1 to the player inventory
                                    }
                                }
                                else
                                {
                                    if (Device.RuntimePlatform == Device.Android)
                                    {
                                        if (purchase.ProductId == "consumable1")
                                        {
                                            var consumedItem = await billing.ConsumePurchaseAsync(purchase.ProductId, purchase.PurchaseToken);
                                            if (consumedItem == true)
                                            {
                                                // Add consumable1 to the player inventory
                                            }
                                        }

                                        if (purchase.ProductId == "nonconsumable1")
                                        {
                                            var consumedItem = await billing.AcknowledgePurchaseAsync(purchase.PurchaseToken);
                                            if (consumedItem == true)
                                            {
                                                // Add nonconsumable1 to the player inventory
                                            }
                                        }
                                    }
                                }
                            }
                            else
                                purchaseSuccesful = false;  // PurchaseState could be PaymentPending
                        }
                    }
                    else
                    {
                        //we are offline or can't connect, don't try to purchase
                        purchaseSuccesful = false;
                    }

                }
                catch (Exception ex)
                {
                    //Something else has gone wrong, log it
                    purchaseSuccesful = false;
                    Debug.WriteLine("Issue connecting: " + ex);
                }
                finally
                {
                    await billing.DisconnectAsync();
                }
            }

            CrossInAppBilling.Dispose();

            return purchaseSuccesful;
        }`

**Comment by jamesmontemagno** [comment]
On Android if you purchase anything you must first Acknowledge a purchase else it will be refunded. See the android documentation
https://developer.android.com/google/play/billing/integrate#process
https://developer.android.com/google/play/billing/integrate#pending
