### ISSUE TITLE
Subscription lifecycle

### ISSUE THREAD

**Issue by brdacon1** [jamesmontemagno/InAppBillingPlugin#363]
I'm trying to verify the user's subscription lifecycle but I can't. Has anyone been able to see if the subscription is valid every time the user enters the app? Can you share the example with me?

**Comment by brdacon1** [comment]
I'm trying to verify the user's subscription lifecycle but I can't. Has anyone been able to see if the subscription is valid every time the user enters the app? Can you share the example with me?

**Comment by RadoslawKubas** [comment]
It depends on the platform.

**Google Play**
Not beautiful, but simple. Since Google recommends restoring purchases every time you launch and resume the app, and the plugin only returns your currently active subscriptions, you just need to check that your subscription is in the list.

**App Store**
**1st way - Apple recommended**
Every time you want to check if your subscription is active, you'll need to validate receipt with Apple. This way you will get all the necessary information. There is no support in the plugin for this way and to get it right and safe without revealing your secrets you need to use a proxy server. 

**2nd way - without validating receipt**
It may be easier to implement and works ok as long as subscription status is not a life changer. You need to remember user subscriptions yourself (you can get the list restoring purchases, it returns all active and not active subscriptions, but there is no info about current auto-renewal status). From the token you can decode subscription expiration date and compare it with the system date to check if it is active. Important thing (Apple's advice), you are not spouse of restoring purchases on every start because it may show the store login popup and disturb the user, so it's a better idea to check the current status Restore purchases) only if the user has expired subscription to see if there is a new renewal. 


**To decode data from token you may use this code:**

`using Claunia.PropertyList;`

```
public static IDictionary<string, object> DecodeTokenAppStore(string token)
        {
            if (Device.RuntimePlatform == Device.Android)
            {
                return null;
            }

            if (String.IsNullOrWhiteSpace(token))
            {
                return null;
            }

            var data1 = System.Convert.FromBase64String(token);
            if (!data1.Any())
            {
                return null;
            }

            var receiptDic = (NSDictionary)PropertyListParser.Parse(data1);
            if (receiptDic == null)
            {
                return null;
            }

            var purchaseInfoContent = receiptDic.ObjectForKey("purchase-info")?.ToString();
            if (string.IsNullOrEmpty(purchaseInfoContent))
            {
                return null;
            }

            byte[] data2 = System.Convert.FromBase64String(purchaseInfoContent);
            var purchaseInfoDic = (NSDictionary)PropertyListParser.Parse(data2);

            if (purchaseInfoDic == null)
            {
                return null;
            }

            var result = new Dictionary<string, object>();

            foreach (var item in purchaseInfoDic)
            {
                result.Add(item.Key, item.Value.ToObject());
            }

            return result;
        }

```

**Comment by brdacon1** [comment]
I managed to solve this problem using this link:
https://www.programmersought.com/article/5211123151/
But I got into another problem, Google asks to confirm the purchase within 3 days
Reading the documentation I found this:
**await billing.AcknowledgePurchaseAsync(PurchaseToken);**
but every time I run this section it creates an order on the new console the purchase token remains the same but the order number varies, is that correct?
Will he charge the user every time he performs this stretch?
**await billing.AcknowledgePurchaseAsync(PurchaseToken);**

**Comment by ssbssb-cmd** [comment]
> **2nd way - without validating receipt**
> ..... From the token you can decode subscription expiration date and compare it with the system date to check if it is active. Important thing (Apple's advice), you are not spouse of restoring purchases on every start because it may show the store login popup and disturb the user, so it's a better idea to check the current status (restore purchases) only if the user has expired subscription to see if there is a new renewal.
 ```

Hi I've managed to get the expiry date by taking "expires-date-formatted-pst" from the token but it is in this format:

"2021-06-30 12:07:44 America/Los_Angeles"

How did you convert this to a DateTime? 
I want to convert it into UTC so that i can compare with DateTime.UtcNow

**Comment by RadoslawKubas** [comment]
@ssbssb-cmd something like that:

```
var token = ShopService.DecodeTokenAppStore(PurchaseToken);

if (token != null && token.TryGetValue("expires-date", out var expiresDateAsStr))
{
 ExpireDate = new DateTime(1970, 1, 1).AddMilliseconds(Convert.ToInt64(expiresDateAsStr));
}
```

**Comment by ssbssb-cmd** [comment]
Thanks!!

So what I am planning to do with my app is get the expiry date, store it in the SecureStorage. Then each time the app loads, I will check if the expiryDate is greater than today's date. If it is not, call Restore Purchases and see if there is a newer expiry date which indicates the subscription is still active.


However - it sounds like couple of edge cases:

1.  Grace Period where payment has failed. 
If the user's payment has failed, and there is a grace period, will the token returned show the expiry date as the end of the Grace Period (e.g. 5 days)? or as the end of the subscription had they renewed it (e.g. 3 mths)?

2. Refunds
Once the expiry date has been stored, if the user cancels the subscription and requests a refund which Apple grants, there won't be any way to know that until I check restore purchases again at the end of the billing period.




Also you mention in the earlier post Option 1) to validate receipt with Apple - is the receipt the Purchase Token? I would need to send that to my server and then my server to get the membership status from Apple if going that route?

**Comment by RadoslawKubas** [comment]
As I mentioned before, option 1 works when the subscription is not a "life and death" issue. 

@1 I did something like that, when app starts:
1.Check locally that the subscription is active, if so continue as usual
2.if not, try to restore purchases (if possible without any user information)
3.If there is a new subscription for the next period, just write down the new expiration date and continue as usual
4.if it was not possible to restore (internet connection) or it was possible to restore, but there is no active subscription I show the user that the subscription is about to expire and if he did not renew it before its expiry + grace date the bonus will not be available (but will retain premium features), the next time the app is launched I will try the same steps again
5. If the grace period + 1 day (1 day just in case) has arrived and there is still no renewal, I inform the user that the premium is deactivated and that to continue, he must re-subscribe (and this time not bother user again with any more messages, maybe he just decided to cancel premium)

@2 I believe first of all, the best way is not to care about it. If I remember correctly, even Apple advices in some guidelines to not cancel user service if he asked refund. Apple doesn't cancel user payment easily, so probably it is not going to be a real problem, and for sure it is not the reason for bother paying users with any additional testing.

**Comment by vandenbrakel** [comment]
Hi, 

Came here to find out how to check if an active subscription is present.

Reading above, can I do this on iOS if I don't care about refunds? And assuming there's only one subscription for simplicity of the example:

```
var purchases = await billing.GetPurchasesAsync(ItemType.Subscription);
var latestSub = new InAppBillingPurchase();
                
foreach (var item in purchases)
                {
                    if (latestSub.TransactionDateUtc.CompareTo(item.TransactionDateUtc) == -1)
                    {
                        //newer
                        latestSub = item;
                    }
                }

//add 1 month of 31 days. Plus three trial days.

Console.WriteLine($"{latestSub.ProductId} {latestSub.State}: {latestSub.TransactionDateUtc} Expires: {latestSub.TransactionDateUtc.AddDays(34)}"); 


//compare with system date here.

```


Thanks for any clarification.

**Comment by jamesmontemagno** [comment]
See https://montemagno.com/ios-android-subscription-implemenation-strategies/
