### ISSUE TITLE
Clairifcation between ConsumePurchaseAsync() vs AcknowledgePurchaseAsync()

### ISSUE THREAD

**Issue by assassin316** [jamesmontemagno/InAppBillingPlugin#365]
Looking at the code, I can't seem to fully understand the two. If I understand, **ConsumePurchaseAsync()** is used in **Android** when purchasing a consumable, correct? And I assume we use **AcknowledgePurchaseAsync()** in **Android** when purchasing a non-consumable? And to clarify both, we call these only after **PurchaseState == Purchased**, correct?

**Comment by jamesmontemagno** [comment]
https://github.com/jamesmontemagno/InAppBillingPlugin/issues/361 see <-
