### ISSUE TITLE
Android in-app purchase acknowledge

### ISSUE THREAD

**Issue by SerkanKrkc** [jamesmontemagno/InAppBillingPlugin#366]
Android in-app purchases are refunded. I am trying to sell non-Consumable products. In the notes: There is information about "acknowledge all purchases" but I could not understand how and at what stage I will do it. Are there any sample codes?

Thanks.

**Comment by jamesmontemagno** [comment]
See https://github.com/jamesmontemagno/InAppBillingPlugin#pending-transactions
