### ISSUE TITLE
Subscription Check if Active

### ISSUE THREAD

**Issue by LukasWagnerX** [jamesmontemagno/InAppBillingPlugin#367]
Hey Guys, i am writing a small CrossApp for iOS/Android and i've got 2 Subscriptions init. Year and Month.
I've tested several snippets from the www.  But i can not check like ( if(sub = 1) {purchased} else {not purchased} 

The is a Snippet like WasItemPurchased(string productId) but that doesn't work. It says "yes" but the Sub is inactive. 

Does someone have a snippet or can introduce me?

I could check this with:  `var purchase = await CrossInAppBilling.Current.PurchaseAsync("month", ItemType.Subscription);`
but i don't want that on every app-opens the popup comes "already buyed".
Is there a solution without server, database,...?
Version Number of Plugin: 4.0.2
Device Tested On: 
Simulator Tested On:
Version of VS:  8.8.4

**Comment by LukasWagnerX** [comment]
edit: 
my mind sayes: if (month = 0 and year = 0){buy} else {int premium = 1;}

**Comment by RadoslawKubas** [comment]
Check this thread #363.

**Comment by jamesmontemagno** [comment]
See https://montemagno.com/ios-android-subscription-implemenation-strategies/
