### ISSUE TITLE
System.NotImplementedException gets thrown.

### ISSUE THREAD

**Issue by diozz** [jamesmontemagno/InAppBillingPlugin#368]
I'm on `Xamarin.Android` and am trying to upgrade from version `2.0.0` to `4.0.2`. I did make all the changes mentioned in the readme. 

When I call `CrossInAppBilling.Current.ConnectAsync()`, its throwing a `NotImplementedException`.

> System.NotImplementedException: 'This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.'

Both my target and compile Android version is 10 (Level 29).

What am I doing wrong?

**Comment by SatyaRamprasad** [comment]
Even i am getting the same error after updating package and following the docs. @jamesmontemagno  Please help us on this. Thanks in advance

**Comment by jamesmontemagno** [comment]
Make sure you are compiling and target api 10+ and that the nuget is installed in your Android project
