### ISSUE TITLE
iOS - Cannot connect to the iTunes Store

### ISSUE THREAD

**Issue by bartdkmediahuis** [jamesmontemagno/InAppBillingPlugin#37]
## Bug 

Version Number of Plugin: 1.1.0.34-beta
Device Tested On: Several iOS devices (iOS 10.x)

### Expected Behavior
Able to buy a certain product

### Actual Behavior
We receive the "Cannot connect to iTunes Store" message.

### Steps to reproduce the Behavior
- We did an upgrade of our app
- Existing products were available
- Connection with the old library is working fine
- Tests run by using a testFlight build (so using the real application identifier)

**Comment by prankard** [comment]
This was on twitter a week ago where the iTunesConnect sandbox was dead but only for buying products.

It would give that message, and then throw an exception in the code when it was purchasing.
I had the same issue, it works for me today. Have you tested it recently?

The issue wasted about a day of my time.

**Comment by jamesmontemagno** [comment]
Haven't been able to reproduce it and working for me.

**Comment by jonastheman** [comment]
I get this messsage, is it necessary to fill out the "Agreements, Tax, and Banking" on iTunes connect in order for success?

**Comment by prankard** [comment]
Yes, it looks like that is the case:
http://stackoverflow.com/questions/19558761/store-kit-transaction-error-cannot-connect-to-itunes-store-on-ios-7-device

That error (when it wasn't working for me when the server was down) is sadly also a generic error they throw for a lot of issues to prevent connection.
