### ISSUE TITLE
UNKNOWN_ERROR in GetProductInfoAsync

### ISSUE THREAD

**Issue by stesvis** [jamesmontemagno/InAppBillingPlugin#372]
Hello, is the plugin supposed to work in **iOS simulators** to `GetProductInfoAsync()`?
I know that you can't test purchases on simulators, as stated [here](https://jamesmontemagno.github.io/InAppBillingPlugin/TestingAndTroubleshooting.html):

> While you could e.g. read your items, you need a real device to test purchasing. Purchasing does not work on Simulators.

From the statement above it sounds like you should be able to get products info form a simulator, but instead i only get an `UNKNOWN_ERROR` as a result.
It works on a physical device though.

Thanks if you can provide any clarification.

**Comment by jamesmontemagno** [comment]
You can only use these APIs on a physical device. None are supported on simulators.
