### ISSUE TITLE
InAppBillingImplementation.PurchaseAsync on iOS returns Exception but only in production

### ISSUE THREAD

**Issue by oonnddrraass** [jamesmontemagno/InAppBillingPlugin#373]
### Exception:
InAppBillingImplementation.PurchaseAsync (System.String productId, Plugin.InAppBilling.Abstractions.ItemType itemType, System.String payload, Plugin.InAppBilling.Abstractions.IInAppBillingVerifyPurchase verifyPurchase)
Plugin.InAppBilling.Abstractions.InAppBillingPurchaseException: The operation couldn’t be completed. (SKErrorDomain error 2.)

### Steps to reproduce the Behavior
Try to purchase products in production because if you try this in sandbox everything works.

### Expected Behavior
Finish purchase and get a response.

### Actual Behavior
The exception appears but if the product is for example subscription you can find a running subscription under an Apple ID account.

### Code snippet
InAppBillingPurchase purchase = await billing.PurchaseAsync(iap_product, ResolveItemType(iap_product), "dev");

**Comment by jamesmontemagno** [comment]
Is your IAP live and active?

**Comment by oonnddrraass** [comment]
Hi,
Yes, it's active and approved by Apple. If I try to purchase the product in sandbox everything works but when I switch to the production there is always an exception in the PurchaseAsync function.

**Comment by jamesmontemagno** [comment]
Looks like this is just on Apple's end -> https://stackoverflow.com/questions/5224598/error-domain-skerrordomain-code-2-cannot-connect-to-itunes-store-userinfo-0x60 that error code is just what I report back based on what they give me. I would recommend trying from a different device or ensuring you are properly signed out of everything.

**Comment by yehorhromadskyi** [comment]
Hi @oonnddrraass, were you able to figure out the reason of the error? I've recently started facing the same issue

**Comment by oonnddrraass** [comment]
Hi, @yehorhromadskyi, for me the problem was in their documentation.
![image](https://user-images.githubusercontent.com/1340254/139812270-f455ab37-1719-4585-8282-a3c7d29add46.png)

The property type was "int" which is working for the TestFlight version but in production, the number needs to be "long".

**Comment by yehorhromadskyi** [comment]
@oonnddrraass, I see, thanks for the response.
