### ISSUE TITLE
Android Crash when unsuccessful Purchase (not attached to window manager)

### ISSUE THREAD

**Issue by SOliasS** [jamesmontemagno/InAppBillingPlugin#375]
I'm using the Plugin for my forms store, but i encountered a reproducible error on Android.
When Executing a Purchase and the Popup opens from below the user can stop the Purchase when swiping from top to bottom.
This results in the window disappearing and the function returns a PurchaseError.UserCancelled so far so good.

But after a few seconds a new Error gets thrown which crashes the app because it's unhandelt.

`Java.Lang.IllegalArgumentException: 'View=DecorView@4bca321[ProxyBillingActivity] not attached to window manager'
`
This error originates from Xamarin.Android.Google.BillingClient.
Similar to https://github.com/xamarin/Xamarin.Forms/issues/8044
It's seems that the Popup which google uses isn't finished when the Activity returns and results in this error.
This issue also occurs when trying to test and the user isn't included in the testgroup and the closes the popup with ok.
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/14180046/115544295-b4674300-a2a2-11eb-9d33-32ca10af043b.png)

Has anybody got an workaround for this issue?

**Comment by jamesmontemagno** [comment]
Where are you calling your purchase call from?

**Comment by jamesmontemagno** [comment]
And you are try/catching everything?

May want to look at this https://github.com/xamarin/Xamarin.Forms/issues/14193#issuecomment-828228605 as I can not reproduce

**Comment by SOliasS** [comment]
everything is executed in a try catch.
...
Found the issue,
I'm using ACR.UserDialogs to let the user know it worked/or not which seems to confilct with the store...
