### ISSUE TITLE
Bad documentation

### ISSUE THREAD

**Issue by Meekohi** [jamesmontemagno/InAppBillingPlugin#378]
https://github.com/jamesmontemagno/InAppBillingPlugin/blob/3ee347586d3dc34c9583994282247bbd0514a761/src/Plugin.InAppBilling/InAppBilling.apple.cs#L184

and the website at https://jamesmontemagno.github.io/InAppBillingPlugin/PurchaseSubscription.html refer to a `payload` but it does not exist in the code.

**Comment by jamesmontemagno** [comment]
Docs now updated for 4.0
