### ISSUE TITLE
ConnectAsync hangs indefinitely

### ISSUE THREAD

**Issue by julien-vandooren** [jamesmontemagno/InAppBillingPlugin#38]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 1.1.0.34-beta
Device Tested On: Samsung Galaxy S3
Simulator Tested On:

### Expected Behavior
ConnectAsync should return at least false.

### Actual Behavior
The second time ConnectAsync is called, it hangs indefinitively.

### Steps to reproduce the Behavior
Try to connect once then disconnect (in a finally).
Try to connect a second time > hang.
Only on some device appearently. It is OK on my Huawei but fails on a SAmsung Galaxy S3 ???

## Feature Request:
Please fill in what you would like

**Comment by jamesmontemagno** [comment]
Have you tried the latest versions? I haven't been able to repro this at all.

**Comment by julien-vandooren** [comment]
You're right. It seems to work as expected now.
Thank you for the follow-up, James.
