### ISSUE TITLE
Adding support for obfuscated account id when purchasing

### ISSUE THREAD

**Issue by Craig-Wheeler** [jamesmontemagno/InAppBillingPlugin#380]
In the Google Play billing docs, it recommends using the setObfuscatedAccountId and/or setObfuscatedProfileId methods on the BillingFlowParams builder to provide user information with the purchase
(https://developer.android.com/google/play/billing/security#fraud).

The current implementation of the private `PurchaseAsync` method does not expose this functionality. Will this be added?

Thanks!

**Comment by jamesmontemagno** [comment]
See -> https://github.com/jamesmontemagno/InAppBillingPlugin/pull/381 

I have never used these and their docs aren't very great.... do you just pass them in and that's it?

**Comment by jamesmontemagno** [comment]
Ah... i see they are returned in the purchase. I have added them to InAppBillingPurchase now

**Comment by Craig-Wheeler** [comment]
These also get returned when calling the purchases.subscriptions.get API, which is how we are going to link purchases to users when processing Google purchase notifications. Thanks for the quick turnaround!

**Comment by jamesmontemagno** [comment]
Gotcha, yeah it should get returned automatically with that extension method that converts it.

**Comment by jamesmontemagno** [comment]
Out in 4.2.0-beta
