### ISSUE TITLE
Promo/offer codes  - presentCodeRedemptionSheet

### ISSUE THREAD

**Issue by rgiurea** [jamesmontemagno/InAppBillingPlugin#383]
Hi James,

thanks for the great work on this plugin, it's really nice and easy to use. 

I was looking through the code/interface and I did not find any way to redeem promo codes in the app. It should be possible with the standard in app purchase library to redeem a code. On iOS it seems that you need to make a special call. On android you can redeem a code during payment. It is also possible in iOS and Android to redeem a full version of the app from the store but then its not very clear to me how we would check that and unlock the purchased item in the app, for eg. premium content.

Would it be possible to implement this kind of feature?

Thanks in advance! Cheers.

P.S: attached a link to the ios and android documentation of the redeem code stuff.

iOS
https://developer.apple.com/documentation/storekit/in-app_purchase/subscriptions_and_offers/implementing_offer_codes_in_your_app
Android
https://developer.android.com/google/play/billing/promo

**Comment by jamesmontemagno** [comment]
#268 dup

**Comment by jamesmontemagno** [comment]
I don't think there is anything special for Android.

On iOS 14+ i can expose presentCodeRedemptionSheet

I think in both cases you should get receipts... is my thinking

**Comment by yonkahlon** [comment]
Yeah, you get a receipt and it contains a field that its a offer code. From Apple's Docs:

> Identify Subscriptions Purchased With Offer Codes
> 
> When a customer successfully redeems a subscription offer code, the receipt contains a transaction with the field: offer_code_ref_name. This field’s value is the offer reference name that you configured in App Store Connect. The field is found in the [responseBody.Latest_receipt_info](https://developer.apple.com/documentation/appstorereceipts/responsebody/latest_receipt_info?language=objc) and [responseBody.Pending_renewal_info](https://developer.apple.com/documentation/appstorereceipts/responsebody/pending_renewal_info?language=objc) objects for receipts, and in the [unified_receipt.Latest_receipt_info](https://developer.apple.com/documentation/appstoreservernotifications/unified_receipt/latest_receipt_info?language=objc) and [unified_receipt.Pending_renewal_info](https://developer.apple.com/documentation/appstoreservernotifications/unified_receipt/pending_renewal_info?language=objc) objects for server notifications.

This feature would be awesome :-)

**Comment by jamesmontemagno** [comment]
@yonkahlon  all of that should be via a backend server so I wont add that in there as that really is part of receipt validation.

**Comment by yonkahlon** [comment]
@jamesmontemagno Yeah 100% :-)

Can I access presentCodeRedemptionSheet from this lib or from Xamarin StoreKit?

**Comment by mfranc28** [comment]
Hi, any news about promocode? With iOS 14+ there is a problem too. When the user redeem promo code nothing happen.
