### ISSUE TITLE
Android Pending Payments Confusion - IPurchasesUpdatedListener Implementation

### ISSUE THREAD

**Issue by jamsoft** [jamesmontemagno/InAppBillingPlugin#384]
I'm just looking at how to deal with Pending payments on Android. After reading the plugin docs and the google docs it states that in order to receive updates we should implement `PurchasesUpdatedListener` - in XF by implementing `IPurchasesUpdatedListener`.

This all sounds fine and reasonable in principal but I'm a still a little confused.

The `InAppBillingPlugin` also sets it's own listener internally https://github.com/jamesmontemagno/InAppBillingPlugin/blob/a0d0f3c620f2bd77c0734e0a2d5f18aa790a7cb1/src/Plugin.InAppBilling/InAppBilling.android.cs#L60 during the call to  ConnectAsync();

This leads me to think that if I also register a listener in my `MainActivity` won't this result in getting multiple updates during a normal purchasing process? Both the Plugin and `MainActiivty listener would be registered at that point.

It looks like this Plugin listener would be disconnected in the call to `DisconnectAsync();`, which is called in my code immediately after any billing processes.

At that point it seems to make sense to have the `MainActiivty` listener to then process any updates changing a Pending into Cancelled or Purchased outside of the `Connect() Disconnect()` flow.

Are there any examples of handling this?

**Comment by jamesmontemagno** [comment]
So i did -> https://github.com/jamesmontemagno/InAppBillingPlugin/pull/385

What i did here is made `IsConnected` visible which should be helpful for Android.

You can connect on startup and register for

```csharp
Plugin.InAppBilling.InAppBillingImplementation.OnAndroidPurchasesUpdated = (billingResult, purchases) =>
{
     // decide what you are going to do here with purchases
};
```

Does that make sense?

**Comment by jamsoft** [comment]
This does make a stack of sense. Thanks James, much more convenient, obvious and explicit.

**Comment by jamesmontemagno** [comment]
Cools, i will try to push a thing out in the next few days

**Comment by jamsoft** [comment]
Would be good to have an example usage I think.

Since the general advice in the documentation follows connect -> do your thing -> disconnect, it would be good to document how this should be treated in a similar or different manner.

It would suggest from the approach above that you connect during app initialisation and would need to then remain connected in order to receive the events.

Unless I'm actually reading this wrong myself at the moment.

**Comment by smalgin** [comment]
Sorry to pick on the closed issue, but I have the weirdest thing happening:

Xamarin app, latest version of billing plugin.

In my MainActivity I added the recommended code snippet to add purchase update listener.
Now I am getting this compile error:
MainActivity.cs(128,64,128,89): error CS0117: 'InAppBillingImplementation' does not contain a definition for 'OnAndroidPurchasesUpdated'

Any ideas? The web is silent...

**Comment by jamesmontemagno** [comment]
Should be there... https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/src/Plugin.InAppBilling/InAppBilling.android.cs#L29

Make sure that you are compiling your Android app against Android 10 +
