### ISSUE TITLE
InAppBillingPlugin with ACR.UserDialogs crashing

### ISSUE THREAD

**Issue by ejastre** [jamesmontemagno/InAppBillingPlugin#386]
Xamarin Forms (Android)
If you use InAppBillingPlugin with ACR.UserDialogs, after closing the InAppBilling screen (success or not), the application crashes with the error:

mono.java.lang.RunnableImplementor.run
RunnableImplementor.java, line 30
Java.Lang.IllegalArgumentException: View=DecorView@42ec0b0[ProxyBillingActivity] not attached to window manager

Versions used: 4.0.2 and 4.2.0-beta

Removed ACR.UserDialogs, it stopped crashing!

**Comment by jamesmontemagno** [comment]
Don't call it from the pop up. You are invoking windows from the pop up which doesn't exist.

**Comment by ejastre** [comment]
When I call the method below, it is opening a pop up with the Billing options and I think the pop up is in conflict with ACR.UserDialogs, any suggestions or just removing ACR.UserDialogs from the project? Thanks

await billing.PurchaseAsync(productId, ItemType.InAppPurchase);
