### ISSUE TITLE
[Feature Request] - UWP Subscriptions

### ISSUE THREAD

**Issue by ksoft1** [jamesmontemagno/InAppBillingPlugin#388]
I created a simple app and published it (on UWP and Android) with hidden availability and create add-on product.
-The InAppPurchase and Subscription work on Android.  

-On UWP, the InAppPurchase only work but Subscription does not work. 

UWP docs specify that :
"_To use subscription add-ons, your app must target Windows 10 Anniversary Edition (10.0; Build 14393) or a later release in Visual Studio, and it must use the Windows.Services.Store namespace instead of the Windows.ApplicationModel.Store namespace._"]

Do you have any idea why Subscription does not works on UWP?

**Comment by jamesmontemagno** [comment]
I do not support Subscriptions currently on UWP. I have to re-write it completely to use the new Windows.Services.Store.

**Comment by jamesmontemagno** [comment]
#103 for tracking
