### ISSUE TITLE
RestoreCompletedTransactionsFinished on iOS obsolete

### ISSUE THREAD

**Issue by makerofthings7** [jamesmontemagno/InAppBillingPlugin#39]
SKPaymentQueue is the replacement for obsolete RestoreCompletedTransactionsFinished() override in this code:

https://github.com/jamesmontemagno/InAppBillingPlugin/blob/cd07a55eacabd093163b3846ea3342fc63fcd427/src/Plugin.InAppBilling.iOS/InAppBillingImplementation.cs#L338

Replace with 

http://stackoverflow.com/a/14313705

**Comment by jamesmontemagno** [comment]
We already use skpaymentqueue and implement that method.

**Comment by jamesmontemagno** [comment]
Closing with not enough information
