### ISSUE TITLE
ConnectAsync argument

### ISSUE THREAD

**Issue by JohnGaby** [jamesmontemagno/InAppBillingPlugin#390]
I am updating from version 2 to version 4 and I find that the ConnectAsync function now takes a boolean instead of an ItemType. Since your examples still show calling it with and ItemType can someone illuminate what I should be doing?

Thanks.

**Comment by JohnGaby** [comment]
I tried just dropping the ItemType from the call and everything seems to work ok. Is this the correct thing to do?

**Comment by jamesmontemagno** [comment]
you don't need to pass anything to it any more.
