### ISSUE TITLE
source code reference does not handle AcknowledgePurchaseAsync correctly

### ISSUE THREAD

**Issue by sjorsmiltenburg** [jamesmontemagno/InAppBillingPlugin#391]
the documentation states: 
_On Android if you purchase anything you must first Acknowledge a purchase else it will be refunded. See the android documentation._

the implementation that is refered to in the same docs does not seem to handle this correctly

_Source code reference -> https://github.com/jamesmontemagno/app-ac-islandtracker/blob/freemium/TurnipTracker/ViewModel/ProViewModel.cs_

```
 else if (purchase.State == PurchaseState.Purchased)
                {
                    try
                    {
                        await CrossInAppBilling.Current.AcknowledgePurchaseAsync(purchase.PurchaseToken);
                    }
                    catch (Exception ex)
                    {

                    }
```

The catch is empty and code assumes that it can set the Pro feautre "ON".

**Comment by jamesmontemagno** [comment]
Yeah up to you to figure out how you want to handle it. I probably need to put a toggle in there to see if I did acknowledge it or not as I assume success. More of a potential bug in my app.

**Comment by sjorsmiltenburg** [comment]
correct, that was what i was trying to tell you :)
because in your text you say that if it is unsucessfull the purchase will be reverted.

**Comment by sjorsmiltenburg** [comment]
I also noticed your implemation doesn't call CrossInAppBilling.Dispose() as mentioned in https://jamesmontemagno.github.io/InAppBillingPlugin/Architecture.html

Is this no longer needed?

**Comment by jamesmontemagno** [comment]
I keep it around becuase i have a global registration in some of my apps, either way doesn't matter really.
