### ISSUE TITLE
Can i use this with a service other than GMS

### ISSUE THREAD

**Issue by gcmnali** [jamesmontemagno/InAppBillingPlugin#393]
Hi, Can i use this plugin with another Billing service for example RevenueCat, except Google Play Billing Library.
Currently i am using your plugin for my android project but i have to implement a new service for some devices that is not installed GMS.
Thanks.

**Comment by jamesmontemagno** [comment]
It only works with Google Play Billing Library, however you can implement the interface on your side and use it cross platform.
