### ISSUE TITLE
`PurchaseState.PaymentPending` and `PurchaseState.Pending`

### ISSUE THREAD

**Issue by MichalTelus** [jamesmontemagno/InAppBillingPlugin#394]
Hi, 

I like this plugin, it's super useful, however I find out one thing that is confusing.
In enum PurchaseState there are two pending states: `PurchaseState.PaymentPending` and `PurchaseState.Pending`. As I understood the `PurchaseState.Pending` is obsolete or not used at all. 

It's a rather small thing so maybe you could remove it, add obsolete parameter or add some explanation when we should use it?

**Comment by jamesmontemagno** [comment]
I will add the obsolete flag. I am not sure why it was ever added, but yeah i only ever return PaymentPending currently.
