### ISSUE TITLE
Setup to test IAP on Android (currently returning zero products)

### ISSUE THREAD

**Issue by ssbssb-cmd** [jamesmontemagno/InAppBillingPlugin#396]
Hi all - i'm struggling with how to setup on Android. I've implemented the InAppBilling plugin on Xamarin Forms and have tested it on an iPhone SandBox which it seems to be working OK (retrieve products, purchase product).

However, when testing on Android device, GetProductInfoAsync it is always returning empty. In the Google Play Console, I have setup the products (Subscriptions) with the correct Product ID and the status is showing as Active. 

I am using Visual Studio Mac and have deployed the app to my Android device in both Debug and Release modes but in both cases it is still returning zero products.

I must be missing some config or something somewhere but I cannot figure out what it is - any suggestions on what might be the missing step?

**Comment by brendacastromonobits** [comment]
Hi, how did you get subscriptions working on iOS, I've been trying to test it but GetProductInfo returns null like product wasn't available. I follow the steps on [https://jamesmontemagno.github.io/InAppBillingPlugin/TestingAndTroubleshooting.html](https://jamesmontemagno.github.io/InAppBillingPlugin/TestingAndTroubleshooting.html) but nothing works. Thanks in advance.

**Comment by jamesmontemagno** [comment]
Unable to reproduce working fine for me. https://www.revenuecat.com/blog/the-ultimate-guide-to-subscription-testing-on-ios
