### ISSUE TITLE
CrossInAppBilling.IsSupported always returns false

### ISSUE THREAD

**Issue by RadiwaRami** [jamesmontemagno/InAppBillingPlugin#397]
I try to implement InApp purchase to my Android App. I read the documentation of the plugin, the principals from Google. I did configuration on the Google side and the code inside my app.

However my app (written in Xamarin) always returns false in the CrossInAppBilling.IsSupported.
I'm testing on the physical device and debugging under Visual Studio 2019 Xamarin.

What could be the reason behind this problem?

**Comment by jamesmontemagno** [comment]
Did you add the nuget into your Android app?

Make sure you are compiling against Android 10 or higher.

**Comment by RadiwaRami** [comment]
Thanks for the quick reply.

Yes, I did all the step from your docs. Added nuget package Plugin.InAppBilling for my android app (this is android only project) , compiling for Android 10.

I guess there is a silly mistake in my code or configuration. I'm implementing payments for the first time (Most of my life I spent programming desktop apps).

**Comment by RadiwaRami** [comment]
My bad (as expected). Now it is ok. I was not compiling for Android 10, which I was sure I checked several times...
