### ISSUE TITLE
Linker Error on Android after Update of Xamarin.Android.Google.BillingClient

### ISSUE THREAD

**Issue by SonicHS** [jamesmontemagno/InAppBillingPlugin#398]
I had a working implementation for a InApp-Purchase in my app (already released)... But then I was stupid enough to update all NuGet-Packages in my project. Which also updated Xamarin.Android.Google.BillingClient to Version 4.0.0 (I have no idea wich version it was before updating). 

Now I get the following Compiler-Exception (in Release Mode with link all assemblys):
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Legacy.targets(5,5): Error XALNK7000: Mono.Linker.MarkException: Error processing method: 'Plugin.InAppBilling.InAppBillingPurchase Plugin.InAppBilling.Converters::ToIABPurchase(Android.BillingClient.Api.Purchase)' in assembly: 'Plugin.InAppBilling.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.String Android.BillingClient.Api.Purchase::get_Sku()
  at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod (Mono.Cecil.MethodReference reference) [0x00013] in [...]

I have a Linker-Config-File wich looks like that:
`<linker>
    <assembly fullname="Plugin.InAppBilling">
		<namespace fullname="Plugin.InAppBilling" />
	</assembly>
    <assembly fullname="Xamarin.Android.Google.BillingClient">
		<namespace fullname="Android.BillingClient" />
	</assembly>
</linker>`

I also tried to put the libraries in the linker-options of the project... same result.

## Bug Information

Version Number of Plugin: 4.0.2 and 4.2.0-beta testet
Device Tested On: -
Simulator Tested On: -
Version of VS: 8.10.5 (build 16) for Mac
Version of Xamarin: 11.3.0.4 (Xamarin.Android)
Versions of other things you are using:
   Xamarin.Android.Google.BillingClient: 4.0.0
  Android Target Version: Android 10
  C#-Language Version: Version 8

### Expected Behavior
Compilation with linking

### Actual Behavior
Linker-Error

**Comment by jamesmontemagno** [comment]
I have a dependency on 3.0.0 of https://www.nuget.org/packages/Xamarin.Android.Google.BillingClient/ so don't update to 4.0 as it will have breaking changes.

**Comment by jamesmontemagno** [comment]
If desired you can use the 5.0.0-beta to use billing client 4.0
