### ISSUE TITLE
How is the correct way to handle iOS Auto-Renew Subscription 

### ISSUE THREAD

**Issue by AlanFloyd** [jamesmontemagno/InAppBillingPlugin#401]
I have read across the issues and searched in internet, but really haven't found any solution that give me trust to release my app to the AppStore, in iOS, Android is working great.

I am using the following code to determinate if the subscription is valid:

`                   var latestSub = new InAppBillingPurchase();
                    foreach (var item in purchases)
                    {
                        Console.WriteLine($"Date: {item.TransactionDateUtc}");
                        if (latestSub.TransactionDateUtc.CompareTo(item.TransactionDateUtc) == -1)
                        {                               
                            latestSub = item;
                        }
                    }

                    var last_date = latestSub.TransactionDateUtc.AddDays(31);
int result = DateTime.Compare(last_date, DateTime.Now);

                    bool valid = false;
                    if (result < 0)
                        valid = false;
                    else if (result == 0)
                        valid = true;
                    else
                        valid = true;
`

As result of the Console.WriteLine I am getting:

Date: 29/07/2021 04:37:15 p. m.
Date: 22/07/2021 09:02:33 p. m.
**Date: 30/07/2021 01:31:31 p. m.**
Date: 29/07/2021 03:47:31 p. m.
Date: 22/07/2021 08:42:33 p. m.
Date: 29/07/2021 04:07:31 p. m.
Date: 22/07/2021 08:47:33 p. m.
**Date: 30/07/2021 01:36:31 p. m.**
Date: 22/07/2021 08:57:33 p. m.
**Date: 30/07/2021 01:41:31 p. m.**
**Date: 30/07/2021 01:46:31 p. m.**
Date: 29/07/2021 04:28:20 p. m.
**Date: 30/07/2021 01:51:31 p. m.**
Date: 29/07/2021 03:52:31 p. m.
**Date: 30/07/2021 01:56:31 p. m.**
Date: 22/07/2021 08:52:33 p. m.
Date: 29/07/2021 04:02:31 p. m.
Date: 29/07/2021 03:57:31 p. m.
Date: 22/07/2021 09:09:22 p. m.
Date: 29/07/2021 03:42:31 p. m.

As I have monthly subscription, in Sandbox that means up to 6 renews, 5 minutes each, I assume that my code is working fine. For 30/07/2021 I have 6 renews, last at 01:56:31. 

As mentioned above, I assume that everything is correct, can you agree? If not, what is my mistake?

Greeting
Alan

**Comment by jamesmontemagno** [comment]
https://gist.github.com/jamesmontemagno/e9502b7605f4068f644d3cfc5fe0f19f
