### ISSUE TITLE
[Feature Request] - Huawei payments

### ISSUE THREAD

**Issue by paleicikas** [jamesmontemagno/InAppBillingPlugin#407]
https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/dev-guide-0000001050130254

**Comment by jamesmontemagno** [comment]
You can implement the interface on you side. I have. I plans to add other stores

**Comment by richaplinvs** [comment]
> You can implement the interface on you side. I have. I plans to add other stores

Hi, not sure from the typo if this means you **do** have plans to add other stores?

**Comment by jamesmontemagno** [comment]
I do not have plans to add other stores, however I am open to contributions.
