### ISSUE TITLE
[Question]  InAppBilling Plugin for MAUI

### ISSUE THREAD

**Issue by Orgbrat** [jamesmontemagno/InAppBillingPlugin#408]
Are you going to migrate the InAppBilling Plugin to MAUI (.Net 6.0)?

**Comment by harima34** [comment]
+1, I'm looking for that too

**Comment by jamesmontemagno** [comment]
Should work just fine as the TFMs are back compat from my understanding else easy to update

**Comment by harima34** [comment]
Hi James, thanks for your message. Actually after install the plugin i got that error :

`Java type 'xamarin.essentials.fileProvider' is generated by more than one managed type. Change the [Register] attribute for the same java type didn't be sent.
'xamarin.essentials.fileProvider' generated by : Microsoft.Maui.Essentials.FileProvider, Microsoft.Maoi.Essentials, Version=1.0.0.0, Culture=neutral, PublickKeyToken=null
'xamarin.essentials.fileProvider' generated by : Xamarin.Essentials.FileProvider, Xamarin.Essentials, Version=1.0.0.0, Culture=neutral, PublickKeyToken=null`

Can you help tell me how to fix that issue ?
Thank you so much

**Comment by jamesmontemagno** [comment]
Ah yes, I think that probably there may be a conflict between Xamarin.Essentials and .NET MAUI Essentials. I think that they are generating the same file names.... I will work with the team on this and see.

**Comment by FalxDrako** [comment]
There is also this:

`Warning	NU1703	'Plugin.InAppBilling 4.0.2' was resolved as a dependency of 'MauiApp2', but the dependency is using 'Xamarin.iOS' while 'MauiApp2' is using 'net6.0-maccatalyst15.0' as its TargetFramework. There might be compatibility issues when MacCatalyst projects depend on Xamarin.iOS projects.	MauiApp2	C:\Program_Dev\.NET\MauiApp2\MauiApp2\MauiApp2.csproj	1	`

@jamesmontemagno any chance InAppBilling can be reliably used in net6.0-maccatalyst?

**Comment by jamesmontemagno** [comment]
I wouldn't see why not. over the holidays i plan on migrating the code over

**Comment by maxkoshevoi** [comment]
@jamesmontemagno Hi, any news on MAUI migration?

**Comment by jamesmontemagno** [comment]
See https://github.com/jamesmontemagno/InAppBillingPlugin/pull/436
