### ISSUE TITLE
iOS LocalizedPrice shows XXX instead of currency symbol on iOS15

### ISSUE THREAD

**Issue by vandenbrakel** [jamesmontemagno/InAppBillingPlugin#409]
## Bug Information

Version Number of Plugin: 2.x and 4.02
Device Tested On: Several iOS devices running latest iOS15 beta
Simulator Tested On: none
Version of VS:  VS 8.10x
Versions of other things you are using:

### Steps to reproduce the Behavior
Build to device running iOS15. Use purchase.LocalizedPrice on iOS 15 beta. Shows XXX.

### Expected Behavior
Show currency symbol. Works with same code on previos iOS versions. Might be formatter issue?

### Actual Behavior
Shows "XXX"

### Code snippet
```
  var items = await billing.GetProductInfoAsync(ItemType.Subscription, "1year_basic_skills", "1month_basic_skills");
                foreach (var item in items)
                {
                        Console.WriteLine(item.ProductId);
                        if (item.ProductId == "1year_basic_skills")
                        {
                            lblPrice.Text = $"3 days trial, renews at {item.LocalizedPrice} / {subPeriod}";
                            LocalizedPriceYear = item.LocalizedPrice;
                            btnYearly.Text = item.LocalizedPrice + " / Year";
                        }

                        if (item.ProductId == "1month_basic_skills")
                        {
                        //    lblPrice.Text = $"3 days trial, renews at {item.LocalizedPrice} / {subPeriod}";
                            LocalizedPriceMonth = item.LocalizedPrice;
                            btnMonthly.Text = item.LocalizedPrice + " / Month";
                        }


                    }

                }
```

### Screenshots
![IMG_3477](https://user-images.githubusercontent.com/3436778/131717116-e59e1e05-c021-41da-8566-dbed2be63955.png)
![IMG_3476](https://user-images.githubusercontent.com/3436778/131717131-81a39523-ace4-42f1-9a2e-52ee443ef56f.png)

**Comment by jamesmontemagno** [comment]
Hmmmmmm maybe apple broke it

https://github.com/jamesmontemagno/InAppBillingPlugin/blob/17af6e5ef943b42cca0cb111fb848fa2a73dd297/src/Plugin.InAppBilling/InAppBilling.apple.cs#L577 is what we use

**Comment by jamesmontemagno** [comment]
What beta are you on?

working here in US atleast. Can you install my app My Cadence and go to the setting a screen.

![5C8A9941-FF48-48A3-A8F8-8A9E6CCD82C4](https://user-images.githubusercontent.com/1676321/132444299-19058000-3abd-4621-8197-6c1f72dd00db.png)

**Comment by vandenbrakel** [comment]
Tested on beta 7 and 8. When I test my existing apps on the App Store the issue isn't there. (compiled with plugin version 2.0.0). When I upload and test the same app in TestFlight on iOS 15 (compiled against iOS14.5) the XXX show up. Not sure what the issue is yet.

**Comment by jamesmontemagno** [comment]
Hmmmmm. Odd. I am testing on beta 8 and on TestFlight as well.  I am building on AppCenter against Xamarin.iSO 14.14.

Can you test out my app, maybe it non US based -> https://testflight.apple.com/join/LuKZw2yD

We should be able to reproduce, what we need to see is what is coming from it. Could test this code in your app

```csharp
var formatter = new NSNumberFormatter()
			{
				FormatterBehavior = NSNumberFormatterBehavior.Version_10_4,
				NumberStyle = NSNumberFormatterStyle.Currency,
				Locale = product.PriceLocale
			};
			var formattedString = formatter.StringFromNumber(product.Price);
```

**Comment by vandenbrakel** [comment]
It looks like Non US indeed. I'm on the euro currency. ![image](https://user-images.githubusercontent.com/3436778/132557514-cd413c99-31c3-411e-8a73-34238f0f85ed.jpeg)

**Comment by jamesmontemagno** [comment]
Yeah or euro specific, interesting.

We can look at this code:
```csharp
var formatter = new NSNumberFormatter()
			{
				FormatterBehavior = NSNumberFormatterBehavior.Version_10_4,
				NumberStyle = NSNumberFormatterStyle.Currency,
				Locale = product.PriceLocale
			};
			var formattedString = formatter.StringFromNumber(product.Price);
```

will need to know what it returns for you for product.PriceLocale and product.Price if you can debug your app locally for me and we can then figure it out.

**Comment by vandenbrakel** [comment]
Output of: https://github.com/jamesmontemagno/InAppBillingPlugin/blob/17af6e5ef943b42cca0cb111fb848fa2a73dd297/src/Plugin.InAppBilling/InAppBilling.apple.cs#L589
`
 ** formatter.StringFromNumber(1.99) = XXX 1,99 for locale nl`

**Comment by jamesmontemagno** [comment]
Interesting... can you expand all of the other properties on both `product` and `product.PriceLocale`

Maybe we need to do a check for iOS 15 and do something else... how annoying.

I am reading the apple forums and seems at though it is on their side....

https://cc.bingj.com/cache.aspx?q=PriceLocale+incorrect+on+ios+15&d=4675364202808903&mkt=en-US&setlang=en-US&w=qJ5Ei9nnvchOHEzlXS5zhbtGsXTR7OxY

So work the question would be is there a currency symbol i can use and replace XXX with it although i wont know if it should go before or after.

**Comment by vandenbrakel** [comment]
It just started working magically. Probably a server side fix at Apple...

Same output now on iOS 15.

**Comment by jamesmontemagno** [comment]
AMAZING! Thanks for confirming!!!! Betas!
