### ISSUE TITLE
PurchaseAsync returns null InAppBillingPurchase result after a successful purchase

### ISSUE THREAD

**Issue by CrewNerd** [jamesmontemagno/InAppBillingPlugin#41]
## Bug 

Version Number of Plugin: 1.1.0.35-beta
Device Tested On: Samsung Galaxy S5 (Android 6.0.1)

### Expected Behavior

On a successful purchase, PurchaseAsync completes with a non-null InAppBillingPurchase.

### Actual Behavior

All indications are that the purchase succeeded (Google Play reports success) but the task result is null. Looking at the account subscriptions in the Google Play app, I can see that the subscription purchase did complete.

I also verified that my OnActivityResult is being called with requestCode=1001, resultCode=Ok, and responseCode=0, and this is being passed along to InAppBillingImplementation.HandleActivityResult.

I'm seeing this for a subscription purchase *and* when purchasing a consumable product.
Note: shortly after the purchase was started, the log shows the following suspicious error:

```
04-29 22:58:36.537: I/MainActivity(21441): PurchaseSubscription: connected, purchasing
04-29 22:58:36.542: I/Finsky(9080): [535] com.google.android.finsky.billing.iab.y.a(32): com.performancephones.crewnerd: Account determined from library ownership - [Ohz2sWuzKyd7LW40g-gyu0tWluk]
04-29 22:58:36.552: E/Parcel(4385): Class not found when unmarshalling: com.google.android.finsky.billing.common.PurchaseParams
04-29 22:58:36.552: E/Parcel(4385): java.lang.ClassNotFoundException: com.google.android.finsky.billing.common.PurchaseParams
04-29 22:58:36.552: E/Parcel(4385): 	at java.lang.Class.classForName(Native Method)
04-29 22:58:36.552: E/Parcel(4385): 	at java.lang.Class.forName(Class.java:324)
04-29 22:58:36.552: E/Parcel(4385): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2404)
04-29 22:58:36.552: E/Parcel(4385): 	at android.os.Parcel.readParcelable(Parcel.java:2358)
04-29 22:58:36.552: E/Parcel(4385): 	at android.os.Parcel.readValue(Parcel.java:2264)
04-29 22:58:36.552: E/Parcel(4385): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
04-29 22:58:36.552: E/Parcel(4385): 	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
04-29 22:58:36.552: E/Parcel(4385): 	at android.os.BaseBundle.getString(BaseBundle.java:920)
04-29 22:58:36.552: E/Parcel(4385): 	at android.content.Intent.getStringExtra(Intent.java:6183)
04-29 22:58:36.552: E/Parcel(4385): 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2695)
04-29 22:58:36.552: E/Parcel(4385): 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2157)
04-29 22:58:36.552: E/Parcel(4385): 	at com.android.server.am.ActivityManagerService.startActivityInPackage(ActivityManagerService.java:6874)
04-29 22:58:36.552: E/Parcel(4385): 	at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:310)
04-29 22:58:36.552: E/Parcel(4385): 	at com.android.server.am.ActivityManagerService.startActivityIntentSender(ActivityManagerService.java:6632)
04-29 22:58:36.552: E/Parcel(4385): 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:292)
04-29 22:58:36.552: E/Parcel(4385): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3995)
04-29 22:58:36.552: E/Parcel(4385): 	at android.os.Binder.execTransact(Binder.java:453)
04-29 22:58:36.552: E/Parcel(4385): Caused by: java.lang.ClassNotFoundException: com.google.android.finsky.billing.common.PurchaseParams
04-29 22:58:36.552: E/Parcel(4385): 	at java.lang.Class.classForName(Native Method)
04-29 22:58:36.552: E/Parcel(4385): 	at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
04-29 22:58:36.552: E/Parcel(4385): 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
04-29 22:58:36.552: E/Parcel(4385): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-29 22:58:36.552: E/Parcel(4385): 	... 17 more
04-29 22:58:36.552: E/Parcel(4385): Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

### Steps to reproduce the Behavior

Call ConnectAsync followed by PurchaseAsync for a subscription or consumable product.

Looking at the code here, I see that there are several reasons why PurchaseAsync can return null. To eliminate one of those possibilities, I removed the "verify" parameter from my purchase calls. The behavior was the same.

It looks like there may be a race condition between PurchaseAsync and the HandleActivityResult callback. tcsPurchase is being set *after* the call to serviceConnection.Service.GetBuyIntent which I think allows the HandleActivityResult call happen while tcsPurchase is still null.

**Comment by rafaelagp** [comment]
I've got the same behavior on non-consumables with the PurchaseAsync method called without verifyPurchase parameter.

**Comment by jamesmontemagno** [comment]
Hmmm, i am in crazy prep for build right now, but if someone could pull in the code into their repo and take a look let me know as I haven't seen it, but who knows.

**Comment by CrewNerd** [comment]
I forked your repo and will look into this more. I should be able to report back by the end of the week.

**Comment by CrewNerd** [comment]
Found the problem... when I pass an empty string for the "payload", it gets deserialized as null, causing the comparison to fail when checking for success. I added code to promote null payloads to string.Empty both on incoming purchase calls, and when looking at the deserialized purchase.

I also fixed the potential race condition with tcsPurchase. I'll submit a PR with the changes.

**Comment by jamesmontemagno** [comment]
Ah, yes this makes sense, you should always pass a payload though as per Google. I will look at the PR though for sure as we can handle this... Although is is better to now allow a blank payload?

**Comment by CrewNerd** [comment]
I think more parameter validation across the board would be a good thing. I wouldn't mind being forced to pass in a payload string, but I don't know if there's really a good reason to not just let null and string.Empty work too.

Either way, I think the tcsPurchase change is a good precaution.
