### ISSUE TITLE
Hangs on ConnectAsync on Android (app in alpha test with in-app purchase setup)

### ISSUE THREAD

**Issue by stewartsims** [jamesmontemagno/InAppBillingPlugin#410]
## Bug Information

Version Number of Plugin: 4.0.2
Device Tested On: Sony Xperia XA1 and TCL 10 Pro
Simulator Tested On: 
Version of VS: 16.11.1
Version of Xamarin: Xamarin Forms 5.0.0.2083
Versions of other things you are using:
Xamarin Essentials 1.6.1

### Steps to reproduce the Behavior
The app hangs on Android on `var connected = await billing.ConnectAsync();` in alpha testing with billing permission and in app purchases setup. The iOS setup is working OK.

### Expected Behavior
App should proceed and connect to Play Store services.

### Actual Behavior
App hangs indefinitely - no error message

### Code snippet
`var connected = await billing.ConnectAsync();`

Sorry to be a pain and bring this up as I see from past issues this is often caused by not following the documentation however to the best of my knowledge I have done everything correctly. Please do let me know if there are any other steps I can take to debug this issue.

**Comment by stewartsims** [comment]
OK an update on this for anyone struggling with a similar issue.

In my case it looks like this has to do with invoking my async method which handled the purchase in a Command and using .Result on that method inside the Command. If I pull everything out into a simple async Button click method it seems to be working.

I am still debugging to pinpoint exactly what causes the app to hang (whether it is not invoking the billing library in the main UI thread or how the result is awaited) but in essence it looks like you have to be careful about how you invoke the library and best to test it in the simplest possible scenario to verify the configuration and basic code to invoke it first.

Sorry if I missed something important in the documentation that explains my issue. Will close this now.

**Comment by stewartsims** [comment]
After more testing the issue in short is simply down to me using `MyPurchaseMethod().Result` - if you're having similar issues try changing it to `var result = await MyPurchaseMethod()` instead.

**Comment by jamesmontemagno** [comment]
https://montemagno.com/c-sharp-developers-stop-calling-dot-result/ :)
