### ISSUE TITLE
[QUESTION] Validate actual state of a subscriprion

### ISSUE THREAD

**Issue by scarrier92** [jamesmontemagno/InAppBillingPlugin#411]
Is there a way to validate the current state of a subscription? Renewed,canceld,refund .... for IOS especially

From research I've found a web api : https://developer.apple.com/documentation/appstorereceipts/verifyreceipt 

Is that implemented in anyway in that api?

**Comment by jamesmontemagno** [comment]
See https://jamesmontemagno.github.io/InAppBillingPlugin/SecuringPurchases.html

**Comment by jamesmontemagno** [comment]
https://gist.github.com/jamesmontemagno/e9502b7605f4068f644d3cfc5fe0f19f as well
