### ISSUE TITLE
IOS: GetPurchasesAsync(ItemType.Subscription); doesn't return any subscriptions

### ISSUE THREAD

**Issue by TomQv** [jamesmontemagno/InAppBillingPlugin#415]
Hi, I'm testing AppBillingPlugin for my InAppPurchases in a new app, which is not yet published in AppStore. Is this suppose to work? I configured a subscription and also a sandbox-account for testing. 

```
_current = CrossInAppBilling.Current;
await _current.ConnectAsync();
```

This is working, I receive the list of my configured InAppPurchases:
`var items = await _current.GetProductInfoAsync(ItemType.InAppPurchase, productIds);`

This is also working, at least at the end I receive a message "successful"
`var subscribtion = await _current.PurchaseAsync(productid, ItemType.InAppPurchase);`

But then this always returned an empty list:
`var subs = await _current.GetPurchasesAsync(ItemType.InAppPurchase);`

Also in my iPhone in Settings-AppSore-My Sandbox account it says, that I have no active subscriptions.

So where am I wrong? Why is the plugin telling me "success" while the subscription is not added into the sandbox-account? I also changed ItemType.InAppPurchase to ItemType.Subscription but this didn't change.

**Comment by jamesmontemagno** [comment]
You would need to query `ItemType.Subscription`.

Checkout this blog -> https://corporate.accuweather.com/newsroom/blog/step-by-step-guide-for-ios-subscription-testing

**Comment by jamesmontemagno** [comment]
Also: https://stackoverflow.com/questions/40087527/ios-manage-my-subscription-with-sandbox-account

**Comment by TomQv** [comment]
Thank you for quick answering.
Changing to `ItemType.Subscription` doesn't help, still my purchased subscription is not returned by `GetPurchasesAsync(ItemType.Subscription); ` But now I get a message "You have subscribed to this in the past". So it is somewhere there? Just not returned with GetPurchasesAsync?
Btw with Non-Consumable InAppPurchases is no problems, they are returned after buying with GetPurchasesAsync, just not the subscriptions.

**Comment by TomQv** [comment]
> Checkout this blog -> https://corporate.accuweather.com/newsroom/blog/step-by-step-guide-for-ios-subscription-testing


> Sandbox Reliability
> 
> Developer Sandbox is famously unreliable. For some reason, Apple never addressed it or they may not understand the inconsistency. Either way, don’t get stressed if it doesn’t work all the time.

Is this the reason, why I don't see my subscriptions? I'm somehow stucked...

**Comment by TomQv** [comment]
I mean, how do I restore the users subscriptions on a new phone or after reinstalling the app, if `GetPurchasesAsync(ItemType.Subscription)` doesn't return, what he or she subscribed before?
Somehow this is my understanding, on how the InAppPurchasePlugin works, or did I miss something?

**Comment by jamesmontemagno** [comment]
It should return them... have you tried testing in TestFlight?

**Comment by TomQv** [comment]
Yes, its the same, Purchases are returned, Subscriptions not. But as said, its a new app, which is not yet approved. 
The funny thing is just, that the purchase procedure with `await _current.PurchaseAsync(productid, ItemType.Subscription);` seems to work, since it gives a success message, but where are they?

**Comment by jamesmontemagno** [comment]
I'll boot up another test project and give it a go and see what's up.

**Comment by TomQv** [comment]
> I'll boot up another test project and give it a go and see what's up.

Thank you )

**Comment by FranzSY** [comment]
Is there an update for this? Our team also having this issues

**Comment by jamesmontemagno** [comment]
Everything working perfect for me, i have documented updates and a sample reference https://gist.github.com/jamesmontemagno/e9502b7605f4068f644d3cfc5fe0f19f
