### ISSUE TITLE
PurchaseAsync and GetProductInfoAsync - productId does not exist

### ISSUE THREAD

**Issue by tklempay** [jamesmontemagno/InAppBillingPlugin#417]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 5.0.1.1, 4.2.0.1 (version used in Production)
Device Tested On: iPhone 6S Plus, iPhone 11 Pro Max, Samsung SM-S757BL
Simulator Tested On: n/a
Version of VS: Visual Studio 2019 16.11.2
Version of Xamarin:
Versions of other things you are using:

We have an app in both Apple and Google stores that has been using your IAB plugin for over a year.  We have a monthly and annual subscription that are working just fine in production today.  Let's call those "xxxx.elite.monthly" and "xxxx.elite.yearly".  We want to switch to a new annual-only subscription model with a new ProductID.  So I created new subscriptions for both Apple and Google with the new Product ID of "xxxx.pro.yearly".  Apple has already approved the subscription.

Here's my problem.  I'm in test mode for this new subscription and no matter what I do, an exception is thrown from IAB when I try to purchase a subscription via PurchaseAsync.  The error I get is "**xxxx.pro.yearly does not exist**".  This happens for both iOS and Android versions of our app.  If I query for subscription information via GetProductInfoAsync, I either get nothing back on Android or an exception on iOS.  

Since this is a new subscription, I thought, maybe I don't have something configured right on the Apple or Google subscription portals.  So I went back to test with our currently working Product IDs.  I get the exact same behavior, "**xxxx.elite.monthly does not exist**".

I have gone back to your instructions, sample code, the troubleshooting guide and listened to you and Frank talk about IAP on your podcasts.  Unfortunately, nothing has worked so far.  I am really, really, really stuck and any help is greatly appreciated!

**Comment by jamesmontemagno** [comment]
They both have to be turned on and ready to test. Unable to reproduce any issues in my apps sorry.
