### ISSUE TITLE
How to test Pending Transactions ?

### ISSUE THREAD

**Issue by jonathanfontaine** [jamesmontemagno/InAppBillingPlugin#419]
I'm using your very nice library to implement an **auto renewable subscription** in my app.

Everything is working as expected, but starting with version 4.X I must handle **Pending Transactions** from outside of my app.

So I have 2 questions :

1. **Do I have to handle Pending Transactions since I only have one non-consumable product ?**
[Google's official documentation](https://developer.android.com/google/play/billing/integrate#pending) notes: _"Additional forms of payment are not available for subscriptions purchases."_

2. **If yes, how could I test it ?**
People are talking about two additional payment methods, namely : 
    - _"Slow test card, approves after a few minutes"_ 
    - _"Slow test card, declines after a few minutes"_

    But I can't find them, I only have :
    - _"Test card, always approves"_
    - _"Test card, always declines"_

Some other people are also wondering what to do in this case, like here : https://stackoverflow.com/questions/68267492/google-play-billing-pending-purchases-not-available-for-subscriptions

**Comment by jamesmontemagno** [comment]
You will have to use License testing:
https://github.com/android/play-billing-samples/issues/199

https://developer.android.com/google/play/licensing/overview

It is a complicated annoying process :(
