### ISSUE TITLE
Untyped exceptions make it hard to validate user flow

### ISSUE THREAD

**Issue by bartdkmediahuis** [jamesmontemagno/InAppBillingPlugin#42]
Please fill out either the bug or feature request section and remove whatever section you are not using.

Version Number of Plugin:1.1.0.35-beta
Device Tested On: iPad

## Feature Request:
Please fill in what you would like

At this moment the library is throwing 2 untyped exceptions with a basic string.
- new Exception("Restore Transactions Failed")
- new Exception("Invalid Product")

In case we want to validate this type of exceptions we are forced to do some string-parsing. Is it possible to convert them to a more typed exception as you do with the "InAppBillingPurchaseException"

**Comment by CrewNerd** [comment]
Agreed - it's also confusing to return null to indicate a failure, when there are several different causes. Parameter validation is also needed on many of the public methods.
