### ISSUE TITLE
How to notify user that pending purchase was completed?

### ISSUE THREAD

**Issue by jasonfisherjlf** [jamesmontemagno/InAppBillingPlugin#425]
I am new to xamarin, but have most of your (absolutely wonderful) plugin working in my test app. The thing I can't figure out is how to write code that will notify the user of a pending purchase that completes/resolves while the app is running. The code for implementing this for OnStart() and OnResume() seems simple enough, but notifying the user while the app is already running is stumping me.

I can see that there is a "OnPurchasesUpdated" listener set up that I assume handles this, but I have no idea how to write code to utilize it in the event that such a notification does come though. How would you do this? I was thinking just a simple pop up to the user to notify them that their purchase is no longer pending would suffice.

**Comment by jasonfisherjlf** [comment]
I poked around some more and came across this comment by @jamesmontemagno: https://github.com/jamesmontemagno/InAppBillingPlugin/issues/384#issuecomment-838863875

Unfortunately, it doesn't make any sense to me how exactly I am supposed to use that listener. I am completely lost as to how to setup and assign the callback for that listener...

**Comment by jamesmontemagno** [comment]
See: https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/README.md#pending-transactions for example
