### ISSUE TITLE
Anomalous use of permissions com.android.vending.BILLING.

### ISSUE THREAD

**Issue by roswer13** [jamesmontemagno/InAppBillingPlugin#426]
Hello James! Google Play Store prompts me with the following message after launching my app in beta mode.

> Your app requests permissions that are used by less than 1% of apps with similar functionality:
> 
> **com.android.vending.BILLING.**
> 
> Users prefer apps that request fewer permissions. In fact, asking for unnecessary permissions can affect your app's visibility in the Play Store. If these permissions are not necessary, you may be able to use workarounds in your app and request fewer permissions. If they are necessary, we recommend that you add an explanation so that users understand why you need the permissions.
> 
> Note: This indication is based on a comparison with apps that have similar functions, but change over time as new and previously published apps are released. 

Attached is the [link with more information](https://developer.android.com/training/permissions/usage-notes).

Best regards.

**Comment by TomasHadraba** [comment]
Same here. It seems that it's shouldn't be [necessary some time](https://developer.android.com/google/play/billing/release-notes#release-1_0).

**Comment by SKeehnen** [comment]
Same issue here. Google is now actively communicating that you should [remove the permission](https://developer.android.com/google/play/billing/migrate#remove).

**Comment by SKeehnen** [comment]
I have found a workaround to remove the permission in your own app:
1) Open your AndroidManifest.xml
2) Add xmlns:tools="http://schemas.android.com/tools" within <manifest ......>
3) After the last <uses-permission ... /> add a new line with <uses-permission android:name="com.android.vending.BILLING" tools:node="remove" />
4) Rebuild and distribute your app

**Comment by jamesmontemagno** [comment]
Will push out 5.1.0-beta

**Comment by TomasHadraba** [comment]
Hi, I installed version 5.1.0, unfortunately it seems that it still requests "com.android.vending.BILLING" permission.

**Comment by jamesmontemagno** [comment]
Double check your code to make sure you didn't add it in there somewhere

**Comment by jamesmontemagno** [comment]
Well actually read what you linked to:

Embedded billing permission inside library’s manifest. It's not necessary to add the com.android.vending.BILLING permission inside Android manifest anymore.

Google embed this permission into it for you so it will always be there.

**Comment by TomasHadraba** [comment]
You are right. Problem will be somewhere else. When I install version 5.1 into new project, it works correctly (without com.android.vending.BILLING permission).
However when I firstly Install  4.0.2 and then update it, permission is still required. I tried uninstall 4.0.2, then install 5.1, clean project, delete NuGet package, remove NuGet cache...nothing works :-(
