### ISSUE TITLE
[Android] InApp Purchases - Method not found: string Android.BillingClient.Api.Purchase.get_Sku()

### ISSUE THREAD

**Issue by Yannick315** [jamesmontemagno/InAppBillingPlugin#429]
I am currently in the process of realizing a not consumable in-app purchase.

At first I had problems with the parameters of the "PurchaseAsync" function.
In all instructions, the function is given three parameters: (Productid, itemtype, payload)

In all examples the parameter "payload" is given as a string.
For me, the function expects a variable with the data type: IInAppBillingVerifyPurchase

After completely omitting this parameter, I was able to make a payment.

After this line:
var purchase = await billing.PurchaseAsync (productId, itemType.InAppPurchase);

the Google dialog appears so that you can pay and "payment successful" appears.
The program then jumps to the catch and the following error message appears:
{System.MissingMethodException: Method not found: string Android.BillingClient.Api.Purchase.get_Sku () 

Unfortunately I can't find a function like "getsku".

- I use a physical device
- The app is uploaded as a signed bundle in the Playstore as an alpha test
- The user is registered as a test user 

Does anyone have any ideas?

Thanks in advance.

Kind regards
Yannick 

### Code snippet

        // Start Level 1
        async void Lvl1Click(object sender, EventArgs args)
        {

            var productId = "mysku";
            var billing = CrossInAppBilling.Current;
            billing.InTestingMode = true;
            try
            {
                var connected = await billing.ConnectAsync();
                if (!connected)
                {
                    await App.Current.MainPage.DisplayAlert("Warning", "No Connection to the Store", "OK");
                    return;
                }

                 var test = await billing.GetPurchasesAsync(ItemType.InAppPurchase);
                var purchase = await billing.PurchaseAsync(productId, ItemType.InAppPurchase);
                

                if (purchase == null)
                {
                    await App.Current.MainPage.DisplayAlert("Warning", "Not purchased", "OK");
                }
                else
                {
                    await App.Current.MainPage.DisplayAlert("Success", "Succesfully purchased", "OK");
                }
            }
            catch (InAppBillingPurchaseException purchaseEx)
            {
                var message = string.Empty;
                switch (purchaseEx.PurchaseError)
                {
                    case PurchaseError.AppStoreUnavailable:
                        message = "Currently the app store seems to be unavailble. Try again later.";
                        break;
                    case PurchaseError.BillingUnavailable:
                        message = "Billing seems to be unavailable, please try again later.";
                        break;
                    case PurchaseError.PaymentInvalid:
                        message = "Payment seems to be invalid, please try again.";
                        break;
                    case PurchaseError.PaymentNotAllowed:
                        message = "Payment does not seem to be enabled/allowed, please try again.";
                        break;
                    case PurchaseError.AlreadyOwned:
                        message = "You already own the Item you request";
                        break;
                }
                //Billing Exception handle this based on the type
                await App.Current.MainPage.DisplayAlert("Warning", message, "OK");
            }

            catch (Exception ex)
            {
                //Something else has gone wrong, log it
                await App.Current.MainPage.DisplayAlert("Warning", "normal Exception" + ex, "OK");
            }
            finally
            {
                await billing.DisconnectAsync();

            } 
       }

**Comment by Yannick315** [comment]
Additional information:

After paying with the test card, I also get an email from Google Play "Test: Your Google Play Order Receipt from ...". Shortly afterwards I get an email "Test: Your Google Play Order Cancellation Receipt from ..." (This test purchase was canceled because it was not acknowledged)

If I press Buy Button in my App again, the PurchaseException "Already owned" appears.

**Comment by jamesmontemagno** [comment]
What version of the plugin are you using?

Also do you have the link skip in -> https://github.com/jamesmontemagno/InAppBillingPlugin#version-4-linker-settings

**Comment by Yannick315** [comment]
Hello James,

many thanks for your response.

I am using your plugin in version 4.0.2. (Latest version available)

You can see a photo of my references attached.

I haven't implemented anything in my app on the subject of "AcknowledgePurchase" and "Pending Transactions".
So far not relevant, because my code throws an exception when I buy it.

The code that I inserted in the post above is all of my code related to the plugin.
Is it possible that something is still missing?

Here are my "using" directives: 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Input;
using System.IO;
using Xamarin.Forms;
using Xamarin.Forms.Xaml;
using Plugin.InAppBilling;

Here again the entire error message: (if that helps) 

{System.MissingMethodException: Method not found: string Android.BillingClient.Api.Purchase.get_Sku()
  at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate, System.Boolean& found) [0x0003f] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.Linq/src/System/Linq/First.cs:94 
  at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.Linq/src/System/Linq/First.cs:37 
  at Plugin.InAppBilling.InAppBillingImplementation.PurchaseAsync (System.String productSku, System.String itemType, Plugin.InAppBilling.IInAppBillingVerifyPurchase verifyPurchase) [0x001c8] in D:\a\1\s\src\Plugin.InAppBilling\InAppBilling.android.cs:255 
  at Plugin.InAppBilling.InAppBillingImplementation.PurchaseAsync (System.String productId, Plugin.InAppBilling.ItemType itemType, Plugin.InAppBilling.IInAppBillingVerifyPurchase verifyPurchase) [0x00099] in D:\a\1\s\src\Plugin.InAppBilling\InAppBilling.android.cs:216 
  at Shot.Level.Lvl1Click (System.Object sender, System.EventArgs args) [0x001ee] in C:\Users\Yannick\******\Level.xaml.cs:86 }

Thanks in advance.

Kind regards
Yannick

![Links](https://user-images.githubusercontent.com/96125513/146322686-4c8e60f0-43fd-43f2-8c00-845dfb2db423.png)

**Comment by jamesmontemagno** [comment]
What are your project linker settings for release?

If you have it on "ALL" then you need to link skip the assembly https://github.com/jamesmontemagno/InAppBillingPlugin#version-4-linker-settings

**Comment by Yannick315** [comment]
I hope we mean the same now, because there is no selection with "ALL" for me.

Right click on the Android project -> Properties -> Android Options (for Release) -> Linker Properties -> Links

It is currently set to "None".
If I switch to "SDK assemblies only" or to "SDK and user assemblies", I can no longer compile the project.
The following error message appears:

Error Mono.Linker.MarkException: Error processing method: 'Plugin.InAppBilling.InAppBillingPurchase Plugin.InAppBilling.Converters::ToIABPurchase(Android.BillingClient.Api.Purchase)' in assembly: 'Plugin.InAppBilling.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.String Android.BillingClient.Api.Purchase::get_Sku()
   bei Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   bei Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   bei Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   bei Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   bei Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   bei Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of internal exception stack monitoring ---
   bei Mono.Linker.Steps.MarkStep.ProcessQueue()
   bei Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   bei Mono.Linker.Steps.MarkStep.Process()
   bei Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   bei MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   bei Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   bei Mono.Linker.Pipeline.Process(LinkContext context)
   bei MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   bei Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   bei Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   bei Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/builder/azdo/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:Zeile 17.	Shot.Android

In the link you sent me (https://github.com/jamesmontemagno/InAppBillingPlugin#version-4-linker-settings)
I don't quite understand where to add this?
"Plugin.InAppBilling; Xamarin.Android.Google.BillingClient"

**Comment by jamesmontemagno** [comment]
Make sure all of your NuGets are on the same version or uninstall and re-install

Also make sure you are compiling against Android 10 or higher as well.

For release of an application you must change the linker setting to "Link SDK Assemblies" don't leave it as None as the entire runtime and sdk will be bundled and your app will be huge.

You can set the link skip like this -> https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker#linkskip

**Comment by Yannick315** [comment]
- All NuGets are on the latest stabable Version
- I compile on Android 10

When I switched to "Link SDK Assemblies", I got a lot of error messages at first. After reinstalling NuGets several times, the errors disappeared.

Now when I want to make a purchase it works.

Thank you very much James!
