### ISSUE TITLE
Get transactionReceipt for iOS old receipt validation service 

### ISSUE THREAD

**Issue by Annelies1** [jamesmontemagno/InAppBillingPlugin#43]
Hi,

In our app, the back-end validates the transaction receipt for iOS. The back-end unfortunately wasn't updated for several years, so it can only handle the transactionReceipt from SKPaymentTransaction. Is there a way to get that property from the PurchaseAsync method? 
Thanks in advance!

regards,
Annelies

**Comment by jamesmontemagno** [comment]
When you implement IInAppBillingVerifyPurchase  and pass it in, you will get

  var receiptUrl = NSData.FromUrl(NSBundle.MainBundle.AppStoreReceiptUrl);
            string receipt = receiptUrl.GetBase64EncodedString(NSDataBase64EncodingOptions.None);

            return verifyPurchase.VerifyPurchase(receipt, string.Empty, productId, transactionId);

**Comment by Annelies1** [comment]
Hi James, 

Thanks for your response. I added the Verify purchase method in my code and see that it gives me a receipt with all transactions ever done.
I will need the deprecated transactionReceipt of skpaymenttransaction. https://developer.apple.com/reference/storekit/skpaymenttransaction/1617722-transactionreceipt?language=objc
Is there any way to get that one? Thanks in advance!

regards,
Annelies

**Comment by jamesmontemagno** [comment]
You should probably fork the repo and customize it to your liking as it is deprecated now so I will not add it in.

**Comment by Annelies1** [comment]
Ok, thanks. Now i know what to do.
