### ISSUE TITLE
After a Subscription purchase, should AutoRenewing show as false?

### ISSUE THREAD

**Issue by rezamohamed** [jamesmontemagno/InAppBillingPlugin#437]
I have setup an Auto-Renewing subscription in Apple Connect and using InAppPurchase with ItemType.Subscription. The purchased item returned always show AutoRenewing=False, is this correct?

![Purchase Subscription](https://user-images.githubusercontent.com/18199852/149550421-8297a395-6263-4e6c-9d9d-ed6ac1ae7513.jpeg)

Further, I am noticing that there is really no proper way to check Subscription Status short of checking GetPurchasesAsync on App Start (because of cancels/refunds etc) - given all the Issues submitted for this here. Is this the approach to take?

**Comment by jamesmontemagno** [comment]
I return info from Apple directly and they do not return if it is auto renewing -> https://developer.apple.com/documentation/storekit/SKPaymentTransaction

You can see here they give you extremely little information -> https://github.com/jamesmontemagno/InAppBillingPlugin/blob/9f0cec772c0b0d165e5a3e437ec85e8e68f29e17/src/Plugin.InAppBilling/InAppBilling.apple.cs#L502

I would read the apple documentation to figure out what is best to do.

You could check so often for a valid subscription. Your app should track (or better a backend) when a subscription expires and when they need to re-new or if it has auto-renewed.

**Comment by rezamohamed** [comment]
@jamesmontemagno Thanks for that. I guess I am looking for some direction on what a best-case scenario would look like. Currently, when I run a GetPurchasesAsync, I get an iteration of the below (sandbox test user with renewal set to 5mins and cancellation after 12 renewals)

![purchase renewal](https://user-images.githubusercontent.com/18199852/149564456-6ddd483b-814b-4ae4-b584-348c6f1729f9.jpg)

So the PurchaseDate is the only thing to go off of. Ideally, I don't want to ping the Apple server each time the app is launched or resumed, but I feel I have no other way of checking regardless of if I have some backend server information. Assuming, purchase made, save the purchase date and expiration date to my server backend - but I still need to check each time the app is launched if the sub was canceled/refunded.

Am I overthinking this or missing something?

**Comment by jamesmontemagno** [comment]
There is no cancelled. I am pretty sure that if they cancel it they can't get a partial refund of a subscription so you don't have to handle that at all. If they purchased it basically unlock it for the timespan that you need and check again for a new renewal later on.

https://www.revenuecat.com/blog/the-ultimate-guide-to-subscription-testing-on-ios is a great guide.

Also see https://codeburst.io/how-to-implement-auto-renewable-subscriptions-for-ios-application-using-react-native-3f9b4df22fd2 which is very short and sweet:


```
The important thing here is that restorePurchases function returns all user purchases, even expired ones, and Apple doesn’t promises that latest one in purchases array will be the newest by transactionDate. So, we need to sort purchases in array by transactionDate (you may use simple array.sort() function for this purposes) and take the purchase with the newest transactionDate.
After that we send receipt transactionReceipt to the server API endpoint (because we need to handle purchase event on the backend side) where receipt is validated and processed.
One of important things to do to make your mobile application more secure is to validate receipts.
There are 2 approaches how to do it: client side and backend side. We used backend side validation. There are 2 endpoints provided for receipts validation:
• https://sandbox.itunes.apple.com/verifyReceipt
• https://buy.itunes.apple.com/verifyReceipt
Use the first one for development and testing purposes and don’t forget to change it to the second one when app will be released to production ;)
Refer to the Apple Developers Documentation for more details.
```

**Comment by vandenbrakel** [comment]
Yes this. It's been asked a lot here including by myself. Take the last approach. Get the token form the last purchase (subscription) using sorting by date.  I've posted an example in another issue. Then take the purchaseToken from that and throw it in the API. It will return a full json with information you can use. 

I'll post examples asap when behind my screen again.

**Comment by jamesmontemagno** [comment]
@vandenbrakel  if you want to add into the documentation at all feel free to do that :)

**Comment by rezamohamed** [comment]
@jamesmontemagno I should have clarified what I meant by canceled/refund...I explicitly meant refund - a user can request a refund by going to (for apple) https://reportaproblem.apple.com/ (haven't explored google yet) which will refund the money, and technically the app subscription should be canceled at that point. In that case, I am trying to figure out how we would get this info. A user could purchase an Annual subscription and then request a refund, but if I don't know that happened somehow then I won't be able to update the backend db and therefore the user would technically have access for the full year.

@vandenbrakel that would be awesome. I am particularly curious about what you mean by testing against the API. Patiently waiting :-)

**Comment by jamesmontemagno** [comment]
You need to do receipt validation then -> https://stackoverflow.com/questions/6439482/how-does-apple-notify-ios-apps-of-refunds-of-in-app-purchases-iap handles this well


https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html#//apple_ref/doc/uid/TP40010573-CH106-SW19

also 

https://developer.apple.com/documentation/storekit/original_api_for_in-app_purchase/handling_refund_notifications

**Comment by rezamohamed** [comment]
> Yes this. It's been asked a lot here including by myself. Take the last approach. Get the token form the last purchase (subscription) using sorting by date. I've posted an example in another issue. Then take the purchaseToken from that and throw it in the API. It will return a full json with information you can use.
> 
> I'll post examples asap when behind my screen again.

@vandenbrakel did you get a chance to put your code in a repo or something to share? thanks!

**Comment by jamesmontemagno** [comment]
See my sub sample here on how to handle 100% in app renewsals and restores: https://gist.github.com/jamesmontemagno/e9502b7605f4068f644d3cfc5fe0f19f

There is no built in api for seeing if things are canceled, you have to do it via the api
