### ISSUE TITLE
Plugin.InAppBillingPurchaseState.FreeTrial state is never received on Subscription testing

### ISSUE THREAD

**Issue by sergepenkin** [jamesmontemagno/InAppBillingPlugin#442]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information
Plugin.InAppBillingPurchaseState.FreeTrial state is never received on Subscription testing

Version Number of Plugin: 5.1.1 beta
Device Tested On: Android 11 Samsung t295 
Simulator Tested On:
Version of VS:  2019 last
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior
The Subscription  has 3 days trial, under testing account it seems to be 3 mins
Is any way  i am testing Subscription Purchase on a real device and testing account  FreeTrial state is never received

### Expected Behavior
Looking and classic approach without any "bad" users
It seems that once the user puschased a Subscription  - the first state shold be FreeTrial  for all trial perion 
( 3 mins for test account and specified for real acccounts ) then - Pending ( Pending Payment) for a short time and then - Purchased 

### Actual Behavior
State is always Purchased 

### Code snippet
none
### Screenshotst
none

**Comment by sergepenkin** [comment]
As says 
https://support.google.com/googleplay/android-developer/answer/140504?hl=en#free&zippy=%2Cfree-trials

How users start a free trial
To start a free trial, a user completes the standard process for purchasing a subscription on Google Play. They aren’t charged at first because the initial period is included with the free trial, and they’re notified by email that the subscription includes a free trial period. Google Play records a transaction of $0.00, and the subscription is marked as purchased for the trial period or until its canceled.

The day after the trial period ends, a user’s payment method is charged for the full subscription amount, which recurs using the subscription’s set time period. The payment status may display as pending for up to 24 hours, even if no [grace period](https://support.google.com/googleplay/android-developer/answer/140504?hl=en#grace) is set.

Note: If a user cancels a subscription at any time during the trial period, the subscription remains active until the end of the trial, and they won’t be charged.

**Comment by sergepenkin** [comment]
Also some infor about Subscription payment states
https://stackoverflow.com/questions/61520605/google-purchases-subscriptions-api-what-does-paymentstate-null-means

**Comment by sergepenkin** [comment]
Hello! Thank you for quick reply!
As far as i see here https://stackoverflow.com/questions/40866990/how-to-check-is-transaction-free-trial-in-android-subscription
I should be enough to add some API method like GetPaymentState 
**OriginalJson** does not contain PaymentState info... in case it should be requested from stores additionally

**Comment by sergepenkin** [comment]
Also AcknowledgePurchaseAsync documentation  should be corrected (including code samle)- AcknowledgePurchaseAsync  should be called within Subsciption trial period but not within 3 days ( period may take longer than 3 days ) 
Correct me please if i am wrong

**Comment by jamesmontemagno** [comment]
I am not sure about the free trial period, would have to read the documentation on that, but yeah you only need to call if IsAcknowledged is false.

**Comment by jamesmontemagno** [comment]
https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptions  this is from the REST API... not the Android API. You need to call it from your backend or from your app.

**Comment by davidbuckleyni** [comment]
Correct me if am wrong but on ios at lest a free trail still goes thru as a purchased item of £0.00 or $0.00. The user still gets a receipt for their free trail purchase I believe purchased is correct here ?

**Comment by jamesmontemagno** [comment]
I think so.... I think you just need to test it out and see what happens on each platform. My assumption is that it will return an active subscription on Android and on iOS what you said David also is valid. I just don't think you can determine if it was on a free trial or not. A safe bet is to make the free trial the same length of your subscription ;) like 1 month free! lol

https://developer.apple.com/documentation/storekit/original_api_for_in-app_purchase/subscriptions_and_offers/implementing_introductory_offers_in_your_app

**Comment by jamesmontemagno** [comment]
Going to close this out as this information comes from the backend and no public API for me to expose to do this.

**Comment by sergepenkin** [comment]
Hello @jamesmontemagno !
i agree that IAP Item PurchaseState and PaymentState are not the same things
But look here please ..
https://stackoverflow.com/questions/61520605/google-purchases-subscriptions-api-what-does-paymentstate-null-means
I think that at least it would be a good thing to expand current plugin withe additioanl method to recreive Purchase/Subscribtion Payment State - that will be enough and it is neccesary to have for development for some cases

**Comment by sergepenkin** [comment]
> https://stackoverflow.com/questions/40866990/how-to-check-is-transaction-free-trial-in-android-subscription
here even code sample to retreivce Item/Subscription PaymentState
 https://stackoverflow.com/questions/40866990/how-to-check-is-transaction-free-trial-in-android-subscription

**Comment by jamesmontemagno** [comment]
Yes, but this is to call the Google API, which should be done in receipt validation. I am not going to call iOS/Android rest backend calls as that is very messy and needs configuration from the developer. I do provide this information back so you can make those calls to your backend.

**Comment by sergepenkin** [comment]
Ок - that you should remove FreeTrial PurchaseState from plugin - it makes developers confusing

**Comment by jamesmontemagno** [comment]
Done!
