### ISSUE TITLE
It is impossible to get Subscription Length

### ISSUE THREAD

**Issue by Dizmus** [jamesmontemagno/InAppBillingPlugin#445]
Hello,

Currently, it is impossible to get length of subscription using CrossInAppBilling.

Can we have this feature implemented? According to documentation, it is possible using native libraries

Thanks

**Comment by jamesmontemagno** [comment]
That is fixed in -> https://github.com/jamesmontemagno/InAppBillingPlugin/pull/443

**Comment by Dizmus** [comment]
> That is fixed in -> #443

Can you please help, how can I get the length of subscription? I can see length of Trial and Introductory offer, but can't find the subscription length itself

**Comment by jamesmontemagno** [comment]
You can see that I am adding this information here to the product information:
https://github.com/jamesmontemagno/InAppBillingPlugin/blob/productdiscounts/src/Plugin.InAppBilling/Shared/InAppBillingProduct.shared.cs

iOS give you # of periods and a time period (day/week/month/year). 

Android gives you back a string which is specified in ISO 8601 format. For example, P1W equates to one week, P1M equates to one month, P3M equates to three months, P6M equates to six months, and P1Y equates to one year.

My recommendation is that you just hardcode the lengths based on what you are creating them as in the portals. You already know ahead of time that it is 1 month or 1 year based on when you setup the sku and they can't change, so just put them in the app.

**Comment by jamesmontemagno** [comment]
you can grab 5.3.0-beta or 6.3.0-beta to test it out

**Comment by Dizmus** [comment]
Hey @jamesmontemagno , 

Thank you for your answer. Sorry for long reply from my side. 

I am from Ukraine, was a bit busy.

I can see now Trial and Subscription length with beta releases. 

Now I am trying to figure out whether subscription is in Trial state. Previously state had TrialOffer value, it doesn't. 

Was there any change in Android core itself?

Thanks for your help, dude!

**Comment by jamesmontemagno** [comment]
You can get the trial offer status from the REST api, not from the android api directly
