### ISSUE TITLE
Delayed Purchase Response

### ISSUE THREAD

**Issue by Erdogan34** [jamesmontemagno/InAppBillingPlugin#449]
Hi,

When I tap the purchase button in testflight mode, response delays about 30 seconds. Is this about the plugin or testflight mode?

**Comment by Erdogan34** [comment]
Yes, UI takes 30 seconds to pop up, sometimes more. I'll post the result here after publish the app.

**Comment by TechnikKTK** [comment]
Hi. Tell me, will there be any delays in production?

**Comment by jamesmontemagno** [comment]
Closing as not reproducable and not an issue from what I have seen
