### ISSUE TITLE
Is there a simplified version of OnShouldAddStorePayment ?

### ISSUE THREAD

**Issue by softlion** [jamesmontemagno/InAppBillingPlugin#451]
On iOS, when a subscription is automatically renewed, OnShouldAddStorePayment is called on next app startup:

```c#
Plugin.InAppBilling.InAppBillingImplementation.OnShouldAddStorePayment = OnShouldAddStorePayment;
``` 

This method has the following signature:
```c#
bool OnShouldAddStorePayment(SKPaymentQueue queue, SKPayment payment, SKProduct product)
``` 

Is there a simplified version or a method call that can convert this payment/product pair into an InAppBillingPurchase object ?

Ty !

## Information

Version Number of Plugin: 5.3.1-beta
Device Tested On: iOS

**Comment by softlion** [comment]
Ok public static InAppBillingPurchase ToIABPurchase(this SKPaymentTransaction transaction)

**Comment by jamesmontemagno** [comment]
I am propagating the event from Apple -> https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/src/Plugin.InAppBilling/InAppBilling.apple.cs#L556-L557

https://developer.apple.com/documentation/storekit/skpaymenttransactionobserver/2877502-paymentqueue
