### ISSUE TITLE
Expose the country of the store

### ISSUE THREAD

**Issue by softlion** [jamesmontemagno/InAppBillingPlugin#452]
For legal reasons, some products can not be exposed to some countries.

Could you expose the country code of the store ?

for ios:
`SKPaymentQueue.Default.Storefront?.CountryCode`

for the other platforms i don't know.
ty !

**Comment by jamesmontemagno** [comment]
Exposing a "storefront" property you can get.

If on iOS 13+ it will return a valid value, else null.
