### ISSUE TITLE
ConsumePurchaseAsync always fails on iOS

### ISSUE THREAD

**Issue by softlion** [jamesmontemagno/InAppBillingPlugin#453]
Hello !
The doc states that to consume a consumable you should call:

`await billing.ConsumePurchaseAsync(purchase.ProductId, purchase.PurchaseToken)`

But that always fails. There is an error in InAppBilling.apple.cs line 421 which calls:

`FinishTransaction(purchaseToken);`

Instead it should call FinishTransaction with the purchase id, not the purchase token (which is a base64 ticket).

Workaround: don't call ConsumePurchaseAsync, instead call:

`await billing.FinishTransaction(purchase.Id)`

Platform:  iOS 15 real device

**Comment by Hobbit7** [comment]
Is it necessary to consume a purchase on iOS? I thought that you only need to call ConsumePurchaseAsync/AcknowledgePurchaseAsync on Android to acknowledge the purchase.

**Comment by softlion** [comment]
Well, when a user buy a consumable, he can consumes it when he needs it. Otherwise it stays "unused" and can be refund by Apple. Your iOS code already provides this feature. In a curious way (ie: restoring purchases), but it's ok.

**Comment by jamesmontemagno** [comment]
What version of the plugin are you using?

I am still working through code changes in the most recent versions where you have to call ConsumeAsync to consume it. Previously it was auto-consumed on iOS.

**Comment by jamesmontemagno** [comment]
You should call it like this on iOS:

```csharp
await billing.ConsumePurchaseAsync(purchase.ProductId, purchase.Id);
```

On Android you need to call it with the PurchaseToken.

**Comment by jamesmontemagno** [comment]
Next version (out today) will now take in the purchase token and the purchase id and also a list of ids that you don't want to auto finish... if you have multiple consumables you would wnat to pass in a list of all of them except the one you want to consume.

**Comment by softlion** [comment]
> What version of the plugin are you using?

5.3.1-beta

**Comment by jamesmontemagno** [comment]
5.3.2-beta will fix this up for you and has new parameters.

**Comment by jamesmontemagno** [comment]
There is no Acknowledged API at all for iOS as you don't have to acknowledge it. 

If you have a consumable in 4.0.2 it will auto finish/consume it on iOS when the purchase is success. The changes coming in 5.3.2 and 6.3.2 will allow you to opt out of that auto finish if you desire.

Android you have to acknowedge all purchases (consumables are acknowledge when you consume them)
