### ISSUE TITLE
system.notimplementedexception: This functionality is not implemented in the portable version of this assembly. 

### ISSUE THREAD

**Issue by b-nishitgupta** [jamesmontemagno/InAppBillingPlugin#454]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information
I have implemented InAppBilling plugin v4 and it is working fine in iOS but in Android I am getting "system.notimplementedexception: This functionality is not implemented in the portable version of this assembly." error. I have the plugin installed in my Android and iOS specific projects and tried with target versions Android 7,8.1,10 & 11 but no luck. @jamesmontemagno  Could you please help me in this regard?
Version Number of Plugin: 4.0
Device Tested On: Android
Simulator Tested On:
Version of VS: 
Version of Xamarin: Xamarin.mac: v8.0
Xamarin.iOS: v15.0
Xamarin.Android: v12.0
Versions of other things you are using:

### Steps to reproduce the Behavior
Implement the InAppBilling code and test it on Android devices.

### Expected Behavior
Should open the InAppBilling popup for Android

### Actual Behavior
The pop up is not opening and throwing an error

### Screenshots
![6bd99498-f8fb-486b-b02f-7a3da04c314d](https://user-images.githubusercontent.com/101477232/158032763-044e0e2d-5cc6-4bf6-ab9d-39df7cc01b56.jpg)

**Comment by jamesmontemagno** [comment]
What are you "Compiling" it against on Android?  You must have it set to COMPILE against Android 10+.

Can you send me a sample project?

**Comment by b-nishitgupta** [comment]
@jamesmontemagno Thank you for your quick response, I tried changing the compile against Android 10+ and it started working.
Also, is there any method or a way to check the purchases in this plugin like getPurchases(); ?

**Comment by jamesmontemagno** [comment]
Yes, see documentation: https://jamesmontemagno.github.io/InAppBillingPlugin/CheckAndRestorePurchases.html
