### ISSUE TITLE
Is it possible to send any custom ID for apple/google stores?

### ISSUE THREAD

**Issue by ederjbezerra** [jamesmontemagno/InAppBillingPlugin#455]
For those whom have a logic that allows users to enjoy the app contents at any device/platform, would be very helpful if we could pass some user id or email and receive that info in the payloads of webhooks, and take some action for that specific Id. Is it possible? I'm afraid after the purchase, the device's internet signal could be lost and I cant complete the tasks at server side.

**Comment by jamesmontemagno** [comment]
You would call the get purchases method and get past purchases. Devs dont' have direct access to that information. I suggest reading through the apple/google/microsoft docs to better understand how IAPs work from their end.
