### ISSUE TITLE
billing.GetProductInfoAsync() Stopped working

### ISSUE THREAD

**Issue by PonyOny** [jamesmontemagno/InAppBillingPlugin#457]
## Bug Information

Version Number of Plugin: 4.0.2
Device Tested On: Multiple iOs devices ( iPhone X, iPhone 12, iPhone 7)
Version of VS: 2022
Version of Xamarin: 5.0.0.2337
Versions of other things you are using:

### Steps to reproduce the Behavior
billing.GetProductInfoAsync() was working properly returning all my product id information, it just stopped working, I have debugged locally and I observe it is always returning now "Plugin.InAppBilling.PurchaseError.ProductRequestFailed" this is happening Locally, Sandbox and Production.

### Expected Behavior
It should return the product information regarding the id's of IAP as it was doing.

### Actual Behavior
It throws and excepcion "Plugin.InAppBilling.PurchaseError.ProductRequestFailed"

**Comment by dennisstromberg** [comment]
I did get the same error in the pre-releases, when I downgraded to stable did it work again.

**Comment by PonyOny** [comment]
I'm using a stable version, it has been working for some months, I have just noticed it has just stopped working.

**Comment by PonyOny** [comment]
I have just tested it again now on Production and it seems to be working again, it may be something todo with Apple.

**Comment by broda02** [comment]
https://www.macrumors.com/2022/03/21/icloud-and-apple-services-down/

**Comment by PonyOny** [comment]
Closing the issue because this probably was something to do with Apple having some problems with their services as @broda02 mentioned on the upper response, it is currently working as expected.
