### ISSUE TITLE
Unable to process purchase

### ISSUE THREAD

**Issue by iknowcodesoup** [jamesmontemagno/InAppBillingPlugin#458]
So, it appears to be something that I have uniquely wrong; seeing as no one else is reporting it as widely or at all.

The short version is that I have personally purchased my own products without any issue using both test cards and my own credit card.

All seems to work fine. However, I am getting loads of the 'Unable to process purchase' errors below from the logs.

I know there are issues with trying to run in an emulator so I have tried to treat them as ignorable errors from test devices that occur during the deployment cycle.

My code, however, has exception handling such as:
```
    catch (InAppBillingPurchaseException ex)
      {
        _ = await Application.Current.MainPage.DisplayAlert(
          AppStrings.Error,
          ex.PurchaseError.ToString(), // for brevity and laziness for now (:
          AppStrings.Okay,
          AppStrings.Close
          );

        this.Log().Error(ex, $"purchaseException:{productId} - { ex.PurchaseError}");
      }
```

Only recently activated IAP on iOS and do not have any reports there (yet?)

## Bug Information

Version Number of Plugin: **4.0.2** tried **5.x-beta**
Device Tested On: **Android 10, 11, iOS 12-15**
Simulator Tested On: **N/A**
Version of VS: **2019**
Version of Xamarin: **5.0.0.2337**
Versions of other things you are using:
AndroidX (LifeCycle) 2.4.02

### Steps to reproduce the Behavior
Not sure. Both PurchaseAsync, GetPurchasesAsync

### Expected Behavior
No exceptions

### Actual Behavior
Exceptions _only_ in production on other devices all over the world (at least the device info shows multiple countries).

### Code snippet

```
Plugin.InAppBilling
InAppBillingImplementation.ParseBillingResult (Android.BillingClient.Api.BillingResult result)
Plugin.InAppBilling
InAppBillingImplementation.PurchaseAsync (System.String productSku, System.String itemType, Plugin.InAppBilling.IInAppBillingVerifyPurchase verifyPurchase)
Plugin.InAppBilling
InAppBillingImplementation.PurchaseAsync (System.String productId, Plugin.InAppBilling.ItemType itemType, Plugin.InAppBilling.IInAppBillingVerifyPurchase verifyPurchase)
BurnCalc.Data.InAppPurchasing
InAppBillingAdapter.PurchaseProduct (System.String productId, System.Boolean isSubscription)

```

### Screenshotst

Note the ones showing 'Unable to process purchase' that again occurs on both purchase and get IAPs.
![image](https://user-images.githubusercontent.com/1696764/159969324-47d38e77-7114-4c6a-8002-6d966809cf71.png)
![image](https://user-images.githubusercontent.com/1696764/159974521-4214a426-5b8f-467a-84df-ef14b4f10d59.png)

**Comment by CleverSoftwarePoland** [comment]
I have the same problem on production.
All Android versions all possible devices.

**Comment by CleverSoftwarePoland** [comment]
@iknowcodesoup i will add more data logs to production code and try to trace exactly what is wrong.

**Comment by CleverSoftwarePoland** [comment]
@iknowcodesoup after submitting update with additional data logging, i can see it throws error but it's error with message "User cancelled.", but i need few more days to check out exact details.

**Comment by iknowcodesoup** [comment]
@CleverSoftwarePoland Interesting result. Is this from compiling locally and breaking or full stack trace from the plugin? Meaning it shows a deeper / nested exception? As I only have gotten user cancelled from cancelling the payment workflow as expected.

**Comment by TechnikKTK** [comment]
hi, i get exception by using this plugin when i use this code on ios on simulator:
path: src\Plugin\InAppBilling\InAppBilling.Aplle.cs row 128 (UNKNOW_ERROR).

this my code:
 var products = await CrossInAppBilling.Current.GetProductInfoAsync(ItemType.InAppPurchase, new string[] { id });
                if (products != null)
                {
                    if (products.Count() > 0)
                    {
                        var product = products.First();
                        var result = await Shell.Current.DisplayAlert("Стиль Полли", $"Вы собираетесь купить {product.Name}({product.Description}) за {product.LocalizedPrice}р.", "Продолжить", "Отмена").ConfigureAwait(true);

                        string d = ";";
                        if (result)
                        {
                            var purchase = await CrossInAppBilling.Current.PurchaseAsync(product.ProductId, ItemType.InAppPurchase,this); **//this Exception after enter appleID (sandbox) and password**

                            if (purchase == null)
                            {
                                Device.BeginInvokeOnMainThread(async () => await Shell.Current.DisplayAlert("Стиль Полли", "Нечего покупать", "OK"));
                                success = false;
                            }
                            else
                            {
                                var pid = purchase.Id;
                                var token = purchase.PurchaseToken;
                                var state = purchase.State;

                                if (!purchase.IsAcknowledged && Device.RuntimePlatform == Device.Android)
                                    await CrossInAppBilling.Current.AcknowledgePurchaseAsync(purchase.PurchaseToken);

                                result = await Shell.Current.DisplayAlert("Стиль Полли", $"Код покупки {pid}, Статус {state}", "Продолжить", "Отмена");


                                success = await CrossInAppBilling.Current.FinishTransaction(purchase);

                                if (success)
                                    await Shell.Current.DisplayAlert(string.Empty, "Поздравляем, вы купили наш журнал", "OK");
                            }
                        }
                    }
                }

**Comment by jamesmontemagno** [comment]
Have you tried it on a device with a sandbox account? Simulators aren't super reliable.

**Comment by TechnikKTK** [comment]
Hi, yes it is. Thanks, by write this package. But i need help:
Why app get input appleID & passwd always?
How change production mode?  ( CrossInAppBilling.Current.InTestingMode = false? )
Should i delete testing account by appstoreconnect when i real pay needed?

Thanks.

**Comment by iknowcodesoup** [comment]
For the original concern - my way of trying to determine why dozens of devices from multiple countries are reporting the error is to change one of my devices to that country / store and attempt a live purchase. At the least, to ease concerns if successful. Would like to find the time this week.

**Comment by jamesmontemagno** [comment]
@iknowcodesoup you are just popping up an exception in all cases which can happen for many reasons...

here is what I do:

```csharp
catch (InAppBillingPurchaseException purchaseEx)
            {
                var message = string.Empty;
                switch (purchaseEx.PurchaseError)
                {
                    case PurchaseError.AppStoreUnavailable:
                        message = "Currently the app store seems to be unavailble. Try again later.";
                        break;
                    case PurchaseError.BillingUnavailable:
                        message = "Billing seems to be unavailable, please try again later.";
                        break;
                    case PurchaseError.PaymentInvalid:
                        message = "Payment seems to be invalid, please try again.";
                        break;
                    case PurchaseError.PaymentNotAllowed:
                        message = "Payment does not seem to be enabled/allowed, please try again.";
                        break;
                    case PurchaseError.UserCancelled:
                        break;
                    default:
                        message = "Something has gone wrong, please try again.";
                        break;
                }

                if (string.IsNullOrWhiteSpace(message))
                    return;

                Console.WriteLine("Issue connecting: " + purchaseEx);
                await DisplayAlert("Uh Oh!", message, "OK");
            }
```

**Comment by jamesmontemagno** [comment]
And also looking at app center that is just returning an error from Google Play that it can't be processed and I bubble up that exception. Could be a number of things on Google's side

**Comment by iknowcodesoup** [comment]
@jamesmontemagno Thank you kindly. After another code review and reflection you have convinced me that there is an issue surrounding error reporting on my end.

Essentially the custom code to write the PurchaseError is not making it to the logs through my Splat / IEnableLogger method.

Steps for my case will be to
1) Replace the error handling with a direct AppCenter.Crashes line with custom dictionary values (fix splat method later if possible)
1) Perhaps now remove some safe errors from the logs, such as BillingUnavailable, as everything else (my own purchase) has seemed to work fine for a while now
1) Wrap PurchaseAsync in my adapter with a BeginInvokeOnMainThread for good measure.

For some reason I feel the last step has made a difference in some cases, but a bit like holding your tongue out when doing a layup.?

**Comment by iknowcodesoup** [comment]
Closing. As expected there were in-fact issues surrounding wrapper code; capturing exceptions and analytic tracking.

**Comment by gtrafford** [comment]
@iknowcodesoup Hi, I'm having this exact issue. Plenty of successful purchases have gone through but I'm still getting a lot of AppCenter errors exactly matching what you were seeing. Are you able to go into a bit more detail as to what the issues were with your exception capturing that you solved to stop this?

Thanks.
