### ISSUE TITLE
RestorePurchases?

### ISSUE THREAD

**Issue by pulmuone** [jamesmontemagno/InAppBillingPlugin#459]
I am developing a PurchaseSubscription.
Should I check "State == PurchaseState.Purchased" or "AutoRenewing=true" in RestorePurchases?

but your code ...
var sorted = subs.Where(p => p.ProductId == productIdSub).OrderByDescending(i => i.TransactionDateUtc).ToList();
var recentSub = sorted[0];
if (recentSub != null)
{
 //Success 
}

Why is RestorePurchases successful when State or AutoRenewing is not checked?

**Comment by jamesmontemagno** [comment]
AutoRenewing is just general information, Purchased state is all you need.

You can decide how you want to check and what state it is in.
