### ISSUE TITLE
Common usability questions

### ISSUE THREAD

**Issue by TechnikKTK** [jamesmontemagno/InAppBillingPlugin#460]
Hi, yes it is. Thanks, by writing this package. But i need help:
Why app get input appleID & passwd always?
How change production mode? ( CrossInAppBilling.Current.InTestingMode = false? )
Should i delete testing account by appstoreconnect when i real pay needed?

Thanks.

**Comment by jamesmontemagno** [comment]
You should test things in a sandbox account on a real device. Please checkout the testing guidance I have outlined in the docs.
