### ISSUE TITLE
Android subscription expiryTimeMillis

### ISSUE THREAD

**Issue by pulmuone** [jamesmontemagno/InAppBillingPlugin#464]
Can I use "expiryTimeMillis" among subscription resource returned values in Android Subscription?

ref:
https://developer.android.com/google/play/billing/subscriptions

**Comment by jamesmontemagno** [comment]
This is in the [Purchases.subscriptions:get](https://developers.google.com/android-publisher/api-ref/purchases/subscriptions/get) in the Google Play Developer API, not in the Billing library, so your API backend would have to use it.
