### ISSUE TITLE
Promo Code support

### ISSUE THREAD

**Issue by scarrier92** [jamesmontemagno/InAppBillingPlugin#465]
Apple has some promo code capacity for  the subscripritions. 

Is it supported by this plugin? 

I'm on the laatest Nuget package 5.0.1-beta release and I don't see it.

Thank you

**Comment by jamesmontemagno** [comment]
https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/src/Plugin.InAppBilling/Shared/IInAppBilling.shared.cs#L135


Present code Redemption is it to open the screen

**Comment by scarrier92** [comment]
Any plans on packaging the newer version as a nuget package?

**Comment by jamesmontemagno** [comment]
It is already on nuget in the preview releases.

**Comment by anila-mathew** [comment]
@jamesmontemagno Are there any examples for implementing promo code in ios for in app purchase in the latest plugin??
