### ISSUE TITLE
Unconsumed consumables are automatically consumed after app restart

### ISSUE THREAD

**Issue by gormster** [jamesmontemagno/InAppBillingPlugin#466]
This is a serious bug. Errors thrown between `PurchaseAsync` and `ConsumePurchase` can cause the user to be charged without receiving their product.

## Bug Information

Version Number of Plugin: 5.3.2
Device Tested On: iPhone SE 2
Simulator Tested On: -
Version of VS: 2022 Preview 9
Version of Xamarin: Xamarin.iOS 15.8.0.3, Xamarin.Forms 4.8.0.1821
Versions of other things you are using: iOS 15.4.1

### Steps to reproduce the Behavior

1. Perform a `PurchaseAsync` with an `ItemType` of `InAppPurchaseConsumable` 
2. Before triggering `ConsumePurchase`, throw an exception (or kill the app)
3. Restart the app and navigate back to the purchase screen

### Expected Behavior
Unconsumed purchases should not be finished until I explicitly consume them.

### Actual Behavior
Unconsumed purchases are automatically finished as soon as I call `GetProducts`.

### Code snippet

```c#
async Task<bool> ProcessPurchase(string receiptData, string productId, string transactionId) {
    // Real code should do something here
    // It would return true on success
    // But it could throw or return false
    return false;
}

async Task PurchaseProduct(string productId, ItemType purchaseType) {

    var billing = CrossInAppBilling.Current;
    try
    {
        var connectionResult = await billing.ConnectAsync();
        if (!connectionResult)
        {
            throw new Exception("Could not connect to billing service. Please try again later.");
        }
        
        InAppBillingPurchase purchase = await billing.PurchaseAsync(productId, purchaseType);

        if (purchase == null)
        {
            throw new Exception("Purchase could not be processed. Please try again later.");
        }

        // Verify the purchase
        var verified = await ProcessPurchase(billing.ReceiptData, productId, purchase.Id);
        if (!verified)
        {
            throw new Exception("Purchase could not be completed. Please try again later.");
        }

        if (purchaseType == PurchaseType.InAppPurchaseConsumable)
        {
            await billing.ConsumePurchaseAsync(productId, purchase.PurchaseToken, purchase.Id);
        }
        else
        {
            await billing.AcknowledgePurchaseAsync(purchase.PurchaseToken);
        }

        // If we got this far, everything's gravy!
        Debug.WriteLine("Purchase was a success!");
    }
    catch (InAppBillingPurchaseException purchaseEx)
    {
        if (purchaseEx.PurchaseError == PurchaseError.UserCancelled)
        {
            Debug.WriteLine("Purchase was cancelled");
            return;
        } else {
            Debug.WriteLine($"Purchase error: {ex}");
        }
    }
    catch (Exception ex)
    {
        Debug.WriteLine($"Error: {ex}");
    }
    finally
    {
        await billing.DisconnectAsync();
    }
}
```

### Comments

It seems like the code is throwing around a list called `doNotFinishTransactionIds` (or `doNotFinishProductIds`) a LOT. As in, it's passed between many, many functions… but why? It's not really documented. It's only ever set to have one value, when I pass in a consumable product type, and any time `RestoreAsync` is called, it wipes the list completely.

It just doesn't seem like there's any reason to even have this automatic behaviour for FinishTransaction. After all, to support Android we need to use `AcknowledgePurchaseAsync` – why not just have this method also call FinishTransaction on iOS, and never bother with automatic finishing?

You can make it clear in the documentation that, if you don't call either Consume or Acknowledge, you will (a) never get paid and (b) get a lot of transaction observer events clogging up your app. After all, we're already expected to [record which transactions have finished and which haven't](https://developer.apple.com/documentation/storekit/skpaymentqueue/1506003-finishtransaction):

> In rare circumstances, this call might fail, and you'll receive updates for that transaction again. For this reason, you should record information in your app about the transactions it has processed and which steps the app has already completed. That way, you don't repeat steps that shouldn't be performed multiple times. For example, if you are processing a consumable transaction, you only want to add the consumable benefit once.

You could also give us a way to handle unfinished transactions that are picked up by the transaction observer. Maybe an event interface, or an `IObservable`, or `ObservableCollection`, or something like that. That way, I could just wait for that to fire rather than have to check my own record of unprocessed transactions.

**Comment by jamesmontemagno** [comment]
So, great question and yes i need to document this more that is for sure. I have some in there https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/docs/PurchaseConsumable.md and https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/docs/CheckAndRestorePurchases.md

 I fixed this in https://github.com/jamesmontemagno/InAppBillingPlugin/issues/414 and implementation here: https://github.com/jamesmontemagno/InAppBillingPlugin/pull/444 

Here is the gist of it...

I have no idea of knowing what is a consumable or not a consumable and what things you want to auto finish or not auto finish, so you need to tell me.

So, when you make the purchase you have to pass in `ItemType.InAppPurchaseConsumable` which will trigger me not to auto-consume the purchase. Now, the other aspect comes in when you GetPurchases, which will finish transactions automatically (which is good for everything except consumables). This is why you need to pass in a list of ids not to auto finish.

So, this means you must call `FinishTransaction` or `ConsumePurchaseAsync` when you actually consume it.  Calling `GetProductInfoAsync` does not finish any transactions, only `GetPurchasesAsync`, but again you should pass in the Ids that you don't want to have auto-finish. There are many legacy reasons for this and when I updated the API we had a lot of discuss as to how to implement and have consistent backwards compatibility


In app purchases are extremely complicated and extremely hard to abstract across multiple platforms. There is a whole company that does this -> https://www.revenuecat.com/

**Comment by gormster** [comment]
Hey, thanks for your help! I'm going to keep this brief as I accidentally closed the tab where I was writing this response :(

It turns out my original report was wrong - it's not `GetProducts` that causes the transaction to be automatically finished, it's simply the first call to `CrossInAppBilling.Current`. That instantiates `InAppBillingImplementation`, which calls `Init`, which adds an observer to the payment queue, which is *instantly* delivered an update for the unfinished transaction. Since it's not on the list of transactions to not autocomplete – this is before we've even got a chance to run any of our own code – it finishes the transaction immediately.

There's also a much worse bug that I hadn't noticed because I was halting the app immediately after `PurchaseAsync` – consumables are automatically finished *anyway*. This is because `PaymentObserver.Finish()` is called *after* `TransactionCompleted` is invoked, and `TransactionCompleted` clears the list of `DoNotFinishTransactionIds`.

Easy enough fix, though I had a bit of trouble getting it to build… I think you forgot to check in the project files for `InAppBillingMauiTest`? Had to drop a bunch of project references to get it to work.

I'm working on a fork of the project now. I'll file a PR with fixes for these bugs if I can sort if out.

**Comment by gormster** [comment]
Ok, I've got it working, I think. I don't love this solution, but it's got no API breaking changes, which is helpful, I think.

I think in future the public `AcknowledgePurchase`, `ConsumePurchase` and `FinishTransaction` methods should only take an `InAppBillingPurchase` object, or perhaps a smaller object that contains a subset of the whole purchase object, just enough information needed for that platform to finish/acknowledge/consume the purchase. That object should be serialisable, too.

In general, I think the way we're handling the "do not autocomplete this product IDs" thing is wrong. For starters, consumable purchases are *always* consumable - there's no need to ever remove them from that list. Because of that, I don't think it's right to pass them in to the functions, they should be set up ahead of time. (I really wish there was a `consumable` flag on `SKProduct`, but alas, no such luck.)

However, if you are loading your product identifiers from a server, you need a way to say "don't automatically finish any transactions unless I say so". So I've added a static flag to `InAppBillingImplementation` called `ShouldAutomaticallyFinishTransactions`. Setting this to false flat-out disables automatic finishing of transactions that have a transaction state of `SKPaymentTransactionState.Purchased`. Transactions are automatically completed in `GetPurchasesAsync` unless their `ProductId` is in the passed-in list of `doNotFinishTransactionIds` (shouldn't this be `IEnumerable`, btw?)

I'd like to work with you to improve this for a future revision, but at the moment we're being crunched and I need to get this out ASAP, so this'll have to do for now.

**Comment by jamesmontemagno** [comment]
Hmmm or is it better to just have a static list of identifiers? I feel as though that is the better fix. Like hey dont' auto finish these consumables ahead of time. I originally was going to go down this route, but perhaps there are edge cases.

The other option is just don't finish any transaction and make the developer do it. I like either of these options better then a global boolean flag.

**Comment by jamesmontemagno** [comment]
@gormster  take a look at https://github.com/jamesmontemagno/InAppBillingPlugin/pull/468 I think that this is the best option probably to just not finalize at all and leave it up to the individuals

**Comment by gormster** [comment]
@jamesmontemagno will do. we are in a bit of a crunch rn though so will have to wait til Friday I reckon.

**Comment by jamesmontemagno** [comment]
@gormster  pushing out new package
