### ISSUE TITLE
6.3.3-beta don't show AcknowledgePurchaseAsync

### ISSUE THREAD

**Issue by pulmuone** [jamesmontemagno/InAppBillingPlugin#470]
Plugin.InAppBilling Version : 6.3.3-beta

![inapperror](https://user-images.githubusercontent.com/42885949/169179474-0ea39c23-191c-4320-9ed6-f9f10a7b5ec9.png)

don't show function AcknowledgePurchaseAsync

**Comment by jamesmontemagno** [comment]
It has been changed to FinalizePurchaseAsync

**Comment by jamesmontemagno** [comment]
And as noted in the release notes you much call it on iOS and Android

**Comment by jamesmontemagno** [comment]
https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/nuget/readme.txt
