### ISSUE TITLE
Subscription FreeTrial - should wait or not?

### ISSUE THREAD

**Issue by sergepenkin** [jamesmontemagno/InAppBillingPlugin#476]
Hello James!

On Feb 2022 i was testing 5.1.1xx and opened the issue
https://github.com/jamesmontemagno/InAppBillingPlugin/issues/442

I also reviewed list of closed issues - there were a few of them regarding this SUBJECT
As far as i see - in both IOS and Android - there is FreeTrial support for subsriptions

Are InAppBillingProduct.AndroidExtras.FreeTrialPeriod and InAppBillingProduct.AppleExtras.IntroductoryOffer.PaymentMode.FreeTrial the only things available for now - to process FreeTrial period  determination

For instance i take them and calc on my own way - if the user in FreeTrial period or not?
In case the user can reinstall the app - it will be nececcary to store the purchase date on the server and calc determinate FreeTrial period manually

The best thing was - to have this property for the in InAppBillingProduct
Am i right that it is not planned now to figure this issue out on the InAppBillingPlugin side ?

Specially if i use InAppBillingPlugin  in XAmarin Forms project - it would help much - having such a property

Thank you for your work!

**Comment by jamesmontemagno** [comment]
Yeah, I am pretty sure you need to calculate them yourself based on the freetrial stuff. but I would read the official documentation. I havent' used them myself. I just expose the properties coming back.
