### ISSUE TITLE
GetPurchasesAsync(ItemType.Subscription) crashes ("Restore Transactions Failed")

### ISSUE THREAD

**Issue by FredrikBrynolfsson** [jamesmontemagno/InAppBillingPlugin#477]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information
I have a problem with GetPurchasesAsync(ItemType.Subscription) which crashes in TestFlight testing.
When running locally the problem have never occurred but on two different devices running with TestFlight crashes. 
I tried the same Sandbox account locally and then the GetPurchasesAsync doesn't crash and returns the correct list.
Testflight test result:
iPad iOS 15.4.1 : crash
iPhone iOS 15.x : crash
iPhone iOS 14.x : works

The same error as described in ticket : https://github.com/jamesmontemagno/InAppBillingPlugin/issues/60
I use the GetPurchasesAsync to check if the user has an active subscription which doesn't work with surrounding the call with a try catch statement since the result list is empty even if the user has an active subscription.

Thanks in advance! 

Version Number of Plugin:
6.3.3-beta
Device Tested On:
iPad iOS 15.4.1
iPhone iOS 15.x
Simulator Tested On:
iPhone SE 2:and iOS 15.5
Version of VS: 
VS2019 on Mac
Version of Xamarin:
Xamarin.Android
Version: 12.2.4.3
Xamarin.iOS
Version: 15.8.0.3

Versions of other things you are using:

### Steps to reproduce the Behavior
* Deploy the app with TestFlight 
* Run the GetPurchasesAsync(ItemType.Subscription)

### Expected Behavior
GetPurchasesAsync(ItemType.Subscription) returns the correct list

### Actual Behavior
GetPurchasesAsync(ItemType.Subscription) crashes with
`Restore Transactions Failed at Plugin.InAppBilling.InAppBillinglmplementation.GetPurchasesAsync(Plugin.InAppBilling.ItemTypeitemType)
`

### Code snippet
`
var billing = CrossInAppBilling.Current;
var connected = await billing.ConnectAsync();

if (!connected)
{
	//Couldn't connect
	return (false, "Couldn't connect to payment server");
}
 var purchases = await billing.GetPurchasesAsync(ItemType.Subscription);
`

**Comment by karha096** [comment]
@jamesmontemagno, this issue is really important to us. an you have a look in the short term?

**Comment by dennisstromberg** [comment]
Same for me

**Comment by smalgin** [comment]
tried in TestFlight + Simulator, TestFlight+ Real device.
Checking in-app purchases - same failure
Checking subscriptions - same failure.

Idk... I'll keep looking at the Apple side - I just set everything up today, maybe Apple Pay needs some time???

**Comment by smalgin** [comment]
Ok everybody, I think I found the answer here: https://developer.apple.com/forums/thread/82859

Essentially: if you are using a sandbox apple ID account, DO NOT USE any Distribution provisioning profiles, only the Development provisioning profile. 

I don't have time to verify this right now... but - can someone do the honors? I'll test and post the results when I will get some time.

**Comment by smalgin** [comment]
Step one: IMPORTANT: When you create a sandbox test apple ID, DO NOT EVER try to use it to sign in on your iPhone! That will render it useless for everything & unrecoverable.
Step two: Discard your broken Sandbox apple ID and create a new one. **Don't use it on iPhone just yet.**
Step three: Build and sign your app with your Development provisioning profile! NOT Distribution profile. I use AppCenter.
Step 4. Push the built app package to the Mac where you have your XCode set up. 
Step 5. Attach your test iPhone to the Mac. in XCode, open Window | Devices and Simulators, verify that you see your iPhone. SANITY CHECK: Your Mac (and your iPhone by that moment)  should already have Provisioning profiles downloaded. If not, go to documentation & start over.
Step 6. Still in Devices and Simulators window, manually add your app package to the iPhone. Provided that you have provisioning profiles set correctly, that will go without any errors.
Step 7. Open your app and try to purchase stuff. When asked for the Apple ID, USE YOUR fresh Sandbox Apple ID.
THAT WILL INSTALL the Sandbox Apple ID as a Sandbox test account on your iPhone!
(I did it while iPhone was still connected, but that should not matter at this point)
Step 8. NOW you should get past the GetPurchasesAsync without any exceptions!
...
Now you will also likely get another error: Invalid Product ID. See my next post.

**Comment by smalgin** [comment]
Ok, what if you have 'Invalid Product ID'?

In AppStore Connect, go to Agreements, Tax and Banking and finish adding your Paid App in the Agreements section.
That should be enough to get you moving. 
The processing will take about 24 hours, so while you are on a forced break, also fill in Tax Forms, Bank information and everything else Apple throws at you.
.
Let me know if these instructions work for you!

**Comment by smalgin** [comment]
FYI - No problems with the plugin after the steps above.

PS  @jamesmontemagno 
![image](https://user-images.githubusercontent.com/8367800/177364492-633e5f7c-6851-4c2c-a920-41b96d1533b3.png)
Wrong release on the Github repo.

Also

New documentation on 6.x pre-release is missing, even in repo. I had to wing it. It works, but seriously people, if you go into pre-release more, pls release some docs as well.

**Comment by jamesmontemagno** [comment]
Looks like thtis is fixed up
