### ISSUE TITLE
New Google Policy: We’re updating our Subscriptions policy to state that users must be able to easily cancel their subscriptions from within the app.

### ISSUE THREAD

**Issue by ProximitySolutionsUK** [jamesmontemagno/InAppBillingPlugin#479]
Just read latest notes from Google re: subscriptions and that inapp cancellation of subscription will be a requirment:

"_We’re updating our Subscriptions policy to state that users must be able to easily cancel their subscriptions from within the app._"

Currently I cant see a way in the InAppBilling plugin to do this - anyone found a work around?

@jamesmontemagno - do you have a suggestion here?  Failure to have this option in any app using subscriptions will result in it being removed from the Play Stores as I understand it This will impact a lot of peoples apps that use the subscription feature very soon (mine included I built for a large corporate).  Will you be updating the plugin to accommodate?

Thanks

**Comment by relecon** [comment]
Looking at the direct policy from [Google's Developer Program Policy](https://support.google.com/googleplay/android-developer/answer/12253906#subscriptions_preview), it looks like you don't necessarily have to provide a means to cancel from the app, rather point them in the direction as to how they would go about cancelling:

"Subscription Management, Cancellation & Refunds
If you sell subscriptions in your app(s), you must ensure that your app(s) clearly disclose how a user can manage or cancel their subscription. You must also include in your app access to an easy-to-use, online method to cancel the subscription. 

**In your app’s account settings (or equivalent page), you can satisfy this requirement by including:

- A link to Google Play’s Subscription Center (for apps that use Google Play’s billing system); and/or
- direct access to your cancellation process.**

If a user cancels a subscription purchased through Google Play’s billing system, our general policy is that the user will not receive a refund for the current billing period, but will continue to receive their subscription content for the remainder of the current billing period, regardless of the cancellation date. The user's cancellation goes into effect after the current billing period has passed.

You (as the content or access provider) may implement a more flexible refund policy with your users directly. It is your responsibility to notify your users of any changes to your subscription, cancellation and refund policies and ensure that the policies comply with applicable law."

Hope this helps!

**Comment by jamesmontemagno** [comment]
Nice, so I don't think that there is an API to call it at all.

I think there is 2 things.... 
1.) If you sell outside of the store you need to link to your page to cancel in the app
2.) if you use in app billing you need to deep link to -> https://developer.android.com/google/play/billing/subscriptions#deep-link

easy peasy
