### ISSUE TITLE
Can not find Plugin.InAppBilling on Nuget search box?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [jamesmontemagno/InAppBillingPlugin#48]
I can not find Plugin.InAppBilling on Nuget search box. 
1. How to use Package Manager Console to install this plugin **for all project** in Xamarin.Forms
2. Does it work with UWP project in Xamarin.Forms?

**Comment by jamesmontemagno** [comment]
1.) check the pre-release checkbox
2.) yes
