### ISSUE TITLE
Android Unsubscribe Functionality

### ISSUE THREAD

**Issue by barrytheunissen** [jamesmontemagno/InAppBillingPlugin#480]
Hi James,

Google Play has now come out with a new mandatory requirement for all submitted apps. 

The app must provide functionality for a user to UNSUBSCRIBE from a subscription from within the app itself now, and not only via Google Play. 

We need functionality in our apps using this plugin to be able to unsubscribe in Google Play, otherwise our apps will be rejected.

Most likely Apple is going to follow suite with Google in the not too distant future.

Just like we currently have billing.PurchaseAsync, we now need something additional like billing.UnSubscribeAsync, or something to that effect.

Kind regards,
Barry

**Comment by jamesmontemagno** [comment]
See: https://github.com/jamesmontemagno/InAppBillingPlugin/issues/479

**Comment by barrytheunissen** [comment]
Thanks James! Brilliant!
