### ISSUE TITLE
App Review says free trial not granted?

### ISSUE THREAD

**Issue by xabaddonx1** [jamesmontemagno/InAppBillingPlugin#481]
I have a 14 day free trial on my subscriptions and it works fine for me in testing and for my beta testers. But for some reason my app review keeps getting rejected saying that the free trial is not granted. There is only one product ID for each sub so I don't see how I could I could be calling PurchaseAsync on the wrong thing... they say it has something to do with receipt validation but I don't see how this could affect if you get the free trial or not. Has anyone run into this before?

**Comment by jamesmontemagno** [comment]
Hmmm do you have the full text that Apple rejected? Any screenshots?

**Comment by xabaddonx1** [comment]
Eventually they realized it was an issue on their end... I'm pretty sure whoever did the review somehow didn't realize that the renewal date would be the same day since they are testing in the sandbox.
