### ISSUE TITLE
Play Billing Library Version 3 Deprecation

### ISSUE THREAD

**Issue by ivanicin** [jamesmontemagno/InAppBillingPlugin#483]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 4.0.2
Device Tested On: Android 9
Simulator Tested On: Android 12
Version of VS: 17.3.3
Version of Xamarin: 17.3.0.296
Versions of other things you are using:

### Steps to reproduce the Behavior
No actions required
### Expected Behavior
The plug-in should support Google Play requirements
### Actual Behavior
From November 1, 2022, all app updates must use Billing Library version 4 or newer. That is near. Official version of the plugin only uses version 3 of Billing library. Technically the Billing Library could be updated itself and my guess is that it will work, but you should at least document that if that is the case.

**Comment by nealculiner** [comment]
I see this issue in my Google Play console as well and I'm using the latest plugin here (thanks for it). Looking forward to learning how to resolve this deprecation message.

**Comment by PonyOny** [comment]
Same here, please update API version of Billing Library.

**Comment by ivanicin** [comment]
Just to note that technically you can do two things to have the app that works:

1.  use the pre-release version of the package
2. update `Xamarin.Android.Google.BillingClient` to the version 4.0

It is not clear just if any of those come with side effects.

If someone has some experience with some of those solutions please report here.

Clearly it would be the best if @jamesmontemagno updated the plugin.

**Comment by jamesmontemagno** [comment]
Yes install pre-release versions 5.x or 6.x.

I will push these to stable.
