### ISSUE TITLE
Documenation bug

### ISSUE THREAD

**Issue by ivanicin** [jamesmontemagno/InAppBillingPlugin#485]
On the page: https://jamesmontemagno.github.io/InAppBillingPlugin/PurchaseNonConsumable.html

It says:

> On Android you must call FinalizePurchaseAsync within 3 days when a purchase is validated. Please read the [Android documentation on Pending Transactions](https://developer.android.com/google/play/billing/integrate#pending) for more information.
> 
> On iOS you must also call

The iOS sentence is incomplete and vague.

**Comment by barrysohl** [comment]
Agreed. It is unclear for iOS consumables, do we call just ConsumePurchaseAsync, or do we have to call both that and FinalizePurchaseAsync?

**Comment by jamesmontemagno** [comment]
For iOS ConsumePurchaseAsync and FinalizePurchaseAsync do the same thing.

**Comment by jamesmontemagno** [comment]
Update docs
