### ISSUE TITLE
Replacement for IInAppBillingVerifyPurchas

### ISSUE THREAD

**Issue by barrysohl** [jamesmontemagno/InAppBillingPlugin#486]
The 5.0 readme says:

1.) We have removed IInAppBillingVerifyPurchase from all methods. All data required to handle this yourself is returned.
2.) iOS ReceiptURL data is avaialble via ReceiptData

But I do not see this explained anywhere in the documentation. Where is ReceiptData available?

**Comment by DiebBlue** [comment]
You should write a dependency injection and use the following code snipped in your xamarin ios project to get the Apple Receipt data:
```

using Xamarin.Forms;
using Foundation;

using YourNameSpace.DependencyInterfaces;
using YourNameSpace.Services.iOS;

[assembly: Dependency(typeof(AppleReceiptData))]
namespace YourNameSpace.Services.iOS
{
    public class AppleReceiptData : IAppleReceiptData
    {
        public string GetReceiptData()
        {
            NSUrl receiptUrl = NSBundle.MainBundle.AppStoreReceiptUrl;
            NSError error = null;
            NSData receipt = NSData.FromUrl(receiptUrl, NSDataReadingOptions.MappedAlways, out error);
            string strreceipt = "";
            
            if (receipt != null && (null == error || error.Code == 0))
                strreceipt = receipt.GetBase64EncodedString(NSDataBase64EncodingOptions.None);
            
            return strreceipt;
        }
    }
}
```

Greets DiebBlue

**Comment by barrysohl** [comment]
Sounds good, thanks. I’ll give it a try! It would be nice to have that as part of the plugin though.

-Barry

**Comment by sachinkanadia** [comment]
Hello All,

I am working on purchasing and restoring on Android for the moment. I don't see how I can verify the purchase compared to the old implementation of IInAppBillingVerifyPurchase. Can someone please let me know what data I would need to verify the purchase?

1) I don't see the SignedData property passed back within the InAppBillingPurchase object but, I do see the Signature property.
2) I don't see the InAppBillingImplementation.InAppBillingSecurity.VerifyPurchase method anymore.

**Comment by jamesmontemagno** [comment]
ReceiptData is available on `CrossInAppBilling.Current.ReceiptData`

I have updated the documentation as the VerifyPurchase interfaces were all removed in recent version as tehy aren't needed and each developer can decide on how to verify. it wasn't adding value as now all the data is returned.
