### ISSUE TITLE
Subscriptions support for Pending Purchases.

### ISSUE THREAD

**Issue by sachinkanadia** [jamesmontemagno/InAppBillingPlugin#488]
Hi There,

I'm wondering if subscriptions support pending purchases.

According to this [thread](https://stackoverflow.com/questions/73756385/android-test-pending-purchases-with-subscriptions) as of 19/09/2022, subscription purchases do not support pending purchases.

I've read the google documentation however it's not clear what the fact of the matter is. 

If it is a requirement to support pending purchases for subscriptions, why can't I see the following payment instruments:
1) Test card, slow to approve.
2) Test card, slow to decline.

Any clarification on this would be much appreciated.

Thank you.

**Comment by jamesmontemagno** [comment]
I don't believe Google supports that for subscriptions.
