### ISSUE TITLE
Do you have sample about Consumable and Trial?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [jamesmontemagno/InAppBillingPlugin#49]
Thank you for your PlugIn. 
Follow your sample about Non-Consumable it's work fine.
Do you have sample about Consumable and Trial?

**Comment by jamesmontemagno** [comment]
So, for consumables it is pretty simple on iOS you just purchase async and pass it in.

On Android though you have to purchase and then pass that info later to consumeasync and it will be consumed.

I will write up some docs on it.

**Comment by jamesmontemagno** [comment]
Update docs, not sure about trials, but I think they work the same.
