### ISSUE TITLE
How To Check Subscription Expiration Date.

### ISSUE THREAD

**Issue by pulmuone** [jamesmontemagno/InAppBillingPlugin#490]
jamesmontemagno Thanks for the great source.

If you want to check the subscription expiration date, you can check it by looking at the receipt.
No need to use API backend.
Developers who need to check the expiration date of subscription receipts(Android/iOS).
This method is necessary because some users cancel after subscription and use it again.

my source
 https://github.com/pulmuone/InAppBillingTest

**Comment by jamesmontemagno** [comment]
You have to figure it out yourself unfortunatelly: https://montemagno.com/ios-android-subscription-implemenation-strategies/
