### ISSUE TITLE
Setting the Developer Payload on Purchase.

### ISSUE THREAD

**Issue by sachinkanadia** [jamesmontemagno/InAppBillingPlugin#491]
Hi There,

I am attempting to write server validation taking guidance from [this](http://jonathanpeppers.com/Blog/securing-google-play-in-app-purchases-for-xamarin-with-azure-functions).

Jonathan sets a developer payload parameter in the article into his native Buy method.

As I am using InAppBillingPlugin directly and not invoking natively I cannot see an overload or way to set the developer payload object when Purchasing a subscription.

The documentation [here](https://jamesmontemagno.github.io/InAppBillingPlugin/SecuringPurchases.html#:~:text=Android,all%20be%20used.) mentions that it can be done. 

Please could an example be provided?

Thank you.

**Comment by jamesmontemagno** [comment]
These are no longer used, see -> https://developer.android.com/google/play/billing/developer-payload
