### ISSUE TITLE
IsAcknowledged is always False on iOS

### ISSUE THREAD

**Issue by sachinkanadia** [jamesmontemagno/InAppBillingPlugin#493]
Hello There,

I am unclear about the following and hoping someone could help.

1) Do we need to call FinalizePurchaseAsync for iOS Subscription purchases after a purchase is made?
2) If so, then it seems IsAcknowledged is always False on the InAppBillingPurchase object within iOS regardless of whether the call to FinalizePurchaseAsync is made or not.
3) If we don't need to call FinalizePurchaseAsync on iOS then this should be fine.

According to the Apple [docs](https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/finishing_a_transaction), we need to Finish a Transaction.

Please could someone advise?

Thank you.

**Comment by jamesmontemagno** [comment]
See -> https://github.com/jamesmontemagno/InAppBillingPlugin#version-5--6-major-update

You do not need to in 6.6.1 as i auto finalize  on iOS. 

IsAcknowledged is Android specific and is now a nullable with no value set on iOS. This is because apple does not expose this at all.

**Comment by sachinkanadia** [comment]
Thank you for the response.

The only thing with auto finalising on iOS is that server-side receipt validation is rendered redundant. There would be no way to roll back the transaction if receipt validation failed after calling Purchase. I was calling FinalisePurchase depending on receipt validation success or failure. But if auto finalise is now enforced what would be the best way to roll back the purchase if receipt validation fails on iOS?



Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
