### ISSUE TITLE
iOS not showing renewals when calling GetPurchasesAsync()

### ISSUE THREAD

**Issue by sachinkanadia** [jamesmontemagno/InAppBillingPlugin#497]
**InAppBilling Plugin Version: 5.6.1
Xamarin Forms Version: 5.0.0.2515
OS Concerned: iOS**

For renewals on iOS, against the Sandbox environment, I am receiving the same Transaction Id (original transaction) for each receipt after calling GetPurchasesAsync() within the App.

I have ensured that I am calling FinalizePurchase on the original purchase and I am quite sure the iOS subscription is set up correctly as it is showing under Auto-Renewing subscriptions in iTunes Connect.

[Source](https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/src/Plugin.InAppBilling/InAppBilling.apple.cs#:~:text=allTransactions.Add(original)%3B)

I found this in the inappbilling source code:

```
	foreach (var trans in SKPaymentQueue.DefaultQueue.Transactions)
	{
		var original = FindOriginalTransaction(trans);
		if (original == null)
			continue;

		allTransactions.Add(original);
	}
```

It seems as though it only ever adds the original transaction and not renewals. Please, could this be investigated?

Many Thanks.

**Comment by sachinkanadia** [comment]
Hi There,

I was wondering if there was an update on this issue?

Any info on this would be much appreciated.

Many Thanks.

**Comment by mbilalbenli** [comment]
@sachinkanadia did you find any solution? i am having the same problem.

**Comment by sachinkanadia** [comment]
@mbilalbenli No. With a workaround, I will have to go live with this issue in InAppBilling.

The workaround will avoid comparing and checking the TransactionId within my verification code for iOS.

**Comment by jamesmontemagno** [comment]
Here is what I do:

```csharp
 var subs = await CrossInAppBilling.Current.GetPurchasesAsync(ItemType.Subscription);

                if (subs?.Any(p => p.ProductId == productIdSub) ?? false)
                {
                    var sorted = subs.Where(p => p.ProductId == productIdSub).OrderByDescending(i => i.TransactionDateUtc).ToList();
                    var recentSub = sorted[0];
                    if (recentSub != null)
                    {
                        if (DeviceInfo.Platform == DevicePlatform.Android)
                        {
                            foundStuff = true;
                            Settings.HasTippedSub = true;
                            Settings.CheckSubStatus = true;

                            //loop through transactions and keep adding a month until valid
                            var date = recentSub.TransactionDateUtc;
                            while (date < DateTime.UtcNow)
                                date = date.AddMonths(1);

                            Settings.SubExpirationDate = date.AddDays(5);

                            SetPro();
                        }
                        else
                        {
                            if (recentSub.TransactionDateUtc.AddSubTime() > DateTime.UtcNow)
                            {
                                foundStuff = true;
                                Settings.HasTippedSub = true;
                                Settings.CheckSubStatus = true;
                                Settings.SubExpirationDate = recentSub.TransactionDateUtc.AddSubTime();
                                OnPropertyChanged(nameof(SubPrice));
                                SetPro();
                            }
                        }

                        if (DeviceInfo.Platform == DevicePlatform.Android && !recentSub.IsAcknowledged)
                        {

                            try
                            {
                                await CrossInAppBilling.Current.AcknowledgePurchaseAsync(recentSub.PurchaseToken);
                            }
                            catch (Exception ex)
                            {
                                Logger.AppendLine("Unable to acknowledge purcahse: " + ex);
                            }
                        }
                    }
                }
```


You don't need to compare transactionids... just the productids

**Comment by sachinkanadia** [comment]
Hi James,

I am expecting the most recent transaction on iOS to be the renewal, not the original transaction as per the documentation [here](https://jamesmontemagno.github.io/InAppBillingPlugin/CheckAndRestorePurchases.html#:~:text=On%20Android%20only%20valid%20on%2Dgoing%20subscriptions%20will%20be%20returned%20(with%20the%20original%20purchase%20date).%20iOS%20returns%20all%20receipts%20for%20all%20instances%20of%20the%20subscripitions).

I need this working otherwise this/your line of code will not work as its always returning the original transaction:
`if (recentSub.TransactionDateUtc.AddSubTime() > DateTime.UtcNow)`

Can we acknowledge that this is a defect and when the fix will go in?

**Comment by sachinkanadia** [comment]
Hi James,

This defect is an easy fix however, it currently renders the InAppBilling Plugin broken on iOS.

Please could you provide the rationale as to why you're deciding to overlook this matter?

**Comment by jameslavery** [comment]
@sachinkanadia I'm experiencing the same/similar problem. I've purchased an auto-renewing subscription, but am not seeing any expiry/renewal data in the purchases being returned.

How did you work around this? I need to know what the status of the current/latest subscription is, along with its expiry/renewal date.
