### ISSUE TITLE
GenerateJavaStubs

### ISSUE THREAD

**Issue by bovp2000** [jamesmontemagno/InAppBillingPlugin#5]
I get the following error after adding the permissions plugin to my android app.

Error MSB4018: The "GenerateJavaStubs" task failed unexpectedly.
System.InvalidOperationException: Application cannot have both a type with an [Application] attribute and an [assembly:Application] attribute.
at Xamarin.Android.Tasks.ManifestDocument.CreateApplicationElement(XElement manifest, List1 subclasses, List1 selectedWhitelistAssemblies)
at Xamarin.Android.Tasks.ManifestDocument.Merge(List1 subclasses, List1 selectedWhitelistAssemblies, Boolean embed, Boolean replaceSplashScreen, IDictionary2 splashScreenClasses, String bundledWearApplicationName, IEnumerable1 mergedManifestDocuments)
at Xamarin.Android.Tasks.GenerateJavaStubs.Run()
at Xamarin.Android.Tasks.GenerateJavaStubs.Execute()
at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
at Microsoft.Build.BackEnd.TaskBuilder.d__26.MoveNext() (MSB4018)

What can I do? I read something about mainApplication.cs but still do not know what to do :(

**Comment by bovp2000** [comment]
This is caused due to the Plugin.CurrentActivity, I went to that plugin and there is answer https://github.com/jamesmontemagno/Xamarin.Plugins/issues/165

**Comment by 5509850** [comment]
Adding Plugin.CurrentActivity in Xamrin.Droid will add a new class in named as Main Application so conflict arise between MainActivity which is already there in Xamarin.Droid and Main Application.
Deleting the MainApplication class will Resolve the Issue.

**Comment by jamesmontemagno** [comment]
I wouldn't just delete the main application, there is important logic inside of it. So failure to move that logic over will cause some serious issues.

**Comment by webmetender** [comment]
I experience the same issue, [the link](https://github.com/jamesmontemagno/Xamarin.Plugins/issues/165) provided in [bovp2000's comment](https://github.com/jamesmontemagno/InAppBillingPlugin/issues/5#issuecomment-274425646) is broken, can someone give the right link to the solution?
Thanks.
A.

**Comment by jamesmontemagno** [comment]
Essentially i put down a MainApplication file that has important information in it to get things working for activity tracking. You may already have a file that has an [Application] attribute, so merge those together.

**Comment by wallacesantos** [comment]
I got this situation on my droid app as well. The problem was caused by these lines in AssemblyInfo.cs file:
   #if DEBUG
   [assembly: Application(Debuggable = true)]
   #else
   [assembly: Application(Debuggable=false)]
   #endif

The applied solution was:
1. Comment those lines in AssemblyInfo file;
2. Adjust the [Application] attribute in the MainApplication class to keep that feature:
    //You can specify additional application information in this attribute
#if DEBUG
    [Application(Debuggable = true)]
#else
    [Application(Debuggable = false)]
#endif
	public class MainApplication : Application, Application.IActivityLifecycleCallbacks
     ....


With this, the project worked fine.

**Comment by devology-rob** [comment]
Hey @wallacesantos you're a lifesaver 🥇  I couldn't work out where the hell it thought I had another 'Application', then stumbled on your comment here.  Thanks - it worked for me.

**Comment by jamesmontemagno** [comment]
See: https://github.com/jamesmontemagno/currentactivityplugin

**Comment by maplemale** [comment]
Thanks @wallacesantos  for the info!

FYI: Everyone who follows this guide: https://developer.xamarin.com/guides/android/deployment,_testing,_and_metrics/publishing_an_application/part_1_-_preparing_an_application_for_release/

and then your guide: https://blog.xamarin.com/integrating-in-app-purchases-in-mobile-apps/

... is going to run into this issue! Suggest at the very least updating the readme.txt and your guide. There are half-a-dozen other options for the nuget. This issue should not be closed / a new one should be opened?

**Comment by dpedrinha** [comment]
Why the hell they removed Forms.Context without providing a solution???? Now I have to use another plugin... Xamarin team ability to F*** with us is unbelievable.

**Comment by dpedrinha** [comment]
@wallacesantos your solution works, but now, I'll have to change this setting on the MainApplication.cs every time I decide to release or debug? It's not viable to have something that I can forget hardcoded. It most certainly will cause problems later and it will take an eternity to find the problem.

**Comment by jamesmontemagno** [comment]
What do you mean? This plugin has nothing to do with Forms.Context at all @dpedrinha

**Comment by dpedrinha** [comment]
The CurrentActivity one does, there's a problem with it that even without another Application in the project it won't compile, and @wallacesantos fix for it is here. Sorry if I missed that the thread was about another plug in. And sorry trashing on the xamarin team on your turf. And BTW, you should add his fix to your readme.txt file from the plug in I'm talking about.
