### ISSUE TITLE
PurchaseAsync never returning, only way to get purchase data is through OnActivityResult. 

### ISSUE THREAD

**Issue by DFerenczi** [jamesmontemagno/InAppBillingPlugin#50]
Hi, 

For Android, do we need to override OnActivityResult when using this library? I've managed to get PurchaseAsync to work earlier but now for some reason the function never returns. Instead I've noticed that my OnActivityResult is called where I can "collect" the purchase data through the Intent. But this will not "be" a cross-platform solution.. Any ideas why the PurchaseAsync function suddenly isn't returning?

/Ferenczi

**Comment by jamesmontemagno** [comment]
Did you follow https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/README.md#setup-1

**Comment by DFerenczi** [comment]
Yes i've followed the readme I'm the slow one.. Checked my commits from yesterday and noticed that I by some reason (blaming Mondays) removed 'InAppBillingImplementation.HandleActivityResult(requestCode, resultCode, data);' from OnActivityResult override.. 

That's why it worked yesterday and not today, sorry for bothering you and thanks for an epic plugin!
