### ISSUE TITLE
docs for v5.x and 6.x are not updated.

### ISSUE THREAD

**Issue by wsoftone** [jamesmontemagno/InAppBillingPlugin#500]
hi,
i tried to use the new version 5.x but i found that the test projects still using AcknowledgePurchaseAsync.
I checked the documentations then i found it refere to the old versions (version 3 or 4 i think).
could you please update the test projects to be able to use the inappbilling in the correct way? 

best regards.

**Comment by jamesmontemagno** [comment]
Please check the documentation as it has been updated: https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/docs/PurchaseNonConsumable.md

**Comment by wsoftone** [comment]
thank you for the update.
I upgraded my app inappbilling from version 4.x to version 5.x. I followed all instructions in your docs... i uploaded my signed apk with new version code in playstore.
Now it works. thank you.
