### ISSUE TITLE
on iOS, InAppBilling purchase receipt is still old/deprecated IOS6-style receipt

### ISSUE THREAD

**Issue by smalgin** [jamesmontemagno/InAppBillingPlugin#501]
## Bug Information

Version Number of Plugin: 6.6.1 and 6.6.2beta
Device Tested On: iPhone SE 2021
Simulator Tested On: N/A
Version of VS: 2019
Version of Xamarin: 5.0.0.2515
Versions of other things you are using:

### Steps to reproduce the Behavior
1) use InAppBilling to purchase a subscription on a sandbox user.

                var purchase = await billing.PurchaseAsync(planName,
                    ItemType.Subscription);

2) obtain the receipt and send it to https://sandbox.itunes.apple.com/verifyReceipt

### Expected Behavior
Receipt should match Apple documentation https://developer.apple.com/documentation/appstorereceipts/responsebody for iOS7-style receipts.

### Actual Behavior
The receipt returned by the InAppBilling is iOS6-style deprecated receipt. This is easy to see - old receipts contain 'bid' field for the bundle identifier. New receipts have the 'bundleId' property.

![image](https://user-images.githubusercontent.com/8367800/195998967-647feb35-4279-4e67-a0d1-6012f19442d0.png)

This is not good.

Breaking existing receipt validators by switching receipt to iOS7-style is not a good idea - but can you provide a way to fetch the iOS7-style receipt for the transaction? Maybe have some method that will take InAppPurchase and return iOS7-style receipt by going to the main bundle receipt URL & fetching the data back?

**Comment by smalgin** [comment]
See the SO link - it is still relevant. https://stackoverflow.com/a/53229609

**Comment by jamesmontemagno** [comment]
I do already, you get it via ReceiptData -> https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/src/Plugin.InAppBilling/InAppBilling.apple.cs#L440

**Comment by smalgin** [comment]
Awesome, thanks! I could not find this in the documentation.
