### ISSUE TITLE
FinalizePurchaseAsync required?

### ISSUE THREAD

**Issue by ssbssb-cmd** [jamesmontemagno/InAppBillingPlugin#502]
Hi,
I've recently upgraded to version 5.6.1 of the InAppBillingPlugin.

Previously, after making a purchase: 

       billing.PurchaseAsync(productId, ItemType.Subscription)

I had the following code to AcknowledgePurchase, for Android only:
            
       if (Device.RuntimePlatform == Device.Android)
                    {
                         //Must call AcknowledgePurchaseAsync else the purchase will be refunded
                         await billing.AcknowledgePurchaseAsync(purchase.PurchaseToken);

                    }

When I upgraded the package, the readme says that this has changed to FinalizePurchaseAsync, and it also needs to be called on iOS after purchase. However the documents online indicates that this is only required, and only on android, if you turn off auto-finalize.

Pls could someone clarify?

For completness, what I have now is this; i've not set any auto-finalize flags. Would this work or should i remove the FinalzePurchaseAsync part?

        var billing = CrossInAppBilling.Current;
                   try
                   {
                       var connected = await billing.ConnectAsync();
                       if (!connected)
                       {
                           //we are offline or can't connect, don't try to purchase
                           return new BaseResponse() { IsSuccess = false, Message = "Unable to connect" };
                       }
        
                       var purchase = await billing.PurchaseAsync(productId, ItemType.Subscription);
       
              
                       //possibility that a null came through.
                       if (purchase == null)
                       {
                           return new BaseResponse() { IsSuccess = false, Message = "Purchase failed" };
                       }
       
       
                       else if (purchase.State == PurchaseState.Purchased)
                       {
       
                           // need this for both iOS and Android now, apparently.
                           var ack = await billing.FinalizePurchaseAsync(purchase.TransactionIdentifier);
                       }
       
                       // app specific code..

**Comment by jamesmontemagno** [comment]
Yes, I reverted it back so iOS auto finalizes like it did previously.

You need to do it on Android just like you did before.

I will update docs and such.
