### ISSUE TITLE
Android subscription different plans

### ISSUE THREAD

**Issue by marko91** [jamesmontemagno/InAppBillingPlugin#505]
Hello,

wondering if it is possible to get / purchase different subscription plans on Android (that are registered under one productId / sku).

On GPlay developer console I have registered one productId / subscription that has two "base plans" - monthly and yearly, which have their own IDs. Using the "base plan" IDs doesn't return any info and the purchase is not successful, while using the "main" productId works.

Should I make two different subscriptions with different productIds for separating between monthly & yearly subscription plan?

Using the latest version (6.7.0).

**Comment by carbonete** [comment]
I have same need

**Comment by jamesmontemagno** [comment]
What I do currently is have 2 different ids, 1 for monthly and one for yearly and that has worked out nicely. 

I will have to look into the other new options they have in there.

**Comment by marko91** [comment]
Thanks! Will use 2 different IDs myself.

**Comment by SteHiggins** [comment]
> What I do currently is have 2 different ids, 1 for monthly and one for yearly and that has worked out nicely.

Does this mean that the user could subscribe to both (monthly and annual)?  ...and we would need to prevent this in our own code?
