### ISSUE TITLE
Trying to find branch or tag for version 5.6.1

### ISSUE THREAD

**Issue by greg84** [jamesmontemagno/InAppBillingPlugin#507]
The [documentation](https://github.com/jamesmontemagno/InAppBillingPlugin/tree/master#important-version-information) says to use version 5.x when using Xamarin Forms, so I'm using version 5.6.1

Now I'm experiencing an issue similar to #487, which talks about finalisation of subscriptions, which may or may not be done automatically, and I can't work out what versions this applies to. So I thought I'd find the code for the version I'm using and take a look.

However, I can't see a [branch](https://github.com/jamesmontemagno/InAppBillingPlugin/branches/all), or a [tag](https://github.com/jamesmontemagno/InAppBillingPlugin/tags), or a [release](https://github.com/jamesmontemagno/InAppBillingPlugin/releases?page=2) for version 5.6.1, how do I know what version of the code was used to build it?

Thanks

**Comment by jamesmontemagno** [comment]
It will match the 6.x versioning... it is the same source code https://github.com/jamesmontemagno/InAppBillingPlugin/releases/tag/v6.6.1.7

**Comment by jamesmontemagno** [comment]
i pulled all stable released that did not auto finalize to 5.6.1 and 5.7.0 are back to the original auto finalize, altthough you can turn it off

**Comment by greg84** [comment]
great! thanks @jamesmontemagno
