### ISSUE TITLE
System.NotImplementedException thrown when used with Avanolia

### ISSUE THREAD

**Issue by lanyusan** [jamesmontemagno/InAppBillingPlugin#512]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:
6.7.0
Device Tested On:
Windows 11
Simulator Tested On:
Version of VS: 
17.4

Version of Xamarin:

Not Xamarin but Avanolia 0.10.18

Versions of other things you are using:

### Reproduce repo
https://github.com/lanyusan/avanolia-iap-bug1

### Steps to reproduce the Behavior

Call `var billing = CrossInAppBilling.Current;`

### Expected Behavior

Should move to next statement

### Actual Behavior

Thrown exception 
```
System.NotImplementedException: 'This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.'
```
### Code snippet
`  var billing = CrossInAppBilling.Current;`

### Screenshots

![image](https://user-images.githubusercontent.com/56706512/207216713-95902ba6-b46b-4990-ba09-eade8841837f.png)

![image](https://user-images.githubusercontent.com/56706512/207216775-878adc99-cd4e-4221-b771-696a5ea4c50d.png)

**Comment by lanyusan** [comment]
I have created a reproduce repo:

https://github.com/lanyusan/avanolia-iap-bug1

Thanks in advance.

**Comment by lanyusan** [comment]
> Correct, IAB supports iOS, Android, mac, Windows... So here for a windows (wpf?) app that would ever be supported as wpf doesn't have a native IAP api.

Sorry. Can I clarify that you meant your package wouldn't support Avalonia? 

I just got started with windows/dotnet/avalonia development so my apology in advance if it is a naive question.

Thanks.

**Comment by jamesmontemagno** [comment]
No worries, plugins like this support the core underlying platforms and does not have a dependency on .NET MAUI, Avalonia, Uno, or Xamarin.Forms or anything like that.

iOS, Android, macOS, and Windows (through WinUI or UWP). 

So if you are using Avalonia under the hood it uses the same platforms that .NET MAUI uses for iOS/Android/Mac, however for Windows it is not using UWP/WinUI 3 and the Windows App SDK. This is where the in app purchase APIs live, so there is no way to access them. I am not an Avalonia expert, but that is from my understanding. Basically what they said here: https://github.com/AvaloniaUI/Avalonia/discussions/9636

So in this regard it is impossible to add any support for Windows in Avalonia, but the plugin would work fine for iOS/Android/Mac

**Comment by lanyusan** [comment]
Thanks for the clarification.

**Comment by lanyusan** [comment]
@jamesmontemagno 

I ran the reproduce repo on Mac. Still the same exception.

If it would get to work on Mac, it is still a great news for Avalonia community and myself of course.

<img width="633" alt="截屏2022-12-15 10 56 43" src="https://user-images.githubusercontent.com/56706512/207762093-72be9485-6ccd-4401-8afe-58f2bf3424e5.png">

**Comment by jamesmontemagno** [comment]
Ah, I guess they are doing their own thing somehow for mac and not using net6.0-mac or net6.0-maccatalyst which how you would go about creating a mac app normally or with .NET MAUI.

So in this case yeah... I wouldn't be able to support what they are doing on desktop it looks like. 

I mean your best bet would be to either use .NET MAUI for desktop or you can use their new Avalonia UI for .NET MAUI so you get the native app shells and can access native APIs

**Comment by lanyusan** [comment]
Got it. Thanks

**Comment by robloo** [comment]
I think the Avalonia can be supported on Windows. Microsoft allows store usage with Win32 apps (desktop bridge apps). The general process for this is outlined here: https://techcommunity.microsoft.com/t5/windows-dev-appconsult/enable-in-app-product-purchases-for-desktop-bridge-converted/ba-p/316901. You just have to interop with the native API's so it isn't quite as straightforward.

I would think since this project supports .NET 6 mac that it would work with Avalonia on that platform already. However, if not, Apple also allows usage of the store through native API's. C# can call into these.

**Comment by lanyusan** [comment]
@jamesmontemagno 

Your plugin can connect to app stores of both mac and windows following suggestions by Avalonia maintainers:

https://github.com/AvaloniaUI/Avalonia/discussions/9636#discussioncomment-4430105

I haven't test other APIs yet but it looks like your plugin would work with Avalonia without code changes from your side.
