### ISSUE TITLE
obfuscatedProfileId requires obfuscatedAccountId to be not null

### ISSUE THREAD

**Issue by domedellolio** [jamesmontemagno/InAppBillingPlugin#513]
Hi there,

we found a possible improvement to be made to the library.
## Context
We were migrating our Xamarim code to version 5.6.1 of the library as the billing process was down due to new restriction to use Google API Billing v4+.

### Bug Information
Version Number of Plugin:  5.6.1
Device Tested On: Android / Samsung

### Steps to reproduce the Behavior (Existing code in our app which was perfectly working before the upgrade )
`InAppBillingPurchase purchase = await CrossInAppBilling.Current.PurchaseAsync(PRODUCT_TO_BUY, ItemType.Subscription, null, profileId.ToString());`

Note: we were inappropriately using the obfuscatedProfileId only in our code (not 100% sure the semantic of this field changed over time)
BTW the returned error was under category: DeveloperError

### Expected Behavior (obfuscatedProfileId requires obfuscatedAccountId to be not null)

From: [https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.Builder#setObfuscatedProfileId(java.lang.String)](url)

![image](https://user-images.githubusercontent.com/11771925/207905547-909fad82-b0a2-4ba0-a271-381f1db09358.png)

### Workaround (using obfuscatedAccountId)
`InAppBillingPurchase purchase = await CrossInAppBilling.Current.PurchaseAsync(PRODUCT_TO_BUY, ItemType.Subscription, accountId.ToString());`

### Improvement
Verify this costraint directly in the library

**Comment by jamesmontemagno** [comment]
See: https://github.com/jamesmontemagno/InAppBillingPlugin/commit/cf7cc36a9cd909b4364ac3c4d19995e6183abd29 for imiprovements
