### ISSUE TITLE
GetPurchasesAsync Exception Error (Android)

### ISSUE THREAD

**Issue by pulmuone** [jamesmontemagno/InAppBillingPlugin#517]
## Bug Information
Version : 
VS2022, 
Android 13
Xamarin.Forms (5.0.0.2545)
Plugin.InAppBilling (6.7.0)
Xamarin.Android.Google.BillingClient (5.1.0)

Error Code :
await CrossInAppBilling.Current.ConnectAsync();
var subs = await CrossInAppBilling.Current.GetPurchasesAsync(ItemType.Subscription); //<- this exception

Error Exception Message : 
TypeRef ResolutionScope not yet handled (46) for .PurchasesResult in image /data/data/app_name/files/.__override__/Plugin.InAppBilling.dll
[0:] Could not resolve type with token 0100003b from typeref (expected class 'PurchasesResult' in assembly '')

BUT Xamarin.Android.Google.BillingClient( 4.0.0)  In 4.0.0 it works fine.

Should I apply the changed part of Xamarin.Android.Google.BillingClient (5.1.0) in Plugin.InAppBilling?

**Comment by jamesmontemagno** [comment]
Don’t update to the new library from google as they have breaking changes
