### ISSUE TITLE
Not issue: When calling PurchaseAsync doe it know what device is using and only calling that store?

### ISSUE THREAD

**Issue by techbud** [jamesmontemagno/InAppBillingPlugin#519]
So when calling purchase Purchase async, does it know what store to call automatically as I have the same product id for google and windows. So my code:

`  var productIds = new string[] { "10", "1", "1" };
                var connected = await billing.ConnectAsync();
                if (!connected)
                    return false;

               ' var items = await billing.GetProductInfoAsync(ItemType.InAppPurchase, productIds);

                InAppBillingPurchase purchase = null;
                foreach (var item in items)
                {
                    switch(item.ProductId)
                    {
                        case "1":
                            purchase = await billing.PurchaseAsync("1", ItemType.InAppPurchase);
                            break;
                        case "2":
                            purchase = await billing.PurchaseAsync("10", ItemType.InAppPurchase);
                            break;
                        default:
                            purchase = null;
                            Debug.WriteLine("Failed to Purchase.");
                            break;
                    }
                }

               

                //possibility that a null came through.
                if (purchase == null)
                {
                    //did not purchase
                }
                else if (purchase.State == PurchaseState.Purchased)
                {
                    // only need to finalize if on Android unless you turn off auto finalize on iOS
                    var ack = await CrossInAppBilling.Current.FinalizePurchaseAsync(purchase.TransactionIdentifier);

                    // Handle if acknowledge was successful or not
                }`
Because they have the same product id they may charge the user twice? I'm assuming that somewhere you're checking for the correct store to call?

Sorry if its a dumb question.

**Comment by techbud** [comment]
bump

**Comment by jamesmontemagno** [comment]
Yes, when your user makes a purchase it will go through Apple, Google, or Microsoft based on the device that it is on. These systems are not tied together or know about purchases across different operating systems.

This means for example if you have an app on iOS & Android and your user has BOTH and iOS & Android device then by default they would need to purchase it on both devices.

The only way around this would for you to create a backend service and tie purchases to an account and store that info in some database. If the user logs in on a device and has purchased it already then you would unlock it.
