### ISSUE TITLE
Compiling errors since lib update (from 4.0.2 to 6.7.0)

### ISSUE THREAD

**Issue by gorbat-o** [jamesmontemagno/InAppBillingPlugin#522]
## Bug Information

Version Number of Plugin: 6.7.0 and all versions in between 4.* and 6.7.0
Device Tested On: MacOS
Simulator Tested On: None
Version of VS: 17.4.3 (Build 21)
Version of Xamarin: 5.0.0.2545
Versions of other things you are using:

### Steps to reproduce the Behavior
Not sure. I updated this library because Google Play Store gave me an error.
![image](https://user-images.githubusercontent.com/7542553/214755515-7d1dca3a-4bbd-4ad1-8b94-7e0ba56ae376.png)

### Expected Behavior
Build.

### Actual Behavior
Failing to build.

https://gist.github.com/gorbat-o/6ea23b43fd64762b057e6c04f923e041

### Code snippet
None needed.

### Screenshot
None needed.

**Comment by jamesmontemagno** [comment]
Did you change your compilation settings to compile against the latest version of Android

**Comment by gorbat-o** [comment]
**AndroidManifest.xml**
<img width="694" alt="image" src="https://user-images.githubusercontent.com/7542553/214926710-a61ef5bc-0942-45c2-ba73-bd4fca76a2e2.png">

**Android Project Configuration** in Build -> General
<img width="869" alt="image" src="https://user-images.githubusercontent.com/7542553/214926945-38aadbf5-b040-41c6-b5b2-60bef1aca7fb.png">

**Comment by gorbat-o** [comment]
[Test.zip](https://github.com/jamesmontemagno/InAppBillingPlugin/files/10514795/Test.zip)
i was able to reproduce this issue here

**Comment by pulmuone** [comment]
> [Test.zip](https://github.com/jamesmontemagno/InAppBillingPlugin/files/10514795/Test.zip) i was able to reproduce this issue here

Xamarin.Android.Google.BillingClient version 5.1.0 in Plugin.InAppBilling causes an error.
Please use Xamarin.Android.Google.BillingClient version 4.0.0.

**Comment by gorbat-o** [comment]
I just tested and it still doesn't compile but I am guessing it's a different issue.

https://gist.github.com/gorbat-o/3d62b6bbf51955f9be2a83a47de371e9

**Comment by pulmuone** [comment]
> I just tested and it still doesn't compile but I am guessing it's a different issue.
> 
> https://gist.github.com/gorbat-o/3d62b6bbf51955f9be2a83a47de371e9

There is a problem with FirebaseDatabase.net in nuget you are using.

**Comment by jamesmontemagno** [comment]
I currently target version 4.0.0 of the google play billing, so that should be brought in automatically.


Keep it simple.. if you only have these nugets

```
  <ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2545" />  
    <PackageReference Include="Xamarin.Essentials" Version="1.7.4" />
    <PackageReference Include="Plugin.InAppBilling" Version="6.7.0" />
  </ItemGroup>
```

works fine.

There is probably some conflict in your dependencies as you have a lot of libraries there. Seems like the firebase ones have some issue.. I removed everything except for 

```
  <ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2545" />  
    <PackageReference Include="Xamarin.Essentials" Version="1.7.4" />
    <PackageReference Include="FirebaseDatabase.net" Version="4.1.0" />
    <PackageReference Include="FirebaseStorage.net" Version="1.0.3" />
    <PackageReference Include="LiteDB" Version="5.0.15" />
  </ItemGroup>
```

This wont compile either, so nothing to do with my library

**Comment by gorbat-o** [comment]
Thank you for the help! the compiler is showing unrelated errors :/
