### ISSUE TITLE
Bug GetPurchasesHistoryAsync

### ISSUE THREAD

**Issue by pulmuone** [jamesmontemagno/InAppBillingPlugin#523]
## Bug Information

Case: ItemType. Subscription (Android)
In the result of GetPurchasesHistoryAsync, the PurchaseState value is always looked up as PurchaseState.Unknown only.
The expiration date has not passed, but PurchaseState.Unknown is there, is there a problem?

Thank you.

Version Number of Plugin: 6.7.0
Device Tested On: Android 13 (Galaxy S20)
Simulator Tested On:
Version of VS:  VS2022
Version of Xamarin:  5.0.0.2545

**Comment by jamesmontemagno** [comment]
Correct, it doesn't' exist they are purchases https://developer.android.com/reference/com/android/billingclient/api/PurchaseHistoryRecord#:~:text=%20PurchaseHistoryRecord%20public%20class%20PurchaseHistoryRecord%20extends%20Object%20Represents,signature%29%20Inherited%20methods%20From%20class%20java.lang.Object%20Public%20constructors

You most likely do not want to use this and want to use 'GetPurchasesAsync'

**Comment by jamesmontemagno** [comment]
See https://github.com/android/play-billing-samples/issues/225

**Comment by pulmuone** [comment]
> See [android/play-billing-samples#225](https://github.com/android/play-billing-samples/issues/225)
Thank you. ~^^
