### ISSUE TITLE
iPhone simulator and device | An unknown error occurred calling billing.PurchaseAsync

### ISSUE THREAD

**Issue by myonlinegolfclub** [jamesmontemagno/InAppBillingPlugin#526]
## Bug Information

Version Number of Plugin: 5.6.1
Device Tested On: iPhone 13 iOS 16.3.1
Simulator Tested On: Simulator 14.2 (986.5)
Version of VS: Visual Studio for Mac 17.4.4 (build 12)
Version of Xamarin: 4.8.0.1687
Versions of Essentials: 1.7.4

### Steps to reproduce the Behavior

1. Add Plugin.InAppBilling to the project
2. Follow all steps here: https://jamesmontemagno.github.io/InAppBillingPlugin/GettingStarted.html
3. Create a Sandbox user and verify the email address
4. Call var billing = CrossInAppBilling.Current; (Works correctly)
5. Call var connected = await billing.ConnectAsync(); (Returns true as expected)
6. Call var a = await billing.GetProductInfoAsync(ItemType.Subscription, "IDHERE"); (Returns subscription details as expected)
7. Call var purchase = await billing.PurchaseAsync(productId: productId, itemType: ItemType.Subscription);

### Expected Behavior

1. Should ask you to login and then show purchase popup

### Actual Behavior

1. Shows login box where you login with the sandbox user account
2. It hangs for a few seconds and then throws the following InAppBillingPurchaseException error:
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/25149881/225071118-27ba4931-e803-4723-85aa-af9f588da378.png">
  at Plugin.InAppBilling.InAppBillingImplementation.PurchaseAsync (System.String productId, Plugin.InAppBilling.ItemType itemType, System.String applicationUserName) [0x0017a] in D:\a\1\s\src\Plugin.InAppBilling\InAppBilling.apple.cs:426 
  at Plugin.InAppBilling.InAppBillingImplementation.PurchaseAsync (System.String productId, Plugin.InAppBilling.ItemType itemType, System.String obfuscatedAccountId, System.String obfuscatedProfileId) [0x00036] in D:\a\1\s\src\Plugin.InAppBilling\InAppBilling.apple.cs:321 
  at PAGENAME (System.String productId, System.String payload) [0x0019c] in LOCATION

### Code snippet
<img width="857" alt="image" src="https://user-images.githubusercontent.com/25149881/225071705-0405307f-50d7-401a-ae52-d63b1d04cb4e.png">

**Comment by myonlinegolfclub** [comment]
Works in TestFlight! Just not on simulator.

**Comment by jamesmontemagno** [comment]
Works only on device, not on simulators
