### ISSUE TITLE
Using Google Play Subscription Offers

### ISSUE THREAD

**Issue by Allough** [jamesmontemagno/InAppBillingPlugin#530]
Thanks for all your hard work on this plugin!

Is there a way to use Google Play offers via this plugin?

For example, I have a subscription with a product id of "basic5". That subscription is currently setup with a base plan with an id also of "basic5" for $9.99. Below that I have two offers. Offer id "basic5free" gets you 1 year free. Offer id "basic5half" gets you 1 year 50% off. Both offers revert to the base plan after the first year.

If I call GetProductInfoAsync with "basic5" i get a price of $9.99. If I try to do the same call with one of the offer id's, I get nothing.

I have to admit that I didn't try calling PurchaseAsync, because I figured if I couldn't get the product info for the offers, I probably can't purchase them either.

**Comment by proteux** [comment]
looks like it might be a work in progress: https://github.com/jamesmontemagno/InAppBillingPlugin/blob/android-v5/src/Plugin.InAppBilling/InAppBilling.android.cs#L277 granted this just uses the first offer instead of letting you specify one

**Comment by jamesmontemagno** [comment]
yes, you can pull down version 7.0.3-bet and start  trying there. 

for purchasing i think i need to have folks pass in an offertoken or something like that.

**Comment by Allough** [comment]
Awesome thank you! I'll try it out next week

**Comment by jamesmontemagno** [comment]
sounds good, let me know how it goes and feel free to post on the PR

**Comment by jamesmontemagno** [comment]
Merging with #521
