### ISSUE TITLE
`NullReferenceException` in `PurchaseAsync` on iOS

### ISSUE THREAD

**Issue by BioTurboNick** [jamesmontemagno/InAppBillingPlugin#533]
## Bug Information

```
Plugin.InAppBilling.InAppBillingImplementation.PurchaseAsync(String productId, ItemType itemType, String obfuscatedAccountId, String obfuscatedProfileId)
```
https://github.com/jamesmontemagno/InAppBillingPlugin/blob/ac395d86e03e7c62d26338624449099960332cb3/src/Plugin.InAppBilling/InAppBilling.apple.cs#L318

Opportunities for nulls in this function are:
- `SKPaymentTransaction` obtained on line 321 may be null
- The `SKPaymentTransaction` object obtained on line 321 may have a null value for `TransactionDate`: https://developer.apple.com/documentation/storekit/skpaymenttransaction

But it's not clear to me when these would occur.

Version Number of Plugin: v6.6.2.1
Device Tested On: iPhone XR, iOS 13.3
Simulator Tested On: n/a
Version of VS: 17.5.4
Version of MAUI: 7.0.86

### Steps to reproduce the Behavior

Unsure, reported in AppCenter on a live device.

### Expected Behavior

No NullReferenceException

### Actual Behavior

NullReferenceException

**Comment by jamesmontemagno** [comment]
Will fix this up in v7
