### ISSUE TITLE
Support for Billing Library version 5 or newer ?

### ISSUE THREAD

**Issue by SKallem439** [jamesmontemagno/InAppBillingPlugin#538]
@jamesmontemagno Hi James, before Nov 01-2023, do We need to upgrade to Billing Library version 5 or newer? As of now, our latest Nuget supports for Play Billing library version for 4 only.

Is there any ETA on that?

Sharing the screenshot for reference.
![image](https://github.com/jamesmontemagno/InAppBillingPlugin/assets/129407269/700b3d2c-16be-4049-82bf-469b01d77571)

Thanks in advance.

**Comment by jamesmontemagno** [comment]
See - https://github.com/jamesmontemagno/InAppBillingPlugin/issues/521 already do in preview
