### ISSUE TITLE
System.TypeLoadException with BillingSDK V5 or V6

### ISSUE THREAD

**Issue by overzealus** [jamesmontemagno/InAppBillingPlugin#539]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 6.7.0
Device Tested On: Samsung M21 Android 12
Simulator Tested On:
Version of VS: 17.5.4
Version of Xamarin: 17.5.0.173, Xamarin Android 13.2.0.0
Versions of other things you are using:

### Steps to reproduce the Behavior
Updated Xamarin.Android.Google.BillingClient package to version 5.2.0 or 6.0.0.1, after that calling  await billing.GetPurchasesAsync(ItemType.InAppPurchase) throws exception.
### Expected Behavior
Should provide purchases list without exceptions.
### Actual Behavior
Throwing exception: System.TypeLoadException: Could not resolve type with token 0100003b from typeref (expected class 'PurchasesResult' in assembly '')
### Code snippet
```
var connected = await billing.ConnectAsync();
if (connected)
{
   var purchasesOneTime = await billing.GetPurchasesAsync(ItemType.InAppPurchase);
}
```

**Comment by pulmuone** [comment]
Which version of Plugin.InAppBilling do you use?
Last Verison 7.0.5-beta

**Comment by jamesmontemagno** [comment]
Correct, you will need to change to v7 beta as you can't just updated the billing library yourself... apis change
