### ISSUE TITLE
In GetPurchasesAsync(), iOS auto-renew subscriptions return date of original subscription, not date of each specific subscription renewal

### ISSUE THREAD

**Issue by mpnow** [jamesmontemagno/InAppBillingPlugin#54]
In the iOS implementation of GetPurchasesAsync(), the list of purchase objects is created using the ToIABPurchase method. That method populates its data using the OriginalTransaction object [here](https://github.com/jamesmontemagno/InAppBillingPlugin/blob/685a18d98e057912d163f12eb99476ef1ab98ff5/src/Plugin.InAppBilling.iOS/InAppBillingImplementation.cs#L406):

           var p = transaction.OriginalTransaction;

This means that the TransactionDateUtc property, which is set just below that, is set to the TransactionDate of the _initial subscription purchase_ even for all subsequent auto-renewal purchase records that the iTunes Store returns.  These subsequent auto-renewal records contain their own TransactionDate property which is the date that specific auto-renewal occurred; but this date is not propagated back to GetPurchasesAsync().

Wouldn't it be better to set the TransactionDateUtc of each returned purchase record to its own TransactionDate, instead of the transaction date of the OriginalTransaction?

in other words, [here](https://github.com/jamesmontemagno/InAppBillingPlugin/blob/685a18d98e057912d163f12eb99476ef1ab98ff5/src/Plugin.InAppBilling.iOS/InAppBillingImplementation.cs#L415) instead of 

                TransactionDateUtc = NSDateToDateTimeUtc(p.TransactionDate),

wouldn't it be better to do this:

                TransactionDateUtc = NSDateToDateTimeUtc(transaction.TransactionDate),

That way, we could use the TransactionDate of the most recent returned InAppBillingPurchase object to know when the user's current subscription started, and combine that with the known length of the subscription to determine if the user has a current valid subscription or not, which is really the whole endpoint I'm trying to get to.

Or alternatively, is this all a moot point and I'm missing a better way to determine if the iOS user has a current valid subscription??

**Comment by mpnow** [comment]
I realize now after further reading and research that the above is not the proscribed way to determine if an auto-renewing subscription is valid or expired.  I believe the correct way is to:

(1) retrieve the user's receipt using **NSData.FromUrl(NSBundle.MainBundle.AppStoreReceiptUrl)**
(2) validate that receipt with the App Store
(3) extract the **latest_receipt** value from the receipt returned from the App Store in (2) above
(4) validate that receipt with the App Store
(5) extract the **in_app** array from the receipt returned in (4) above
(6) use the **expires_date** property of the most recent receipt in the **in_app** array to determine if the user is currently subscribed or not.

If someone can confirm the above steps, that would be great.  It seems to be working properly for me using that sequence.

**Comment by jamesmontemagno** [comment]
Have you read through: http://jonathanpeppers.com/Blog/securing-in-app-purchases-for-xamarin-with-azure-functions ?

**Comment by jamesmontemagno** [comment]
Going to close as I think you have everything you need here.

**Comment by mpnow** [comment]
Yes - not only read it but used it to implement my receipt verification. Works great!

**Comment by jho123456** [comment]
Hi James,

I'm also trying to get the autorenew status of my subscription. 

In the App Store I have configured an Auto-Renewable Subscription. 

I'm using the following to purchase and restore respectively:

InAppBillingPurchase purchase = await billing.PurchaseAsync(MYSUBSCRIPTION_PRODUCTID, _itemType);

and

List<InAppBillingPurchase> purchases = (await billing.GetPurchasesAsync(ItemType.Subscription))?.ToList();
InAppBillingPurchase purchase = the latest purchase in the purchases list

The iPhone system message assures that the purchase will be autorenewing until cancelled.

However the purchase that is returned always has the following set:

purchase.AutoRenewing == false;

Is this a problem with the way I'm using the plugin APIs or is it a problem with the plugin?

Whatever the case I'd like to get the autorenew status without using a server if possible.
