### ISSUE TITLE
Sdk Style Project mixing Xamarin and Maui in the same version? 

### ISSUE THREAD

**Issue by EmilAlipiev** [jamesmontemagno/InAppBillingPlugin#540]
Hi @jamesmontemagno,

Sorry if that is a wrong place to ask this question but i couldnt find any discussion tab or similar. 
I see in your project file you have defined xamarin and maui together

`   <TargetFrameworks>netstandard2.0;MonoAndroid10.0;Xamarin.iOS10;Xamarin.TVOS10;Xamarin.Mac20;net6.0-android;net6.0-ios;net6.0-maccatalyst;net6.0-tvos;net6.0-macos</TargetFrameworks>`

but you say in the description to use v6.x for maui and v5 for xamarin. I am concerned and very much interested into understand why is that?
Can we not have a single version supporting Xamarin and Maui in Sdk Style projects in the same version?

You have done nice videos about Sdk style projects in the past. Maybe it is another idea to extend with this question how far we can extend the TargetFrameworks for Sdk Style projects?

thanks for your answer

**Comment by jamesmontemagno** [comment]
v7 aligns this together and takes care of it.

It doesn't really matter, mostly just which version of VS it was built against.
