### ISSUE TITLE
Is v7 of .Net Maui supported?

### ISSUE THREAD

**Issue by EdwardMcFlurry** [jamesmontemagno/InAppBillingPlugin#541]
Hi @jamesmontemagno 

Does the plug-in support the latest version of .Net Maui (iOS) as I seem not to make any Purchases using the provided productid that is correct and valid?

**Comment by jamesmontemagno** [comment]
Yup, is fully supported.

**Comment by EdwardMcFlurry** [comment]
Eish @jamesmontemagno I have been getting this error every time I attempt to make a Non-Renewing-Subscription purchase but with the following error below

![00aff176-2ddf-4ea4-bd82-239c302f182e 2](https://github.com/jamesmontemagno/InAppBillingPlugin/assets/46613832/32c96446-b996-44d0-92f3-34fd5ffdacd5)

**Comment by EdwardMcFlurry** [comment]
> Eish @jamesmontemagno I have been getting this error every time I attempt to make a Non-Renewing-Subscription purchase but with the following error below
> 
> ![00aff176-2ddf-4ea4-bd82-239c302f182e 2](https://user-images.githubusercontent.com/46613832/248570714-32c96446-b996-44d0-92f3-34fd5ffdacd5.JPG)

@jamesmontemagno any idea what went wrong here 🙏🏻

**Comment by jamesmontemagno** [comment]
What did you set the duration for your subscription?

**Comment by EdwardMcFlurry** [comment]
> What did you set the duration for your subscription?

@jamesmontemagno sorry, I was away for a while.

Please see attached screenshot...

<img width="1223" alt="Screenshot 2023-07-25 at 14 38 02" src="https://github.com/jamesmontemagno/InAppBillingPlugin/assets/46613832/c6be23d0-8a7f-4048-bd54-41f01e6bc5bf">

**Comment by EdwardMcFlurry** [comment]
> > What did you set the duration for your subscription?
> 
> @jamesmontemagno sorry, I was away for a while.
> 
> Please see attached screenshot...
> 
> <img alt="Screenshot 2023-07-25 at 14 38 02" width="1223" src="https://user-images.githubusercontent.com/46613832/255901344-c6be23d0-8a7f-4048-bd54-41f01e6bc5bf.png">

@jamesmontemagno in order for me to accurately test this out on my physical iPhone, do I need to set up the Development certificate & provisional profile on the AppStoreConnect with the same BundleID or can I just use my Production certs???

**Comment by jamesmontemagno** [comment]
Yes, you need to test on a physical device with all your certs or from testflight.

INTestingMode is just a windows things

**Comment by jamesmontemagno** [comment]
Make sure you ar querying the item correct first for product details

**Comment by EdwardMcFlurry** [comment]
@jamesmontemagno no it's alright, I managed to crack it and eventually released it to App Store for review and it passed. First time releasing an App to Apple Store and I'm super excited 😎
