### ISSUE TITLE
Deprecation alert 

### ISSUE THREAD

**Issue by francescovigot** [jamesmontemagno/InAppBillingPlugin#542]
Hi
Despite, I use the 6.7 version, I got this alert in my google play developer console, I attached a screenshot.
![billing](https://github.com/jamesmontemagno/InAppBillingPlugin/assets/29005428/6bc9af26-50c8-49b2-b481-ec0a2827b85c)

**Comment by jamesmontemagno** [comment]
You need to upgrade to the 7.0-beta

**Comment by francescovigot** [comment]
But the latest version available in visual studio and Nuget is 6.7.0

**Comment by francescovigot** [comment]
Any news? please check the screenshot.
![Untitled](https://github.com/jamesmontemagno/InAppBillingPlugin/assets/29005428/1fc3dcd9-ca0a-48e0-9260-6a9498635e45)

**Comment by broda02** [comment]
Change nuget to allow beta levels ?On 9 Jul 2023, at 16:24, Francesco Vigot ***@***.***> wrote:﻿
Any news? please check the screenshot.

**Comment by francescovigot** [comment]
I Installed the latest version of the IAB with this command NuGet\Install-Package Plugin.InAppBilling -Version 7.0-beta
but when I want to connect to the google play gateway, nothing happens

`  public async Task PurchaseSubscription(string subId)
        {



            if (_isBusy)
                return;

            _isBusy = true;
            try
            {

                // check internet first with Essentials
                if (Connectivity.NetworkAccess != Xamarin.Essentials.NetworkAccess.Internet)
                    return;



                // connect to the app store api
                var connected = await CrossInAppBilling.Current.ConnectAsync();
                if (!connected)
                    return;



                //try to make purchase, this will return a purchase, empty, or throw an exception
                var purchase = await CrossInAppBilling.Current.PurchaseAsync(subId, ItemType.Subscription);
                ShowProgressDialog("Please Wait....");
                `
