### ISSUE TITLE
Google Play Billing version 5 with a Xamarin app

### ISSUE THREAD

**Issue by om297** [jamesmontemagno/InAppBillingPlugin#543]
I'm using InAppBillingPlugin v5.x with a Xamarin App, as per your recommendations.

Play console is giving the following message: 
"We've detected that this app is using an old version of Google Play Billing. From November 1, 2023, all app updates must use Billing Library version 5 or newer."

Is Billing v5 supported by InAppBillingPlugin and specifically is there a recommended solution for using InAppBillingPlugin in Xamarin Apps beyond November 2023?

**Comment by pulmuone** [comment]
![image](https://github.com/jamesmontemagno/InAppBillingPlugin/assets/42885949/3f8ad25d-d4f6-4d69-862e-e4f078afde6b)

**Comment by znematov** [comment]
> ![image](https://user-images.githubusercontent.com/42885949/252864132-3f8ad25d-d4f6-4d69-862e-e4f078afde6b.png)

Does this beta version use the new version of the billing library?, How can know what version is the IAP using?

**Comment by hoangonpattern** [comment]
Hi @jamesmontemagno 
We developed an MAUI mobile application, that is using InAppBillingPlugin ver 6.7.0, (which means using the Google Play Billing version 4) on which we identify our trial period by checking the value of the property:
InAppBillingProductAndroidExtras.FreeTrialPeriod

At the moment, we got the same notification from Google that required us to update Google Play Billing to a version that is greater or equal to 5, following this thread we updated the InAppBillingPlugin to the latest version 7.0.5-beta, that uses the Google Play Billing version 6.

At this version, the property InAppBillingProductAndroidExtras.FreeTrialPeriod does not exist any more..

Is there an alternative property from the class InAppBillingProductAndroidExtras for this obsoleted one please?
We would need to check is there a free trial period existing from the product.

Many thanks!

**Comment by jamesmontemagno** [comment]
So you need to check the migration docs from Google as they have changed their entire API... becuase they always do.

Most details are in the phase: https://developer.android.com/reference/com/android/billingclient/api/ProductDetails.PricingPhases which are found in the SubscriptionOfferDetails
