### ISSUE TITLE
Question: Is there a way to "Restore" purchases from other apps if bundle ID + product ID is known?

### ISSUE THREAD

**Issue by Sebastian1989101** [jamesmontemagno/InAppBillingPlugin#546]
I have a subscription model in my apps that unlocks all of my apps. As of now, the user has to "Restore" it in the subscriptions origin app each period so that the token I use to share these info is refreshed. However as part of the token, I also know the origins bundle ID and product ID. Would it be possible to call the restore method with these (and maybe more) infos to get the updated period for the subscription once it has expired?

**Comment by pulmuone** [comment]
Android adds Google.Apis.AndroidPublisher.v3 to nuget
This can be done with the code below.
Example)
_googleService.Purchases.Subscriptionsv2.Get(packageName, purchaseToken);
Android needs to apply for "Enable Google API access" in the Google Play Console.
(https://learn.microsoft.com/en-us/dotnet/maui/android/deployment/publish-google-play#enable-google-api-access)

Day Quotas = 200,000
https://developers.google.com/android-publisher/quotas?hl=en

200,000 over Request
https://support.google.com/googleplay/android-developer/contact/apiqr?hl=en

iOS verifies with http.
![ios](https://github.com/jamesmontemagno/InAppBillingPlugin/assets/42885949/ee89e8de-72d0-44d6-834c-05baa46a2e2a)

However, iOS can be used for free if you log in to your subscription account from another smartphone without having to share your family account.
I found 12 people using one subscription and created a subscription management service in Azure Funciton.

**Comment by Sebastian1989101** [comment]
Thanks for the reply, however this does not match the question (or do I just miss something here?). My question is related to: 

App 1: Starts subscription. 
App 2: Should also benefit from subscription of App 1, I do this with a Token I share through iCloud bound to the User Account. However, this token needs to be refreshed from App 1 on each new period (so each month on monthly subscription). 

What I look for is, that App 2 is also able to access the purchases of App 1 so it is able to refresh the subscription token itself.

**Comment by pulmuone** [comment]
If you know the PurchaseToken, you can do this.
RequestBody's password can be requested from Apple Developer.
![ios2](https://github.com/jamesmontemagno/InAppBillingPlugin/assets/42885949/43525a67-dca2-4689-b115-bb43b6e9374b)

**Comment by pulmuone** [comment]
If both Android and iOS know the purchaseToken, they can query the subscription status (expiration date) of that token.

**Comment by Sebastian1989101** [comment]
I see. In that case I have to just add a 2nd method to my Web API that does the validation if the bundle ID differs. Thanks for the input! :)

**Comment by pulmuone** [comment]
There are two passwords in iOS.
Global password :
appstoreconnect -> User and Access -> Share password

App password:
app info -> app share password

**Comment by jamesmontemagno** [comment]
Thanks for the input on this one. closing now
