### ISSUE TITLE
Navigating back when the GPay widget appears results in an error

### ISSUE THREAD

**Issue by Engisan** [jamesmontemagno/InAppBillingPlugin#549]
Version Number of Plugin: 7.0.5
Device Tested On: Samsung S21 FE, latest Android updated
Simulator Tested On: -
Version of VS: 17.7.0
Version of Xamarin:  7.0.92/7.0.100         VS 17.7.34003.232  
Versions of other things you are using: 
akgul.Maui.DataGrid 3.0.0
Community Toolkit 5.3.0
Plugin.Firebase 2.0.5
Microsoft.AspNetCore.SignalR.Client 7.0.5
+ standard packages installed when a new MAUI project is created

### Steps to reproduce the Behavior
1. Start the payment process as documented (connect the current billing, purchase consumable product)
2. Right after the bottom google payment widget appears, press BACK android button

### Expected Behavior
The widget is closed, nothing happens

### Actual Behavior
Exception:
Android.Views.InflateException: 'Binary XML file line #41 in com.roombet.roombet365:layout/design_layout_snackbar_include: Binary XML file line #41 in com.roombet.roombet365:layout/design_layout_snackbar_include: Error inflating class android.widget.Button'

Android.Runtime.JNIEnv.monodroid_debugger_unhandled_exception
in Android.Runtime.JNINativeWrapper._unhandled_exception at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:12,5
in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:23,26
in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
in System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0
in Android.App.SyncContext. at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:36,19	
in Java.Lang.Thread.RunnableImplementor.Run at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36,6
in Java.Lang.IRunnableInvoker.n_Run at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Java.Lang.IRunnable.cs:84,4
in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:22,5

**Comment by Engisan** [comment]
It actually crashes everytime when the payment is not properly paid, everytime I close the payment widget the app crashes. For me this is a big problem because this cannot go to production at all :/
@jamesmontemagno any idea when you would be able to look into this?

**Comment by jamesmontemagno** [comment]
What does your code look like? This looks like you are calling it from some third party library perhaps and it isn't handling it properly. What if you call it from just a button on a page?

**Comment by Engisan** [comment]
@jamesmontemagno 
No, pretty normal page.

Xaml:
`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
            xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
            x:Class="FunRivalsMobile.Views.MainViewTest">
    <VerticalStackLayout>
        <Button Clicked="DoPay" Text="Test In-App Payment"></Button>
    </VerticalStackLayout>
</ContentPage>`

And code behind:
`public partial class MainViewTest : ContentPage
{
    private readonly IPaymentService _paymentService;
    public MainViewTest()
    {
        InitializeComponent();
        _paymentService = MauiProgram.Services.GetRequiredService<IPaymentService>();
    }

    private async void DoPay(object sender, EventArgs e)
    {
        try
        {
            await _paymentService.PaySubscription();
        }
        catch (Exception ex)
        {
            await ToastService.ShowAlert($"Errrrrrror! {ex.ToString()}");
        }

    }
}`

And here is the test method from the PaymentService
`public async Task PaySubscription()
{
    var billing = CrossInAppBilling.Current;
    try
    {
        var connected = await billing.ConnectAsync();
        if (!connected)
        {
            throw new ApplicationException("Purchasing process did not connect to store. Payment was not processed.");
        }

        var purchase = await billing.PurchaseAsync("subscription1", ItemType.Subscription);

        if (purchase == null)
        {
            throw new ApplicationException("Null purchase result. The payment did not process correctly");
        }
    }
    catch (Exception ex)
    {
        //log resp transaction to azure together with the general ex detail
        throw;
    }
    finally
    {
        await billing.DisconnectAsync();
    }
}`

The purchase widget appears on the bottom, once it is closed, the app crashes. It does not matter on when you close the widget.

**Comment by jamesmontemagno** [comment]
What is your ToastService doing? get rid of that and see what happens

**Comment by Engisan** [comment]
Oh wow... a good tip. The Toast service shows Toast or Snackbar from CommunityToolkit, depending on the parameters. And it works fine in my app, everywhere I use it.

BUT when combined with the payment widget, it does not work! I would not expect that. Anyway, that was the root cause here. 

Thank you for your time, James! I guess you can close this one as it seems to be rather the CommunityToolkit issue.
