### ISSUE TITLE
com.android.vending.BILLING is deprecated

### ISSUE THREAD

**Issue by WPDeveloper011** [jamesmontemagno/InAppBillingPlugin#551]
I am using latest version of Plugin in my Xamarin app which was working fine till 31-Aug but with now google has deprecated "com.android.vending.BILLING" and asked to replace it with "com.google.android.play.billingclient.version", plugin is not working. It fails when user click on making any in-app purchase.

Request you to fix this.

**Comment by Toine-db** [comment]
Same here, just received the following message:

_By November 1, 2023 version 4 will be deprecated and any updates to existing apps will first require you to migrate to PBL version 5 or newer._

**Comment by jamesmontemagno** [comment]
V7 uses the newest version.
