### ISSUE TITLE
Apple Receipt Verifier

### ISSUE THREAD

**Issue by nealculiner** [jamesmontemagno/InAppBillingPlugin#552]
I'm late to things like this as always but on my server I use the REST API /verifyReceipt which I'm learning is deprecated as I update my server side services. Have you considered adding the new Apple receipt verification functionality in your plugin so we have an all in one solution for our apps?

https://developer.apple.com/documentation/appstorereceipts

https://developer.apple.com/documentation/appstorereceipts/validating_receipts_on_the_device

Thank you.

**Comment by pulmuone** [comment]
I developed it by changing it to the App Store Server API method.
Deployed to Azure-Function.
https://blog.naver.com/gwise/223212329137

**Comment by dmariogatto** [comment]
Another sample implementation using Azure Functions,

- Using the deprecated [verifyReceipt](https://github.com/dmariogatto/azure-functions-iap-verify/blob/82f328b5654f8fcdb328865dd4bab24c8ff947e4/src/Iap.Verify/AppleVerifyReceipt.cs) endpoint
- Using the new [App Store Server](https://github.com/dmariogatto/azure-functions-iap-verify/blob/82f328b5654f8fcdb328865dd4bab24c8ff947e4/src/Iap.Verify/AppleVerifyTransaction.cs) API

**Comment by pulmuone** [comment]
> Another sample implementation using Azure Functions,
> 
> * Using the deprecated [verifyReceipt](https://github.com/dmariogatto/azure-functions-iap-verify/blob/82f328b5654f8fcdb328865dd4bab24c8ff947e4/src/Iap.Verify/AppleVerifyReceipt.cs) endpoint
> * Using the new [App Store Server](https://github.com/dmariogatto/azure-functions-iap-verify/blob/82f328b5654f8fcdb328865dd4bab24c8ff947e4/src/Iap.Verify/AppleVerifyTransaction.cs) API

very good~

**Comment by jamesmontemagno** [comment]
Closing due to response. thanks for the samples!

**Comment by nealculiner** [comment]
We don't all use azure so there is no solution here for me.
