### ISSUE TITLE
Android PBL 5.0 + compliance / compatibility?

### ISSUE THREAD

**Issue by blmiles** [jamesmontemagno/InAppBillingPlugin#555]
Hello,

@jamesmontemagno 

## re Msg about Google Play Billing Library

I received this from Google and have implemented the current version of THIS library, yet to be deployed.

_We are sending you this reminder as one or more of your apps is still using Play Billing Library (PBL) version 4. By November 1, 2023 version 4 will be deprecated and any updates to existing apps will first require you to migrate to PBL version 5 or newer.
Important notes: If your app is targeting Android 14 or higher, you must update to PBL 5.2.1 or PBL 6.0.1 or higher._

According to your version notes, which I think are dated ...
Android: **We now use Google Play Billing Version 4.0!**

According the package mngr, Plugin.InAppBilling targets _Xamarin.Android.Google.BillingClient 6.0.1_

**Does Plugin.InAppBilling target Google's Play Billing Library (PBL) 5.2.1 or (PBL) 6.0.1 or higher?**

Thank you!

**Comment by Meekohi** [comment]
Looks like it already uses Billing Client 6.0?
https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/src/Plugin.InAppBilling/Plugin.InAppBilling.csproj#L101C29-L101C29
Would be nice if someone can confirm.

**Comment by blmiles** [comment]
@Meekohi  Actually, I was just about to post ...
According to the release notes:
Version 7.0+  - Major Android updates
....
**2.) Android: Now using Android Billing v6**
....
