### ISSUE TITLE
Getting Trial period of subscription on Android

### ISSUE THREAD

**Issue by Dizmus** [jamesmontemagno/InAppBillingPlugin#558]
## Bug Information

Version Number of Plugin: 7.0.5
Device Tested On: Google Pixel 7 Pro
Simulator Tested On:
Version of VS: VS for Mac
Version of Xamarin: Xamarin.Android - Version: 13.2.1.2
Versions of other things you are using:

### Steps to reproduce the Behavior

Install Plugin.InAppBilling to Android application (Xamarin or MAUI)
Try to retrieve FreeTrialPeriod Length

### Expected Behavior

InAppBillingProductAndroidExtras contains information about Trial Length

### Actual Behavior

subscriptionOfferDetail.BasePlanId and PricingPhase.BillingPeriod contains about the subscription itselft

### Code snippet

InAppBillingProductAndroidExtras inAppBillingProductAndroidExtras = inAppBillingProduct.AndroidExtras;
            var subscriptionOfferDetail = inAppBillingProductAndroidExtras.SubscriptionOfferDetails.SingleOrDefault();

            if (subscriptionOfferDetail == null)
            {
                throw new Exception($"Offer of subscription is not found");
            }
            
            var freeTrialPeriod = subscriptionOfferDetail.BasePlanId;

            var phase = subscriptionOfferDetail.PricingPhases.Single();

            switch (freeTrialPeriod.ToUpper())
            {
                case "P3D":
                    return 3;
                case "P7D":
                case "P1W":
                    return 7;
                default:
                    throw new Exception($"Cannot parse length of subscription: {freeTrialPeriod}");
            }

**Comment by Dizmus** [comment]
<img width="630" alt="image" src="https://github.com/jamesmontemagno/InAppBillingPlugin/assets/5767723/3b027919-a1b1-4e0e-8f63-338228821a2b">

**Comment by jamesmontemagno** [comment]
Unfortunatelly Google got rid of it :( you have to parse it yourself: https://stackoverflow.com/questions/72632982/how-to-get-freetrialperiod-of-subscribtion-from-productdetails

**Comment by Dizmus** [comment]
@jamesmontemagno , thanks, now I got it. 
Google doesn't send information about trial offer if user is not eligible for it. So, basically, there is no way to get trial length is user has already purchased a subscription
