### ISSUE TITLE
PurchaseAsync crashes without exception in Release mode on iOS.

### ISSUE THREAD

**Issue by DFerenczi** [jamesmontemagno/InAppBillingPlugin#56]
Hi!

## Bug Information
We've implemented the procedure to make an IAP in our viewmodel and it works great on Android where we have successfully published an alpha-version of the app och purchased products without any problems. 

On iOS however we are trying to get or app and IAP-product approved by Apple with the same code. When debugging the code (same code as for android ofc) we can go through the purchase-procedure in a sandbox-environment which is great. 

So we archived and sent our IPA to apple for review and got rejected because the app crashed when they tried to purchase a product, without any message. This is how we found out that purchasing a product doesn't work in release. Please see code below. 

We know we "get past" the ConnectAsync call and we know we connect successfully through adding DialogService.ShowMessage all over the place but we never see Dialog box in the catch-block. And the app just crashes without any output. This suggests that the PurchaseAsync function fails without throwing an exception? Is this possible? We don't understand how/why the catch-block doesn't hit. 

Version Number of Plugin: 1.1.0.34-beta
Device Tested On: iPhone 6 10.3.2, iPhone 7 10.3.2
Simulator Tested On: N/A
Version of VS: Visual Studio for Mac 7.01
Version of Xamarin: Xamarin Mac 3.4.0.36
Versions of other things you are using: N/A

### Expected Behavior
Not expecting a purchase to be made since Apple hasn't approved the app/IAP-product but maybe a sanbox-purchase? Or at least expecting a exception to be thrown.

### Actual Behavior
App crashes without exception. 

### Code snippet
```
                try
                {
                    IsLoading = true;
                    var productId = "questionnaire1";
                    var isConnected = await CrossInAppBilling.Current.ConnectAsync();
                    if (!isConnected)
                    {
                        return;
                    }

                    var purchase = await CrossInAppBilling.Current.PurchaseAsync(productId, ItemType.InAppPurchase, "apppayload", msgData.Verification);
                    if (purchase == null)
                    {
                        await DialogService.ShowError(Translations.TXT_COULD_NOT_PURCHASE_FUNDS_OR_INTERNET, Translations.TXT_COULD_NOT_PURCHASE_QUESTIONNAIRE_TITLE, "OK", null);
                        IsLoading = false;
                    }
                    else
                    {
                        var purchaseResult = await Analys360Service.PurchaseQuestionnaire(msgData.QuestionnaireId, CurrentUser);
                        if (purchaseResult.Error != null || !purchaseResult.Result)
                        {
                            await DialogService.ShowError(Translations.TXT_COULD_NOT_PURCHASE_FUNDS_OR_INTERNET, Translations.TXT_COULD_NOT_PURCHASE_QUESTIONNAIRE_TITLE, "OK", null);
                            IsLoading = false;
                        }
                        else
                        {
                            await DialogService.ShowMessage(Translations.TXT_QUESTIONNAIRE_UNLOCKED, Translations.TXT_PURCHASE_SUCCESSFUL_TITLE);
							
                            if (Device.RuntimePlatform == Device.Android)
							{
								var c = await CrossInAppBilling.Current.ConsumePurchaseAsync(purchase.ProductId, purchase.PurchaseToken);
								
                                if (c != null)
								{
                                    System.Diagnostics.Debug.WriteLine("Consumed!");
								}
								else
								{
                                    System.Diagnostics.Debug.WriteLine("Failed consumed!");
								}
							}
                        }

						await FetchQuestionnaires();
						IsLoading = false;
                    }
                }
                catch (Exception e)
                {
                    await DialogService.ShowMessage(Translations.TXT_PURCHASE_NOT_COMPLETED, Translations.TXT_PURCHASE_CANCELED);  <--- THIS DIALOG IS NEVER SHOWN..
                }
                finally
                {                    
                    await CrossInAppBilling.Current.DisconnectAsync();
                    IsLoading = false;
                }        
```     

Thanks i advance!

/Daniel

**Comment by jamesmontemagno** [comment]
Are you using advanced linker modes in release? You may want to link skip them out.  Without a stack trace I can not help as I have 2 apps in the app store using the plugin without issue. 

Recommendation is to test your app in Test Flight and check sandbox user to see what is happening.
