### ISSUE TITLE
This app targets Android 14 or above, and your current Play Billing Library version doesn't support Android 14.

### ISSUE THREAD

**Issue by MichaelSL** [jamesmontemagno/InAppBillingPlugin#567]
When uploading a bundle to Google Play store it doesn't allow to publish the package because of the error:

```
This app targets Android 14 or above, and your current Play Billing Library version doesn't support Android 14. To target the latest Android version, please update your PBL version to either 5.2.1, or 6.0.1 and above.
```

Setting Target Version to Android 13 (API 33) is a workaround

**Comment by Tvde1** [comment]
We've received the message

> Important notes: If your app is targeting Android 14 or higher, you must update to PBL 5.2.1 or PBL 6.0.1 or higher.
> 
> This is your final reminder: By November 1, 2023 version 4 will be deprecated and any updates to existing apps will first require you to migrate to PBL version 5 or newer. We are sending you this reminder as one or more of your apps is still using Play Billing Library (PBL) version 4.
> Important notes: If your app is targeting Android 14 or higher, you must update to PBL 5.2.1 or PBL 6.0.1 or higher.

It's unclear to me whether I have to update something, or whether InAppBillingPlugin needs an update.

**Comment by jamesmontemagno** [comment]
Use: https://www.nuget.org/packages/Plugin.InAppBilling/7.1.0-beta
