### ISSUE TITLE
iOS: PurchaseState is purchase when subscription is already bought

### ISSUE THREAD

**Issue by d66ni** [jamesmontemagno/InAppBillingPlugin#568]
I am calling PurchaseAsync for an subscription that is already subcribed. The iOS dialog tells me that there is already a subscription, but the PurchaseAsync Method returns the PurchaseState => purchased.
So I can't differentiate between a new subscription and a request where a subscription is already active.
Is there another flag which shows the difference?

**Comment by jamesmontemagno** [comment]
You need to calculate the times based off past purchases to see if active. See https://montemagno.com/ios-android-subscription-implemenation-strategies/

**Comment by d66ni** [comment]
Thx James for the answer and the link!
