### ISSUE TITLE
Installing without nuGet: using Com.Android.Vending.Billing;

### ISSUE THREAD

**Issue by sylvain46** [jamesmontemagno/InAppBillingPlugin#57]
Hi.
First thanks for your plugin.

For some reason I can't install it using nuGet.
So I've manually included your source files in my projects.

On iOS, no issue... :)

On Android, there are some:
I had to install NewtonSoft.jSON: that's ok!

Now I'm stuck with InAppBillingImplementation.cs not compiling, because:
using Com.Android.Vending.Billing; fails
IInAppBillingService and IInAppBillingServiceStub are unknown...

I guess I have to reference something there, but after searching quite a while, I couldn't figure out what.

Thanks,
Sylvain.

**Comment by jamesmontemagno** [comment]
You should get a : Plugin.InAppBilling.VendingLibrary.dll reference when installing into Android. 

You can also check your packages/Plugin.InAppBilling/MonoAndroid10/lib

**Comment by sylvain46** [comment]
Thanks for your answer (and sorry about the delay: holidays are terrible! ;) ).

Plugin.InAppBilling.VendingLibrary.dll worked out: I just had to replace your plugin.currentActivity(nuGet) with a
Activity Context => (Activity)Xamarin.Forms.Forms.Context;
since for some reason I couldn't get it to work...

But that was no big deal... ;)

Thanks again, Sylvain (continuing exploring in app payments).
