### ISSUE TITLE
Missing documentation about "PresentCodeRedemption".

### ISSUE THREAD

**Issue by ikeremozcan** [jamesmontemagno/InAppBillingPlugin#570]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information
There is missing documentation about what should we do after 'PresentCodeRedemption'. How can we get notified that users successfully redeemed a code. Then purchased a subscription.

Version Number of Plugin: 7.1.0
Device Tested On: -
Simulator Tested On: -
Version of VS: 17.6 build 1569
Version of Xamarin: 5.0.0.2612
Versions of other things you are using:

### Steps to reproduce the Behavior
-

**Comment by jamesmontemagno** [comment]
It calls: https://developer.apple.com/documentation/storekit/skpaymentqueue/3566726-presentcoderedemptionsheet

Not much there to be honest, it just pops it up... I mean i would probably say wait for your app to return to on the UI and then query to see if there are new purchases.
