### ISSUE TITLE
Close subscription pop up returns Purchased state

### ISSUE THREAD

**Issue by juniorsaraviao** [jamesmontemagno/InAppBillingPlugin#571]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 7.1.0
Device Tested On: iPhone 12 v16.6.1
Version of VS: 17.6.3
Version of MAUI: 7.0.92

### Steps to reproduce the Behavior

1. Download the attached project [MauiSampleBilling.zip](https://github.com/jamesmontemagno/InAppBillingPlugin/files/13303803/MauiSampleBilling.zip).
2. Change the `ApplicationId` (csproj), `package` in AndroidManifest.xml and `CFBundleIdentifier` in Info.plist with the associated one in the Subscription.
3. Change the `productIdSub` in SubscriptionService.cs with your ProductId subscription.
4. Install the app and purchase the subscription.
5. Reinstall the app after some hours (around ~2hr).

### Expected Behavior
If the pop up to purchase a subscription appears and then it closes (Tap the 'X'), the Purchase state shouldn't be **Purchased**.

### Actual Behavior
If the pop up to purchase a subscription appears and then it closes (Tap the 'X'), the Purchase state is  **Purchased**.

See the video: 

https://github.com/jamesmontemagno/InAppBillingPlugin/assets/43689290/d9e05cfe-c165-473b-9930-07e948af0089

It's possible to export the app logs and it will show:

```
2023-11-09 04:14:32Z [INF] Purchase state: Purchased
2023-11-09 04:14:32Z [INF] Subscription purchased
2023-11-09 04:14:32Z [INF] Subscription Expiration Date: 2023-11-09T04:19:32.7017540Z
2023-11-09 04:14:32Z [INF] Transaction date: 2023-11-01T15:48:35.0000000Z
```

**Comment by juniorsaraviao** [comment]
any updates or suggestions related to this bug?

**Comment by jamesmontemagno** [comment]
I mean it could just be a zombie subscription, did you validate that it is valid? on iOS it returns ALL instances of purchases from the past.

So if you already purchased it, you would have one in your records. Read: https://montemagno.com/ios-android-subscription-implemenation-strategies/
