### ISSUE TITLE
Google Billing API 

### ISSUE THREAD

**Issue by Sebastian1989101** [jamesmontemagno/InAppBillingPlugin#573]
The current release of this lib for Xamarin.Forms (5.6.1) is no longer able to publish apps to the Google PlayStore. Can we get an update for the newer billing library? Or is any newer version of this compatible with Xamarin.Forms? As I cannot update all my projects to MAUI because MAUI is still a mess..

**Comment by broda02** [comment]
The 7.x level works fine for Xamarin Forms...


On 18 November 2023 at 11:42:22, Sebastian Kruse ***@***.***) wrote:

The current release of this lib for Xamarin.Forms (5.6.1) is no longer able to publish apps to the Google PlayStore. Can we get an update for the newer billing library? Or is any newer version of this compatible with Xamarin.Forms? As I cannot update all my projects to MAUI because MAUI is still a mess..

**Comment by Sebastian1989101** [comment]
@broda02 7.x is compatible with Forms? I had remembered that @jamesmontemagno sayed somewhere that 5.x is the Version for the old Forms projects and 6.x is for .NET 6 / MAUI. So I assumed 7.x is just .NET 7 / MAUI?

**Comment by broda02** [comment]
Works fine. I use it with mine On 18 Nov 2023, at 17:47, Sebastian Kruse ***@***.***> wrote:﻿
@broda02 7.x is compatible with Forms? I had remembered that @jamesmontemagno sayed somewhere that 5.x is the Version for the old Forms projects and 6.x is for .NET 6 / MAUI. So I assumed 7.x is just .NET 7 / MAUI?

**Comment by AmaluThomas** [comment]
@broda02 you mean in release mode?
@jamesmontemagno can you update if any newer version with forms?

**Comment by broda02** [comment]
Yes in AppStore release mode.. On 20 Nov 2023, at 10:02, AmaluThomas ***@***.***> wrote:﻿
@broda02 you mean in release mode?
@jamesmontemagno can you update if any newer version with forms?

**Comment by AmaluThomas** [comment]
@broda02  Thanks for reply.

What about android? are you able to build in android release mode and able to publish to google console? can you provide the version of inappbilling plugin used and .net version, please?

**Comment by Tvde1** [comment]
Just try it, man

**Comment by AmaluThomas** [comment]
Work fine now... just need to update the billing library for all the projects, ie, android native also along with forms project and follow the documentation by james

**Comment by jamesmontemagno** [comment]
It is fully supported yes. It says it right here: https://github.com/jamesmontemagno/InAppBillingPlugin#platform-support
