### ISSUE TITLE
We've detected unsupported versions of Google Play Billing: AIDL

### ISSUE THREAD

**Issue by Tvde1** [jamesmontemagno/InAppBillingPlugin#575]
## Bug Information
To be able to publish an update to the Play Store, I upgraded `Plugin.InAppBilling` to `7.1.0` (because version 4.0 of billing has been deprecated). To my surprise, I get the following message:
```
Error

We've detected that one or more of the app bundles included in this release are using the following Play Billing Library versions
  * AIDL
These are unsupported versions of Google Play Billing. Upgrade to a supported version to publish this app.
```

From what I understand, this is the oldest billing library. I suppose Google Play flags this as a false positive. I re-built and re-uploaded the aab files twice, to make sure I did not choose an old aab file.

Any clue on how to find out what's wrong?

Version Number of Plugin: 7.1.0
Device Tested On: -
Simulator Tested On: -
Version of VS: 2022 17.9.0 Preview 1.0
Version of Xamarin: 5.0.0.2578
Versions of other things you are using:

**Comment by Tvde1** [comment]
I tried some older versions but none worked. A solution was to add:
```diff
 <?xml version="1.0" encoding="utf-8"?>
 <manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="157" android:versionName="1.5.7" package="com.my.app" android:installLocation="auto">
	<uses-sdk android:minSdkVersion="28" android:targetSdkVersion="33" />
	<application android:label="My App" android:theme="@style/MainTheme" android:icon="@drawable/icon" android:largeHeap="true">
+		<meta-data
+			android:name="com.google.android.play.billingclient.version"
+			android:value="6.0.1" />
	</application>
```
I suppose this is something from the `Xamarin.Android.Google.BillingClient` NuGet package

**Comment by jamesmontemagno** [comment]
Interesting.... i should be able to add it in via my library, but I opened an issue just incase

https://github.com/jamesmontemagno/InAppBillingPlugin/pull/576

**Comment by jamesmontemagno** [comment]
give 7.1.1-beta a try and it should put it in there, you can see the merge androidmanifest in the obj folder

**Comment by jamesmontemagno** [comment]
https://github.com/jamesmontemagno/InAppBillingPlugin?tab=readme-ov-file#version-7-major-updates  documented here just incase, but it should trickle down
