### ISSUE TITLE
[Future] iOS 11 - paymentQueue from AppStore

### ISSUE THREAD

**Issue by Sebastian1989101** [jamesmontemagno/InAppBillingPlugin#58]
Just found another question where I can't find any answer in the current descriptions of this plugin. So, is there any way to handle in app payments that starts from the AppStore? See: https://developer.apple.com/documentation/storekit/skpaymenttransactionobserver/2877502-paymentqueue

**Comment by jamesmontemagno** [comment]
These were added in iOS 11, which isn't available just yet. So there isn't anything you need to do today. I will add this as an enhancement for iOS when iOS 11 hits stable.

**Comment by Sebastian1989101** [comment]
I know it's not stable yet. I just started with the preparation for iOS 11 on my current apps and I just stumbled on this. Good to know it will be added in the future.

**Comment by jamesmontemagno** [comment]
Things like these are always handy!

Now we have to get you to make a tvOS application! About to try to add support for it for in app billing :) I think the API is 1 to 1 :)

**Comment by jamesmontemagno** [comment]
Also to investigate: https://itunespartner.apple.com/en/apps/news/45333106?sc_cid=NSL-AP-ENREC
