### ISSUE TITLE
What ProductId do we use for windows?

### ISSUE THREAD

**Issue by brightertools** [jamesmontemagno/InAppBillingPlugin#580]
Do we use the Partner Centre Package/Identity/Name ?

In the MyStreamTimer app, I can see multiple ProductId's is this because the app is in the store as multiple times with different names for  the different tiers?

I have just setup a trial, and just trying to check if the user has purchsed, do I need to setup an add-on to make this work?

**Comment by jamesmontemagno** [comment]
Inside of Partner Center you will want to create a new add-on and you give it a product id. 

In my stream timer on Windows i have 3 tiers (just different amounts people can pay) so i have mstbronze, mstgold, mstsilver.

![image](https://github.com/jamesmontemagno/InAppBillingPlugin/assets/1676321/eaff3b46-0e1e-4662-bfc6-8876302def3b)


Now, on the mac I use subscriptions as well as the mstgold as an option.

This library doesn't support subscriptions on windows at this time.

Hope that is helpful.
