### ISSUE TITLE
Is there a difference between "FinalizePurchaseAsync" and "FinalizePurchaseOfProductAsync"?

### ISSUE THREAD

**Issue by jonathanfontaine** [jamesmontemagno/InAppBillingPlugin#582]
I'm using :
- Nuget Plugin.InAppBilling 7.0.5
- Xamarin.Android SDK 13.2.2.0 
- Xamarin 17.8.0.155

Some of my clients are complaining that their purchase has not been finalized/acknowledged :

![image](https://github.com/jamesmontemagno/InAppBillingPlugin/assets/10338401/a78e55e9-9b62-4712-b1d2-7523ee5a807d)
(when they hit "confirm", they say nothing happens...)

I'm using the following code to finalize/acknoledge the purchase :
``` c#
private bool Ack(InAppBillingPurchase purchase)
{
    if (purchase.IsAcknowledged != true)
    {
        var result = CrossInAppBilling.Current.FinalizePurchaseOfProductAsync(purchase.ProductId).Result;
        if (result.Any())
            return result.First().Success;
        else
            return false;
    }
    else
    {
        return true;
    }
}
```

Is it ok? Or do I need to replace : 
``` c#
var result = CrossInAppBilling.Current.FinalizePurchaseOfProductAsync(purchase.ProductId).Result;
```
by
``` c#
var result = CrossInAppBilling.Current.FinalizePurchaseAsync(purchase.TransactionIdentifier).Result;
```

Is there a difference between those two lines?

**Comment by jamesmontemagno** [comment]
Yes they are a bit confusing... https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/src/Plugin.InAppBilling/Shared/IInAppBilling.shared.cs#L35-L47 I will clean this up...

```FinalizePurchaseAsync``` is for iOS/Android when you know your transaction id...

```FinalizePurchaseOfProductAsync``` is ONLY for iOS when you turned off auto finalize.


this is outlined here: https://jamesmontemagno.github.io/InAppBillingPlugin/PurchaseNonConsumable.html

**Comment by jonathanfontaine** [comment]
Thank you very much @jamesmontemagno !
