### ISSUE TITLE
[Question] Possible to use in non-Xamarin project (Unity3d) ?

### ISSUE THREAD

**Issue by shubhank008** [jamesmontemagno/InAppBillingPlugin#584]
As title says, is it possible to use this plugin system in non-xamarin projects, like Unity3D.
Basically use it as a standalone independent .net/c# code.  

Wanted to do IAP validation server-side for our game built on Unity.

**Comment by jamesmontemagno** [comment]
You would want: https://docs.unity3d.com/Packages/com.unity.purchasing@4.8/manual/index.html

For my library to work the base needs to be built on UWP/WinUI3, .NET/Xamarin for iOS/Android/Mac, Xamarin.Forms/.NET MAUI

**Comment by shubhank008** [comment]
> You would want: https://docs.unity3d.com/Packages/com.unity.purchasing@4.8/manual/index.html
> 
> For my library to work the base needs to be built on UWP/WinUI3, .NET/Xamarin for iOS/Android/Mac, Xamarin.Forms/.NET MAUI

Unfortunately works only client-side and not server-side (standalone)

**Comment by jamesmontemagno** [comment]
My library is also client-side, both google/apple have server-side apis that work with their IAP programs.
