### ISSUE TITLE
Inquiry Regarding Privacy Policy in InAppBillingPlugin

### ISSUE THREAD

**Issue by Nonaba002** [jamesmontemagno/InAppBillingPlugin#586]
Hello,
I'm currently assessing the InAppBillingPlugin package for potential integration into our project. As part of our due diligence concerning data privacy and compliance, I'm reaching out to inquire about the privacy policy associated with this package.
Could someone from the maintainers' team kindly provide information on whether InAppBillingPlugin collects any user data or sensitive information during its operation or integration? Understanding its approach to privacy and data collection is crucial for us to ensure alignment with our project's privacy policies.
Your clarification on this matter would greatly assist us in making an informed decision about utilizing this package.
Thank you for your attention to this inquiry.
Best regards,
Nonaba002

**Comment by jamesmontemagno** [comment]
This library is just an abstraction of the native APIs. This library does not collect any user data or information at all. All date from the native APIs just passes through to the user of the library.

hope that helps.
