### ISSUE TITLE
Published app in GooglePlay it still uses testing cards etc

### ISSUE THREAD

**Issue by Engisan** [jamesmontemagno/InAppBillingPlugin#589]
It seems the application payments are still done vs google's test sandbox server because I can see only testing cards in the payment widget. This happens in the application published to google play and installed from the google play!

I went through the docs but I cannot see anything about it, so I expected the library handling it itself. 
What am I doing wrong here, please?

Version Number of Plugin: 7.1.0
Device Tested On: Samsung S21FE
Version of VS: the latest now
Version of Xamarin: the latest MAUI .net 8

**Comment by Engisan** [comment]
So I did some more checks and it seems like it works on other devices but mine. I was beta tester, testing the dev version on my device. And for some reason now the purchases on the production app still act like it was the testing version on my device :/ I already left the beta program and tried to reinstall the app. Still the same, I can still see only "Testing cards" during the purchases...

**Comment by jamesmontemagno** [comment]
Correct, if you are in a beta group or linked account then it will show those. This is on google's side, not this library  https://developer.android.com/google/play/billing/test

**Comment by Engisan** [comment]
Oh.... I thought it will just ADD these possibilities not that it will completelly remove the real cards :) I will remove my account from there then. Thank you, James! :)
