### ISSUE TITLE
GetPurchasesAsync(ItemType.InAppPurchase) also returns subscriptions?

### ISSUE THREAD

**Issue by Denny966** [jamesmontemagno/InAppBillingPlugin#592]
I'm confused what the difference is between ItemType.Subscription and ItemType.InAppPurchase because the latter returns all in app purchases.

It is not wrong since a Subscription is technically an InAppPurchase

So is the type ItemType.InAppPurchase just a general name for all in app purchases?

## Bug Information

Version Number of Plugin: 7.0.5
Device Tested On: iPhone 6s iOS 14.6
Version of VS: 17.8.0
Version of MAUI: .NET 8

### Steps to reproduce the Behavior
```
var subscriptionPurchases = await CrossInAppBilling.Current.GetPurchasesAsync(ItemType.Subscription);
var singlePurchases = await CrossInAppBilling.Current.GetPurchasesAsync(ItemType.InAppPurchase);
```

### Expected Behavior
ItemType.Subscription to return subscriptions only
ItemType.InAppPurchase to return single purchases only

### Actual Behavior
ItemType.Subscription returns subscriptions only
ItemType.InAppPurchase returns subscriptions and single purchases

### Code snippet
```
var subscriptionPurchases = await CrossInAppBilling.Current.GetPurchasesAsync(ItemType.Subscription);
var singlePurchases = await CrossInAppBilling.Current.GetPurchasesAsync(ItemType.InAppPurchase);
```

### Screenshots
![image](https://github.com/jamesmontemagno/InAppBillingPlugin/assets/12098006/9085a59a-de28-412c-9598-5fdca0482a22)

**Comment by jamesmontemagno** [comment]
I added a note in the docs:

> Note: On iOS there is no API to determine if a purchase was a subscription or in app purchase, so all purchases regardless of type will be return. It is required on Android. It is best to query and then check for Id.
