### ISSUE TITLE
StoreKIt

### ISSUE THREAD

**Issue by Novotnde** [jamesmontemagno/InAppBillingPlugin#595]
Hello, 

I have implemented successfully on android in app billing, however on iOS I am having some issues. 

This is displayed with my in-app purchases : 

"These in-app purchases or subscriptions can't be promoted on the App Store because your latest approved binary doesn’t include the required StoreKit APIs. [Learn More](https://developer.apple.com/app-store/promoting-in-app-purchases/)"

I had a look and it seems that the package does include StoreKit APIs . I have plugin version 7.05.

**Comment by jamesmontemagno** [comment]
You will need to implement OnShouldAddStorePayment: https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/src/InAppBillingTests/InAppBillingTests.iOS/AppDelegate.cs as an example.

**Comment by Novotnde** [comment]
I have that implemented. Any other suggestion please?
