### ISSUE TITLE
Issue: Xamarin Android "Could not load file or assembly 'Microsoft.Maui.Essentials'"

### ISSUE THREAD

**Issue by HelmuthWcs** [jamesmontemagno/InAppBillingPlugin#596]
Hi, I tried to upgrade my Xamarin Android App to the new Project SDK format because Visual studio warn of deprecation of the old format. 

After porting the App I get an exception while calling 
var purchase = await billing.PurchaseAsync(sku, ItemType.InAppPurchase);
Exception:
"Could not load file or assembly 'Microsoft.Maui.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies."

Plugin.InAppBilling 7.1.0
Xamarin.Essentials 1.8.1

Calling or not calling "Xamarin.Essentials.Platform.Init(this, savedInstanceState);" in main activity makes no difference. The library seems to think this is a Net Maui project which it isn't. Trying to install "Microsoft.Maui.Essentials" fails because of imcompability.

**Comment by Vintar** [comment]
Same problem

**Comment by jamesmontemagno** [comment]
Xamarin.Essentials is not compabitible with .NET 6+ style apps so you will want to remove that

See https://learn.microsoft.com/en-us/dotnet/maui/migration/native-essentials?view=net-maui-8.0&tabs=android

**Comment by kerams** [comment]
> Xamarin.Essentials is not compabitible with .NET 6+ style apps

It works perfectly fine with Avalonia targetting `net9.0-android`.

**Comment by jamesmontemagno** [comment]
No, you just want to migrate it and set a csproj reference: https://learn.microsoft.com/en-us/dotnet/maui/migration/native-essentials?view=net-maui-8.0&tabs=android
