### ISSUE TITLE
Android app suddenly showing "free" instead of localized price for subscriptions

### ISSUE THREAD

**Issue by CrewNerd** [jamesmontemagno/InAppBillingPlugin#597]
I don't think this is a bug in InAppBillingPlugin but I wanted to post here in case others are running into this problem.

After a recent, trivial update to my app, I published to Google Play for closed testing. The update was rejected, citing a policy violation related to clarity around subscription pricing. The screenshot showed that instead of showing localized prices for my monthly and annual subscriptions, the price was displayed as "Free". Of course, they didn't way what locale the screenshot was from.

I double-checked my pricing in all locales and none of them were free. I tried appealing the rejection, pointing out that nothing in that part of my app had changed and that this must be a bug or a mis-configuration somewhere in Google Play, but they sent an email just re-stating the policy and not addressing my comments at all.

Since then, they have flagged the same issue on the production version of my app, which was obviously fine when it was originally published. In my own locale (US), the pricing looks fine.

I'm still pleading with Google Play to actually work with me to solve this, but if anyone else has seen something like this, please comment here.

## Bug Information

Version Number of Plugin: 7.0.5
Device Tested On: unknown
Version of VS: Mac 17.6.9
Version of Xamarin: 13.2.2.0

**Comment by CrewNerd** [comment]
Update: looking at the screenshot they sent, it looks like the problem was in India, so I'm removing my app from the store there. We'll see if this solves the problem, or if they'll report the same issue in another country now.

**Comment by CrewNerd** [comment]
Removing my app from the India app store seems to have worked around the problem.

**Comment by CrewNerd** [comment]
I'm reopening this as a heads-up for others who might be affected. This appears to be an ongoing issue with Google Play. As soon as I submitted another app update, but problem appeared again in a different country. I filed a bug against Google about the problem. If you've been affected also, please up-vote the bug [here](https://issuetracker.google.com/issues/331680207).

**Comment by mpwhitt** [comment]
I was experiencing a similar issue with my updates being rejected due to the price not displaying.  I wasn't able to reproduce the issue, but added code to check for the existence of ".99" in the price and the update was approved.
