### ISSUE TITLE
iOS payment really slow ios 17+

### ISSUE THREAD

**Issue by harima34** [jamesmontemagno/InAppBillingPlugin#599]
Hello, i got an iphone X (last ios 16.7.7), iphone 13(ios 17.4.1) and iphone 15plus (ios 17.4.1) . I am on sandbox (tried with debug and testflight app);

When i am calling CrossInAppBilling.Current.PurchaseAsync, on iphone 13 and iphone 15plus it can take 1 minute to get a response, but with the iphone X it take 5 seconds. Debug or testflight version didn't change anything.

The only difference i found is the ios version are different.
What can be the problem ? 
Thank you!

**Comment by Meekohi** [comment]
Sandbox is just insanely slow unfortunately in my experience, it's an issue with Apple. It seems to get worse the more purchases your account has.

**Comment by harima34** [comment]
@Meekohi! That makes a lot of sense considering my experience too. I'll definitely try setting up a fresh Sandbox environment and a new Apple ID to see if the speed improves.

**Comment by pulmuone** [comment]
Apple's Sandbox environment is very slow. It is also explained in the official manual.

"The rate limits in the sandbox environment are 10% of the limits in the table above.
The App Store server may make adjustments to reduce or increase these rate limits as needed at any time.
"
--ref : https://developer.apple.com/documentation/appstoreserverapi/identifying_rate_limits

**Comment by Meekohi** [comment]
Politely, this has nothing to do with rate limits. Request don't fail they are just insanely slow, even your first request of the day or etc.

**Comment by jamesmontemagno** [comment]
Sandbox users can be very slow. I would create a new one, as they get stuffed with transactions
