### ISSUE TITLE
Developer hasn't acknowledged your purchase

### ISSUE THREAD

**Issue by nitwill** [jamesmontemagno/InAppBillingPlugin#606]
Version Number of Plugin: 7.1.0
Device Tested On: Android 13
Simulator Tested On: NA
Version of VS: VS for Mac 17.6.12 (build 410)
Version of Xamarin: Xamarin Forms 5.0.0.2662
Versions of other things you are using:

### Steps to reproduce the Behavior
1. Tap on a button to pay the subscription
2. Shows an alert: "Developer hasn't acknowledged your purchase"
3. Then does nothing.
### Expected Behavior
It should done the purchase.
### Actual Behavior
Shows an alert: "Developer hasn't acknowledged your purchase"
### Code snippet
On executing the below code:
InAppBillingPurchase purchase = await CrossInAppBilling.Current.PurchaseAsync(productIdSub, ItemType.Subscription);
It throws an exception: 'Plugin.InAppBilling.InAppBillingPurchaseException', with message: "Unable to process purchase." and the alert pops up: "Developer hasn't acknowledged your purchase".
How to acknowledge the purchase?
### Screenshotst
![acknowledge](https://github.com/jamesmontemagno/InAppBillingPlugin/assets/91594473/c163d01d-5408-43d6-911d-aeb11b574ae6)

**Comment by jamesmontemagno** [comment]
you must finalize purchase: https://jamesmontemagno.github.io/InAppBillingPlugin/PurchaseNonConsumable.html

**Comment by nitwill** [comment]
Hi James,

I have already implemented the finalize purchase code. Please see the below code I implemented.

InAppBillingPurchase purchase = await CrossInAppBilling.Current.PurchaseAsync(productIdSub, ItemType.Subscription);
                    try
                    {
                        var ack = await CrossInAppBilling.Current.FinalizePurchaseAsync(purchase.TransactionIdentifier);
                    }
                    catch (Exception ex)
                    {
                    }
I think 'purchase.TransactionIdentifier' is the purchase token?
I went to my Google Play Console account and went to 'Order'. There I can see many transaction and their purchase token.
So, if I want to acknowledge a particular transaction. Shall I pass the purchase token to 'CrossInAppBilling.Current.FinalizePurchaseAsync' method?

**Comment by jamesmontemagno** [comment]
You can loop through all your purchases and call FinalizePurchaseAsync with a bunch of the ids:

https://developer.android.com/google/play/billing/integrate#non-consumable-products is a good read, or if this is a consumable you should consume.

and https://developer.android.com/google/play/billing/test#one-time


for other issue: https://support.google.com/googleplay/thread/216318274/error-this-version-of-the-application-is-not-configured-for-billing-through-google-play?hl=en

**Comment by nitwill** [comment]
Thank you James for your help. I will read it and if I found some doubts, will let you know.
