### ISSUE TITLE
Your app, uses a version of Google Play Billing Library that will be deprecated soon. From Aug 31, 2024, all apps must use version 6.0.1 or later.

### ISSUE THREAD

**Issue by nasfia** [jamesmontemagno/InAppBillingPlugin#613]
I have received an email regarding my app from Google Play Console reporting 

Your app, uses a version of Google Play Billing Library that will be deprecated soon. From Aug 31, 2024, all apps must use version 6.0.1 or later.

As per my understanding, the latest InAppBillingPlugin still using Google Play billing 6.0.1

Can you please help with the way around? or are you planning to update InAppBillingPlugin with compatible version of Google Play Billing.

**Comment by jamesmontemagno** [comment]
Version 7.1.0 uses 6.0.1 and 7.1.2-beta uses 6.1.0.1
