### ISSUE TITLE
InAppBillingImplementation does not exist

### ISSUE THREAD

**Issue by sachinkanadia** [jamesmontemagno/InAppBillingPlugin#617]
## Bug Information

Version Number of Plugin: 7.13
Device Tested On: N/A
Simulator Tested On: N/A
Version of VS: Visual Studio Mac 17.6.13 (build 424)
Version of Xamarin: 5.0.0.2515
Versions of other things you are using: N/A

### Steps to reproduce the Behavior
N/A

### Expected Behavior
The code should compile.

### Actual Behavior
I'm trying to upgrade InAppBilling to submit the app to the store.
The code does not compile and produces the error: "InAppBillingImplementation does not exist" when I upgrade to version 7.13. 
However, this class does exist in Android InAppBilling.
The last working version was 7.0.5.

### Code snippet & Screenshotst
![Screenshot 2024-07-20 at 14 29 57](https://github.com/user-attachments/assets/cc0adb73-4832-4b15-bdb0-37af1d343be8)

**Comment by jamesmontemagno** [comment]
are you targeting monoandroid13.0

**Comment by sachinkanadia** [comment]
Updated compilation target to Android 13.0 and it now works. Thanks, James.
