### ISSUE TITLE
Calling billing.GetPurchasesAsync on iOS keeps asking users to sign in with apple ID

### ISSUE THREAD

**Issue by Kas-code** [jamesmontemagno/InAppBillingPlugin#619]
I am not sure if this is a bug or not, but when I call `billing.GetPurchasesAsync` on iOS, it will pop up a dialog asking the user to sign in with their apple ID. It seems that even if they enter their apple account information correctly, the dialog will just pop up again the next time my application calls `billing.GetPurchasesAsync`.

I want to use the billing plugin for a monthly subscription to my app. As a side question, I am not sure when to call `billing.GetPurchasesAsync` to check that the subscription is still active and hasn't been cancelled. Should I call it every time my app starts up or only once a month to check that the subscription hasn't lapsed? The documentation is not clear on this.

Does the user need to sign in every time with their apple Id when I call `billing.GetPurchasesAsync` ?

**Comment by atkinsonbg** [comment]
- "when I call billing.GetPurchasesAsync on iOS, it will pop up a dialog asking the user to sign in with their apple ID"

Is this on the Simulator or a real device?

- "I am not sure when to call billing.GetPurchasesAsync to check that the subscription is still active"

This is a business decision for you to decide. It will depend on how critical that check is for your needs. You may want to call it every time the user opens the app, as they could have cancelled right before they launch it. Or if its not that critical, you could check once a week, etc. No hard rules there.

**Comment by brianbentwood** [comment]
I have had this same issue.  It comes and goes.  The repeating request for a login occurs only on the simulator for me.

**Comment by jamesmontemagno** [comment]
This is a simulator and apple sandbox user thing
