### ISSUE TITLE
What is the exact steps for Android in Xamarin.Forms?

### ISSUE THREAD

**Issue by pallavbohara** [jamesmontemagno/InAppBillingPlugin#62]
I had already implemented In-App purchase in Android Studio.But having trouble in Xamarin.Forms.I have followed:-

1. Installed the plugin in PCL and Android project.
2. Overrided OnActivityResult() in MainActivity.

My doubt is --
1. Where to put **PUBLIC KEY** i get from google play console?
2. Where to put product id's?

Error i am getting. On Running Code now--
`Java.Lang.NoClassDefFoundError: md58ca8ca9a1f8dc9075a0cb027f5be086b/InAppBillingServiceConnection`

. Thanks in advance.

**Comment by jamesmontemagno** [comment]
Please read the documentation:

https://jamesmontemagno.github.io/InAppBillingPlugin/

Also probably make sure that you don't LINK ALL or make sure that the vending library is not linked out.

**Comment by pallavbohara** [comment]
@jamesmontemagno 

1. I read the document you mentioned.
2. Now this is serious issue, the **Public Key** i am talking of is this -- 
![image](https://user-images.githubusercontent.com/23195991/28461171-fdb515a8-6e32-11e7-8ad1-fabe9a0a552b.png)
3. I am just using this code ` public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
            Purchase();
        }

        private async void Purchase()
        {
            try
            {
                var productId = "mysku";

                var connected = await CrossInAppBilling.Current.ConnectAsync();

                if (!connected)
                {
                    //Couldn't connect to billing, could be offline, alert user
                    return;
                }

                //try to purchase item
                var purchase = await CrossInAppBilling.Current.PurchaseAsync(productId, ItemType.InAppPurchase, "apppayload");
                if (purchase == null)
                {
                    //Not purchased, alert the user
                }
                else
                {
                    //Purchased, save this information
                    var id = purchase.Id;
                    var token = purchase.PurchaseToken;
                    var state = purchase.State;
                    
                }
            }
            catch (Exception ex)
            {
                //Something bad has occurred, alert user
            }
            finally
            {
                //Disconnect, it is okay if we never connected
                await CrossInAppBilling.Current.DisconnectAsync();
            }
        }
    }`
4. I not inserted this key any where in code. Still able to make purchase(my credit card got debited). Also that purchase is showing in **Google Play Console**
5. Also I not understood what do you mean by **LINK ALL**.

I am new to mobile as well as Xamarin.Forms please **Help!**
