### ISSUE TITLE
Android - Steps to test on a real device?

### ISSUE THREAD

**Issue by atkinsonbg** [jamesmontemagno/InAppBillingPlugin#622]
This is not a bug, I'm just looking for someone who has debugged on a physical device.

## Bug Information

Version Number of Plugin: 8.0.2-beta
Device Tested On: Android - BLU B160V, Tracfone
Simulator Tested On: N/A
Version of Jetbrains Rider: 2023.3.4 
Version of Maui: 8.0.20
Versions of other things you are using: 

### Steps to reproduce the Behavior

- Created a Closed Testing release in Google Play Console
- Added testers in Google Play Console
- Created a Subscription on my app in Google Play Console
- Created a keystore and have created a 'Release' build with it
- Uploaded the signed AAB to Google Play Console for the Closed Testing release
- Release was approved by Google (realized this was needed before my subscription could be queried)
- Signed into the Android device with a user from the testers group
- Connected phone via USB, and launched a Debug session on the device
- Called 'GetProductInfoAsync' and the subscription details are returned successfully (YAY!)
- Called 'PurchaseAsync' and get an error stating "this version is not configured for billing"

### Expected Behavior
n/a

### Actual Behavior
n/a

### Code snippet
`var purchase = await billing.PurchaseAsync("MY_SUB_ID", ItemType.Subscription);`

What I think is happening is, I've signed the AAB as a Release build and that is tied to the Subscription, so when I run a Debug build on the device, the signatures don't match and I can't purchase the subscription.

Can anyone provide the steps to Debug this successfully? Thanks, and @jamesmontemagno this package is sweet, thank you for making this!!

**Comment by wickedw** [comment]
HI @atkinsonbg 

Can you set the keystore information for your DEBUG configuration to the same as your RELEASE config and try again?

**Comment by atkinsonbg** [comment]
Hey @wickedw thanks for the reply!

I did try that, and the build is successful, but during install I get the following error: "Error ADB0010 : Mono.AndroidTools.InstallFailedException: The package was not properly signed (NO_CERTIFICATES)." 

When I built the release for upload I used the following: `dotnet publish -c Release -f net8.0-android -p:AndroidSigningKeyPass=$(ANDROID_KEYSTORE_PASS) -p:AndroidSigningStorePass=$(ANDROID_KEYSTORE_PASS)`

My csproj has this PropertyGroup (normally):
`<PropertyGroup Condition="$(TargetFramework.Contains('-android'))">
		<AndroidKeyStore>True</AndroidKeyStore>
		<AndroidSigningKeyStore>.android/MY_KEY_NAME.keystore</AndroidSigningKeyStore>
		<AndroidSigningKeyAlias>MY_KEY_ALIAS</AndroidSigningKeyAlias>
	</PropertyGroup>`

And I used this to try debugging with:
`<PropertyGroup Condition="$(TargetFramework.Contains('-android'))">
		<AndroidKeyStore>True</AndroidKeyStore>
		<AndroidSigningKeyStore>.android/MY_KEY_NAME.keystore</AndroidSigningKeyStore>
		<AndroidSigningKeyAlias>MY_KEY_ALIAS</AndroidSigningKeyAlias>
		<AndroidSigningKeyPass>PASS</AndroidSigningKeyPass>
		<AndroidSigningStorePass>PASS</AndroidSigningStorePass>
	</PropertyGroup>`

**Comment by atkinsonbg** [comment]
Still getting the error stating "this version is not configured for billing", even after getting a signed Debug build going.

So if anyone has any ideas on that one, please let me know.



------------------

I did however find the issue for "error: "Error ADB0010 : Mono.AndroidTools.InstallFailedException: The package was not properly signed (NO_CERTIFICATES)."

Turns out my keystore file somehow got corrupted and I was missing the error. When I hit debug in the IDE and build would happen, and I was getting a generic "java build error code 2" or something like that. Hitting debug again would get past that error but the install failed with the error above. Luckily, I was smart enough to save off a copy of the keystone file and copying it back in and all worked correctly for the install.

**Comment by atkinsonbg** [comment]
Fixed one issue, still having another! So turns out signing the app was not the issue at all. I have confirmed that debugging a debug-signed version works fine and I the code can communicate with the Play billing APIs just fine.

Fix for error stating "this version is not configured for billing":

1. Make sure your testers and configured and they have accepted
- I created a Closed testing track and under the "Testers" tab I included a test Gmail account
- Logged into the phone with that account
- At the bottom of the Track page, there is a "How testers join your test" section, copy that link and go to it on the phone, join the program

2. Navigate to the Play Console home screen, and click Settings from the left nav
3. Click the License testing link on that page
- From here, you should see the Test group you created in the Track on the app page. You have to select a group and hit Save, see this link: https://community.revenuecat.com/sdks-51/android-says-this-version-of-the-application-is-not-configured-for-billing-through-google-play-3929

When you land on this page, it looks like its already selected, but it is not. So select your testers group, select "RESPOND_NORMALLY" for the Lincense response section and hit save. Now the billing seems to work correctly.

**Comment by atkinsonbg** [comment]
Now my problem is, if I call `GetProductInfoAsync` I get the product details back, but if I call `PurchaseAsync` it says it can not find the product! @wickedw did you see this issue?

I'm making progress which is good, but still not quite there.

**Comment by atkinsonbg** [comment]
The app has to be Published as well. Mine was in Unpublished, once published the billing worked great.
