### ISSUE TITLE
Compatibility with non-MAUI/AOT environments

### ISSUE THREAD

**Issue by orosbogdan** [jamesmontemagno/InAppBillingPlugin#626]
I am developing an app in godot(game engine), I wanted to know if this library is AoT friendly and if it's compatible in non-MAUI applications.

**Comment by jamesmontemagno** [comment]
I am not 100% sure how godot work and what it builds at the end of the day.

You would have to be using net8.0-android, but i don't think that is how it works, they use .net embedding into a native app in which this library will not work.

It has to be a .NET for Android or .NET MAUI Android app

**Comment by orosbogdan** [comment]
What about native AoT compatibility, using like .net8.0-ios ?
