### ISSUE TITLE
Postman Receipt Testing 

### ISSUE THREAD

**Issue by wickedw** [jamesmontemagno/InAppBillingPlugin#63]
Hi,

Thanks for a great library,

This is a polite request for assistance than any issue with code.

I am about to sort out server side receipt validation for an auto-renewable subscription, and have basically created a postman request for testing in accordance with this -

https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html#//apple_ref/doc/uid/TP40010573-CH104-SW1

To get the receipt I have used this - 

```
 public class InAppPurchaseVerify : IInAppBillingVerifyPurchase
        {
            public Task<bool> VerifyPurchase(string signedData, string signature, string productId = null, string transactionId = null)
            {
                DebugWriteFunc("signedData: " + signedData);
                return Task.FromResult(true);
            }
        }
```

and then cutting and pasting the Base64 string into the postman request - i.e. 

```
{
	"receipt-data" : "MIIbMAYJKoZIhvcNAQcCoIIbITCCGx0CAQExCzAJBgUrDgMCGgUAMIIK0QYJKoZIhvcNAQcBoIIKwgSCCr4xggq6MAoCAQgCAQEEAhYAMAoCARQCAQEEAgwAMAsCAQECAQEEAwIBADALAgELAgEBBAMCAQAwCwIBDwIBAQQDAgEAMAsCARACAQEEAwIBADALAgEZAgEBBAMCAQMwDAIBCgIBAQQEFgI0KzAMAgEOAgEBBAQCAgCLMA0CAQ0CAQEEBQIDAYfOMA0CARMCAQEEBQwDMS4wMA4CAQMCAQEEBgwEMTA4MzAOAgEJAgEBBAYCBFAyNDcwGAIBBAIBAgQQDjIM36q1sOSeG29LSQWgYTAbAgEAAgEBBBMMEVByb2R1Y3Rpb25TYW5kYm94MBwCAQUCAQEEFI1R2",
	"password" : "MYKEY"
}
```

But I am getting -

> {"status":21002, "exception":"com.apple.jingle.mzfairplay.validators.DrmInvalidArgumentException"}

in response from sandbox - https://sandbox.itunes.apple.com/verifyReceipt -  (and production).

I have had a look at SO but most errors like this are carriage returns in the base64 and it all looks fine from the code :(

Does anyone have an experience of this error AND if I am doing something wrong in my approach?

Best Regards
Matt

**Comment by wickedw** [comment]
After leaving this message and going away I thought "right lets re-create another sandbox user" - as someone mentioned it once in the multitude of comments I read along the way.

And lo and behold, a receipt we now have (and a MUCH longer Base64 string! to boot).

Thanks.

**Comment by jamesmontemagno** [comment]
:) glad to hear it is all working, yeah test users are a pain.

**Comment by ArdaDinler** [comment]
First of all, thank you for this library. It's vey useful and simple usage. jamesmontemagno :) 

I'm new in Xamarin Cross Platform. I don't know how to implement IInAppBillingVerifyPurchase from iOS and Android.  Could you explain more detail for sandbox user.

Thanks in advance.

**Comment by jamesmontemagno** [comment]
https://jamesmontemagno.github.io/InAppBillingPlugin/SecuringPurchases.html
