### ISSUE TITLE
Upgrade to 7.1 of android billing

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/InAppBillingPlugin#631]
Is now available: https://developer.android.com/google/play/billing/migrate-gpblv7

**Comment by rezamohamed** [comment]
In the Readme there is a mention of 'Version 8 Major Updates', however, nuget only shows 7.1.3. Is the v8 not released yet?

**Comment by rezamohamed** [comment]
I had to search nuget and found the beta release. Is this it?
https://www.nuget.org/packages/Plugin.InAppBilling/8.0.3-beta

**Comment by jamesmontemagno** [comment]
The versions don't align with Android billing library stuff. 8.0.3-beta uses BillingClient 6.2.1

**Comment by rezamohamed** [comment]
> The versions don't align with Android billing library stuff. 8.0.3-beta uses BillingClient 6.2.1

@jamesmontemagno Sorry, that wasn't very clear. On the readme it says to use the v8 Major Version (the only v8 I see is the beta), and here are you saying don't use the v8 beta? Which is the correct version to use with the Android Billing v7?

**Comment by jamesmontemagno** [comment]
v8 is now out on stable and that is built against Android Billing v6.2

**Comment by rezamohamed** [comment]
Thanks for clarifying! will try it out now

**Comment by rezamohamed** [comment]
@jamesmontemagno still open question on this, should I be targeting 6.2.1 here:

`<meta-data android:name="com.google.android.play.billingclient.version" android:value="6.2.1"/>`

or the latest v7 version 7.1.1 and change the android:value = "7.1.1"? 

https://developer.android.com/google/play/billing/release-notes

**Comment by jamesmontemagno** [comment]
It is whatever version i built it against. Although you shouldn't have to add it anymore

**Comment by rezamohamed** [comment]
> Although you shouldn't have to add it anymore

Ah even better, I will go ahead and remove <meta-data android:name="com.google.android.play.billingclient.version" android:value="6.2.1"/> from the Android Manifest. Thanks!
