### ISSUE TITLE
Dependency conflict upgrading to 8.0.4: Xamarin.AndroidX.Lifecycle.LiveData.Core

### ISSUE THREAD

**Issue by mfeingol** [jamesmontemagno/InAppBillingPlugin#637]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 8.0.4
Device Tested On: PC
Simulator Tested On:
Version of VS: latest
Version of Maui: latest
Versions of other things you are using:

### Steps to reproduce the Behavior

Upgrade from 7.1.3 to 8.0.4 in a Maui project that has this explicit dependency:

```<PackageReference Include="Xamarin.AndroidX.Fragment.Ktx" Version="1.8.3.1" />```

The reason this is needed is documented [here](https://learn.microsoft.com/en-us/answers/questions/1791244/maui-net-8-on-android-throwing-an-exception).

### Expected Behavior

Clean build

### Actual Behavior

NU1608: Detected package version outside of dependency constraint: Xamarin.AndroidX.Lifecycle.LiveData 2.8.3.1 requires Xamarin.AndroidX.Lifecycle.LiveData.Core (>= 2.8.3.1 && < 2.8.4) but version Xamarin.AndroidX.Lifecycle.LiveData.Core 2.8.5.1 was resolved.
NU1107: Version conflict detected for Xamarin.AndroidX.Lifecycle.LiveData.Core.Ktx. Install/reference Xamarin.AndroidX.Lifecycle.LiveData.Core.Ktx 2.8.5.1 directly to project Sideroads.Maui to resolve this issue. 
 Sideroads.Maui -> Xamarin.AndroidX.Fragment.Ktx 1.8.3.1 -> Xamarin.AndroidX.Lifecycle.LiveData.Core.Ktx (>= 2.8.5.1) 
 Sideroads.Maui -> Plugin.InAppBilling 8.0.4 -> Xamarin.AndroidX.Lifecycle.LiveData 2.8.3.1 -> Xamarin.AndroidX.Lifecycle.LiveData.Core.Ktx (>= 2.8.3.1 && < 2.8.4).

**Comment by jamesmontemagno** [comment]
You could try 9.0-beta which has upgraded dependencies. 

Assumption here is just dependency conflicts since you have items specified. I have a bunch already https://www.nuget.org/packages/Plugin.InAppBilling/8.0.4#dependencies-body-tab

**Comment by mfeingol** [comment]
Thanks. 9.0-beta fixes the problem with Xamarin.AndroidX.Fragment.Ktx 1.8.3.1, but not with the newly release 1.8.4:

```
 Sideroads.Maui -> Xamarin.AndroidX.Fragment.Ktx 1.8.4 -> Xamarin.AndroidX.Lifecycle.LiveData.Core.Ktx (>= 2.8.6) 
 Sideroads.Maui -> Plugin.InAppBilling 9.0.0-beta -> Xamarin.AndroidX.Lifecycle.LiveData 2.8.5.1 -> Xamarin.AndroidX.Lifecycle.LiveData.Core.Ktx (>= 2.8.5.1 && < 2.8.6).
```

Looks like another deps update might be needed. :-)

**Comment by jamesmontemagno** [comment]
or just tried it out and 9.0.1-beta which i will put out will use 1.8.4

**Comment by jamesmontemagno** [comment]
shouuld be fixed up now
