### ISSUE TITLE
Submitting to the apple store

### ISSUE THREAD

**Issue by techbud** [jamesmontemagno/InAppBillingPlugin#642]
I'm trying to submit my app to the Apple App Store and they seem to be using simulators. My app has a user pay after 30 days of use and its a one-time consumable that the user can purchase.

But it seems they use a simulator and the payment processing doesn't work and it keeps getting rejected in the review.

Has anyone submitted a project to the Apple store and overcome this obstacle because it's getting old?

**Comment by CyborTronik** [comment]
Facing a similar issue. Looks like MAUI is doomed in that regard. Looking for a solution still...

**Comment by techbud** [comment]
> Facing a similar issue. Looks like MAUI is doomed in that regard. Looking for a solution still...

I'm giving in and going to write native storkit code and hopefully this works.

**Comment by CyborTronik** [comment]
Have you tried RevenueCat or Stripe instead?

**Comment by techbud** [comment]
> Have you tried RevenueCat or Stripe instead?
I don't think Apple will allow that in app?

**Comment by CyborTronik** [comment]
RevenueCat should be the same (I hope for better stability). While Stripe should be allowed, however they might want you to put on their subscription system

**Comment by CyborTronik** [comment]
@techbud I got some success by following the testing solution from https://github.com/xamarin/xamarin-macios/issues/9909

**Comment by techbud** [comment]
> @techbud I got some success by following the testing solution from https://github.com/xamarin/xamarin-macios/issues/9909

Did you make it through the review process?

**Comment by CyborTronik** [comment]
I was able to test locally in the iOS simulator. It worked fine with the storekit with the 'Local StoreKit configuration' and solved a few bugs. However, I need help getting it to work when I use Store Kit sync with the App Store. I get an error about: Plugin.InAppBilling.InAppBillingPurchaseException: Invalid products found when querying product list
   at Plugin.InAppBilling.InAppBillingImplementation.GetProductInfoAsync(ItemType itemType, String[] productIds, CancellationToken cancellationToken)

**Comment by CyborTronik** [comment]
I achieved a bit of progress after completing the bank details. The app store will return invalid product id in production if your tax and bank details are not validated. Which doesn't bring much transparency.

so now I received the following message from review (which is a progress overall):
```
"Users restore transactions to maintain access to content they've already purchased. For example, when they upgrade to a new phone, they don't lose all of the items they purchased on the old phone. Include some mechanism in your app to let the user restore their purchases, such as a Restore Purchases button."

Next Steps

To restore previously purchased in-app purchase products, it would be appropriate to provide a "Restore" button and initiate the restore process when the "Restore" button is tapped by the user. Note that automatically restoring purchases on launch will not resolve this issue.
```

**Comment by jamesmontemagno** [comment]
Welcome to the world of in app purchases, things are very complicated.

You need to have a restore option as well in your app. If you have subscriptions a way for them to manage it.

Best to read apple docs.

I have 2 apps in the app store using this library just fine.
