### ISSUE TITLE
Xamarin.AndroidX.Lifecycle.* NuGets dependencies are referencing an older version

### ISSUE THREAD

**Issue by dottam** [jamesmontemagno/InAppBillingPlugin#647]
In version 9 (and 8 as well) all `Xamarin.AndroidX.Lifecycle.*` NuGets are referencing an older version (2.8.6) which makes it impossible to upgrade to i.e. my app requires `Xamarin.GooglePlayServices.Cast.Framework` v122.0.0.1 which requires v2.8.7.1 of those `Xamarin.AndroidX.Lifecycle.*` NuGets

Does the library requires exact version of those libraries?

**Comment by CleverSoftwarePoland** [comment]
Same problem here.
warning NU1608: Detected package version outside of dependency constraint: Xamarin.AndroidX.Lifecycle.Process 2.8.5.1 requires Xamarin.AndroidX.Lifecycle.Runtime (>= 2.8.5.1 && < 2.8.6) but version Xamarin.AndroidX.Lifecycle.Runtime 2.8.6 was resolved.

This error brakes "publish" for Android on .MAUI 9

**Comment by rezamohamed** [comment]
i'm using the plugin version 8.0.5 and have the following implictly referenced. Using Maui .net 8, everything is working fine.

![CleanShot 2024-11-26 at 20 45 49@2x](https://github.com/user-attachments/assets/f4230b59-9802-47a0-b881-32dbd2304c04)

**Comment by jamesmontemagno** [comment]
These things are hard. Different versions of .NET MAUI are built against different versions, you will want to install all manually if possible
