### ISSUE TITLE
IInAppBillingVerifyPurchase in PCL

### ISSUE THREAD

**Issue by pavelsedina** [jamesmontemagno/InAppBillingPlugin#65]
Guys, please, is there any easy way how to use Verify mechanism described here (https://jamesmontemagno.github.io/InAppBillingPlugin/SecuringPurchases.html) when using pcl project type? in PCL I cannot use __ANDROID__ directives :-( Thanks for any hint.

**Comment by jamesmontemagno** [comment]
That verification code must go into your Android project. You must implement the interface and pass it in.
