### ISSUE TITLE
[ANDROID] App hangs when you repeatedly open and close purchase items without purchasing

### ISSUE THREAD

**Issue by rezamohamed** [jamesmontemagno/InAppBillingPlugin#653]
This is my Purchase service

```
    public async Task<InAppBillingPurchase> PurchaseAsync(string productId, ItemType itemType)
    {
        InAppBillingPurchase purchase = null;

        try
        {
            // Prevent starting a new connection if one is already in progress
            if (_isConnecting)
            {
                // Return immediately or handle this case gracefully (e.g., show a loading indicator)
                return null;
            }

            _isConnecting = true; // Mark as connecting

            // Connect to billing service if not already connected
            if (!_isBillingConnected)
            {
                await billing.ConnectAsync();
                _isBillingConnected = true;
                _isConnecting = false; // Mark as no longer connecting
            }

            if (billing == null)
                throw new Exception("Not connected to the billing service");

            purchase = await billing.PurchaseAsync(productId, itemType); //, "payload");

            //await billing.DisconnectAsync();
        }
        finally
        {
            // Disconnect only if we were connected
            if (_isBillingConnected)
            {
                await billing.DisconnectAsync();
                _isBillingConnected = false;
            }

            _isConnecting = false; // Mark as no longer connecting
        }

        return purchase;
    }
```

What I am finding is that on Android only, when I tap on a product to purchase (either in app or subscription) and close the dialogue without purchasing and repeatedly do this with all the products, after about 5 tries or so (the number varies), the app hangs on Android. 

I am catching UnhandledException and via logging, a System.AggregateException is throwing with the following message:
```
System.AggregateException
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
```

I am catching all the exceptions in the caller ViewModel and doing something with the exception (logging, console, etc) but it still seems to happen on multiple attempts.

The kicker is that my app is failing App Review because the tester sees this as a potential issue. Any ideas on how I can resolve this?

Specs:
.NET 8
Plugin.InAppBilling Version="8.0.5"
Targeting Android 34, min 31.
Testing on a physical device.

**Comment by rezamohamed** [comment]
App is still hanging intermittently. I get an ApplicationNotResponding event in Sentry logging:

![CleanShot 2024-12-01 at 09 26 12@2x](https://github.com/user-attachments/assets/ad46ebf3-49fe-4618-bcd9-dc38497ce786)

**Comment by pulmuone** [comment]
![image](https://github.com/user-attachments/assets/29175fcc-e177-49f5-b7e5-a75d5a2a4954)
You must call FinalizePurchaseAsync. If you do not call FinalizePurchaseAsync, Android will refund you if you do not confirm within 3 days of subscription.

**Comment by rezamohamed** [comment]
Yea I already do the finalize, it’s a separate service call (if Android, if purchased). 

But my issue is that I show the available products (in app and subscription). When you essentially click to Buy, a dialog is shown, I tap anywhere outside that, the dialog closes, I Disconnect the connection. So essentially before I even need to Finalize since I’m not purchasing per se, just attempting to buy against all the products one by one. 

Now the issue is when I do this same exact sequence a few times, the app hangs. It’s intermittent, and there is no specific number of attempts after which it hangs.

**Comment by pulmuone** [comment]
![image](https://github.com/user-attachments/assets/6c3af1b9-557d-4788-9fb6-2565998db9f7)

public async Task<InAppBillingPurchase> PurchaseAsync(string productId, ItemType itemType)
{
	InAppBillingPurchase purchase = null;

	var billing = CrossInAppBilling.Current;

	try
	{
	
		// connect to the app store api
		var connected = await billing.ConnectAsync();
		if (!connected)
		{
		
			await DisplayAlert("No InAppBilling", "Conncet Error");
			return;
		}


		purchase = await billing.PurchaseAsync(productId, itemType); //, "payload");

		if (purchase != null)
		{
			if (purchase.State == PurchaseState.Purchased || purchase.State == PurchaseState.Restored)
			{
					try
                    {
                        var ack = await billing.FinalizePurchaseAsync(purchase.TransactionIdentifier);
                    }
                    catch (Exception ex)
                    {
                    }			
			}
		}

	}
    catch (InAppBillingPurchaseException purchaseEx)
    {
        var message = string.Empty;
        switch (purchaseEx.PurchaseError)
        {
            case PurchaseError.AppStoreUnavailable:
                message = "Currently the app store seems to be unavailble. Try again later.";
                break;
            case PurchaseError.BillingUnavailable:
                message = "Billing seems to be unavailable, please try again later.";
                break;
            case PurchaseError.PaymentInvalid:
                message = "Payment seems to be invalid, please try again.";
                break;
            case PurchaseError.PaymentNotAllowed:
                message = "Payment does not seem to be enabled/allowed, please try again.";
                break;
            case PurchaseError.UserCancelled:
                //don't do anything
                break;
            default:
                message = "Something has gone wrong, please try again.";
                break;
        }

        if (string.IsNullOrWhiteSpace(message))
            return;

        await DisplayAlert(purchaseEx.PurchaseError.ToString(), message);
    }
    catch (Exception ex)
    {
        await DisplayAlert("Uh Oh!", $"Looks like something has gone wrong, please try again. Code: {ex.Message}");
    }	
	finally
	{
		await billing.DisconnectAsync();
	}

	return purchase;
}

**Comment by rezamohamed** [comment]
Yea our code is indentical. On iOS everything works fine. Can you attempt on Android the multiple purchase attempts - don’t purchase - close dialog - reattempt purchase. That’s the use case that’s hanging.

**Comment by pulmuone** [comment]
Show me code.... "MainActivity.cs" Android

**Comment by rezamohamed** [comment]
```
[Activity(Theme = "@style/Maui.SplashTheme", MainLauncher = true,
    LaunchMode = LaunchMode.SingleTop,
    ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation | ConfigChanges.UiMode |
                           ConfigChanges.ScreenLayout | ConfigChanges.SmallestScreenSize | ConfigChanges.Density)]
public class MainActivity : MauiAppCompatActivity
{
    public static Context context;

    protected override void OnCreate(Bundle savedInstanceState)
    {
        context = this;
        base.OnCreate(savedInstanceState);

        //to force portrait only mode
        RequestedOrientation = ScreenOrientation.Portrait;
    }
}
```

haven't change this much, only added 'LaunchMode = LaunchMode.SingleTop'

**Comment by pulmuone** [comment]
"System.AggregateException
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread."

https://chatgpt.com/

If you ask chatgpt about this error message, you'll get an answer. It looks like a thread problem.

**Comment by rezamohamed** [comment]
Yea, I've already tried that and attempted all the solutions it has provided. The issue persists. I can't be the only one that is having this issue as its a pretty common scenario where a user attempts a purchase, closes the dialog, retries a different purchase and cancels out of that as well - repeatedly.

**Comment by pulmuone** [comment]
Let's try adding two catches first.

catch (InAppBillingPurchaseException purchaseEx)
{
    var message = string.Empty;
    switch (purchaseEx.PurchaseError)
    {
        case PurchaseError.AppStoreUnavailable:
            message = "Currently the app store seems to be unavailble. Try again later.";
            break;
        case PurchaseError.BillingUnavailable:
            message = "Billing seems to be unavailable, please try again later.";
            break;
        case PurchaseError.PaymentInvalid:
            message = "Payment seems to be invalid, please try again.";
            break;
        case PurchaseError.PaymentNotAllowed:
            message = "Payment does not seem to be enabled/allowed, please try again.";
            break;
        case PurchaseError.UserCancelled:
            //don't do anything
            break;
        default:
            message = "Something has gone wrong, please try again.";
            break;
    }

    if (string.IsNullOrWhiteSpace(message))
        return;

    await DisplayAlert(purchaseEx.PurchaseError.ToString(), message);
}
catch (Exception ex)
{
    await DisplayAlert("Uh Oh!", $"Looks like something has gone wrong, please try again. Code: {ex.Message}");
}

**Comment by rezamohamed** [comment]
this is my ViewModel code 

```
    [RelayCommand]
    private async Task Buy(string type)
    {
        if (!HaveInternetConnection())
        {
            PopupMessage = Constants.MsgNotConnectedToInternet;
            IsOpenPopup = true;
            return;
        }

        if (!isProcessing)
        {
            try
            {
                isProcessing = true;

                BusyPurchasesIndicator = true;

                InAppBillingPurchase purchaseResult = type switch
                {
                    "Monthly" => await inAppBillingService.PurchaseAsync(Constants.DC_MONTHLY_SUB, ItemType.Subscription),
                    "Yearly" => await inAppBillingService.PurchaseAsync(Constants.DC_YEARLY_SUB, ItemType.Subscription),
                    "Lifetime" => await inAppBillingService.PurchaseAsync(Constants.DC_LIFETIME_PURCHASE, ItemType.InAppPurchase),
                    _ => null
                };

                if (purchaseResult != null)
                {
#if ANDROID
                    await inAppBillingService.FinalizeAndroidPurchaseAsync(purchaseResult);
#endif
                    // yay, purchase made
                    var purchaseSettings = new UserSettings()
                    {
                        PurchaseId = purchaseResult.Id,
                        ProductId = purchaseResult.ProductId,
                        IsSubscribed = purchaseResult.State.ToString() == "Purchased",
                        TransactionDate = purchaseResult.TransactionDateUtc,
                        PurchasePlatform = DeviceInfo.Current.Platform.ToString()
                    };

                    subscriptionStatusService.StartListeningForSubscriptionChanges();

                    await datastore.SavePurchaseSettings(purchaseSettings);

                    isProcessing = false;

                    await Cancel();
                    BusyPurchasesIndicator = false;
                }
                else
                {
                    isProcessing = false;
                    // boo, didn't purchase
                    BusyPurchasesIndicator = false;
#if DEBUG
                    logger.LogInfo("** Purchase attempt failed **");
#endif
                }
            }
            catch (InAppBillingPurchaseException purchaseEx)
            {
                isProcessing = false;

                BusyPurchasesIndicator = false;

            HandleInAppBillingPurchaseException(purchaseEx);
#if IOS
            if (PopupMessage != "") IsOpenPopup = true;
#endif
            }
            catch (Exception ex)
            {
                isProcessing = false;
                BusyPurchasesIndicator = false;

                // Log or handle the exception as needed
                logger.LogError(ex);
                PopupMessage = ex.Message;
                IsOpenPopup = true;
            }
            finally
            {
                isProcessing = false;

                BusyPurchasesIndicator = false;
                await SafeDisconnectAsync();
            }
        }
    }
```

```
    private async Task SafeDisconnectAsync(int retryCount = 3, int delayMilliseconds = 500)
    {
        for (var attempt = 1; attempt <= retryCount; attempt++)
        {
            try
            {
                // Attempt to disconnect
                await inAppBillingService.DisconnectAsync();
                return; // Exit once disconnected
            }
            catch (Exception)
            {
                // If this was the last attempt, rethrow or log as a critical failure
                if (attempt == retryCount)
                {
                    logger.LogError(new Exception("Failed to disconnect on attempted subscription purchase"));
                    throw new Exception("Failed to disconnect on attempted subscription purchase");
                }

                // Wait before retrying
                await Task.Delay(delayMilliseconds);
            }
        }
    }
```

**Comment by rezamohamed** [comment]
I may have solved this, maybe a workaround - but it works. I surrounded every call with a check like this:

if (billing.IsConnected)
...
