### ISSUE TITLE
GetPurchasesAsync Exception

### ISSUE THREAD

**Issue by MarcorOnline** [jamesmontemagno/InAppBillingPlugin#66]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 1.2.2 (nuget)
Device Tested On: iPhone 6S Plus
iOS Version: iOS 8

Hello. 
I'm using this library to purchase Auto-Renewable Subscriptions on Xamarin Forms.  
The purchase process works, but after 1 month (subscription expiration) I'm having an issue to check if already exists (restore). 
When I try to get the purchased items, using GetPurchasesAsync, an exception occurs:

https://gist.github.com/MarcorOnline/319897c5256614272aed9c62acc47376

### Code snippet

var storePurchased = await billing.GetPurchasesAsync(ItemType.Subscription);

Thanks for your support

**Comment by MarcorOnline** [comment]
I'm looking the source code of this plugin and, maybe, there is a bug in "ToIABPurchase" method:

`var p = transaction.OriginalTransaction;
if (p == null)
  p = transaction;

if (p == null)
  return null;`

Should be replaced with:
`var p = transaction?.OriginalTransaction ?? transaction;
if (p == null)
  return null;`

I don't know if the crash is related with this, but can be an improvement.

Thanks

**Comment by MarcorOnline** [comment]
@jamesmontemagno I discovered that the real problem is that is necessary to call "CrossInAppBilling.Dispose()" to reset the "CrossInAppBilling.Current" instance. It's not enoug to simply call dispose (for example with using) on the "CrossInAppBilling.Current" instance.

Working with Subscriptions I've found another problem in the "ToIABPurchase" method. Preferring the "OriginalTransaction" it's not possible to detect the last renewing DateTime.

Why you don't use directly the "transaction" object?

Best regards,
Marco

**Comment by jamesmontemagno** [comment]
I am not sure what you are talking about on the Dispose...

It should be:

CrossInAppBIlling.Current.Dispose();

However you never really need to do this from my testing.

**Comment by MarcorOnline** [comment]
@jamesmontemagno CrossInAppBIlling.Current.Dispose(); is not sufficient.
If you look the code, the "Current" entity is not resetted and if you try to use it again you obtain an exception because the "observer" (in iOS implementation) is nulla after CrossInAppBIlling.Current.Dispose();

If you call "CrossInAppBilling.Dispose()" the CrossInAppBIlling.Current.Dispose();  is included, but also a new Lazy for "Current" is created.

To reproduce the problem:
- Get CrossInAppBIlling.Current
- Call "GetPurchasesAsync"
- Call dispose
- Get CrossInAppBIlling.Current again
- Call "PurchaseAsync" -> Exception!

Best regards,
Marco

**Comment by jamesmontemagno** [comment]
I have updated the documentation.

**Comment by rbmanian75** [comment]
@MarcorOnline  Can you able to make it working restore purchases for subscription? If so could you please post the code on how to do it?. I am in the same situation.
Thanks
