### ISSUE TITLE
PurchaseAsync throwing exception in Simulator, even though transaction succeeds

### ISSUE THREAD

**Issue by EdwardCaulfield** [jamesmontemagno/InAppBillingPlugin#67]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 1.2.2
Device Tested On: iPhone 5 with FlightTest & iOS 10.3.3 does not have issue
Simulator Tested On:  iOS Simulator with iOS 10.3, simulating iPhone 6, has issue
Version of VS: VS Mac, 7.0.1 (build 24)
Version of Xamarin: 
Versions of other things you are using: 

Xamarin.Forms 2.3.4.247
Xamarin.Google.iOS.MobileAds 7.16.0
Xam.Plugins.Settings 3.0.1
SkiaSharp 1.59.1
SkiaSharp.Views 1.59.1
SkiaSharp.Views.Forms 1.59.1

### Steps to reproduce the Behavior

var purchase = await CrossInAppBilling.Current.PurchaseAsync( item_ID , ItemType.InAppPurchase,  "apppayload");

### Expected Behavior

Process completes without error or exception

### Actual Behavior

On simulator, PurchaseAsync *always* throws a GeneralError with message "Cannot connect to iTunes Store", even when transaction has successfully completed. Simulator does not give "purchases worked fine" message, which I do receive when testing on real iPhone 5.

Interestingly, the behaviour changes if I repeat the purchase without killing / restarting the simulator.

1st time through - Prompted to buy and then informed that item was already purchased
subsequent tests - Prompted to buy and *not* informed that the item was already purchased

### Code snippet

        async Task<bool> Buy_Feature(int pFeature_ID)
        {
            try
            {
                bool connected = await CrossInAppBilling.Current.ConnectAsync();

                if (!connected)
                {
                    Display_Connection_Failure();
                    //Couldn't connect to billing, could be offline, alert user
                    return false;
                }

                //try to purchase item
                var purchase = await CrossInAppBilling.Current.PurchaseAsync( _Purchaseable_Items[pFeature_ID] , ItemType.InAppPurchase, "apppayload"); 
                if (purchase == null)
                {
                    HomePage.Display_Non_Fatal_Error(_Title_Store_Error, _Error_Purchase_Failed, _Response_Button_Text_Cancel);

					return false;
                }
                else
                {
                    //Purchased, save this information
                    string id = purchase.Id;
                    string token = purchase.PurchaseToken;
                    var state = purchase.State;

                    Enable_Function(pFeature_ID);

					return true;
                }

            }
            catch (InAppBillingPurchaseException pPurchase_Exception)
            {
                Display_Purchase_Exception( pPurchase_Exception);
                return false;
            }
			catch (Exception ex)
			{
				//Something else has gone wrong, log it
				Debug.WriteLine("Issue connecting: " + ex);

                return false;
			}
            finally
            {
                //Disconnect, it is okay if we never connected
                await CrossInAppBilling.Current.DisconnectAsync();

                CrossInAppBilling.Dispose();
            }

### Screenshots

![image](https://user-images.githubusercontent.com/2613598/28873632-c7536e82-778e-11e7-8ee9-54e87535bad1.png)

![image](https://user-images.githubusercontent.com/2613598/28873641-d3a0ccac-778e-11e7-9b38-47815ba318e3.png)

**Comment by jamesmontemagno** [comment]
It's not possible to test IAP on simulators.

**Comment by EdwardCaulfield** [comment]
Thanks!

Best Regards,

Edward Caulfield
http://www.ar-intelligence.info/
+41 76 281 1960

If you're not progressing, you're regressing;

This email and any files transmitted with it may contain confidential and/or legally protected information. They are intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the sender and delete it immediately, considering its dissemination, distribution or copying being strictly prohibited.
