### ISSUE TITLE
Crash with no error in UWP?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [jamesmontemagno/InAppBillingPlugin#69]
Purchase success on Andoird. 
But on UWP (Lumia 950 XL) it's crash with no error throw, but it's working fine when run in Debug mode and working fine on Windows 10 PC. 
What happened!

**Comment by nguyenthanhliemfc** [comment]
On my Lumia
In Debug mod, when purchase app show log in screen and purchase successful.
But,
When run normal from app list on phone, my app don't show log in screen and jump out to Home screen. Then I try normal run app on Windows 10 PC, it's purchase success.
Only happen on Lumia when run in normal mode!

**Comment by jamesmontemagno** [comment]
And the app is already on the app store? or are you in debug mode?

do you know what the error is?

**Comment by nguyenthanhliemfc** [comment]
Here my app link 
https://www.microsoft.com/en-us/store/p/vietlott/9nnt9nstt56q
It's Vietnamese, to purchase follow this step
1 Open humberger menu
2 Click on "Xoá Quảng Cáo" 
3 Click on "Xoá Quảng Cáo Vĩnh Viễn
And it's crash 
But working fine on PC

**Comment by prashantvc** [comment]
@nguyenthanhliemfc Is this still an issue with your app?

**Comment by nguyenthanhliemfc** [comment]
@prashantvc Yes, it's still happend with Windows 10 mobile

**Comment by nguyenthanhliemfc** [comment]
@jamesmontemagno It's only happend with Windows 10 Mobile. It's working fine on Windows 10 Pro for PC
