### ISSUE TITLE
Object reference not set to an instance of an object on ConnectAsync

### ISSUE THREAD

**Issue by egimbernat** [jamesmontemagno/InAppBillingPlugin#71]
I have tried several way and always I getting the error. I have all configured, the Billing permission, app on alpha and compiling against api 26.

## Bug Information

Version Number of Plugin: 1.2.2
Device Tested On: Samsung Galaxy S7 Edge
Version of VS: 2017 Enterprise - 15.3.1
Version of Xamarin: 4.6

StackTrance = https://gist.github.com/egimbernat/991b516159329d528696d042fc5619d8

### Steps to reproduce the Behavior
Try to ConnectAsync and error ocurrs.

### Expected Behavior
Connects successfully

### Actual Behavior
Exception is thrown

### Code snippet

 ```
 var billing = CrossInAppBilling.Current;
            try
            {
                var connected = await billing.ConnectAsync();

                if (!connected)
                {
                    return;
                }

                var subscriptions = await billing.GetProductInfoAsync(ItemType.Subscription, prods.Where(p => p.Type == 1).Select(c => c.Id).ToArray());

                foreach (var item in subscriptions)
                {
                    var prod = prods.First(p => p.Id == item.ProductId);
                    prod.Name += $" - {item.LocalizedPrice} {item.CurrencyCode}";
                    AvailableProducts.Add(prod);
                }

            }
            catch (InAppBillingPurchaseException pEx)
            {
                ProcessInAppBillingException(pEx);
            }
            catch (Exception ex)
            {
                ex.Process();
            }
            finally
            {
                await billing.DisconnectAsync();
            }

```

**Comment by jamesmontemagno** [comment]
Have you read through this: https://jamesmontemagno.github.io/InAppBillingPlugin/TestingAndTroubleshooting.html your app most likely isn't configured correct.

**Comment by egimbernat** [comment]
Yes I have readed it, but not succeed :( In fact is not a new app, I had an existing implementation of InApp Billing, so for sure it was working, I re-made the app and now I using the plugin.

The unique difference I saw, is that I'm using Net.Standard instead of PCL and Package Reference on the host projects, something like this:

```
    <CopyNuGetImplementations>true</CopyNuGetImplementations>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
```

**Comment by acrabb** [comment]
I'm seeing the same issue. I went through the configuration you linked @jamesmontemagno.
VS says its on line 589 which is `if (Context.PackageManager.QueryIntentServices(serviceIntent, 0).Any())`

Any thoughts?

**Comment by jamesmontemagno** [comment]
It is impossible to be on API 26 as we don't support it yet.

**Comment by jamesmontemagno** [comment]
You should not be compiling against API 26 at all, that would be a terrible idea.

I will take a look at that code though, do you know which part is the null ref exception?

**Comment by egimbernat** [comment]
I do, it's the Context. I will downgrade the API and will inform the result.

**Comment by jamesmontemagno** [comment]
Did you remove the MainApplication.cs file that was added to your app?

https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/src/Plugin.InAppBilling.Android/InAppBillingImplementation.cs#L47 

this grabs your current activity that is active.

**Comment by egimbernat** [comment]
No, I left it as is installed. Let me downgrade some things, test it and return with a verdict if all went fine.

**Comment by egimbernat** [comment]
Ok, so I downgrade all to compile against API 25, it's important to remove API 26 and Tools in order to work (Terrible idea to have this API right now installed).
Even that Current context was setting always was null on the Connect method.
Now works fine.

**Comment by jamesmontemagno** [comment]
Glad you got it working. I will test this out with the SDKs, but only API 25 is supported currently.

**Comment by acrabb** [comment]
I just got it working too. Turns out our project already depended on `Plugin.CurrentActivity` and whoever added it before must have removed `MainApplication.cs`

**Comment by EmilAlipiev** [comment]
@jamesmontemagno Does plugin already support api level 26 or 27?

**Comment by jamesmontemagno** [comment]
yup

**Comment by EmilAlipiev** [comment]
I am seeing this exception on my production as well. I have tested with 2 different accounts on 2 different android phones and my tests were successful. I cant get purchases, however I see some users get this exception as below. What could be the possible reason?
```

System.NullReferenceExceptionObject reference not set to an instance of an object
Raw
  at Plugin.InAppBilling.InAppBillingImplementation+InAppBillingServiceConnection.OnServiceConnected (Android.Content.ComponentName name, Android.OS.IBinder service) [0x00033] in <dc8bf25b40af44ada99053dbb7431c30>:0 
  at Android.Content.IServiceConnectionInvoker.n_OnServiceConnected_Landroid_content_ComponentName_Landroid_os_IBinder_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_name, System.IntPtr native_service) [0x00017] in <fb3979555cbc4c178444b284242e6fbe>:0 
  at (wrapper dynamic-method) System.Object:e422cf66-676d-4c5b-a484-486933c57518 (intptr,intptr,intptr,intptr)
```
