### ISSUE TITLE
Promo Codes .... how to implement

### ISSUE THREAD

**Issue by davidbell81** [jamesmontemagno/InAppBillingPlugin#72]
First of all thanks so much for creating this plugin. It is great. However I am having trouble trying to implement Promo Codes for Consumable in app purchases.
In my app the user has to buy tickets to view content. When the tickets run out they are prompted to buy more via in app purchases. I have also generated some promo codes via ItunesConnect and these can be redeemed through appstore app on the iphone. When a user does this they are taken to my app but I have no way of implementing the purchase. 
Currently when they purchase through the app I just adjust a sql database locally once I see that the transaction was completed but with promo codes I have no way of knowing they have processed a transaction.

Any ideas?

**Comment by davidbell81** [comment]
Maybe has something to do with SKPaymentTransactionObserver ????

**Comment by jamesmontemagno** [comment]
Promo Codes are redeemed through iTunes Connect and are returned as a transaction purchase from my understanding.

**Comment by jamesmontemagno** [comment]
You may also want to follow the normal flow of putting some code in your app delegate for that.

**Comment by davidbell81** [comment]
Thanks James, 
Any chance you can point me in the right direction for this. I assume this will involve getting my hands dirty in platform specific code rather than using your very nice plugin?

**Comment by jamesmontemagno** [comment]
Basically all the stuff in the docs: https://jamesmontemagno.github.io/InAppBillingPlugin/TestingAndTroubleshooting.html

Should be very minimal code.

**Comment by jamesmontemagno** [comment]
You should check for promo code purchases with: https://jamesmontemagno.github.io/InAppBillingPlugin/CheckAndRestorePurchases.html
