### ISSUE TITLE
GeneralError Received when Running Code

### ISSUE THREAD

**Issue by Silent-Zebra** [jamesmontemagno/InAppBillingPlugin#74]
Hi James,

Thanks so much for your work on this. I can tell it wouldn't have been easy to put this plugin together.

I would really appreciate it if you could help with an issue I'm having. I'm a bit new to app development/coding so please bear with me. I've read the documentation, and after several days of trying things, I still can't get the sample code to work. 

Here's the code I have so far, adapted from the sample code provided, and cleaned to be easier to read. NotificationMessageBox is a custom function that displays a message box with the desired text. I am using a shared project, and am just building the iOS side for now:

    public async void MakePurchase()
    {
        if (!CrossInAppBilling.IsSupported)
        {
            NotificationMessageBox("CrossInAppBilling not supported");
            return;
        }

        var billing = CrossInAppBilling.Current;
        try
        {
            var connected = await billing.ConnectAsync();
            if (!connected)
                NotificationMessageBox("Not Connected");
            else
            {
                var purchase = await billing.PurchaseAsync("productID", ItemType.InAppPurchase, "payload");
                //where productID is the com.website.product format for the item in the app store
              
                if (purchase == null)
                {
                    NotificationMessageBox("Not Purchased");
                }
                else
                {
                    NotificationMessageBox("Purchased");
                }
            }
        }
        catch (InAppBillingPurchaseException purchaseEx)
        {
            switch (purchaseEx.PurchaseError)
            {
                //Error handling code removed for sake of simplicity/readability
            }
        }
        finally
        {
            await billing.DisconnectAsync();
        }

        CrossInAppBilling.Dispose();
    }

All code compiles, and the project builds. Everything works fine until I get to the line:

var purchase = await billing.PurchaseAsync("productID", ItemType.InAppPurchase, "payload");

With a break point on this line, as soon as I take one step, I get the prompt to sign in to the app store. After I sign in, the code then immediately jumps to the catch, skipping over the entire if (purchase == null) statement (it doesn't even check the if statement).

At this point, the variable "purchase" is still null.

The purchaseEx error that I get is of the type GeneralError, of which unfortunately the only description provided in the documentation is "other error". Even looking at the source code, it refers to an unknown error received.

Finally, at the end of the code block above, the app crashes.

Interestingly, even when I change the productID to a nonsense string, I get exactly the same behaviour and same error - it appears to fail before it even makes the call to the app store to check the product?

I read somewhere that you can't test in-app purchases on an emulator, so I tried deploying to a physical device, but got the same behaviour and error messages as well. I've tried with a real and a sandbox Apple ID and got the same results (though maybe I incorrectly used the sandbox account?)

Any suggestions as to where I'm going wrong would be greatly appreciated. Happy to provide any further information that might be helpful.

**Comment by asjit** [comment]
try changing 
`public async void MakePurchase()`
to
`public async Task MakePurchase()`

Ash.

**Comment by jamesmontemagno** [comment]
Be sure to read through: https://jamesmontemagno.github.io/InAppBillingPlugin/TestingAndTroubleshooting.html

**Comment by Silent-Zebra** [comment]
Thanks for the responses and suggestions!

Asjit - I tried changing to Task but got the same behavior.

I'll take another read through the documentation and revert.

**Comment by Sebastian1989101** [comment]
Did you try this in the Simulator? This is exactly what happens to me when I run it in the Simulator but it "works"  on an actual device through TestFlight and AppStore Builds.

**Comment by jamesmontemagno** [comment]
I'm unable to reproduce, works just fine.

**Comment by Silent-Zebra** [comment]
Alright so looks like I finally got it working. I will still need to test it in actual production, but at least I'm getting success messages from the sandbox environment (in iOS - I will have to figure out Android later...).

Notes below for reference. I recognize the below will probably be obvious for many, but I'll leave it here as a record for myself and maybe this can help someone who's just starting out somewhere :)

Key things from the iOS side: sandbox testers can apparently be corrupted if you log in to any production environment. I suspect I may have done this accidentally somehow during my tests. And for some reason, the first time I tried it (choosing "use an existing account" when prompted), I had to enter my account details twice. It failed (could not connect to iTunes). Then, I tried again, (so this time the device recognized my testing username, and I only had to enter the password) and it worked.

Code example (with call to CheckPurchase() as the starting point):

    async void CheckPurchase()
    {
		
	bool purchaseIsSuccessful = await TestMakePurchase("com.website.appName.purchaseName", "");

        if (purchaseIsSuccessful)
        {
            //Success! Do what you want here

        }
        else
        {
            //:(
        }
    }

    public async Task<bool> TestMakePurchase(string productId, string payload)
    {
        var billing = CrossInAppBilling.Current;
        try
        {
            var connected = await billing.ConnectAsync();
            if (!connected)
            {
                //we are offline or can't connect, don't try to purchase
                return false;
            }

            //check purchases
            var purchase = await billing.PurchaseAsync(productId, ItemType.InAppPurchase, payload);

            //possibility that a null came through.
            if (purchase == null)
            {
                //did not purchase
                return false;
            }
            else
            {
                //purchased!
                return true;
            }
        }
        catch (InAppBillingPurchaseException purchaseEx)
        {
            
                //Error handling code removed for sake of simplicity/readability

        }
		
        finally
        {
            await billing.DisconnectAsync();
        }
    }

I'm cautiously optimistic this means I should be able to get this working now. Thanks all for the help, and of course, thanks James for your work putting this plugin together :)

**Comment by Sebastian1989101** [comment]
@Silent-Zebra all the stuff you write is very well documented from @jamesmontemagno here: https://jamesmontemagno.github.io/InAppBillingPlugin/
