### ISSUE TITLE
Purchase of Subscription Feature works fine on my iPhone & iPad Mini, bombs for Apple with "Cannot connect to iTunes Store"

### ISSUE THREAD

**Issue by EdwardCaulfield** [jamesmontemagno/InAppBillingPlugin#77]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

The purchase of a subscription Feature works fine on my iPhone 5 and iPad Mini, but when Apple tests it for approval of the Feature, it fails with "Cannot connect to iTunes Store", which is the message I am getting from the PurchaseException object. Apple indicates they are testing on an iPad.

Before I open a TSI with Apple, I wanted to first see if you've seen this issue before and have suggestions for its resolution. 

Also, I expect that if I open a TSI with Apple, they will want to review the iOS specific code, not the plug-in calls I am using in Xamarin.  I assume that I may provide them the source to this plug-in.  Any issues with this?

Many thanks in advance.

Edward

Version Number of Plugin: 1.2.2
Device Tested On: iPhone 5, iPad Mini, iPad, all running 10.3.3
Simulator Tested On:  Not testable on simulator
Version of VS: 7.1 (build1297)
Version of Xamarin: 2.3.4-270
Versions of other things you are using:

SkiSharp, SkiaSharp.Views, SkiaSharp.Views.Forms 1.59.1
Xam.Plugins.Settings  3.0.1
Xamarin.Build.Download 0.4.7
Xamarin.Google.iOS.MobileAds 7.19.0

### Steps to reproduce the Behavior

Purchase a subscription Feature

### Expected Behavior

Purchase is processed correctly

### Actual Behavior

Purchase fails with "Cannot connect to iTunes Store"

### Code snippet

        void Display_Purchase_Exception(InAppBillingPurchaseException pPurchase_Exception)
        {
            var message = string.Empty;
            switch (pPurchase_Exception.PurchaseError)
            {
                case PurchaseError.AppStoreUnavailable:
                    message = "Currently the app store seems to be unavailble. Try again later.";
                    break;
                case PurchaseError.BillingUnavailable:
                    message = "Billing seems to be unavailable, please try again later.";
                    break;
                case PurchaseError.PaymentInvalid:
                    message = "Payment seems to be invalid, please try again.";
                    break;
                case PurchaseError.PaymentNotAllowed:
                    message = "Payment does not seem to be enabled/allowed, please try again.";
                    break;

                default:
                    message = pPurchase_Exception.Message;
                    break;

            }

            //Decide if it is an error we care about
            if (string.IsNullOrWhiteSpace(message))
                return;

            //Display message to user
            //Something bad has occurred, alert user
            HomePage.Display_Non_Fatal_Error(_Title_Store_Error, _Error_Purchase_Failed + ", Message : " + message, Global_Functions._Response_Button_Text_Cancel);
            return;
        }

### Screenshot

<img width="1759" alt="screen shot 2017-09-11 at 4 23 43 pm" src="https://user-images.githubusercontent.com/2613598/30470033-6fb86eac-99f3-11e7-922c-e31ea826424b.png">

**Comment by jamesmontemagno** [comment]
I would assume their test user is not correct, that is usually what it means. I have not had any issue and obviously the code path is the same for all devices.

The code is under MIT and you can do/share whatever.

**Comment by EdwardCaulfield** [comment]
Hello James,

Thanks for the quick reply.

Best Regards,

Edward Caulfield
http://www.ar-intelligence.info/
+41 76 281 1960

If you're not progressing, you're regressing;

This email and any files transmitted with it may contain confidential and/or legally protected information. They are intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the sender and delete it immediately, considering its dissemination, distribution or copying being strictly prohibited.

**Comment by prashantvc** [comment]
> but when Apple tests it for approval of the Feature, it fails with "Cannot connect to iTunes Store"
Did they share device logs with you? Device logs are resourceful in these scenarios. How did it go with Apple TSI?

Since you're working with Apple TSI, I am closing this issue. Please don't hesitate to reopen if you continue to have any trouble

**Comment by EdwardCaulfield** [comment]
Thanks for the idea about the device logs.  Didn't know this was an option.

I will update the thread if / when a resolution is determined.

Best Regards,

Edward Caulfield
AR Intelligence 
www.ar-intelligence.info

**Comment by EdwardCaulfield** [comment]
BTW - would you be able to recommend a link where I can educate myself about device logs?

Best Regards,

Edward Caulfield
AR Intelligence 
www.ar-intelligence.info

**Comment by prashantvc** [comment]
>  would you be able to recommend a link where I can educate myself about device logs? 

You can find the instructions [here](https://stackoverflow.com/a/27824736/85606) to get logs from local device.

> but when Apple tests it for approval of the Feature, it fails

Apple will usually send you the detailed report when approval process fails. You can request the logs from them if they are not shared with you already

**Comment by EdwardCaulfield** [comment]
Many thanks for the info!  Apple not only didn’t provide a detailed report, they originally didn’t even say why the Feature was rejected.  I had to ask for an explanation. I suspect I got the Newbie on the team this time.

Best Regards,

Edward Caulfield
http://www.ar-intelligence.info/
+41 76 281 1960

If you're not progressing, you're regressing;

This email and any files transmitted with it may contain confidential and/or legally protected information. They are intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the sender and delete it immediately, considering its dissemination, distribution or copying being strictly prohibited.

**Comment by mateusz-dot** [comment]
@EdwardCaulfield did you resolved this issue? I have same problem as you had.

**Comment by EdwardCaulfield** [comment]
It has been so long, that I unfortunately forgot how this was rectified.  If I remember correctly, I opened a rectification request with Apple and then it was suddenly cleared.

Sorry that I cannot say more....
