### ISSUE TITLE
Additionnal info in the doc : Plugin.CurrentActivity must be setup 

### ISSUE THREAD

**Issue by jonathanantoine** [jamesmontemagno/InAppBillingPlugin#8]
## Feature Request:
Please add in your readme / documentation that the Plugin.CurrentActivity must be setup (http://motzcod.es/post/133609925342/access-the-current-android-activity-from-anywhere) to use this plugin. Otherwise it will throw a NullRefException.

Thanks a lot for your plugin and your work !

**Comment by jamesmontemagno** [comment]
It is a dependency and will bring in the file automatically for you when you add the nuget.

**Comment by jonathanantoine** [comment]
You're right but if you are dumb enough to remove it (as me :'() because you think it's kind of a "documentation / example" file, you will spend a long time figuring out where it comes from.

**Comment by asj-it** [comment]
Can you just add 
`CrossInAppBilling.Current.Activity = this`
in your mainactivity - as I don't currently have an application - or do you need to have the application there too?

**Comment by jonathanantoine** [comment]
@asj-it  : I think you can set it in your main activity (in fact it's CrossCurrentActivity.Current.Activity) but I think it's nicer if you have "Plugin.CurrentActivity" set up the right way if there is a dependency on this package.

**Comment by jamesmontemagno** [comment]
@asj-it you could, but I don't recommend it. The application class handles it a lot nicer for you :)

**Comment by Metlina** [comment]
@jamesmontemagno I can have normal MainActivity and your MainApplication in same project? Also only application class that I have is in PCL.

**Comment by jamesmontemagno** [comment]
The Xamarin.Forms App is different then the Android Application ;) so you are good.
