### ISSUE TITLE
ConsumePurchaseAsync throws NullReferenceException

### ISSUE THREAD

**Issue by falox** [jamesmontemagno/InAppBillingPlugin#80]
## Bug Information

Version Number of Plugin: 1.2.2
Device Tested On: Ulefone U007 (Android 6)
Simulator Tested On: N/A
Version of VS: 15.3.3 (2017)
Version of Xamarin: 4.6.0.299
Versions of other things you are using:

### Steps to reproduce the Behavior

I cannot isolate the problem, since it's specific for my project. The strange thing is that I'm making a normal call, so it should work. 

I've verified both parameters are not null, The previous `PurchaseAsync` call is successfull.

`await CrossInAppBilling.Current.ConsumePurchaseAsync("valid purchase id", "valid purchase token");`

This code is inside a Service. 

Looking at the source code, line 392 (see the stacktrace below) is a comment, so I cannot understand the exact causes. Since both input parameters are not null, is maybe [Context](https://github.com/jamesmontemagno/InAppBillingPlugin/blob/3523a959cd5e1c0e029deb441adf5baff3d7d95d/src/Plugin.InAppBilling.Android/InAppBillingImplementation.cs#L403) null?

### Expected Behavior

Doesn't throw exception

### Actual Behavior

Throws exception

```
I/mono-stdout(12754): System.NullReferenceException: Object reference not set to an instance of an object.
  at Plugin.InAppBilling.InAppBillingImplementation.ConsumePurchaseAsync (System.String productId, System.String purchaseToken) [0x00000] in C:\projects\inappbillingplugin\src\Plugin.InAppBilling.Android\InAppBillingImplementation.cs:392 
```

**Comment by prashantvc** [comment]
@falox It's not obvious what is `null` here, since you cannot isolate the problem, and stack trace is not helpful.

I recommend you clone this repository, and reference project/source instead of Nuget package, this will help you debug better, step directly into `ConsumePurchaseAsync` 

Let us know if you need assistance to debug it

**Comment by falox** [comment]
Thanks @prashantvc 

The exception is thrown [here](https://github.com/jamesmontemagno/InAppBillingPlugin/blob/3523a959cd5e1c0e029deb441adf5baff3d7d95d/src/Plugin.InAppBilling.Android/InAppBillingImplementation.cs#L398):

`if (serviceConnection.Service == null)`

serviceConnection was null, since another thread had called `DisconnectAsync()` in the meantime and serviceConnection is a static shared variable. Maybe the line could be changed in:

`if (serviceConnection?.Service == null)`

It will still throw a exception, but with a meaningful message.

Since I cannot serialize the calls to `CrossInAppBilling.Current`, as a workaround I've wrapped the Connect/Disconnect methods in my service:

```
public class InAppService : IInAppService
{
	// NOTE: these methods are still not thread-safe, you should add an exclusive lock

	private int _connections = 0;
	private async Task<bool> ConnectAsync()
	{
		bool result = false;

		if (_connections == 0)
		{
			result = await CrossInAppBilling.Current.ConnectAsync();
		}
		else
		{
			result = true;
		}

		_connections++;

		return result;
	}

	private async Task DisconnectAsync()
	{
		_connections = Math.Max(0, _connections - 1);

		if (_connections == 0)
		{
			await CrossInAppBilling.Current.DisconnectAsync();
		}
	}
	
	:
}
```

**Comment by jamesmontemagno** [comment]
I'll add some more checks for null in next version.
