### ISSUE TITLE
Payload

### ISSUE THREAD

**Issue by timdmaxey** [jamesmontemagno/InAppBillingPlugin#81]
I am creating subscription just fine and passing a payload it's a guid string. All good..

When checking the subscription, Payload is blank, need something to check against the server.

InAppBillingPurchase purchase = await CrossInAppBilling.Current.PurchaseAsync(productId, ItemType.Subscription, uguid);

Works fine...

var verify = DependencyService.Get<IInAppBillingVerifyPurchase>();
                var purchases = await billing.GetPurchasesAsync(ItemType.Subscription, verify);

                foreach (var item in purchases)
                {
                    if (item.ProductId.ToString() == productId)
                    {
                        await DisplayAlert("Purchase", item.State.ToString() + " " + item.TransactionDateUtc.ToLocalTime() + " PL: " + item.Payload + " PID: " + item.ProductId + " ID: " + item.Id, "OK");
                        
                    }

                }

The item.Payload is always blank, not the guid string I passed? Any ideas?

**Comment by timdmaxey** [comment]
Basically trying to check on application load if the user has a subscription that is active, and update our server subscription expires on date. Tried the verify to see if i could save a receipt id or something to the server and then pull that back???

**Comment by jamesmontemagno** [comment]
Did you read through: https://jamesmontemagno.github.io/InAppBillingPlugin/SecuringPurchases.html

Also based on the type of subscription you should be tracking it.

**Comment by jamesmontemagno** [comment]
Payload is only for Android and is what is used to verify the transaction from google.

**Comment by timdmaxey** [comment]
Hey thanks for responding your awesome! Yes I did go through that and I can pass the verify variable to the purchase and do a GetPurchaseAsync, but not sure what to do from there, sorry...

Is/does the verify variable have return items in it from the purchase side? I couldn't see anything but a VerifyPurchase routine? Trying to grab something from the purchase to save to our server so I can check the subscription and update a subscription expires on the server side...

thanks man for all your work!

**Comment by timdmaxey** [comment]
ok so the verify variable does return receipt? thanks

**Comment by jamesmontemagno** [comment]
Yup! that is the signed data :)

**Comment by timdmaxey** [comment]
Hey so this is what I got: Prob not correct, but I get to the else and the var verify is null and there is the VerifyPurchase bool event... Trying to see how to get that "signed data" Sorry kinda new to this...

var verify = DependencyService.Get<IInAppBillingVerifyPurchase>();
						InAppBillingPurchase purchase = await CrossInAppBilling.Current.PurchaseAsync(productId, ItemType.Subscription, "payloadisforandroid", verify);
						if (purchase == null)
						{
							//Something went wrong with the purchase
							UserDialogs.Instance.Loading().Hide();
							await DisplayAlert("Subscribe", "We are sorry, but the subscription did not go through.", "Ok");

						}
						else
						{
                            await DisplayAlert("debug", verify.ToString(), "OK");
							//Purchased, save this information
							var id = purchase.Id;
                            Helpers.Settings.STOREIDSetting = purchase.Id;
                            Helpers.Settings.ISSTORESetting = "true";

}
