### ISSUE TITLE
Support for Mac

### ISSUE THREAD

**Issue by saldoukhov** [jamesmontemagno/InAppBillingPlugin#82]
Any plans for that?

**Comment by jamesmontemagno** [comment]
No plans to add macOS at this time as it is already too complicated for me to support these 4 platforms.

**Comment by Suplanus** [comment]
Any plans to reopen this issue?

**Comment by x-ji** [comment]
@Suplanus There's an open issue https://github.com/jamesmontemagno/InAppBillingPlugin/issues/202 though nobody seems to be taking it yet.
