### ISSUE TITLE
Offline restore

### ISSUE THREAD

**Issue by henrik6** [jamesmontemagno/InAppBillingPlugin#83]
I haven't looked into the implementation, but it seems there are no methods to store or restore the non-consumables to/from "cache", eg in shared preferences or similar. So if  the user isn't online, he/she won't be able to access the purchased items ? It would be great if this API would provide such offline-restore functionality!

**Comment by jamesmontemagno** [comment]
You just need to save this locally when someone purchases something. Use the settings plugin or something equivalent.
