### ISSUE TITLE
Auto-Renewing and TransactionDateUTC Parameters 

### ISSUE THREAD

**Issue by Vaibhav-Khanna** [jamesmontemagno/InAppBillingPlugin#85]
While testing the in-app auto-renewal subscription with sandbox test user, the auto renewing parameter is always false whereas it is setup as auto-renewing in iTunes connect. And transaction date  is the same for all the renewed subscriptions that are generated in sandbox  @environment.
<img width="357" alt="screen shot 2017-10-10 at 7 07 41 pm" src="https://user-images.githubusercontent.com/14903776/31389700-880a3462-adef-11e7-8515-e0c880a16edc.png">

Now question is if this is a limitation in testing phase, how should we be sure that in production these parameters will be received correctly ? or if its a bug in the plugin ?
# @jamesmontemagno @Redth

**Comment by jamesmontemagno** [comment]
Apple does not tell me this info: https://developer.apple.com/documentation/storekit/skpaymenttransaction

You will need to figure that out yourself since you set up as auto-renewing.
