### ISSUE TITLE
PurchaseAsync() returning Error

### ISSUE THREAD

**Issue by ConsentDevelopment** [jamesmontemagno/InAppBillingPlugin#9]
I am getting the following error message when trying to purchase a item on the Android platform ;

    Error - The item you requested is not available for purchase

Everything is setup correctly and using the IAP test product ID "android.test.purchased" works fine.

The app is published and the IAP product is active.  The APK uploaded is signed with the same signing key used for the test debug APK.  

The test user has been added to the developer account and also added as a closed beta tester.

Device - Nexus 5x, Android 7.1.1

**Comment by ConsentDevelopment** [comment]
Found the problem.  I had to active the Google tester account using the Opt-in URL. 

Everything is now working perfectly :)

**Comment by jamesmontemagno** [comment]
Yup! The debugging is the "fun" part :)

**Comment by jamesmontemagno** [comment]
Checkout: 1.1.0.15-beta

**Comment by EmilAlipiev** [comment]
@ConsentDevelopment  I had that also missing but after even doing it, it doesnt work for me. what else did you do? as you said using test is no problem
