### ISSUE TITLE
[Question] How to deal with offline mode?

### ISSUE THREAD

**Issue by Maxikq** [jamesmontemagno/InAppBillingPlugin#90]
Hi,

your plugin looks pretty nice and I would like to use it in my project, however I'm confused how to deal with offline mode? I want application to be able to 'know' if user purchased something or not, even if app is offline. 

What are best practices for that? I couldn't find any guide even on Apple Developer. Do you have any recommendations how to implement this functionality using your plugin?

Best regards

**Comment by jamesmontemagno** [comment]
Well each platform caches this information, but you should use some secure settings to figure out what they have purchased. I just use my settings plugin, but more secure is to use keystores.
