### ISSUE TITLE
Multiple Login Dialogs

### ISSUE THREAD

**Issue by wickedw** [jamesmontemagno/InAppBillingPlugin#91]
Hi,

Again, not sure if this is a BUG at all, but I am in the final stages of testing in-app purchases (this is an auto-renewing subscription).  All the code works in terms of checking for existing subscription and buying a new one (and remotely checking these values etc via IInAppBillingVerifyPurchase).

So, really great, but the reason for this polite help request ...

When testing via TestFlight (and my real IOS ITunes account), and I am now getting MANY MANY (5-7+) login requests when trying to check / restore my initial purchase (when calling GetPurchasesAsync) and when I finally get to Buy a Subscription (via PurchaseAsync).

If I type passwords for them all in, things eventually seem to get to the end of the process, and I am fairly sure I only had to do it the once on the first even install for that user.

But if this was the case in production, it would break my app, and was just wondering if anyone has seen anything similar in TestFlight (I had issue with sandbox accounts during development but this is slightly different)?

I get the feeling that the number of dialogs in increasing as I test the app and re-purchase the subscriptions, which makes me feel it "could" be something to do with similar to this -

https://stackoverflow.com/questions/4988663/skpaymentqueue-addtransactionobserver-asking-for-app-store-password-on-startup-a

Although I can see the code specifically -

https://github.com/jamesmontemagno/InAppBillingPlugin/blob/master/src/Plugin.InAppBilling.iOS/InAppBillingImplementation.cs 

calls to -

SKPaymentQueue.DefaultQueue.FinishTransaction(transaction);

I am not familiar with the IOS workflow for all of this (hence was trying to get by with using the plugin and not digging in), but will download the source and link into my app and debug the workflow to see if can get it to repeat during development builds, and if anyone has any ideas how one would test this at the testflight stage, very welcome.

Thanks for your help.

p.s. got about 12-13 dialogs on my latest single purchase test :( can send screenshots internally if that helps at all.

Version Number of Plugin: 1.2.1 (and just tried latest 1.2.3.107) 
Device Tested On: IOS
Version of VS: Latest
Version of Xamarin: Latest

**Comment by wickedw** [comment]
With regards to getting this debugging in my local project, I have the following set up (as this is an old project) -

Xamarin.IOS.Library (Core Logic)
Xamarin.IOS Platform Project

I have downloaded source from github and included (and referenced instead of Nuget)

Plugin.InAppBilling.Abstractions
Plugin.InAppBilling
Plugin.InAppBilling.IOS

Builds fine, but not sure how to get InAppBillingImplementation constructor breakpoint to fire on device testing.

Does this sound correct? or am I missing something.

Thanks
Matt

**Comment by jamesmontemagno** [comment]
Yeah for debuggign, you should add Abstractions/iOS to your iOS project and then InAppBilling and Abstractions to your PCL/NetStandard

**Comment by wickedw** [comment]
Thanks James, I will persevere until I get a breakpoint hit :)

**Comment by wickedw** [comment]
![image](https://user-images.githubusercontent.com/4195207/32319582-fdf3dae6-bfb2-11e7-9ad0-6c4fa78a0474.png)

As I do not have a PCL in this project, just a Xamarin.IOS Library (which referenced the InAppBilling Nuget etc originally), will this stop the debugging working (i.e. effects the bait and switch somehow?)

Thanks
Matt

**Comment by jamesmontemagno** [comment]
Nope, just reference the Abstractions and iOS project

**Comment by wickedw** [comment]
Right, pasted the code in and got it debugging, "interestingly" on app start I got 12 transactions in the UpdateTransactions call (now this is using the Debug build NOT the test flight build, so not 100% sure whose transactions these where) -

Resolved pending breakpoint at 'InAppBillingImplementation.cs:747,1' to void WTMXAM.Core.BL.Class.PaymentObserver.UpdatedTransactions (StoreKit.SKPaymentQueue queue, StoreKit.SKPaymentTransaction[] transactions) [0x00027].
Updated Transaction | ProductId:SUBSCRIBE_YEAR | AutoRenewing:False | State:Purchased | Id:1000000316908988
Thread finished: <Thread Pool> #6
Thread finished: <Thread Pool> #7
Thread finished: <Thread Pool> #4
Thread started: <Thread Pool> #9
Thread started: <Thread Pool> #10
Thread started: <Thread Pool> #12
Thread started: <Thread Pool> #11
Updated Transaction | ProductId:SUBSCRIBE_YEAR | AutoRenewing:False | State:Purchased | Id:1000000316908988
Updated Transaction | ProductId:SUBSCRIBE_YEAR | AutoRenewing:False | State:Purchased | Id:1000000316908988
Resolved pending breakpoint at '/Users/matthewwaring/Dropbox/Xamarin2/WTMXam/WTMXAM.Core/BL/Class/InAppBillingImplementation.cs:771,1' to void WTMXAM.Core.BL.Class.PaymentObserver.UpdatedTransactions (StoreKit.SKPaymentQueue queue, StoreKit.SKPaymentTransaction[] transactions) [0x000fa].
Thread finished: <Thread Pool> #10
Updated Transaction | ProductId:SUBSCRIBE_YEAR | AutoRenewing:False | State:Purchased | Id:1000000316908988
Updated Transaction | ProductId:SUBSCRIBE_YEAR | AutoRenewing:False | State:Purchased | Id:1000000316908988
Updated Transaction | ProductId:SUBSCRIBE_YEAR | AutoRenewing:False | State:Purchased | Id:1000000316908988
Updated Transaction | ProductId:SUBSCRIBE_YEAR | AutoRenewing:False | State:Purchased | Id:1000000316908988
Updated Transaction | ProductId:SUBSCRIBE_YEAR | AutoRenewing:False | State:Purchased | Id:1000000316908988
Updated Transaction | ProductId:SUBSCRIBE_YEAR | AutoRenewing:False | State:Purchased | Id:1000000316908988
Updated Transaction | ProductId:SUBSCRIBE_YEAR | AutoRenewing:False | State:Purchased | Id:1000000316908988
Updated Transaction | ProductId:SUBSCRIBE_YEAR | AutoRenewing:False | State:Purchased | Id:1000000316908988
Updated Transaction | ProductId:SUBSCRIBE_YEAR | AutoRenewing:False | State:Purchased | Id:1000000316908988
2017-11-02 10:27:19.967 WTMIOS[403:32853]  ** formatter.StringFromNumber(4.49) = £4.49 for locale en_GB@currency

Which the for loop seemed to then clean up with FinishTransaction (they where gone on next restart) ...

On searching some more, I think its something to do with the auto-renew system in sandbox mentioned here -

https://stackoverflow.com/questions/10722630/skpaymentqueue-finishtransaction-within-network-completion-block

"After weeks of "phantom" purchases, I've finally realized what is going on. It wasn't the fault of finishTransaction: or AFNetworking.
The transactions that were occurring at app launch were actually part of the auto-renewal process that Apple was performing. The life of a 1 month subscription in the Apple Sandbox is 5 minutes, so I would have 1, 2, or 3 transactions in the queue when launching my app depending upon whether it has been 5, 10, or 15 minutes since I launched it last.
I had to tweak some server-side settings to make sure the renewals weren't being treated the same as fresh subscriptions."

Still not sure exactly what to do next, as not sure why they weren't getting cleared, but will continue with some console.writelines in the TestFlight output around the Trans Q ...

**Comment by wickedw** [comment]
Just an update to close this thread, the app has been live on the app store for about a week and no horrible dialogs, hurrah!

Although whatever apple is doing with sandbox is still horrible for all the testflight beta testers as sandbox login dialog pops-up loads still, if I have any support incidents at the end of the year I will raise with apple support and get it sorted.

Thanks again for library.
