### ISSUE TITLE
inAppBilling.PurchaseAsync works on sandbox, doesn't work on App store

### ISSUE THREAD

**Issue by vorotnyaknazar** [jamesmontemagno/InAppBillingPlugin#93]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 1.2.3.107
Device Tested On: iPhone 
Simulator Tested On:
Version of VS: Community 15.4.1
Version of Xamarin: Xamarin iOS 11.2
Versions of other things you are using:

### Steps to reproduce the Behavior
On sandbox inAppBilling.PurchaseAsync returns, On App store it stuck or something because non of code below never executes and there are no Exceptions too.
### Code snippet
if (!CrossInAppBilling.IsSupported)
            {
                await CoreMethods.DisplayAlert(null, "In-app billing isn't supported", "OK");
                return;
            }

            var result = await userDialogs.ConfirmAsync("Are you sure you want to subscribe with 30 days trial period?", null, "Yes", "No");
            
            if (!result)
            {
                return;
            }

            var inAppBilling = CrossInAppBilling.Current;
            try
            {
                var connected = await inAppBilling.ConnectAsync();
                if (!connected)
                {
                    await CoreMethods.DisplayAlert(null, "Unable to connect", "OK");
                    return;
                }
                
                var purchase = await inAppBilling.PurchaseAsync(appConfig.SubscriptionProductId, ItemType.Subscription, appConfig.SubscriptionPayload);

                if (purchase == null)
                {
                    await CoreMethods.DisplayAlert(null, "Purchase isn't made", "OK");
                }
                else
                {
                    settings.SubscriptionReceipt = getPurchaseReceiptService.Get(purchase.PurchaseToken);

                    var resp = await userAccountService.Subscribe(settings.SubscriptionReceipt);

                    if (!resp.IsSuccessfull)
                    {
                        await CoreMethods.DisplayAlert(null, resp.Message, "OK");
                    }
                    else
                    {
                        await CoreMethods.DisplayAlert(null, "Thank you for subscription!", "OK");
                        await CoreMethods.PushPageModel<MainPageModel>();
                        App.ClearNavigationStack();

                        if (!settings.IsEmailVerified)
                        {
                            await CoreMethods.PushPageModel<EnterVerificationCodePageModel>();
                        }
                    }
                }
            }
            catch (InAppBillingPurchaseException purchaseEx)
            {
                var message = string.Empty;
                switch (purchaseEx.PurchaseError)
                {
                    case PurchaseError.AppStoreUnavailable:
                        message = "Currently the app store seems to be unavailble. Try again later.";
                        break;
                    case PurchaseError.BillingUnavailable:
                        message = "Billing seems to be unavailable, please try again later.";
                        break;
                    case PurchaseError.PaymentInvalid:
                        message = "Payment seems to be invalid, please try again.";
                        break;
                    case PurchaseError.PaymentNotAllowed:
                        message = "Payment does not seem to be enabled/allowed, please try again.";
                        break;
                }
                    
                if (string.IsNullOrWhiteSpace(message))
                    return;

                await CoreMethods.DisplayAlert(null, message, "OK");
            }
            catch (Exception ex)
            {
                await CoreMethods.DisplayAlert(null, ex.Message, "OK");
            }
            finally
            {
                await inAppBilling.DisconnectAsync();
            }

**Comment by AndreiMisiukevich** [comment]
@vorotnyaknazar 

Hi) could you help me with my issue? I can't startup sandbox... maybe any advices?
https://github.com/jamesmontemagno/InAppBillingPlugin/issues/99

Or I can write to your email or skype or etc.

**Comment by jamesmontemagno** [comment]
Unable to reproduce
