### ISSUE TITLE
IOS 11 System.NullReferenceException: Object reference not set to an instance of an object   at Plugin.InAppBilling.InAppBillingImplementation.PurchaseAsync

### ISSUE THREAD

**Issue by ArtemKumeisha** [jamesmontemagno/InAppBillingPlugin#94]
## Bug Information

Version Number of Plugin: 1.2.3.107
Device Tested On: iPhone 5s
Simulator Tested On: iPhone 8
Version of VS: 7.2.2
Xamarin.IOS.framework: 11.2.1

Hi. I updated Xamarin.IOS.Framework to latest version (before all work fine) and after in  PurchaseAsync(string productId, string payload, IInAppBillingVerifyPurchase verifyPurchase = null) i catched System.NullReferenceException: Object reference not set to an instance of an object   at Plugin.InAppBilling.InAppBillingImplementation.PurchaseAsync
See full StackTrace here please https://gist.github.com/ArtemKumeisha/9dda6f4b1a951c1ee091397eb959097f. Do any meet such a problem?  Thanks.

**Comment by ArtemKumeisha** [comment]
I reset Mono to 4,8 version and made magical ritual "LogOut/In" in Itunes and Plugin start correctly work again.

**Comment by prashantvc** [comment]
> I reset Mono to 4,8 version

I don't think the Mono would cause this issue. 
Could you try using the latest Mono _again_ to see if helps?

**Comment by ArtemKumeisha** [comment]
I don't  know what happens when i try to use the latest Mono. But I can not make a purchase all the time)) "System.NullReferenceException: Object reference not set to an instance of an object at Plugin.InAppBilling.InAppBillingImplementation.PurchaseAsync".

**Comment by andyvasilevich** [comment]
I catch this exception too. Please help.

**Comment by jamesmontemagno** [comment]
closing as I can not reproduce. Not having any issues on my end.

**Comment by ivanicin** [comment]
> closing as I can not reproduce. Not having any issues on my end.

@jamesmontemagno I can confirm that I've got the report on this through AppCenter on the latest version of the plugin.

InAppBillingImplementation.PurchaseAsync (System.String productId, Plugin.InAppBilling.Abstractions.ItemType itemType, System.String payload, Plugin.InAppBilling.Abstractions.IInAppBillingVerifyPurchase verifyPurchase)
System.NullReferenceException: Object reference not set to an instance of an object.

I don't understand why you need to reproduce the problem when the code is short and the failure can happen only in one case as far as I can see, and that is if p in that method is null. Just check it and probably raise some human readable exception and that's all.
