### ISSUE TITLE
Android :  could it be possible to use the application context ?

### ISSUE THREAD

**Issue by jonathanantoine** [jamesmontemagno/InAppBillingPlugin#95]
I want to build a "singleton" service for my whole app and I've got issue with the current implementation because I can't left the activity "used at start" while using the service.

**Comment by jamesmontemagno** [comment]
It needs the activity

**Comment by jonathanantoine** [comment]
Sorry for being asking but I looked to the code and I didn't find where it's needed. Am I missing something?

Thank you for answering anyway 😊

**Comment by Sevenish** [comment]
Only PurchaseAsync really needs the Activity. The other calls could just use application context. There is even a constuctor for InAppBillingServiceConnection that does this. But it is not used.

I have CrossConnectivity setup but my GetProductInfoAsync runs before an activity is created (from the application class).
