### ISSUE TITLE
Android : A ndroid.runtime.JavaProxyThrowable in "OnServiceConnected"

### ISSUE THREAD

**Issue by jonathanantoine** [jamesmontemagno/InAppBillingPlugin#96]
First of all : **thanks a lot for this great plugin** !

I've got a lot (thousands..) of crash report like this in my google play dev console : https://gist.github.com/jonathanantoine/2445ebb1a651ef4e49c3a027216aa2d8 

## Bug Information

Version Number of Plugin: 1.2.3.107
Device Tested On: hundreds
Simulator Tested On: none 
Version of VS:  VS 2017 15.4
Version of Xamarin: 4.7.10.38 (34c1b6c)
 
Android 8.0 but it was happening with 7.1 too ..

### Steps to reproduce the Behavior
I can't manage to reproduce the issue by myself. 
Here is what I do in my app : 
1.   I create a singleton service on my first activity
2.  I connect to the play store using CrossInAppBilling.Current.ConnectAsync
3.  I retrieve in app product infos and purchase informations.

The user can navigate to other activities during this process.

### Expected Behavior
No crash report
### Actual Behavior
A lot of crash reports :(
### Screenshotst
Don't seems to be related to a specific version of the OS 
![capture](https://user-images.githubusercontent.com/3800550/32904561-e4651bbc-caf7-11e7-9fbe-9e6cf3472aa3.PNG)

**Comment by jamesmontemagno** [comment]
It is recommended not to do navigation as it can mess up with the process. I recommend refactoring not to do that.
