### ISSUE TITLE
[iOS] Can't test purchases (subscriptions)

### ISSUE THREAD

**Issue by AndreiMisiukevich** [jamesmontemagno/InAppBillingPlugin#99]
Hi. Firstly I respect you for your work. Great plugin!

So, about my problem
I use <package id="Plugin.InAppBilling" version="1.2.3.107" targetFramework="xamarinios10" /> this version of the plugin.

I created sandbox tester, created subscription on the store. And operated according to manual.

But after filling test apple id and password into system-input, I get next error-message
*This apple id is only valid for purchases in the {NAME OF COUNTRY STORE}. You will be switched on this store*

Where {NAME OF COUNTRY STORE} is sandbox tester's region.

Maybe any suggestions, how can I fix it?

Thanks a lot

Best regards

**Comment by AndreiMisiukevich** [comment]
By the way, I don't receive info from store

GetProductInfoAsync returns empty IEnumerable.

**Comment by jamesmontemagno** [comment]
Be sure to checkout: https://jamesmontemagno.github.io/InAppBillingPlugin/TestingAndTroubleshooting.html 

I can't help with testing as it is different for everyone and is extremely complicated.

**Comment by dsharkov** [comment]
@AndreiMisiukevich 

According to [In-App Purchase Configuration](https://developer.xamarin.com/guides/ios/platform_features/in-app_purchasing/in-app_purchase_basics_and_configuration) probably you don't have iOS Paid Applications contract:
You will not be able to test any StoreKit functionality until you have an iOS Paid Applications contract – StoreKit calls in your code will fail until Apple has processed your Contracts, Tax, and Banking information.

**Comment by AndreiMisiukevich** [comment]
Thanks a lot.
We are waiting its processing now..

**Comment by hendeavors** [comment]
I had everything setup properly. I wasn't able to see a list of products until the Bundle Identifier in Info.plist matched the Bundle ID on itunesconnect.
